### ISSUE TITLE
Me: "Revert Pending Change" for account email is hard to find

### ISSUE THREAD

**Issue by charliescheer** [wordpress-mobile/WordPress-iOS#10104]
If there is a pending change to the email address on your account in all devices you will see an alert that informs you that your the change is there and needs to be approved.

In iOS, however, there is no way to cancel that change if you no longer want your email changed.  It is possible cancel in web and in Android, but not iOS.  Would it be possible to add a cancel change link to the pending change alert?

<img src='http://cld.wthms.co/dbXZUb+'>

To reproduce:
1. Go to Me > Account Settings
2. Change your email to something new
3. An alert will appear on that same page saying there is a pending change, but no way to dismiss the change.

iOS 11.4.1
WordPress 10.7
iPhone 6s

**Comment by rachelmcr** [comment]
There is a way to cancel the pending change, but you have to tap on Email first. That brings you here:

![2018-09-06 12 22 08](https://user-images.githubusercontent.com/8658164/45148445-2dcbc900-b1bf-11e8-81a6-1f9680783a7f.png)


I'll tag this for design review — perhaps there's a way we can make that more obvious.

**Comment by osullivanchris** [comment]
I've had a look at this issue on hack week. I went through the flow on iOS and Android and considered a number of changes which are in the image below.

Option 1:
Pros: simple, cheap
Cons: can't do the action on the upper level, no improvement to the UI or alignment with Android

Option 2:
Pros: user can see the issue and act on it one level up, and cancel if desired
Cons: Not aligned with Android

Option 3:
Pros: Same pros as 2 + aligned with Android
Cons: Not sure this is a component we use elsewhere anyway, so consistency may not be an advantage. Also looks very material and a bit out of place here.

Option 4:
Pros: Same pros as 2 + tidied up UI. The blue UI is neither ours nor something that can be consistent with Android. Thought that making it look more like the list might make things clearer, and making the aciton red.
Cons: not aligned to Android. Might be less visible


**Recommendation: Option 1**
- As I understand this issue was reported because @charliescheer didn't think it was possible to cancel the change request at all.
- As it turned out, @rachelmcr pointed out it is possible, maybe just not very clear as its one level deeper
- Assuming there are not lots of user reports of issues (correct me if I'm wrong) this doesn't seem like a high priority issue or a big user problem knowing what we know. Having explored it I think the slight improvement of adding an icon in option 1 would be the cheapest and make it more obvious.

Feedback welcome as always

![cancel email change](https://user-images.githubusercontent.com/50576199/62048083-dd5cc000-b203-11e9-9857-ea64342d3af1.png)

**Comment by rachelmcr** [comment]
> Assuming there are not lots of user reports of issues (correct me if I'm wrong) this doesn't seem like a high priority issue or a big user problem knowing what we know. Having explored it I think the slight improvement of adding an icon in option 1 would be the cheapest and make it more obvious.

Agreed. I'm not aware of this as a significant point of confusion or something that gets a lot of user reports, so I think the lowest friction solution (option 1) makes sense at this point.

Also, just to follow up on this point about option 4:

> The blue UI is neither ours nor something that can be consistent with Android.

I _think_ the blue UI came from copying the Calypso UI for the pending email change banner at the time it was implemented, as seen in the screenshot on the original issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/4823. The Calypso banners have a new style, so if we decide to make a bigger change I don't think there's any reason to stick with the blue UI. The current Calypso UI is most similar to the snackbar style in option 3:

![Screenshot 2019-07-30 12 06 28](https://user-images.githubusercontent.com/8658164/62124596-8833b380-b2c2-11e9-8200-4af597038b54.png)

**Comment by osullivanchris** [comment]
@rachelmcr ah great. Thanks for the context that's really good to know. I'll check with the team for any feedback and make sure they agree with the proposal before I set this to done from design side

**Comment by megsfulton** [comment]
Out of all of the options, I prefer behavior you outlined in option 1. 

Regarding the banner...we might want to evaluate how we translate that new style to the mobile apps (as a separate issue) and coordinate with the Muriel team on it. To me, the dark card inline looks out of place in the context of the mobile apps.

**Comment by osullivanchris** [comment]
Proposal: we go with option 1 for now, which is a minimal addition that helps users find this information if they're missing it today. If we get feedback that its more of an issue we have the others in our pocket.

Regards the banner style, agree it can be tackled as a separate issue and we could try to find other banners like that which we have in the app.
