### ISSUE TITLE
Translation : Pending email Change

### ISSUE THREAD

**Issue by charliescheer** [wordpress-mobile/WordPress-iOS#10105]
If your account has a change to the email address on your WordPress.com account pending there is an alert that appears on the page Me > Account Settings. On iOS that is not being translated from English to any language that I tested (I tested French (France), French (Canada), Chinese (Simplified), Spanish (EU))

I did a quick look in the polyglot page to see if the string was there and I did find it for French and it is translated https://translate.wordpress.org/projects/apps/ios/dev/fr/default?filters%5Bterm%5D=pending+change&filters%5Buser_login%5D=&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc but it is not appearing in the app for some reason.

<img src='http://cld.wthms.co/dbXZUb+'>

To reproduce:
1. Set your device language to not english
2. Go to Me > Account Settings and set a new password for your account
3. Observe the alert that appears, it should still be in English

iOS 11.4.1
WordPress 10.7
iPhone 6s

**Comment by rachelmcr** [comment]
I believe the issue here is that we're including dynamic variables in the NSLocalizedString:

https://github.com/wordpress-mobile/WordPress-iOS/blob/4ac54edd8c4db2978a0122f97e137c755e627d4a/WordPress/Classes/ViewRelated/Me/AccountSettingsViewController.swift#L171

It looks ok in the [English Localizable.strings file](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Resources/en.lproj/Localizable.strings#L4189), but the backslash is stripped in other language files, e.g. the [French Localizable.strings file](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Resources/fr.lproj/Localizable.strings#L3742) so it no longer matches the original string.

It seems we have to use `sprintf` parameters for variables like this.

**Comment by rachelmcr** [comment]
This was fixed in https://github.com/wordpress-mobile/WordPress-iOS/pull/10511.
