### ISSUE TITLE
Document icon appears as image placeholder & randomly in comments

### ISSUE THREAD

**Issue by rclations** [wordpress-mobile/WordPress-iOS#10279]
This week I started noticing document icons randomly appearing in the reader.

### Expected behavior
No document icons.

### Actual behavior

1. Document icon is enlarged as an image placeholder https://cloudup.com/cZamJ4T69jK
2. Document icon displays randomly in comments https://cloudup.com/c-yR-L6wWyB

### Steps to reproduce the behavior
1.
2. Visit any post with comments, either on Reader on Notifications and navigate to the comments.

##### Tested on iPhone X, iOS 12.1 beta 4, WPiOS 10.9 and 11.0

**Comment by rachelmcr** [comment]
Thanks for the report! I'll add to this to our groundskeeping project to see if we can look into this before 12.1 is out of beta.

**Comment by jkmassel** [comment]
This appears to have been a bug in iOS 12.1 beta 3. On devices with 12.1 beta 4 and greater, the issue does not appear. Unfortunately, there are no published release notes for 12.1b4, so it's tough to know if there was a fix as part of that release.

While it's still possible there's an issue in our code, it doesn't seem worth chasing down an issue that only appeared in a beta for a small number of users – especially if the root cause may be somewhere in Apple's frameworks. 

**Tested on:**
- iPhone X[s] running iOS 12.1 beta 5 (16B5089b) with: WP Internal 11.1.0.20181023 and 11.1.0.0
- iPhone 8 / X Simulator running iOS 12.1 beta 4 (16B5084a) with a fresh build of the 11.1 branch (built using Xcode 10.1 beta 3 (10O45e)

**Comment by jklausa** [comment]
I just upgraded to 12.1 GM and can confirm I’m not seeing the icons.
