### ISSUE TITLE
Domain Registration: valid addresses fail when they contain non-alphanumeric characters such as ö or ß

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#10536]
As reported by @thehenrybyrd for the domain registration flow on a business site:

I also discovered [an issue] with adding latin characters with diacritical markings, such as ė.

Adding such characters gives a validation error: “Please enter a valid [field name]”

![registerdomainvalidation1](https://user-images.githubusercontent.com/8658164/48939211-6603bd80-ef0b-11e8-9366-56a96b1d0a0e.png)

In Calypso, the error is “This field can only contain the following characters: “a-z A-Z 0-9 . , ‘ – [space]”.

![registerdomainvalidation2](https://user-images.githubusercontent.com/8658164/48939281-9b101000-ef0b-11e8-8486-7256755c3a98.png)

In addition, Calypso quickly substitutes the character without the diacritical mark.

**Comment by rezzap** [comment]
User reporting something similar here: 

2746750-zen

Trying to register a domain with German characters (ö & ß) in surname and address fields and getting error invalid. Details are in the ticket screenshots.

**Comment by rezzap** [comment]
I believe there is something similar being reported here again:

3026840-zen

This seems to be coming up every once in a while and we've come to the habit of sending people to the browser for domain registration where they seem to be able to complete the process. I'm not sure how much of this is getting reported but since it affects paid users and domain upgrades it may be worth increasing the priority here @designsimply.
