### ISSUE TITLE
Add dependency attribution

### ISSUE THREAD

**Issue by jkmassel** [wordpress-mobile/WordPress-iOS#10623]
At the moment, there's no way to view a list of the open-source projects we depend on from within the app.

Someone can go to Me > App Settings > About WordPress for iOS, then tap "Source Code", which will bring them to this Github repo, but it'd be nice to recognize the folks whose work we're building on in a bit of a nicer way (h/t to @stevebaranski noticing that we weren't already doing this!)

CocoaPods does all the work here for us – it produces a nice markdown-formatted file that we can display to the user. 

What we need is a design for how that'll look.

I could see it being similar to the Activity Log (Me > Help + Support > Activity Logs > Current), but that page has some rather odd styling (the scroll indicator is constrained to the white box, as a for-instance).

The text of this will read somewhat similarly to one of those logs – it's a bunch of license files, but I think we still ought to present them in a nice way.

If you'd like, we could take a stab at something, then run it by you, or if you'd prefer to design something from the ground up, that's great too! 

Attached is a sample of the currently generated Markdown file.

[Pods-WordPress-acknowledgements.txt](https://github.com/wordpress-mobile/WordPress-iOS/files/2657846/Pods-WordPress-acknowledgements.txt)

**Comment by megsfulton** [comment]
Here's a mockup of what this could look like. Ideally, the text area extends the full width of the page.

The size of the text is the standard 16 that we use throughout the iOS app and the title of the library is bold. 
 
![Acknowledgements_blueprint](https://user-images.githubusercontent.com/161697/56925062-5290eb80-6a83-11e9-8c97-47fb5c2ef180.png)

Is "Acknowledgements" the common label for this page? I was looking at a few examples and found it labeled differently in each app I looked at. Credits, Open Source Libraries, Libraries We Use were the other labels I came across.

**Comment by stevebaranski** [comment]
Hello @megsfulton - thanks for sharing this design. In my experience, _Acknowledgments_ is the heading I've used previously, and observed most in practice, including in/from apps from Apple.

**Comment by jtreanor** [comment]
Just for a little more context here, the new entry on the about page will need to be added [here](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/ViewRelated/Me/AboutViewController.swift#L232).

Since the file generated by CocoaPods is in markdown, we will need to convert this to some format usable by the app. This could be done either by including a new pod in the app to support rendering markdown or by converting the `Pods-WordPress-acknowledgements.txt` to HTML when `pod install` is run using a gem such as https://github.com/gjtorikian/commonmarker and displaying it in a webview. I would favour the second approach here in order to keep our iOS dependencies to a minimum.
