### ISSUE TITLE
Publicize: Show default publicize message on "Customize the message" screen

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#10665]
Currently in the editor, under Post Settings > Sharing you can see a preview of the default publicize message. However, when you select "Message" you are taken to a "Customize the message" screen that is empty:

![image from ios 5](https://user-images.githubusercontent.com/8658164/50021561-673b7e00-ffd1-11e8-8f81-72e6a721f2cd.png)

@m noted that he expected the default publicize text to appear on that screen. That would mirror the Calypso behavior, which fills the "Customize the message" field with the default text:

![screenshot 2018-12-14 18 56 25](https://user-images.githubusercontent.com/8658164/50021753-f8125980-ffd1-11e8-8bc7-62f179c31aed.png)

**Comment by yaelirub** [comment]
Ok. Now that I know how to get here (Create a sharing connection to your site and then go to one of the draft posts and choose Post Settings and then under Sharing section, choose "message"
The next screen comes up with an empty cell. That's because the publicizedMessage on the post is nil.

Investigating more.

**Comment by yaelirub** [comment]
Ok. Now that I know how to get here (Create a sharing connection to your site and then go to one of the draft posts and choose Post Settings and then under Sharing section, choose "message"
The next screen comes up with an empty cell. That's because the publicizedMessage on the post is nil.

Investigating more.

**Comment by yaelirub** [comment]
After investigating and chatting with @rachelmcr I fixed the issue by showing the post display title in the message cell.
