### ISSUE TITLE
Numeric tags are removed after post creation or edit

### ISSUE THREAD

**Issue by codebykat** [wordpress-mobile/WordPress-iOS#10735]
I have a blog where I use the years as tags, and noticed that:
1. When I edit and update an existing post tagged as "2018", that tag is deleted (other tags are preserved).
2. When I create a new post using "Save as Draft" from the photo share sheet, and add the tag "2018", the draft is created without that tag.

### Expected behavior

Tags should be preserved.

### Actual behavior

Numeric tags are silently removed.

### Steps to reproduce the behavior

1. Add a tag "2018" via share sheet:

![img_b107a3dc87f2-1](https://user-images.githubusercontent.com/52152/50618098-8b3e0100-0ea5-11e9-8972-64c875a94dec.jpeg)
![img_b107a3dc87f2-2](https://user-images.githubusercontent.com/52152/50618101-91cc7880-0ea5-11e9-9745-cc25368a05ea.jpeg)

2. Note that the created draft does not include this tag.

3. Edit a post with an existing numeric tag:

![img_2663](https://user-images.githubusercontent.com/52152/50618147-ca6c5200-0ea5-11e9-9a27-d61933f0a8a3.PNG)

4. Note that after updating, the tag has been removed:

![screen-shot-2019-01-02-at-3 19 31-pm](https://user-images.githubusercontent.com/52152/50618166-de17b880-0ea5-11e9-9f4e-fbee1a58bc61.png)

##### Tested on [device], iOS [version], WPiOS [version]

iOS 12.1.1, WPiOS 11.5 (internal beta)

**Comment by codebykat** [comment]
Tags that begin or end with numbers, but contain some letters, are okay. e.g. "best-of-2018" and "2018-test" both came through okay.

**Comment by rachelmcr** [comment]
I tested this and here's what I see (iPhone XS, iOS 12.1.2, WPiOS 11.5.0.20190102 beta).

With the share extension:
* All numeric-only tags are removed.

When editing a post in the app:
* If the first tag is numeric only, it will be removed.
* Text tags are never removed, and numeric tags are not removed if they aren't the first tag in the list of tags.
* Tags are reordered to display numeric tags first in the list, so if you add a numeric tag (not first in the list of tags) it will end up being removed on a subsequent save.

**Comment by stevebaranski** [comment]
This is a curious one. I started by _only_ creating / editing posts on a self-hosted site (created by Jurassic Ninja), but wasn't able to reproduce it consistently.

After transitioning to a WPCOM site and using the Share extension, I'm running into the error. The funny thing is that it seems like the something is happening between the client & server. I captured some logs via Charles and here's what I'm seeing. 

For a POST to `https://public-api.wordpress.com/rest/v1.1/sites/<site ID>/posts/<post ID>?context=edit&locale=en`.

The **request** includes both tags (as one would expect), but the response only includes one of them.

**Request Excerpt :**
```
{
	...
	"tags": [
		"2018",
		" alpha"
	],
        ...
}
```

**Response Excerpt :**
```
{
	...
		"post_tag": {
			"alpha": {
				"ID": 17363,
				"name": "alpha",
				"slug": "alpha",
				"description": "Test",
				"post_count": 1,
				"meta": {
					"links": {
						"self": "https://public-api.wordpress.com/rest/v1.1/sites/156571618/tags/slug:alpha",
						"help": "https://public-api.wordpress.com/rest/v1.1/sites/156571618/tags/slug:alpha/help",
						"site": "https://public-api.wordpress.com/rest/v1.1/sites/156571618"
					}
				}
			}
		},
		"post_format": {
		},
		"mentions": {
		}
	},
	"tags": {
		"alpha": {
			"ID": 17363,
			"name": "alpha",
			"slug": "alpha",
			"description": "Test",
			"post_count": 1,
			"meta": {
				"links": {
					"self": "https://public-api.wordpress.com/rest/v1.1/sites/156571618/tags/slug:alpha",
					"help": "https://public-api.wordpress.com/rest/v1.1/sites/156571618/tags/slug:alpha/help",
					"site": "https://public-api.wordpress.com/rest/v1.1/sites/156571618"
				}
			}
		}
	},
	...
}
```

**Comment by rachelmcr** [comment]
Although Android and Calypso web don't have the same kind of share extension as iOS, since part of this issue occurs in the regular iOS editor and it looks like a possible server issue I tested numeric tags in Android and Calypso to compare results. In both cases, all tags (including all numeric tags) were retained.

I noticed that Calypso first makes a request to the `tags` endpoint to get the tag ID for any entered tags, and when it makes the request to the `posts` endpoint it uses the tag IDs instead of tag names. I haven't checked the Android requests & responses, but is it possible that when the tags are sent to the API it's treating numeric tags like tag IDs and dropping them when there isn't a tag with a matching tag ID?

**Comment by rachelmcr** [comment]
>  is it possible that when the tags are sent to the API it's treating numeric tags like tag IDs and dropping them when there isn't a tag with a matching tag ID?

I'm pretty sure this is what's happening. To test this theory, I created a new post through the iOS share extension and added a numeric tag corresponding with a numeric tag name on my site (`2018`), a numeric tag that corresponded with the tag ID for an existing tag on my site (`47298`, which is the tag ID for the tag `amazing` on my site), and a regular text tag (`test`). When I checked the resulting post in the app, it had the tags `amazing` and `test` instead of the mix of text and numeric tags I had entered.

**Comment by stevebaranski** [comment]
> is it possible that when the tags are sent to the API it's treating numeric tags like tag IDs and dropping them when there isn't a tag with a matching tag ID?

The only bit I'd add is that the numeric tag is being sent up as type `String` (i.e., `"2018"` in the request above). The IDs in the response appear to be numeric (i.e., `17363` lacks the wrapping quotes).

**Comment by rachelmcr** [comment]
cc @jkmassel
