### ISSUE TITLE
Reader: Maintain consistent spacing above/below images in post detail

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#10866]
### Expected behavior

I expect consistent spacing above/below images in the Reader.

### Actual behavior

At least for posts created in Gutenberg, there is inconsistent spacing above/below images in the app Reader. We should account for common variations in source code around images (e.g. extra carriage returns, paragraph tags, div tags) and ensure the post detail shows consistent spacing.

One example is with images that are aligned left/right/center in Gutenberg. These images have div tags around them (whereas non-aligned images do not), adding extra space above and below the image in the app Reader.

##### Tested on [iPhone XS], iOS [12.1.2], WPiOS [11.6.0.20190115]
Original report from an end user (internal ref: p4a5px-2kH-p2)

**Comment by designsimply** [comment]
This came up in 13.5 beta testing. The problem where too much extra space appears around images also happens in Reader Comments. 

Testing steps:

1. Open a site you follow (or follow one).
1. Add a comment to the followed site with the sample content from below>
1. View the post comments in the Reader.

Sample content, 2 image links on 2 lines with a single line break and no spaces between them: 

```
https://s.w.org/style/images/about/wmark.png
https://s.w.org/style/images/about/simplified.png
```

<img src="https://user-images.githubusercontent.com/1119271/68438502-9a56a500-0181-11ea-994b-d0d55453e730.PNG" width="540" alt="IMG_0185">
<sup>Tested with WP Internal 13.6.20111104 (HockeyApp) on iPad Mini 4 (WiFi) (iPad5,1) iPadOS 13.2.</sup>

**Comment by designsimply** [comment]
@shiki may I ask for a little time on this one? If you can fix it in a short timeframe, could you do it for 13.7? If it's more involved than it seems, could you just check it out and leave some notes with your findings?

**Comment by guarani** [comment]
@shiki, I took a look at this and gained some insights into where the problem may lie.

The image view (blueish background) is a `CachedAnimatedImageView`, and is too tall for the image it displays - leaving a top and bottom margin (red arrows). Since the image is vertically centered in the image view, the top and bottom margins sum between images to create a much larger gap than expected.

![views](https://user-images.githubusercontent.com/1898325/68445062-96de1080-01b7-11ea-9fcc-27e23d74602a.png)


Here’s my take on the issue:
1. The image comes in with no size information in this case:  "<img src=\"https://s.w.org/style/images/about/simplified.png\" />"
2. `WPRichContentView.sizeForAttachment` receives an attachment with width and height zero
3. `sizeForAttachment` sets both width and height to `maxDisplaySize` since they're both zero
4. `maxDisplaySize` uses `UIScreen.main.bounds` (which seems incorrect) to get the size of the available space, and uses the greater of size’s width and height to return a square CGRect
5. Since `maxDisplaySize` is always a square (same height and width), the image attachment is given a square area

In our case above, the available screen width was larger than the height, so the width was used to determine `maxDisplaySize`. Now, since the image is wider than it is tall, it doesn’t occupy all the vertical space given to it. The image view content mode, `scaleAspectFit`, ensured the image is vertically centered.


I’d say the fix could actually be in `ImageLoader`, because since no size information comes in the HTML, we probably need to check the image size as soon as it’s downloaded (I had a quick look in code but didn’t see that this is already being done anywhere). 
Hope that helps.

**Comment by leandroalonso** [comment]
After the Reader Detail refactor we follow the same space as the web, and the code that caused this issue doesn't exist anymore.
