### ISSUE TITLE
Media picker: Action sheet for other media sources appears out of place on iPad

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#10881]
### Expected behavior

When I add media from another source (free photo library, Giphy, other apps) I expect the action sheet to choose the source to appear near the toolbar/bottom of the screen in the editor.

### Actual behavior

When I tap the ellipsis to choose another media source:

![photo 23-01-2019 09 38 14](https://user-images.githubusercontent.com/8658164/51599490-96f67380-1ef7-11e9-8a54-ab0a7b41e412.png)

The action sheet to choose the media source appears in the top left:

![photo 23-01-2019 09 38 18](https://user-images.githubusercontent.com/8658164/51599479-9067fc00-1ef7-11e9-94a4-32c4535ed1ff.png)

### Steps to reproduce the behavior

1. Open the editor on an iPad.
2. Tap in the post content area.
3. Tap the + toolbar button to add media.
4. Tap the ellipsis to add media from another source.

**Comment by ngoctr** [comment]
I noticed this happened when working on #13803. The reason is the underlying anchor view for the popover has been disappeared when the keyboard being resigned. @frosty I made a quick fix to show the sheet in the center screen as follow. Please let me know if you are happy with this, so I will put it in the PR for #13803. Thanks James.

![image](https://user-images.githubusercontent.com/17534738/78628085-8c46b500-78d6-11ea-9fc0-fc0906271ba9.png)

**Comment by frosty** [comment]
Thanks @ngoctr! However, would it be possible to open a separate PR for that fix, as it's kind of distinct from the Tenor changes?

**Comment by ngoctr** [comment]
Sure @frosty, it should be. I will submit a separate PR for this one.

**Comment by ScoutHarris** [comment]
Fixed with https://github.com/wordpress-mobile/WordPress-iOS/pull/13841.
