### ISSUE TITLE
Replace occurrences of Offline error alerts with Notice

### ISSUE THREAD

**Issue by yaelirub** [wordpress-mobile/WordPress-iOS#11035]
To implement the "Snackbar" feature to replace Offline error alerts, we decided to reuse `Notice`. This task is to replace the Offline error alerts like this with `Notice`:

<img src="https://user-images.githubusercontent.com/198826/53174760-ca382b00-35a7-11e9-8a11-9fa0e8e4b550.png"  width="320" />

## Dependencies

To complete #11005, the `Notice` will have to be redesigned to use the latest Muriel design guidelines. That will be done in #11033. But this task can still be done without waiting for that.

**Comment by shiki** [comment]
There are still some Alerts that have not been replaced with Notices. They were replaced in #11158 but we decided to revert the changes since the app workflow was changed and the user experience may be negatively affected. We decided to replace the most disruptive ones (#11171) for now.

We will need to discuss more how to approach the other Alerts. We'll create separate issues for those.
