### ISSUE TITLE
Media "Upload failed" message stuck for a post in the Blog Posts locally even after the image uploaded normally on a retry

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#11176]
While testing 11.9 alpha with my iPad I managed to get one post into a funny state where it's labeled with "Upload failed" locally on the post card in the Blog Posts list even though tapping retry fixed the image upload and the post seemed to get publish normally after that. The post itself is tagged locally with a red "Upload failed" message that won't go away even after restarting the app.

I took a few screenshots while creating the post originally: https://cloudup.com/cex0l-3oxwL 

Original failed media error as seen on my iPad:

<img src="https://user-images.githubusercontent.com/1119271/53673252-a037d600-3c43-11e9-8df5-945de9098694.PNG" width="388" alt="img_0061">
<sup>WP Internal 11.9.0.20190226 on iPad Mini 4 (WiFi) (iPad5,1) iOS 12.1.4</sup>

Stuck "Upload failed" message that appears locally on the Blog Posts list:

<img src="https://user-images.githubusercontent.com/1119271/53673362-31a74800-3c44-11e9-92ef-12ff01009cce.PNG" width="388" alt="img_0080">
<sup>WP Internal 11.9.0.20190226 on iPad Mini 4 (WiFi) (iPad5,1) iOS 12.1.4</sup>

Here are the app logs which looked relevant to me for the corresponding timestamp of the failed media upload: 

```
2019-02-28 19:23:00:926 Error occurred importing to Media with asset export error, code: 4, error: Error Domain=WordPress.MediaAssetExporter.AssetExportError Code=4 "The image could not be added to the Media Library." UserInfo={NSLocalizedDescription=The image could not be added to the Media Library.}
2019-02-28 19:23:18:378 🔵 Tracked: media_service_upload_failed, properties: {
    "error_code" = 0;
    "error_description" = "Error Domain=MediaServiceErrorDomain Code=0 \"Media doesn't have an associated file to upload.\" UserInfo={NSLocalizedDescription=Media doesn't have an associated file to upload.}";
    "error_domain" = MediaServiceErrorDomain;
}
```

<sup>(note that I uploaded two images successfully but deleted those and added a third and the third one is the only one that had an upload error)</sup>

More app logs: https://mc.a8c.com/pb/2084e/raw/

Checked it with my iPhone and it looks fine there:

<img src="https://user-images.githubusercontent.com/1119271/53673306-d37a6500-3c43-11e9-9de8-c7213f353a8b.PNG" width="270" alt="img_2070">
<sup>WP Internal 11.9.0.20190226 on iPhone 6S iOS 12.1.4</sup>

Site details

* `alleged-swift.jurassic.ninja`
* Jetpack 7.0.1
* WordPRess 5.2-alpha-44784
* Gutenberg toggled "on" in the App Settings 

Tested with WP Internal 11.9.0.20190226 on iPad Mini 4 (WiFi) (iPad5,1) iOS 12.1.4.

**Comment by SergioEstevao** [comment]
I tested this a bit and here are my findings:

- When you start a new post and add some images/media objects to it. The post object will have this media objects attached to it on CoreData.
- You then press publish while the upload is going on and exit the editor
- The app tries to upload the media and then upload the post.
- The issue here is that sometimes the media upload can fail on the background and post is published anyway.
- We are then stuck with media that is failed to upload that is associated/attached to the post.
- So we will see the error status for the post when viewing the post list.

For this to be sorted out we need two make one of the following:

- Make sure we only upload the post after all media is upload successfully.
- Or media that fail is removed from the post associations after the post is published

There is also another edge scenario that is media that was created originally from a iCloud stored photo. Sometimes the download from iCloud can fail and then the media object is stuck on the error state and we cannot recover because we don't keep any reference to the original PHAsset.

**Comment by elibud** [comment]
@SergioEstevao can you take care of this one please?

**Comment by SergioEstevao** [comment]
I can, I think I still have a pending PR for this from my last Groundskeeping rotation.
