### ISSUE TITLE
Please add the ability to modify the slug for pages on the WordPress app

### ISSUE THREAD

**Issue by theblindadvocate** [wordpress-mobile/WordPress-iOS#11225]
### Expected behavior
I would like the ability to modify a slug to a WordPress page.

### Actual behavior
I cannot find an option to modify the slug for the page.

### Steps to reproduce the behavior
1. Go to a page and edit it.
2. Tap on more.
3. Tap on Post Settings.
4. There, you will only see set feature image, and other options, but not modifying the slug of the page. For example, the URL is https://www.theblindadvocate.com/youtube-videos and you change it to https://theblindadvocate.com/youtube

##### Tested on [device], iOS [version], WPiOS [version]
Testing on iPhone 6s, iOs 12.1.4, WordPress app version 11.8.

Attached below is the screenshot of what I am talking about.

<img src="https://user-images.githubusercontent.com/47901227/54094890-60c36500-437a-11e9-8b35-49a0c712345b.png" width="270" alt="Screenshot of the WordPress Page Post Settings from the WordPress iPhone app">

**Comment by theblindadvocate** [comment]
Sorry for the error. What I was saying is, "There, you will only see set feature image, and other options, but not the ability to modify the slug."
![C59FB839-09FB-4AF8-AE08-FC6586491D86](https://user-images.githubusercontent.com/47901227/54094673-0c6bb580-4379-11e9-9d28-8566744705cd.png)

**Comment by designsimply** [comment]
Tested and confirmed. Thank you for filing a request about this including a screenshot.

**Comment by rachelmcr** [comment]
This came up again recently in a ticket (internal ref: 2272842-zen) where the user has a more page-centric site and wants to be able to edit the page slug from within the app.

Not being able to do that within the app requires switching between web and app to complete the task, which decreases the utility of the app (encouraging him to use only the web since he knows he'll need to use the web for that purpose, and switching directly from the page editor in the app to the web and vice-versa is not smooth).

**Comment by mdrockwell** [comment]
Another suggestion for this here: 3695237-zd-woothemes

**Comment by mdrockwell** [comment]
Another here: 3723276-zd-woothemes

**Comment by reginabally** [comment]
We pointed the user to change the Slug using the WPiOS app (version 16.9) in 3869849-zd-woothemes but found out this isn't available on WPiOS. The same option can be found on WPAndroid.

**Comment by joashrajin** [comment]
+1 at #5474735-zen
