### ISSUE TITLE
Stats: Request to link directly to posts/pages from stats

### ISSUE THREAD

**Issue by eurello** [wordpress-mobile/WordPress-iOS#11344]
Some feedback from a customer on the per-post/page stats view in the iOS app as compared to Android app:

> In the android app, if I viewed my daily stats, I could tap on a post title
and it would take me to the stats page on just that post. If I tapped on the
title again from that page, it would take me directly back to that post. The IOS
app will not do this. There seems to be no link directly back to that post from
the stats page. Very frustrating.

The customer would like for the link back to the post to be available from the stats area on the iOS app, as it is in the Android app.

#1902265-zen

**Comment by ScoutHarris** [comment]
Hey @SylvesterWilmott .

This issue is regarding the post title in the Post Stats view. Currently in Android, on Post Stats the post title is tappable, and displays the post.

![post_stats](https://user-images.githubusercontent.com/1816888/55111239-9026e100-509f-11e9-9c6d-247d286f52ca.png)


However, the iOS design (and thus the implementation) does _not_ have the title as tappable.

![Post Stats](https://user-images.githubusercontent.com/1816888/55111462-13e0cd80-50a0-11e9-939f-1e7381b48406.png)

I'm assuming iOS should follow Android's functionality here?

**Comment by SylvesterWilmott** [comment]
Thanks @eurello for relaying the feedback

@ScoutHarris We should include this for sure. @planarvoid Let's also include this in the new Android post stats if we haven't already.
