### ISSUE TITLE
[Stats Refresh] Blog stats: show NRV when offline

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#11427]
Tapping “Stats” on a post list view item displays the “No Connection” alert

**Comment by diegoreymendez** [comment]
I'm removing this from Offline Posting Improvements, since this will be taken care of in Offline Stats when that happens.

**Comment by ScoutHarris** [comment]
Hey @jklausa . This wasn't fixed by https://github.com/wordpress-mobile/WordPress-iOS/pull/11864 . The `No Connection` alert is still shown. 

I'm not sure how this _can_ work, since Post Stats isn't persisted to Core Data. And even it it was, it's highly unlikely to have the stats for any post in the list.

**Comment by ScoutHarris** [comment]
Hey @diegoreymendez .

Thanks for the explanation; that makes more sense. 😄 

I agree, I think in this case we can show the no results view with the offline message.

**Comment by staskus** [comment]
This is an outdated task, so I'm closing it.

Out of curiosity, I checked how it works now, and we show "No connection" view:

https://github.com/wordpress-mobile/WordPress-iOS/assets/4062343/26456b2e-5bd5-464e-8901-2e89c2959ca6

It works exactly how it was planned to do:

> In this case, my opinion is that showing an inline message, in the form of opening a no-results ("you're offline") view could be the best option.

cc @guarani
