### ISSUE TITLE
Remove FakePreviewBuilder from the app

### ISSUE THREAD

**Issue by yaelirub** [wordpress-mobile/WordPress-iOS#11699]
Now that we are auto saving a post and uploading a draft before preview,
we can take the last step in [Get rid of local previews](https://github.com/wordpress-mobile/WordPress-iOS/issues/9282) and remove the FakePreviewBuilder from the code.

After looking into this, I have a couple of questions that maybe @koke or @diegoreymendez  can help figure out. 

1. Currently we are showing the fake preview in cases where we can't find a url (either a preview url returned from auto save or a permalink on the post):

https://github.com/wordpress-mobile/WordPress-iOS/blob/425915492ad719b81f39e00cfc533dcbacba24bd/WordPress/Classes/ViewRelated/Post/PostPreviewGenerator.swift#L31

https://github.com/wordpress-mobile/WordPress-iOS/blob/425915492ad719b81f39e00cfc533dcbacba24bd/WordPress/Classes/ViewRelated/Post/PostPreviewGenerator.swift#L104

https://github.com/wordpress-mobile/WordPress-iOS/blob/425915492ad719b81f39e00cfc533dcbacba24bd/WordPress/Classes/ViewRelated/Post/PostPreviewGenerator.swift#L113

In this case, should we replace showFakePreview() with ` delegate?.previewFailed...` (which shows the empty view with a defined error message)?

2. When trying to preview while offline, the check for `url = post.permaLink.flatMap(URL.init(string:))` will fail for draft (since the upload call failed). I believe the technical solution proposed [here](https://github.com/wordpress-mobile/WordPress-iOS/issues/11653) will allow the upload post to get called when we regain connectivity and as a result create the permalink which we will have to reload the preview web view with.  Is that correct?

**Comment by koke** [comment]
> Currently we are showing the fake preview in cases where we can't find a url (either a preview url returned from auto save or a permalink on the post) 

Seeing all the all the other items crossed in #9282 I imagine this is fine and showing a message saying that we can't preview is what we want for the remaining cases. But for reference, in which scenarios would we not have a URL?

I'll leave the other question for Diego, since I haven't looked much into the current plans for offline support.

**Comment by diegoreymendez** [comment]
### About showing a fake preview when we don't have a URL:

Can I ask you to provide a link for that snippet of code?

But in general: that specific snippet of code is tricky, because the initialization of the URL shouldn't really return `nil` unless we used a malformed URL.

If our API provided us with a malformed URL, we would want to:

1. Record the problem in a way that can tell us if there's an issue with our APIs, and
2. Recover from it, if possible.

For recording the problem, [Fabric used to have a method to record an error, without really crashing the App for the user](https://docs.fabric.io/apple/crashlytics/logged-errors.html).  I'm not sure if Sentry has something similar (@jkmassel do you know?).

Recovering from the error depends on the context around that code.  It may mean just not doing anything, showing an error VC of some sort, or something else.

### About uploading the preview again when the device goes online:

For previews specifically, I don't think we want to queue their uploads cos if the user decides to exit the preview screen, the autosave is no longer necessary.

I think the VC we show should have the logic it needs to try uploading again when the retry button is pressed, or when the device detects it's back online.

**Comment by yaelirub** [comment]
>Can I ask you to provide a link for that snippet of code?

@diegoreymendez , I updated with code snippets. 

>because the initialization of the URL shouldn't really return nil unless we used a malformed URL.

When it comes to draft posts, the initialization of the url will return nil if the upload of the post failed (in offline for example).

**Comment by diegoreymendez** [comment]
> When it comes to draft posts, the initialization of the url will return nil if the upload of the post failed (in offline for example).

If the post upload fails, since we already know we have nothing to preview, can't we just avoid running the preview generator?

I think preventing it from running when there's nothing to preview would help simplify things a bit.

**Comment by yaelirub** [comment]
@diegoreymendez , those calls are in the preview generator generate method but I see where you're going with this and will try to come up with something here
