### ISSUE TITLE
"Generating Preview..." HUD is blocking user interaction. Use progress bar instead.

### ISSUE THREAD

**Issue by yaelirub** [wordpress-mobile/WordPress-iOS#11812]
This is spun off of #11722 
detailed comment here:  https://github.com/wordpress-mobile/WordPress-iOS/pull/11722#pullrequestreview-243054234

The loading HUD blocks any interaction, so I can't get away from the preview screen until the request times out.
> 
> ![Screen Shot 2019-05-29 at 08 09 41](https://user-images.githubusercontent.com/8739/58533577-351d8180-81e9-11e9-9461-045df779476e.png)
> ![Screen Shot 2019-05-29 at 08 08 46](https://user-images.githubusercontent.com/8739/58533581-36e74500-81e9-11e9-9919-25157b6c843a.png)

Steps to reproduce:
1. Edit published post
2. Turn to offline mode on simulator or Network Link Conditioner enabled and 100% packet loss on device.
3. Tap to preview

## Decision
We are going to implement something similar to uploading a media with a progress bar 
![IMG_1287](https://user-images.githubusercontent.com/50576199/60177658-59cd3f00-9811-11e9-9f63-fba3ac1aa1cd.PNG)
It shows a loading state, with a description, and doesn't block the user from using the UI

![Generating preview loader](https://user-images.githubusercontent.com/50576199/60177701-74071d00-9811-11e9-8fc4-1af0a8026e30.jpg)

**Comment by osullivanchris** [comment]
@yaelirub on this one, I definitely think we could come up with an alternative loading animation that doesn't block the UI. However, in the screenshots I see above, even if there was no animation, it looks like the UI has still not loaded.

The bigger issue to me is lazy loading / caching things where possible. Then there will be useful things in the UI, which we can get out of the way of.

Changing the spinner is a valid task, but won't add much value until the UI becomes useful when online. Does that make sense?

One other note: I read research before that its better to use system style loaders rather than anything too custom. The study found that if you use custom loaders, the user will associate the slowness with your app. But if you use system loaders, the user will blame the slowness on the device/network. So if we use a different loader it should still feel like part of the OS.

Looking at the HIG there's a few options 
https://developer.apple.com/design/human-interface-guidelines/ios/controls/progress-indicators/
- A progress bar achieves what I was looking for above. Although it doesn't have a label. We might want something with a label to explain what is happening
- Do we use the "Network Activity Indicator"? If we use that, we could have something dismissable as you mentioned, and then the user would still have that indicator to know something is still happening

Hope that's not too much information. Would like to hear your thoughts!

**Comment by yaelirub** [comment]
@osullivanchris  thank you so much for your input on this. 

>The bigger issue to me is lazy loading / caching things where possible. Then there will be useful things in the UI, which we can get out of the way of.

The issue here is that the preview url is generated in the response to the auto save API call. We are making this call upon the user's request to preview the post. The caching option is not really valid here imo because we need to preview the updated post without actually uploading it. You will find that when the user requests to preview without making any changes the loading is fast and almost immediate as we are making the call only if there were local changes. 

> Do we use the "Network Activity Indicator"? If we use that, we could have something dismissable as you mentioned, and then the user would still have that indicator to know something is still happening

We do use it in other places and could use it here too. If we do that maybe we can show a snack bar with "generating preview" while the network activity indicator is spinning?

**Comment by yaelirub** [comment]
@osullivanchris , want to make the call on how we should handle this?
From a technical perspective, we have to make the call when the user requests to preview, so some loading time is necessary. The question is what's the best way to message the user.

**Comment by osullivanchris** [comment]
Hey I found something similar we are doing here
![IMG_1287](https://user-images.githubusercontent.com/50576199/60177658-59cd3f00-9811-11e9-9f63-fba3ac1aa1cd.PNG)

If thats something re-usable it seems like the quickest thing to do to get this unblocked? Shows a loading state, with a description, and doesn't block the user from using the UI. Let me know if it works!
![Generating preview loader](https://user-images.githubusercontent.com/50576199/60177701-74071d00-9811-11e9-8fc4-1af0a8026e30.jpg)
