### ISSUE TITLE
Domain Credit: the register domain step can be very slow

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#11834]
In beta testing, the register domain step took ~26s to complete on a fast wifi connection [~100Mbps](https://user-images.githubusercontent.com/1119271/58734384-89289180-83b4-11e9-8e56-78279c17c246.PNG). Can this step be made faster by any chance?

Video: [2m35s](https://cloudup.com/cf2Yh01tm2E)
<sub>Tested with WP Internal 12.5.0.20190524 on iPhone 6S iOS 12.3.1.</sub>

<img src="https://user-images.githubusercontent.com/1119271/58735037-6e571c80-83b6-11e9-9054-829fc5823cb4.png" width="270" alt="Screen Shot 2019-05-31 at 3 07 45 PM">

**Comment by Gio2018** [comment]
Closing this one because, as discussed on Slack, the registration step is indeed slow but this is mostly because the domain registration itself contains a lot of steps, and there isn't much that we can improve at app level. We will use this as an opportunity to communicate with the user while the domain is registered. cc @startuptester
