### ISSUE TITLE
Editor: Updating a post on a self-hosted site makes preview unavailable

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#11952]
### Expected behavior

I expect that I will be able to save a draft post and preview it repeatedly while I am working on it.

### Actual behavior

On a self-hosted site (without Jetpack), I can only preview the post when I first create/save it or when I first open a saved draft. If I update a saved draft, when I try to preview it I always get the "Preview Unavailable" screen.

The app logs show this error:

```
2019-06-19 13:10:52:158 displayPreview: Post permalink is unexpectedly nil
```

### Steps to reproduce the behavior

1. Select a self-hosted site in the app.
2. Start a new post and enter title/content.
3. Save the draft.
4. Preview the post. The preview loads.
5. Go back to the editor and make a change to the post.
6. Update the draft.
7. Preview the post. Result: The "Preview Unavailable" screen appears.

![2019-06-19 13 10 57](https://user-images.githubusercontent.com/8658164/59765752-a1464f00-9296-11e9-941c-ccda7f5dfe8b.png)

**Comment by elibud** [comment]
CC: @yaelirub

**Comment by yaelirub** [comment]
When we're first saving the post createPost in `PostServiceRemoteXMLRPC` gets called and returns a remotePost with the appropriate values.

but updatePost  in `PostServiceRemoteXMLRPC` returns a remotePost with mostly null values (including the url). 
I'm trying to figure out why.
Any thoughts? @diegoreymendez , @aerych ?

**Comment by diegoreymendez** [comment]
@yaelirub - As we chatted yesterday, and to keep the history here, you can check the actual backend response to figure out if the relevant values are being returned as `null` or if they're being omitted.  If they're being omitted we should figure out why we're overwriting them (or why we don't have them to being with).

The first thing for this issue would be to have a more complete analysis of what's going on.

**Comment by yaelirub** [comment]
Sorry for pining you both before providing more information and thanks @diegoreymendez for your advice.

When we upload a post on a request to preview we call the uploadPost method in PostService. 
That call creates a remotePost in https://github.com/wordpress-mobile/WordPress-iOS/blob/e26bb0f8ba71e7650a4149b145748aca68e66d59/WordPress/Classes/Services/PostService.m#L720

We then call updatePost with this remotePost. The issue is that we don't assign value to the URL property of the remote post.

This is not an issue with WP sites because the updatePost method in PostServiceRemoteRest returns a remote post object (has a URL value) that we update our local post with. 

When the site is self hosted updatePost in PostServiceRemoteXMLRPC is called and it returns a boolean. We then invoke a callback with the remote post we made the call with (that has no URL).

In my PR to fix this I'm setting the remote post URL with the abstract post permalink upon its creation. 
Can you think of a reason why we weren't doing that before?

**Comment by aerych** [comment]
> Can you think of a reason why we weren't doing that before?

So previewing after creating a post works, but previewing after updating a post doesn't. Let's have a closer look at the two methods to see what they might be doing different. 

To [create a post](https://github.com/wordpress-mobile/WordPressKit-iOS/blob/4.1.3/WordPressKit/PostServiceRemoteXMLRPC.m#L84) we call the `metaweblog.newPost` [endpoint](https://codex.wordpress.org/XML-RPC_MetaWeblog_API#metaWeblog.newPost), which returns the `postID` of the newly created post.  While we're in the [success block](https://github.com/wordpress-mobile/WordPressKit-iOS/blob/4.1.3/WordPressKit/PostServiceRemoteXMLRPC.m#L101) we go ahead and use the returned `postID` to [fetch full post object](https://github.com/wordpress-mobile/WordPressKit-iOS/blob/4.1.3/WordPressKit/PostServiceRemoteXMLRPC.m#L29) from the API.  This gets us a fully populated remote post which we return to the caller via the [success](https://github.com/wordpress-mobile/WordPressKit-iOS/blob/4.1.3/WordPressKit/PostServiceRemoteXMLRPC.m#L103) callback.  Cool.

When [updating a post](https://github.com/wordpress-mobile/WordPressKit-iOS/blob/4.1.3/WordPressKit/PostServiceRemoteXMLRPC.m#L123) we call the `metaweblog.editPost` [endpoint](https://codex.wordpress.org/XML-RPC_MetaWeblog_API#metaWeblog.editPost) which, as you pointed out, returns a boolean.  Right in the [success block](https://github.com/wordpress-mobile/WordPressKit-iOS/blob/4.1.3/WordPressKit/PostServiceRemoteXMLRPC.m#L146) we have `TODO` to fetch the updated post, ostensibly the same way we do in the create method, and return it rather than the captured `post`.  I think this is your hint at what steps need to happen next.  

As for why there is a difference, its really hard to say.  Probably its not intentional.  Possibly its a long neglected oversight as that line of code seems to have been in place since it was added [over five years ago](https://github.com/wordpress-mobile/WordPress-iOS/commit/b087b8870c7691db443fdb9787b69067e6c638d8#diff-7c928b0db8fcd494f324529be533d27cR111).  (ouch!)

**Comment by yaelirub** [comment]
Thanks for the response @aerych.
I will update the code to fetch the post on a successful response from `metaweblog.editPost`
