### ISSUE TITLE
Media: Improve Media Library Full Message

### ISSUE THREAD

**Issue by thehenrybyrd** [wordpress-mobile/WordPress-iOS#12092]
### Expected behavior

When the Media Library on my site is full, I expect a clear message explaining this.

### Actual behavior

The error message is vague. It says there's not enough space, but it isn't clear _where_ there isn't enough space.

![unclearerror](https://user-images.githubusercontent.com/15107387/60974761-4f439700-a333-11e9-98a4-68a61fe1bc61.png)

I would suggest adapting the wp-admin Media Library messaging:
> Looks like you have used 3.0 GB of your 3.0 GB upload limit (100%)

### Steps to reproduce the behavior

1. Get a site with a full media library
2. Upload an image to a post on that site

User report: #2167501-zen

**Comment by rfaile313** [comment]
Another user report/request in 2371631-zen

**Comment by rachelmcr** [comment]
The message shown in the media library is now more explicit, for example:

> Not enough space to upload
> 100% of 3 GB used on your site

I'm going to close this issue since the error is now closer to the suggested error message, and there's a new issue https://github.com/wordpress-mobile/WordPress-iOS/issues/14397 with further suggested improvements to the current behavior.
