### ISSUE TITLE
Upgrade Zendesk SDK to 3.0.0

### ISSUE THREAD

**Issue by jkmassel** [wordpress-mobile/WordPress-iOS#12107]
Currently, the Zendesk SDK is at version `2.3.1`. 

There's a new major version available at: https://github.com/zendesk/zendesk_sdk_ios/releases/tag/3.0.0

It appears to be bug fix release made backwards-incompatible by the addition of another required library.

This is a technical debt task. At this point, we'd like to scope it out for possible inclusion in groundskeeping. It's marked as medium priority because we need to stay on top of these SDK changes until they're no longer tied to a specific Xcode version.

**Comment by frosty** [comment]
I just tested updating the pod to 3.0.1, and I don't see any issues – it just seems to work. Is there any reason we shouldn't just do this? Without adding any imports for the new library it just seems to work. Could be because we're not using the UiConfiguration class directly?

**Comment by jkmassel** [comment]
If we have the bandwidth to test it _extensively_ this cycle, we could include it in 13.0. In the past, things have broken when we upgraded the SDK, even just between minor versions, so I'd just want to be _really_ sure it'll be stable :) 

@designsimply – WDYT?

**Comment by designsimply** [comment]
@jkmassel the biggest concern at the moment is helping unblock users who have reported not being able to use the Contact Us form. It sounds to me like we don't really have a lock on whether an SDK update will do that yet (we need more reports/more data/more steps to reproduce for that case). Because of that, I don't think it's urgent enough to push into 13.0 but would like to get something on the roadmap to update the Zendesk SDK before iOS 13 comes out because it will likely help us to be on the latest SDK when we want to test the next Zendesk SDK release for iOS 13 compatibility.

Moved this to the `Prioritized iOS` list in Groundskeeping because if it can be done within a maintenance rotation then it will help move other issues forward. If it cannot, then I will recommend making it a project for a product team instead of trying to tackle it as maintenance where the amount of time and number of people is a bit more limited.

Another possibility would be to start a project to switch from using the Zendesk SDK to the Zendesk API by building our own integration.

Possibly related: https://github.com/wordpress-mobile/WordPress-iOS/issues/12145

**Comment by frosty** [comment]
Fwiw, when testing with 3.0.1 I was still getting a crash when trying to add media to a ticket from my camera or device media library (the small selection of recent media worked fine though).

**Comment by designsimply** [comment]
@frosty your comment led me to figure out some solid testing steps for the crash report at https://github.com/wordpress-mobile/WordPress-iOS/issues/11397 and I left a comment at https://github.com/wordpress-mobile/WordPress-iOS/issues/11397#issuecomment-516569278 with testing steps and notes.

@jkmassel as discussed on Slack, we'll go ahead and update from Zendesk SDK 2.3.1 to 3.0.1 and add a line item to the WPiOS 13.0 call for testing to make sure it gets tested—internally only though because we don't want to clobber people with Testflight updates and the plan is to revert if we find an unreasonable amount of breakage in the Profile > Help & Support > Contact Us screen.

**Comment by charliescheer** [comment]
Responding to 2258325-zen per the message we received

**Comment by designsimply** [comment]
Noting this was tested as part of 13.0 beta testing but still needs further testing.

<sup>(internal reference: p5T066-XE-p2#comment-3346)</sup>

**Comment by designsimply** [comment]
I've added this to the 13.1 calls for testing today, see https://make.wordpress.org/mobile/2019/08/15/call-for-testing-wordpress-for-ios-13-1/#comment-19647 and https://wordpress.slack.com/archives/C02RQC4LY/p1566235079030600. ❤️
