### ISSUE TITLE
Quick Start v2: VoiceOver: consider providing a hint on what will happens after activating the tour

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#12130]
Steps to reproduce:

1. Go to Settings > General > Accessibility > VoiceOver and toggle the setting on.
1. Open a site in the app which has Quick Start v2 enabled or create a new site and select the option for quick start at the end of Site Creation ([screenshot](https://user-images.githubusercontent.com/1119271/61245040-d95f7700-a708-11e9-84ea-7ad966003389.png)).
1. Try to understand what this screen is for with eyes closed.

**Result:** when the Quick Start tour is first opened, the purpose and that it's a checklist might be obvious to most users though it may not be clear for VoiceOver users. It would be good to set a hint on what will happens after activating the tour. ([23s](https://cloudup.com/cRHXP_npaag))

<img src="https://user-images.githubusercontent.com/1119271/61247023-7b815e00-a70d-11e9-9a6a-ee68633c71f0.png" width="270" alt="wpios-quick-start-opt-in"> <img src="https://user-images.githubusercontent.com/1119271/61247021-7ae8c780-a70d-11e9-80d2-25815a37adbe.png" width="270" alt="wpios-quick-start-customize-your-site">
<sup>Tested with WP Internal 12.8.0.201907011 on iPhone 6S iOS 12.3.1.</sup>

<p style="clear:both;"><sub>(internal reference: p77Llu-bQ6-p2 h/t @etoledom)</sub></p>

**Comment by mindgraffiti** [comment]
>when the Quick Start tour is first opened, the purpose and that it's a checklist might be obvious to most users though it may not be clear for VoiceOver users.

That's a good point. However it's not possible to do in the current code with the current UI. We would need additional design work and additional UI.

What you're asking for is a summary of the page. The best place in the current UI to put a summary would be on the page title ("Customize Your Site"). `navigationItem.title` is a plain string and [not built for adding accessibility hints](https://stackoverflow.com/questions/37283596/setting-accessibility-hint-to-uinavigationitem).  Side note: [this answer](https://stackoverflow.com/a/37535675/4150507) is not valid because it's suggesting creating a page title as a button, just so an accessibility hint can be added. That's misusing the UI, because they created a "useless" button that doesn't execute an action.

We could add a row with plain text that summarizes the checklist. Then VoiceOver could read it and treat it the same way any other user would. 

I suggest closing this issue because the main My Site navigation has other ways to solve this problem. There are accessibility hints supported in the "Customize Your Site" row and "Grow Your Audience" row [in this PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/14289/files). So if the user closes out of the modal and has VoiceOver read the Next Steps section, a summary is read to them for both rows.

**Comment by mindgraffiti** [comment]
I also considered adding a summary to the Fancy Alert buttons ("Yes, Help Me") but determined that it was too much information. Putting a summary on the button overloads the button's responsibilities.

**Comment by kean** [comment]
Quick Start is removed in 25.3 – closing.
