### ISSUE TITLE
Domain Credit: domain registration phone validation fails if you use a "+" symbol in the country code

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#12181]
To prepare:

1. Setup a WordPress.com blog and apply a plan to it.
1. Do not register the domain yet.
1. Have an external keyboard connected to your device.

To test:

1. In the app, go to My Sites > {site} > Register Domain.
1. Fill out the "Domain contact information" form.
1. Using an external keyboard, enter "+1" for the country code.
1. Tap the "Register domain" button.

**Result:** if a "+" symbol is included in the country code in the "Domain contact information" form then the form fails saying, "Please enter a valid phone number." ([42s](https://cloudup.com/cwLRUkbYXm5))

**Suggestions:** either allow users to enter a plus symbol in the country code field and account for that in form validation or change the country code field into a dropdown to match Calypso.

<img src="https://user-images.githubusercontent.com/1119271/61658175-0ae4bf00-ac82-11e9-8f83-8c0d5032e187.png" width="270" alt="please-enter-a-valid-phone-number">
<sup>Tested with WPiOS 12.8.1 on iPhone 6S iOS 12.3.1</sup>

<sub>h/t @rfaile313 for the report in Slack p1563811379004200-slack-cellular-happiness</sub>

**Comment by elibud** [comment]
Ping @jklausa

**Comment by rfaile313** [comment]
User report in 2197458-zen

>I have this problem with my phone number. Why it doesn’t take it ?

**Comment by jklausa** [comment]
I'll take that on as part of groundskeeping / hack week!

**Comment by rfaile313** [comment]
Another report in #2200396-zen

>I’m trying to register a domain however when I enter my country’s area code 001 and my 10 digit phone number for the US it’s telling me my phone number is wrong. What exactly is wrong???

**Comment by thehenrybyrd** [comment]
Another in #2199725-zen

Basically we need to make the validation on this screen better over all. In this case, the user hasn't entered a country code because people in the US don't know about country codes (honest).
Ideally we'd fill in the country code automatically based on the stated Country, and the user could edit if their phone number doesn't come from that country.
We should also allow the formats +000, +00, +0 and 0, 00, 000, for the country code field ideally.

![IMG_1810-23-07-19-19-09](https://user-images.githubusercontent.com/15107387/61780546-6b533800-ae0b-11e9-974d-e9526dddc42b.png)
