### ISSUE TITLE
[Auto-upload Published] Publish button in draft's success notice should auto-upload it

### ISSUE THREAD

**Issue by shiki** [wordpress-mobile/WordPress-iOS#12362]
📣 Part of #12240. Please use the `issue/12240-master-branch` as the target branch. 

**Waited on : https://github.com/wordpress-mobile/WordPress-iOS/pull/12466**

When a draft is successfully uploaded, we show a notice like this:

<img src="https://user-images.githubusercontent.com/198826/63533362-e02c9700-c4c9-11e9-9739-8bb14c50f33a.png" width="320">

Tapping on the **Publish** button on that notice should mark the post as “confirmed for auto-uploading“. If the user is offline, the post will be automatically published later. 

## Tasks 

- [ ] Possibly add a test in `PostNoticeViewModelTests`. Mocks for `PostCoordinator` have been added in #12358 so perhaps we should wait for that to be merged.

**Comment by yaelirub** [comment]
@shiki,
So this seems pretty simple and should be fixed by adding `post.shouldAttemptAutoUpload = true`and save to context
in `PosticeNoticeViewModel's publishPost()` but since we are checking for hasRemote in:
https://github.com/wordpress-mobile/WordPress-iOS/blob/c1d32840deca04240a7ff1d26a843b5b37add607/WordPress/Classes/Services/PostAutoUploadInteractor.swift#L30
Posts that has been uploaded as draft will return `.nothing` for their action (as oppose to .upload which the status the autoUploader checks for auto uploading. 

My question is why do we have the hasRemote check?

**Comment by yaelirub** [comment]
closed with #12523
