### ISSUE TITLE
Page Settings Option Labeled as Post Setting

### ISSUE THREAD

**Issue by charliescheer** [wordpress-mobile/WordPress-iOS#12374]
When you are editing a page in iOS if you click on the options button, the new menu that appears shows the title of the settings as  "Post Settings"  instead of page settings.

<img src="https://cdn-std.dprcdn.net/files/acc_593859/Bu8iNT" />

Probably a low priority to fix this, but since the settings available for Pages and Posts are different it would be clearer if the settings said Page instead of Post.

To replicate:
Go to My site > Pages > Options Menu

The selection in the menu is title Post Settings and when you load the settings page it also says Posts

**Comment by designsimply** [comment]
Tested and confirmed that My Site > Pages > More menu says "Post Settings" instead of "Page Settings."

<img src="https://user-images.githubusercontent.com/1119271/65198745-832cee00-da41-11e9-82d3-75513db2c98c.PNG" width="270" alt="IMG_3078"> <img src="https://user-images.githubusercontent.com/1119271/65198747-832cee00-da41-11e9-9447-aa4ee50b5245.PNG" width="270" alt="IMG_3079">
<sup>Tested with WPiOS 13.2.1.2 (TestFlight) on iPhone 6S iOS 13.1.</sup>

**Comment by negna1** [comment]
if this issue is still open i would like to work on that

**Comment by charliescheer** [comment]
I just checked and confirmed this issue is still there.  @negna1  go for it!
