### ISSUE TITLE
Universal Links: App accepts draft post links but does not open editor

### ISSUE THREAD

**Issue by antons** [wordpress-mobile/WordPress-iOS#12388]
iA Writer iOS app includes a custom WordPress sharing feature. The sharing feature does not use the sharing extension included in the WordPress app. The sharing feature uploads posts (including local images) as drafts to Jetpack-enabled sites, and opens them in Safari for users to verify and publish. WordPress iOS app intercepts these URLs, but doesn’t open the post editor.

#### In iA Writer

1. Create a document in iA Writer.
2. Open the document and tap the share icon at the bottom.
3. Select the “New Draft on WordPress” action (this is a custom iA Writer action, NOT the WordPress sharing extension).

#### Programmatically

Open a valid `https://wordpress.com/post/{blog_id}/{post_id}`link to a draft post on from an iOS app using `-[UIApplication openURL:options:completionHandler:]`.

### Expected behavior
Best: WordPress iOS app opens a post editor.
Good: WordPress iOS app ignores the link and allows it to be opened in Safari, where the user can edit the blog post.

### Actual behavior
WordPress iOS app intercepts the URL, but shows My Sites → {site_name}. This is confusing.

**Comment by designsimply** [comment]
Steps to reproduce:

1. Create a document in iA Writer (I tested with v5.2.8).
1. Open the document and tap the share icon at the bottom.
1. Select the WordPress app icon.
1. Observe the draft of the post for review and tap "Next".
1. Tap "Publish".

**Result:** a post is created and published without opening the post in the editor. ([30s](https://cloudup.com/cmusNj-t3F4))

I do feel this is by design but I don't know the reasoning behind the decision. @frosty is this something we want to consider keeping as a feature enhancement request or is there a technical reason for not opening the editor when using the share extension?

<img src="https://user-images.githubusercontent.com/1119271/65200438-00f1f900-da44-11e9-870b-dc373028a15b.png" width="270" alt="publishing-post">
<sup>Tested with WPiOS 13.2.1.2 (TestFlight) on iPhone 6S iOS 13.1.</sup>

**Comment by antons** [comment]
@designsimply This issue is NOT about the sharing extension included with WordPress app. 

Steps to reproduce:

1. Create a document in iA Writer.
2. Open the document and tap the share icon at the bottom.
3. Select the New Draft on WordPress action (this is a custom iA Writer action, NOT the WordPress sharing extension).

**Comment by designsimply** [comment]
@antons just adding a quick note to say I tested this in WPiOS 13.4 beta and it's working for me now (and I think I'm using the correct custom extension this time around, thanks for noting that): [13s](https://cloudup.com/c6Jjrlkqyix).

Note: I had a bit of trouble getting it to work at first and it seemed to just time out after I tapped the share icon then "Share…", but eventually it worked!
