### ISSUE TITLE
Reader: Quote style extends too far vertically when post begins with a quote

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#12456]
### Expected behavior

I expect quotes in Reader posts to have a vertical left border extending the height of the quote itself.

### Actual behavior

If the quote is the first thing in the post, the left border extends over the post title:

<img src="https://user-images.githubusercontent.com/8658164/64182364-09e9a480-ce60-11e9-82f6-2e886b94330b.PNG" width="50%">

##### Tested on [iPhone XS], iOS [12.4], WPiOS [13.2.0.20190827]
Also tested in WPiOS 13.1 (app store) and the issue does not exist there.

**Comment by elibud** [comment]
@danielebogo can this be a regression caused by dark mode changes?

**Comment by danielebogo** [comment]
@elibud @rachelmcr running 13.1 I saw the quote bar is extended but hidden by the white background.
<img width="441" alt="Screenshot 2019-09-05 at 10 55 15" src="https://user-images.githubusercontent.com/912252/64332088-d75cba80-cfcb-11e9-90ea-650ed4a38ca6.png">

Dark mode changes made it visible due to the clear backgrounds. I can fix those as before supporting the dark mode, but the bar needs to be fixed separately I think.

**Comment by rachelmcr** [comment]
This was fixed in https://github.com/wordpress-mobile/WordPress-iOS/pull/12479.
