### ISSUE TITLE
Reader: Gradient visible on left and right edges of the author/timestamp on post detail

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#12457]
### Expected behavior

I expect the Reader post detail to show the author's Gravatar, display name, and post timestamp on a white background.

### Actual behavior

The Reader post detail shows a gradient just to the left of the author's name (between the name and Gravatar) and all the way on the right side:

<img src="https://user-images.githubusercontent.com/8658164/64183018-13274100-ce61-11e9-9839-1df62add22eb.PNG" width="33%" alt="IMG_0348">

##### Tested on [iPhone XS], iOS [12.4], WPiOS [13.2.0.20190827]
Also tested in WPiOS 13.1 (app store) and the issue does not exist there.

**Comment by elibud** [comment]
@danielebogo just mentioning you in case you miss the item being added to the Master Issue.

**Comment by designsimply** [comment]
This came up again during the Reader Improvements projects after switching to the new webview-based Reader detail view and appears fixed by https://github.com/wordpress-mobile/WordPress-iOS/pull/14380. Props @frosty. 🎉

I tested the byline on individual posts in the Reader using WPiOS 15.2.0.0 TestFlight beta on iPhone 11 iOS 13.5.1 after switching the device appearance to light and dark mode and also changing the in-app appearance settings to light, dark, and system default in App settings and I wasn't able to see the errant gradient edges. 👍
