### ISSUE TITLE
SIWA: Logged in to wrong wpcom account after disconnecting on Apple side

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#12464]
### Expected behavior
If I disconnect from WordPress in my Apple ID account, I expect it to completely disconnect SIWA for my wpcom account.

### Actual behavior
After I disconnected from WordPress in my Apple ID account and tried logging in again, I ended up **logged in to the wrong account**.

### Steps to reproduce the behavior

1. I logged in using SIWA while **hiding** my Apple email. This created a new WordPress.com account with a proxy Apple email address.
2. I logged out of the app.
3. In my Apple account, I disconnected from WordPress. (I did not make any changes in my WordPress.com account.)
4. In the app, I logged in using SIWA and shared my **real** Apple email.

Result: I was logged in to the WordPress.com account using my proxy email address, which had been de-authorized from Apple’s end.

**Comment by ScoutHarris** [comment]
Hey @rachelmcr . I'm not sure this is actually a bug. When logging in with Apple, Apple has a User ID associated with an Apple ID. When logging either way (using a proxy email or real email) the User ID is the same because you're using the same Apple ID. Which is why you're logging into the same WP account.

I don't see a way around this (and I'm not sure we should).  @astralbodies do you have any thoughts on this?

**Comment by ScoutHarris** [comment]
Also - 

> If I disconnect from WordPress in my Apple ID account

This doesn't block WP from using your Apple ID. It only revokes authorization to use it. Since you're logging into the WP app with the same Apple ID, you're actually re-authorizing WP on that Apple ID. (i.e. it's behaving as it should)

**Comment by rachelmcr** [comment]
> When logging either way (using a proxy email or real email) the User ID is the same because you're using the same Apple ID. Which is why you're logging into the same WP account.

Thanks for that clarification! It's a strange experience when I expect the connection to be based on email address (rather than User ID, which I wasn't aware of) but I can see how it works now.

One related issue to this scenario is that I will end up with a WordPress.com account linked to the (now non-functional) proxy Apple email address that was used when I first created the account. I can log in using my Apple ID, but I can't receive any emails from WordPress.com and I might not realize that my email address hasn't changed. If the re-authorization in this scenario is expected behavior then we might want to consider what we can do to notify the user about the non-functional wp.com account email address / help them update that account email to one that works.

**Comment by ScoutHarris** [comment]
I agree, it isn't exactly clear what happened.

> notify the user about the non-functional wp.com account email address / help them update that account email to one that works.

I'm not sure how we'd go about doing this. I'll do some more testing in the app and see what information we can glean from Apple in this scenario.

Also, ping @designsimply in case users get confused.

Since this isn't really a bug, I'm closing this issue.
