### ISSUE TITLE
SIWA: checkAppleIDCredentialState when CredentialState is .notFound

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#12572]
Related issue: #12399 

### Expected behavior

When removing WordPress as a connected app on id.apple.com, I'd expect to be logged out of the app upon launch.

### Actual behavior

When launching the app after performing the steps I did below the user was not logged out.

### Steps to reproduce the behavior

1. Build and run. Make sure you're signed in with SIWA.
2. Go to id.apple.com, log in, and remove WordPress as an app for Sign in with Apple.
3. Background the app and kill the app.
4. Relaunch the app.
5. User is not logged out.

Console mentions:

```2019-09-27 13:00:04.862899-0500 WordPress[1426:1723064] [core] Credential State request returned with error: Error Domain=AKAuthenticationError Code=-7074 "(null)"
2019-09-27 13:00:04:867 WordPress[1426:1723064] checkAppleIDCredentialState: Apple ID state not found: The operation couldn't be completed. (com.apple.AuthenticationServices.AuthorizationError error 1000.)```

The CredentialState in this case is `.notFound` so the user isn't being logged out.


##### Tested on iPhone 6s Plus, iOS 13.0 GM, WPiOS branch `issue/12535-siwa_handle_revoked_credential`

**Comment by ScoutHarris** [comment]
After some testing, it appears Apple has changed (fixed?) the `CredentialState` for the scenario @astralbodies noted.
- iOS 13.0 returns `notFound`
- iOS 13.1 return `revoked`

@astralbodies and I discussed it, and agreed this is an acceptable edge case, instead of handling 13.0 and 13.1 differently. 

To note, `notFound` is currently (and will still be) considered a valid state as this is the state when one uses an Apple ID for the first time.
