### ISSUE TITLE
[Dark Mode] My Ticket has white text

### ISSUE THREAD

**Issue by danielebogo** [wordpress-mobile/WordPress-iOS#12604]
Profile > Help & Support > My Tickets screen is still light colored:

<img src="https://user-images.githubusercontent.com/1119271/65921511-a9d31900-e39f-11e9-8518-97cae36a6d2c.PNG" width="270" alt="IMG_3107">

**Comment by danielebogo** [comment]
@designsimply @frosty @ScoutHarris this is a Zendesk SDK issue and the new version `3.0.2` fixes it. I would create another Issue to update Zendesk and see it it also fixes #12297

**Comment by ScoutHarris** [comment]
> I would create another Issue to update Zendesk

My 2 cents - I agree with this. I would leave this issue and the other open until Zendesk is updated to be sure it actually fixes them.

**Comment by ScoutHarris** [comment]
Create https://github.com/wordpress-mobile/WordPress-iOS/issues/12701 to update Zendesk.

**Comment by designsimply** [comment]
I found that the text in Help & Support > My Tickets is now readable when testing #12770—it's black text on a light gray background instead of white text on a light gray background. 👍

<img src="https://user-images.githubusercontent.com/1119271/67602296-89df0d00-f733-11e9-9b18-228f478a02da.PNG" width="270" alt="IMG_2982 1">
<sup>Tested with 13.5(dev) branch `update/zendesk-to-3.0.2` on iPhone 6S iOS 13.1.3.</sup>

**Comment by ScoutHarris** [comment]
Fixed with https://github.com/wordpress-mobile/WordPress-iOS/pull/12770.
