### ISSUE TITLE
App extensions not configured on login

### ISSUE THREAD

**Issue by frosty** [wordpress-mobile/WordPress-iOS#12697]
### Expected behavior

Once I've logged into the app with my WordPress.com account, I should be able to use the share extension to share content to my site. I should also be able to long press on system notifications to view more detail about them.

### Actual behavior

After logging in, if I attempt to share something from another app (for example, Safari), I'm told that the share extension is not configured and I'm unable to share:

![IMG_BF1ECA9F8244-1](https://user-images.githubusercontent.com/4780/66835152-ed5c8400-ef56-11e9-99d7-1eb653508643.jpeg)

Likewise, if I tap and hold on a system notification, it fails to expand to show me additional content.

It seems as though the necessary auth tokens for the extensions are not being setup up correctly any more.

@danielebogo did some sleuthing, and it seems that `setupShareExtensionToken` is never called. `setupWordPressExtensions` _is_ called but in AccountService's `setupAppExtensionsWithDefaultAccount`, `defaultBlog` is always nil. This means that the block to remove all extension tokens is called:

```
dispatch_async(dispatch_get_main_queue(), ^{
            TodayExtensionService *service = [TodayExtensionService new];
            [service removeTodayWidgetConfiguration];

            [ShareExtensionService removeShareExtensionConfiguration];

            [NotificationSupportService deleteContentExtensionToken];
            [NotificationSupportService deleteServiceExtensionToken];
        });
```

Does anybody know of anything that's changed recently that could affect these behaviours? The only things I'm aware of that could be even vaguely related are SIWA (ping @ScoutHarris) and the changes to merge accounts (ping @aerych).

### Steps to reproduce the behavior

- Run the app on a device – I did a fresh install from the App Store.
- Sign into the app.
- Navigate to another app and attempt to use the WordPress share extension.

**Comment by aerych** [comment]
It seems that visiting the Me tab before using the share extension prevents the glitch. 🤔

**Comment by aerych** [comment]
Looks like this glitch can be traced back to [this PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/12400). 

Prior to #12400, the call to fetch account details was made after an account was created and its blogs synced. To address some of the dup account/blog issues we were seeing, this call was [moved](https://github.com/wordpress-mobile/WordPress-iOS/pull/12400/files#diff-ea93f07ae7d3a5c24691e0430a280691L31) so we fetch account details before creating an account.  This was done so we'd have the account ID, username, etc. handy when attempting to de-dup.  The glitch described in this issue stems from moving the call to fetch account details.

The fetched account details include the ID of the primary blog, (or default blog as represented in core data). Prior to #12400, the user's blogs would already be synced and present in the app. When the call to fetch account details was completed, `AccountService updateAccount:withUserDetails` would be called.  It, in turn, would call `AccountService configurePrimaryBlogWithID:account:` which fetches the blog from core data and assign it to the defaultBlog relation on the Account instance.  The code expects the blog to exist at this point.  

The easy fix would be to restore the call to update user details after syncing blogs, but I wonder if it might be better to update the Account model to store the primary blog ID and lazy load the defaultBlog rather than rely on a relation. 

Thoughts?

**Comment by designsimply** [comment]
Noting this is a duplicate report of https://github.com/wordpress-mobile/WordPress-iOS/issues/12674 but I am closing 12674 in favor of 12697 as this issue has more follow-up detail. 🙂
