### ISSUE TITLE
Discrepancy in badge counts

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#1281]
There is a discrepancy between the seen flags on a PN in the app vs what's being pushed with badge reset.  I suspect the logic behind the blue dot is at fault in this case.

![img_0026](https://f.cloud.github.com/assets/373903/2295441/ec2a1492-a08f-11e3-85bb-b82439c3d825.PNG)

**Comment by jleandroperez** [comment]
I've just tested the following scenarios:

#### Scenario A:
1. Fresh install WPiOS
2. Log into your dotcom account
3. Close tha app and receive a push notification.
4. Open WordPress.com in your browser, and hit the Notifications button.

As a result, the app gets the reset message, and the count goes to zero.

#### Scenario B:
1. Fresh install WPiOS
2. Log into your dotcom account
3. Close the app and receive a push notification.
4. Open the app and tap over the Notifications tab. 
5. Note that the badge is reset
6. Close the app
7. Receive another push notification

As a result, the app's badge will display a (1), because the previous push was marked as read.

--

I'm closing this issue as cannot repro, since it probably got solved with the new notifications backend.
If anything, please, feel free to reopen.

Thanks!
