### ISSUE TITLE
Stats: The message "An error occurred" shows on the Insights tab

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#12945]
Steps to reproduce:

1. Log in to a WP.com account
2. Select a regular WP.com account (free plan, free domain)
3. Go to Stats
4. Open the Insights tab
5. Scroll down and notice any "An error occurred" messages
6. Add more cards and again look for errors 
7. If no errors occur, try different sites until you see errors 

| <img src="https://github.com/wordpress-mobile/WordPress-iOS/assets/1898325/69b989eb-f71b-43b1-80b9-16accdda8797" /> | <img src="https://github.com/wordpress-mobile/WordPress-iOS/assets/1898325/4bfe8244-b047-45f0-a5e1-069e21addc00" /> |
| - | - |

**Comment by elibud** [comment]
@frosty can someone from your team look at both the iOS and Android issues? It might be that the site is taking a bit to sync so we may want to display a better message here.

**Comment by frosty** [comment]
Sure, we can take a look at this 👍

**Comment by staskus** [comment]
## Update

I could reproduce the issue.

"An error occurred" on some cards appears because we receive data successfully but it's in the wrong format than the parser implemented in `WordPressKit` expects. The parser fails because some fields are missing. 

For example, we get `jsonResponse`:

```
▿ 3 elements
  ▿ 0 : 2 elements
    - key : "country-info"
    - value : 0 elements
  ▿ 1 : 2 elements
    - key : "date"
    - value : 2023-01-18
  ▿ 2 : 2 elements
    - key : "days"
    - value : 0 elements { ... }
```

and we try creating `StatsTopCountryTimeIntervalData` out of it. However, because [there's no `views` field](https://github.com/wordpress-mobile/WordPressKit-iOS/blob/6d6c6aad1dfcecda3eedf6397326d3fb2a20a366/WordPressKit/Time%20Interval/StatsTopCountryTimeIntervalData.swift#L47), the parsing [fails with `ResponseError.decodingFailure`.](https://github.com/wordpress-mobile/WordPressKit-iOS/blob/6d6c6aad1dfcecda3eedf6397326d3fb2a20a366/WordPressKit/StatsServiceRemoteV2.swift#L136)

Based on this, I don't see a direct connection with a Jetpack installation and these errors. I can reproduce the same issue after creating a fresh .com site. 

### Potential Solution

Based on this finding, we could consider:
a) be more relaxed in our decoding strategy and return an empty entity, or `.empty` status, instead of `.decodingError` 
b) treat a `.decodingError` as an "Empty" state in the cards

It's also suggested to show "a welcome screen instead" if all the Stats are empty, however, showing the possible selection of cards and correctly displaying that they don't have data yet may be a better solution.

### Priority

- Frequency: The issue happens always and affects new sites
- Severity: The issue does not break Stats behavior but misleads the users while the site Stats are empty 

Priority: Low

**Comment by guarani** [comment]
I also see "An error occurred" on some parts of the screen on established sites (not fresh sites) when loading the Months or Years tabs.

**Comment by staskus** [comment]
> I also see "An error occurred" on some parts of the screen on established sites (not fresh sites) when loading the Months or Years tabs.

@guarani, thanks for reporting. The error is quite generic, so there can theoretically be different types of failures. For empty sites, it happens because parsing fails due to an expected field missing. However, maybe the same thing is happening for established sites as well.

**Update:** The issue is reproducible with the [en.blog.wordpress.com](en.blog.wordpress.com) site

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by staskus** [comment]
More information from @guarani:

> I tried a few setups and these errors weren't 100% reproducible but happened in maybe 1 out of 3 tries:
> - Existing account, existing Simple site, custom domain: Seeing "An error occurred" on Insights (Views & Visitors, Total Likes, Total Comments, Most Popular Time).
> - Existing account, existing Simple site, free domain: Same issues as above, also see the error on Insights (This Year, Posting Activity)
> - Existing account, existing Atomic site, free domain: Seeing "An error occurred" on Insights (Most Popular Time).

> these established sites were testing sites and had very little traffic.

**Comment by staskus** [comment]
This is also one more big reason why "An error occurred" is shown. We load an `error` state by default from the cache if the value doesn't exist. Sometimes there simply be no value, for example, no latest post, so this logic can generate "An error occurred" for all the cards.

![image](https://github.com/wordpress-mobile/WordPress-iOS/assets/4062343/75de6f0b-85cd-4dcb-b3bd-ae104647bdbd)
