### ISSUE TITLE
“Local Changes” label persisting alongside pages that have been saved remotely in Aztec

### ISSUE THREAD

**Issue by SiobhyB** [wordpress-mobile/WordPress-iOS#13023]
### Expected behavior

The **Local Changes** label shouldn't appear alongside pages that have been saved remotely.

### Actual behavior

The **Local Changes** label persists alongside pages in Aztec, even when changes are saved remotely.

This was reported in 2524786-zen and @rachelmcr came up with the steps to replicate when discussing in p1575019654140300-slack-cellular-happiness.

This is specific to pages (doesn't happen with posts) and the Aztec editor (doesn't happen with Gutenberg).

### Steps to reproduce the behavior

1. Start with a page created in Aztec or the web classic editor.
2. Open the page in the app and edit it.
3. Update the page and confirm the changes are saved/uploaded.
4. Exit the editor and notice that the page now has the “Local Changes” label even though the changes were saved remotely.

##### Tested on iPad Pro, WPiOS 13.6

**Comment by zdenys** [comment]
Another report in 2536903-zen. Posts (not Pages) that have been published already on the site are still appearing in the app in Draft and Scheduled tabs respectively with annotation `Local changes` below them.

**Comment by rachelmcr** [comment]
@zdenys The case in 2536903-zen looks more like the issue reported in https://github.com/wordpress-mobile/WordPress-iOS/issues/9449, where a post is still listed as a draft in the app even though it was published remotely (so the versions of the post in the app and on the web are different). As noted on that issue, the user should be able to open those posts in the app and discard local changes (to sync the post with the remote/web version). Could you try that and follow up on that issue if it isn't resolved?

This issue is specifically about pages where there is no difference between the version in the app and on the web, but the "Local Changes" label still appears.

**Comment by zdenys** [comment]
>The case in 2536903-zen looks more like the issue reported in #9449, where a post is still listed as a draft in the app even though it was published remotely (so the versions of the post in the app and on the web are different).

Indeed. Thanks for pointing that out.

>As noted on that issue, the user should be able to open those posts in the app and discard local changes (to sync the post with the remote/web version). Could you try that and follow up on that issue if it isn't resolved?

I sent a follow-up to the user. And commented on #9449 instead. Thank you!

**Comment by yaelirub** [comment]
This appears to be happening in posts as well: p4a5px-2vt

**Comment by sarahfg** [comment]
Another report that 

> published posts on my website still appear under Drafts with ‘local changes’ on the app

#2670813-zen

**Comment by rezzap** [comment]
We have another report of this here:

#2749243-zen 

Post is published, available on the website and shows as online when viewed in wp-admin. However, in the app shows under 'future' with Local Changes.

**Comment by sarahfg** [comment]
Another report here: #2756940-zen . User's most recent post shows as a draft in their app. They are using Aztec

**Comment by rezzap** [comment]
Another report in #2744980-zen

The content of the page in the app with the 'local changes' label does not match what they see in the published version. My understanding is that they can't open the page in the app as it forces them to update which means their content would then be overwritten. 

Pages were built with Aztec so they open in the Classic Editor, but they use the Block Editor by default in the app for this site. 

iPhone  6Plus 12.4.5 | WordPress app 14.2
iPad mini (5th gen) 13.3.1 | WordPress app 14.1

**Comment by rachelmcr** [comment]
Any cases where the content in the app _doesn't_ match what's on the web is probably best tracked in https://github.com/wordpress-mobile/WordPress-iOS/issues/9449, since that issue is specifically about issues with how to resolve local changes and conflicts between web (remote) and app (local).

This issue is meant to track cases where the Local Changes label is applied even though the post/page has been saved remotely.

Once thing I noticed while doing some related tested was that at least with certain post content I could reproduce this with posts by doing the following steps:

1. Create a post in the block editor. (This may require some specific kind of block content; I haven't identified exactly what causes it but I do have some sample content that reproduces it consistently.)
2. In the app, open the post in the editor and then switch to the classic editor.
3. Make an edit in the classic editor and update the post.

At least in some cases, this will cause the Local Changes label to persist even though the update is synced remotely. It seems to be specifically caused by a flow where you switch from the block editor to the classic editor in the app while editing the post.

**Comment by kean** [comment]
The "local changes" scenario was eliminated in the scope of pcdRpT-6vS-p2. I believe this issue no longer applies.
