### ISSUE TITLE
Quick Start: Site Icon tour doesn't highlight the site icon on screen

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#13071]
### Expected behavior

In a Quick Start tour, I expect a blue dot to appear on screen any time I'm instructed to tap, to guide me to the right place on screen.

### Actual behavior

In the Site Icon tour, it tells me "Tap Your Site Icon to upload a new one" but it doesn't show me on screen where that is.

### Steps to reproduce the behavior

1. Create a new site in the app.
2. When prompted, accept more help getting started to get the Quick Start tours.
3. Select the "Upload a site icon" tour.
4. Notice that the prompt comes up but the site icon isn't highlighted on screen.

<img src="https://user-images.githubusercontent.com/8658164/70559995-a4eccb80-1b7f-11ea-97ed-1e1ee5993edf.png" width="50%">

**Comment by diegoreymendez** [comment]
Hey @rachelmcr - there are some important UI changes in `develop` (bleeding edge).  I am seeing that the icon is highlighted appropriately.  Could you confirm if that's the case?

This is what I'm seeing:

<img width="541" alt="Screen Shot 2020-03-04 at 7 09 12 PM" src="https://user-images.githubusercontent.com/1836005/75927938-20db7480-5e4c-11ea-81d7-6e75318dc02f.png">

/cc @frosty since I believe these improvements are coming from your team.  Do you happen to know if this is coming out in 14.4?  Is it feature flagged? (I saw a `.meMove` flag which looks related)

/cc @yaelirub

**Comment by ScoutHarris** [comment]
cc @bjtitus (pretty sure this has been fixed)

**Comment by bjtitus** [comment]
@diegoreymendez @rachelmcr The new UI was enabled in 14.3 so this bug should not be present in any future releases.

**Comment by diegoreymendez** [comment]
I’m closing this and tagging it in the 14.3 milestone.
