### ISSUE TITLE
New post/page: The Title border is blue

### ISSUE THREAD

**Issue by ScoutHarris** [wordpress-mobile/WordPress-iOS#13246]
### Expected behavior
Using the block editor, when creating a new page/post, the Title border was previously grey.

![IMG_5EFB8DAD4F90-1](https://user-images.githubusercontent.com/1816888/72644727-fe8aa780-392e-11ea-8975-48365c99043a.jpeg)

### Actual behavior
Using the block editor, when creating a new page/post, the Title border is now blue.

### Steps to reproduce the behavior
Create a new post/page. Notice the blue box around the Title. 

iPad:
<img width="603" alt="Screen Shot 2020-01-17 at 1 30 29 PM" src="https://user-images.githubusercontent.com/1816888/72644745-09453c80-392f-11ea-8167-66d75988e1d0.png">

iPhone:
<img width="463" alt="Screen Shot 2020-01-17 at 1 30 48 PM" src="https://user-images.githubusercontent.com/1816888/72644754-0fd3b400-392f-11ea-8073-13d9fd507a44.png">

**Comment by oguzkocer** [comment]
I have looked into this issue in WPAndroid and although I didn't get anywhere concrete, my findings so far may be of help.

* Block Editor in Calypso also has a border for at least some blocks: https://cloudup.com/cDCHqmziOjf
* An inspection of the views in the Android Layout Inspector or Stetho's Elements tab didn't reveal anything useful except that the block highlighted has focus.
* On Android, I suspected maybe the focus was the issue because since API 26, if something has focus it can be highlighted with this property: https://developer.android.com/reference/android/view/View#attr_android:defaultFocusHighlightEnabled. However, I can see the border even in API 24. (I am still not 100% sure it's not related to this)
* The borders look exactly the same(?) on iOS and Android

I am fairly certain that these are added from the Gutenberg codebase, so it's probably best to get someone from the Gutenberg mobile team to have a look at it. They'd have more knowledge about how to debug things in React native and have the necessary tool setup.

Hope this helps!

**Comment by designsimply** [comment]
I asked @iamthomasbishop about this and here's what I found:

> Short version: that’s the expected style because of a change in border-color 😀
> 
> Long version: We switched to use stronger borders while working on some of the nested blocks work, but I also just [proposed a refinement](https://github.com/wordpress-mobile/gutenberg-mobile/issues/1802) to how we highlight selected blocks. I am also considering a slightly weaker border color, but I’d like to give it some time because I think it’s mostly noticeable because we’re used to seeing a very dim gray border.

Based on that feedback, I am closing this issue as works-as-expected. Thank you @ScoutHarris for raising the issue and @oguzkocer for looking into it and @iamthomasbishop for the design decsion explanation!
