### ISSUE TITLE
Notifications: Adjust Colors

### ISSUE THREAD

**Issue by jleandroperez** [wordpress-mobile/WordPress-iOS#13282]
### Details:

The purpose of this issue is to track pending Notifications Color updates mentioned in PR #13152.

We'd need to define:

- New Section Header BG Color
- New Cell Selection color
- New Background color (Undefined!)

Should we, then, replicate the UX we've got in My Sytes?

cc'ing @osullivanchris and @mattmiklic 

Gentlemen, working on this on your command! (Please bear in mind we'd need Dark + Light palletes).

**Comment by mattmiklic** [comment]
My thinking is that by using a white (black in dark mode) background rather than a grouped table view style (with an offwhite backgound behind white table cells) we could simplify the visual appearance and make unread items stand out more easily. Here's a quick mockup of what I'm thinking. The only change in light mode is to the background color of section headers. In dark mode, the section header color remains the same but the background of read notifications is now black.

<img width="1031" alt="Screen Shot 2020-01-27 at 12 48 27 PM" src="https://user-images.githubusercontent.com/1396552/73199968-e28fbe80-4103-11ea-8e27-7822ac092826.png">

**Comment by osullivanchris** [comment]
Love this, really simple solution! Thanks @mattmiklic I'm definitely happy to go this route. 

Its in line with the work you're doing on Android as well moving away from grey page backgrounds.
