### ISSUE TITLE
[GlobalStep] [Dark Mode] White content placeholders show when switching between different Posts List views

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/WordPress-iOS#13326]
### Description
When switching between tabs while viewing Blog Posts, while the ones that have content to be displayed do so gracefully, switching to empty tabs cause Empty Posts with blank lines to be displayed for a moment.

### Reproduction Rate
4/4 100%

### Expected behavior
Switching tabs while in Blog Posts should be graceful as it happens when loading Site Pages.

### Actual behavior
Switching to tabs that have no content to be displayed fill the screen with empty posts.

### Steps to reproduce the behavior
1. Install WordPress 14.1
2. Log in to an account.
3. Select a Site.
4. Navigate to Blog Posts.
5. Switch to the Scheduled tab.
6. Remove all scheduled posts.
7. Switch to another tab.
8. Switch back to the scheduled posts.

##### Tested on the following
iPad Pro 12.9” (13.1.2)
iPhone 8+ (13.1.2)

#### Please see the attached video for more information
[iOSBlogPostsTabs.zip](https://github.com/wordpress-mobile/WordPress-iOS/files/4133614/iOSBlogPostsTabs.zip)

### Submitted by:
Luis Pimenta

**Comment by designsimply** [comment]
Thanks for the report! What you're seeing is the loading placeholder, which is intentional, but it does look as though the lines aren't quite the right color when viewing in dark mode. ([27s](https://cloudup.com/ceCY-sR3oIW))

<img src="https://user-images.githubusercontent.com/1119271/73504141-9787dc80-438b-11ea-9a1a-4b9862bea1d4.png" width="300" alt="posts-list-placeholders-in-light-mode"> <img src="https://user-images.githubusercontent.com/1119271/73504142-9787dc80-438b-11ea-958e-13f8101dc81f.png" width="300" alt="posts-list-placeholders-in-dark-mode">

<sup>Tested with WPiOS 14.1.0.0 TestFlight beta on iPad Mini 4 (WiFi) (iPad5,1) iPadOS 13.3.</sup>
