### ISSUE TITLE
Information Architecture: Reader Navigation - UI

### ISSUE THREAD

**Issue by bjtitus** [wordpress-mobile/WordPress-iOS#13322]
Related issues

#13580
#13581
#13582

Design: https://wp.me/pauD4L-Dx

**Comment by Gio2018** [comment]
Hey @osullivanchris ! I started looking into the new reader navigation, and have a few questions

- Just confirming that when users tap on the filter (which defaults to all sites), a view will be shown containing the available sites or tags to follow. As reported here https://ministryofmagicp2.wordpress.com/2020/01/28/ia-project-my-site-ios/#comment-572:
  - There will be two tabs, one for 'Sites' and one for 'Tags'
  - This will be a popover on iPad, a bottom sheet on iPhone (both landscape and portrait?)
  - Users will be able to choose among one of the available options between sites and tags
  - Is all of the above correct?

- Looking at this design https://ministryofmagicp2.wordpress.com/2020/01/28/ia-project-my-site-ios/#comment-571 and this video: https://videopress.com/v/rxedOJxu, seems like the filter will only appear in the 'Following' tab of the main reader navigation, and will remain visible when the user scrolls down: is this correct?

- Still from this design: https://ministryofmagicp2.wordpress.com/2020/01/28/ia-project-my-site-ios/#comment-571, what will be the rules to show the simplified navigation banner (first time only, other?)

- What will the settings section exactly do? It seems that will replace the existing `Add Site` and `Add Tag` functionalities that we have on iOS, on two different tabs. What else should go in there? (Apologies for my lack of knowledge of the existing Android app..)

- The current search results return posts and sites, as shown in the video https://videopress.com/v/rxedOJxu, but look slightly different: `Posts` result include a `Follow` action on the top right of each post, while `Sites` result do not have a `Follow` action: does this mean that we need to change these two?

- Are there any significant differences between the current design in portrait mode, and the landscape on devices with regular horizontal size class?

That's it for now, thanks!!

**Comment by osullivanchris** [comment]
Thanks for the clarifications @Gio2018 

Q1 re sites/tags filter
> Is all of the above correct?

yes all of that sounds correct as far as I can tell. I think it should be a bottom sheet on iPhone landscape and portrait

> seems like the filter will only appear in the 'Following' tab of the main reader navigation, and will remain visible when the user scrolls down: is this correct?

yep the filter only applies to the 'following' tab. We made it sticky on Android as not all users discovered it in user research. We also changed the default title of the bar from "All sites" To "Filter" to make it a bit more of a call to action

> what will be the rules to show the simplified navigation banner (first time only, other?)

Good question. I think probably the first time the user opens the version containing the changes. Is that too lose?

> What will the settings section exactly do? It seems that will replace the existing Add Site and Add Tag functionalities that we have on iOS, on two different tabs. What else should go in there? (Apologies for my lack of knowledge of the existing Android app..)

The settings will allow the user to manage tags and sites. That's all I'm picturing for now. One thing we are losing with the top level list that we have today is the home for managing tags. So it makes sense to put it together with managing sites like we have on Android. So that will be a bit of a restructure on iOS

> does this mean that we need to change these two?

No I don't intend on making any changes there. Its probably just a difference between iOS and Android. In general there's lots of things I spotted that we could change in reader. But I've tried to keep it to just the main navigation. We could get lost diving too deep into reader. And we discovered on Android that even when we tried to address a couple of quick wins as side pieces of work while fixing things in reader, those quick wins were not even that quick either! 

> Are there any significant differences between the current design in portrait mode, and the landscape on devices with regular horizontal size class?

Still a couple of things to work through on this as discussed today. Will follow up tomorrow

**Comment by Gio2018** [comment]
Thanks for answering the questions @osullivanchris ! In regard to this one
> > what will be the rules to show the simplified navigation banner (first time only, other?)
> 
> Good question. I think probably the first time the user opens the version containing the changes. Is that too lose?
> 

I believe it's okay. The changes seem pretty intuitive, so users should not need to be reminded more than once that there has been a change in UI, I guess?

**Comment by osullivanchris** [comment]
> I believe it's okay. The changes seem pretty intuitive, so users should not need to be reminded more than once that there has been a change in UI, I guess?

Exactly. The changes should make the app easier to use, so we're not trying to make a tutorial to explain how to use it, or anything that heavy. I think its just about acknowledging to the user that something has changed as a courtesy, with the option to read about why if they are interested.
