### ISSUE TITLE
Information Architecture: Create Button

### ISSUE THREAD

**Issue by bjtitus** [wordpress-mobile/WordPress-iOS#13320]
Design: https://wp.me/pauD4L-wu-p2
Latest Updates: https://wp.me/pauD4L-nx-p2

![ios-my-site-blueprint](https://user-images.githubusercontent.com/3250/73475890-781e8e80-434e-11ea-9385-8ea783d34778.png)

- [x] Add feature flag. (https://github.com/wordpress-mobile/WordPress-iOS/pull/13474)
- [x] Add new Create Button (https://github.com/wordpress-mobile/WordPress-iOS/pull/13474)
- [x] Show/Hide Create Button. (https://github.com/wordpress-mobile/WordPress-iOS/pull/13555)
- [x] Add alert sheet to select Post or Page.
- [x] Ensure deep links are using new presentations. (The code for presenting a new post has not changed) (https://github.com/wordpress-mobile/WordPress-iOS/pull/13707)
- [x] Ensure views are correct for Dark Mode.
- [x] Move create button off of Tab Bar view controller and into BlogList or its navigation controller. (https://github.com/wordpress-mobile/WordPress-iOS/pull/13681)
- [x] Add Accessibility support.
  - [x] Disable animation if Reduce Motion is enabled (https://github.com/wordpress-mobile/WordPress-iOS/pull/13555#issuecomment-597044164) (https://github.com/wordpress-mobile/WordPress-iOS/pull/13681)
- [x] Add Tracks. (https://github.com/wordpress-mobile/WordPress-iOS/pull/13705)
- [x] Fix layout issue after logging in to app (button jumps from left to right) (https://github.com/wordpress-mobile/WordPress-iOS/pull/13767)
- [x] Enable feature flag for internal. (https://github.com/wordpress-mobile/WordPress-iOS/pull/13777)
- [x] Enable feature flag for all.
- [ ] Remove feature flag.

**Comment by bjtitus** [comment]
@osullivanchris It came up in a [PR discussion](https://github.com/wordpress-mobile/WordPress-iOS/pull/13474#issuecomment-589910190) that there are some cases where controls are obscured by the Floating Action Button:

<a href="https://user-images.githubusercontent.com/3250/75085162-93129780-54e3-11ea-81ba-41a38f808022.png"><img src="https://user-images.githubusercontent.com/3250/75085162-93129780-54e3-11ea-81ba-41a38f808022.png" width="300"></a>   <a href="https://user-images.githubusercontent.com/3250/75085176-af163900-54e3-11ea-8213-d8d55ec6832f.png"><img src="https://user-images.githubusercontent.com/3250/75085176-af163900-54e3-11ea-8213-d8d55ec6832f.png" width="300"></a>

The Site Pages screen seems to be the main one assuming we are only showing the button on Blog Details, Blog Posts, and Site Pages. This isn't necessarily breaking anything since all of the options are available from the editor screen but I thought I'd bring it up to see if there's anything we should consider adjusting to make this less of an issue.

**Comment by osullivanchris** [comment]
Thanks for the flag @bjtitus 

If we are displaying a Floating Action Button on Blog Posts and Site Pages views - will that floating action button bring up a sheet, per the site screen, or will it go directly to a new post/page according to where you are? On Android it behaves like the latter. It pre-dated the new iA work. If we are also introducing the FAB to this level it should behave the same.

Regards the position above some controls. As mentioned its not a total blocker, as it can still be achieved in the post. But that doesn't feel like a great solution. I wonder if we could just add additional padding/space below the last list item, so that it can scroll to a position where the controls can be accessed? Or does this feel too hacky?

<img width="375" alt="Screenshot 2020-02-24 at 12 02 29" src="https://user-images.githubusercontent.com/50576199/75151003-941f1100-56fd-11ea-9845-60161e01a9e4.png">

**Comment by bjtitus** [comment]
> will that floating action button bring up a sheet, per the site screen, or will it go directly to a new post/page according to where you are?

We should be able to do either one. I think we should most likely match Android's behavior.

> I wonder if we could just add additional padding/space below the last list item, so that it can scroll to a position where the controls can be accessed?

This is what I was thinking as well. Technically, it's a little bit tricky, but if we're assuming the button is always visible on this screen we can definitely do it.
