### ISSUE TITLE
Migrate from self-hosted Peril to Danger on GitHub Actions

### ISSUE THREAD

**Issue by loremattei** [wordpress-mobile/WordPress-iOS#13366]
We've been using [Peril](https://github.com/danger/peril) to support PR reviews for a couple of years now and it has become a key part of our process. 

Peril is basically a self-hosted version of [Danger](https://github.com/danger/danger).

Since GitHub released Actions, the development of Peril has stalled and the authors and maintainers have focused on improving Danger and making it work flawlessly with GH Actions.

We currently host Peril on a free Heroku account and with the  projects we've now hooked we're reaching its limits. 

Given the above, it would be interesting for us to investigate the migration from Peril to Danger on GitHub Actions. 
Our rules are Danger's rules and they are already stored in a [shared repository](https://github.com/automattic/peril-settings/), so it should be possible to run mixed environments and to migrate on a phased roll out.

**Comment by mokagio** [comment]
Here's an update on the state of this. We decided to **pause the migration effort, because of time and return of investment considerations**.

Danger, whether the Ruby or the Javascript implementation, works great for PRs. We were able to replicate the centralized nature of the Peril configuration by defining project specific `Dangerfile`s that imported and run the granular checks they needed, see [here](https://github.com/Automattic/danger-settings).

Unfortunately, I wasn't able to replicate Peril's behavior for `issues` and `status` webhooks in the Danger + GitHub Actions setup.

- There is [a bug](https://github.com/danger/danger-js/issues/999) that makes Danger when running on a workflow triggered by an [`issues` event](https://help.github.com/en/actions/reference/events-that-trigger-workflows#issues-event-issues).
- When a GitHub Actions workflow runs as a result of a [`status` event](https://help.github.com/en/actions/reference/events-that-trigger-workflows#status-event-status), there is no PR attached to it, and [Danger only expose its GitHub API interface](https://github.com/danger/danger-js/issues/1048). We'd have to add extra code to manipulate the status value and post on the PR like [we currently do with Peril](https://github.com/Automattic/peril-settings/blob/23332976e0e0eb59cd25b2aabc946e4eee7ae234/org/pr/installable-build.ts).

We _could_ adopt Danger only for PR checks and keep Peril for the other ones, but this would mean maintaining two setups instead of one, for no real gain. Danger even runs slower than Peril, because of the GitHub Actions CI boot time.

Moreover, Danger via GitHub Actions [fails to run on PR coming from forks](https://github.com/danger/danger-js/issues/918#issuecomment-646409597). This is a limitation that CircleCI has as well, meaning that if we were to migrate we'd already have in place the processes to take over a PR for a fork to run CI on it. Still, it's something that "just works" on Peril, adding another point against using Danger right now.

Given we have more impactful work to do right now, we decided to pause the migration project. I'll be keeping an eye on the Danger repos and revisit every 3 months or so.

I'll also set Danger via GitHub Actions up in one of our internal tools in Automattic, in order to keep the setup up to date, so that when the time comes, we'll have a quick start reference.

**Comment by jkmassel** [comment]
This was done a few months ago.
