### ISSUE TITLE
[GlobalStep] The controls to switch between pictures when viewing a gallery in Fullscreen are inconsistent

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/WordPress-iOS#13433]
### Description
When viewing pictures of a Gallery block in Fullscreen, the user can zoom and swipe to switch between pictures.
It has been observed that the controls to switch between pictures are very sensitive and inconsistent. Consequently when the user is zooming in and out the picture, it may unintentionally switch to another picture.

### Reproduction Rate
4/4 100%

### Expected behavior
The controls should be consistent and reflect the user’s motion.

### Actual behavior
The controls to switch between pictures are inconsistent and hard to use.

### Steps to reproduce the behavior
1. Install WordPress 14.2
2. Log in to an account.
3. Open the Post Editor.
4. Add a Gallery block.
5. Press “Add Media”.
6. Press “WordPress Media Library”.
7. Add some pictures.
8. Open the post in the Reader.
9. Tap a picture to view it in Fullscreen.
10. Explore the controls by Swiping and Zooming in and out.
##### Tested on the following
iPhone XR (12.0.1)

#### Please see the attached video for more information
[ImageControls.zip](https://github.com/wordpress-mobile/WordPress-iOS/files/4192733/ImageControls.zip)

### Submitted by:
Luis Pimenta

**Comment by designsimply** [comment]
Adding a screenshot from the attachment inline for reference:

<img width="270" alt="Screen Shot 2020-08-12 at Aug 12 5 21 46 PM" src="https://user-images.githubusercontent.com/1119271/90077838-62f0c800-dcc0-11ea-8b3d-27f7f726a5df.png">

**Comment by designsimply** [comment]
The WPiOS Reader was updated to render post content inside a WebView in 15.2. Props @leandroalonso. 🎉

That change had the side effect of making the gallery no longer open the carousel view (which is the one where you can swipe through the images).

Because the original issue was filed while viewing a post from within a different type of WebView, this would make the issue one that should be filed in https://github.com/Automattic/wp-calypso/issues if it were still reproducible. However, I re-tested with WPiOS 15.5.0.0 TestFlight beta comparing the in-app Reader, mobile web Reader, and front-end Reader gallery interactions and found that I couldn't replicate the problem described where the controls to switch between pictures in a carousel are inconsistent and hard to use—scrolling and zooming worked well for me in the front-end view and the in-app Reader and mobile web Reader views have changed and it appears you cannot currently see the carousel view in those areas. ([2m12s](https://cloudup.com/cDOSwrs3K0o))

WPiOS Reader post view|WPiOS Reader Gallery image detail view|Mobile Web Reader post view|Mobile Web front-end post view|Mobile Web front-end image detail view
---|---|---|---|---
![image](https://user-images.githubusercontent.com/1119271/90079617-a863c400-dcc5-11ea-8811-10b7efc601e7.png)|![image](https://user-images.githubusercontent.com/1119271/90079701-dba65300-dcc5-11ea-9d44-bcb01bf003e0.png)|![image](https://user-images.githubusercontent.com/1119271/90079748-01335c80-dcc6-11ea-973c-d29739242f08.png)|![image](https://user-images.githubusercontent.com/1119271/90079829-350e8200-dcc6-11ea-93a6-d0748c2c1764.png)|![image](https://user-images.githubusercontent.com/1119271/90079844-4061ad80-dcc6-11ea-982a-2f37d3ca0929.png)

<p style="clear:both;"><sup>Tested with WPiOS 15.5.0.0 TestFlight beta on iPhone 6S iOS 13.6.</sup></p>
