### ISSUE TITLE
Comments made using Gutenberg appears with big spacing between paragraphs

### ISSUE THREAD

**Issue by leandroalonso** [wordpress-mobile/WordPress-iOS#13507]
### Expected behavior

The comment should have regular paragraph spacing.

### Actual behavior

The comment has huge spacing between the paragraphs.

<img src="https://user-images.githubusercontent.com/7040243/74877475-48a6e480-5344-11ea-8fac-d4226b7bbf63.png" width="300" />

### Steps to reproduce the behavior

1. Create a comment using Gutenberg
2. Check the comment on the "Notifications" tab of the app

**Comment by emilylaguna** [comment]
Did some quick digging into this. It looks the notifications server call is returning the text with a lot of extra new line characters which is causing both iOS and Android to render the extra spacing.

```json
{
"text": "\n\n\nTest quote\n\n\n\n\n\n\nTest comment reply\n\n",
"ranges": [{
    "type": "blockquote",
    "indices": [2, 19]
}]
```

**Comment by dmsnell** [comment]
My initial analysis is that this is going to be hard to fix without building support for Gutenberg posts into the notification builder. As noted in a Slack conversation: this work needs to be performed server-side.

The catch is that we can't cleanup the text _after_ processing because that would mess up the ranges, as you see there in the example - if we removed the successive newlines then the block quote would apply to the wrong portion of text.

It shouldn't be a massive project at least because we should be able to run `do_blocks()` on the content before processing it. Will need some time to play around with the idea before I get a patch together.

I'm very happy to help someone walk through this code if they want to try fixing it.

**Comment by dmsnell** [comment]
Tracking in p9zg7s-5k-p2
