### ISSUE TITLE
Post updates made on desktop did not appear updated when opened in the app

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#13524]
From a 1-star review "Am frustrated " – Jan 13, 2020 – Version 13.9

> I wrote a blog post on desktop and scheduled it for this Thursday. It said all changes were saved. I open the app and the post is not under the scheduled tab, but the Drafts tab. It is also missing edits that I made on the desktop site. Now either the desktop site, or the app is not refreshing/saving properly. I do not like publishing something with glaring errors. I proofread for hours. According to the app, my last revisions on desktop weren’t saved or they’re just not showing up on the app!

Noting this App Review so we can investigate it. 🧐

**Comment by diegoreymendez** [comment]
This is probably due to our lack of version-conflict resolution.

#### Suggested steps:

1. Create a post in either platform and save as draft.
2. Edit the same post in mobile, change some text and then without saving or discarding simply close the App.
3. Edit the post in the web and publish it.

#### Result:

If you reopen the mobile app you’ll see the local changes, and the post will still be a draft. Refreshing the list won’t cause the posts to sync.

**Comment by rachelmcr** [comment]
@designsimply This sounds like a duplicate of https://github.com/wordpress-mobile/WordPress-iOS/issues/9449. What do you think of closing this issue and adding this report there?

**Comment by designsimply** [comment]
Aha, well, I saw two potential issues: scheduled posts appear as drafts in the app and edits made on the web do not appear in the app. I agree it needs further investigation and that we can consolidate to https://github.com/wordpress-mobile/WordPress-iOS/issues/9449 until it becomes more clear.
