### ISSUE TITLE
Crash on startup iPhone 6s for version 14.3

### ISSUE THREAD

**Issue by rezzap** [wordpress-mobile/WordPress-iOS#13684]
We have a user who reported in a review that the app crashes on startup for them. They mention:

"I've tried uninstalling and reinstalling twice, but failed. The screenshots are attached showing the required info i.e. App Version 14.3 Latest Available on store and phone info." 

There's also a screen recording of this in the ticket. 

Can someone help try to find logs for this and see what's causing this to happen? 

<img src="https://user-images.githubusercontent.com/10325627/77065153-ac224180-69d8-11ea-93a1-3a56a75c5fbf.png" width="200" alt="image3"> <img src="https://user-images.githubusercontent.com/10325627/77065159-ad536e80-69d8-11ea-83f4-7f44f55856de.png" width="200" alt="image1"> <img src="https://user-images.githubusercontent.com/10325627/77065165-af1d3200-69d8-11ea-95eb-114326d0bcec.png" width="200" alt="image2">

Reported in 2798326-zen

**Comment by designsimply** [comment]
> Can someone help try to find logs for this and see what's causing this to happen?

Logs for crashes like this can be really difficult to find (ref: https://github.com/wordpress-mobile/WordPress-iOS/issues/12338#issuecomment-522666856). Because this particular type of crash happens so early after starting up the app, it's unlikely the app has time to even capture a a crash report and send it to our crash-tracking software (currently Sentry). Even if the app did have time to send in a crash report, the user would have had to have had their app settings set to automatically send in crash reports and not everyone has set that up and since the crash is happening so quickly (grr) there's really not a way for them to check it. _If_ they could check the setting though, they would want to do the following:

**How to update app settings to report crashes to us**

1. Go to Account > App Settings > Privacy Settings.
1. Turn on the Collect information option.
1. Go to Account > Help & Support.
1. Turn on the Extra Debug option.

<img src="https://user-images.githubusercontent.com/1119271/79262466-9aed1900-7e4e-11ea-87d2-86d96f5e0acb.PNG" width="200" alt="IMG_3834"> <img src="https://user-images.githubusercontent.com/1119271/79262475-9de80980-7e4e-11ea-9889-0e43a95f7087.PNG" width="200" alt="IMG_3835">
<p style="clear:both;"><sup>Tested with WPiOS 14.6.0.1 TestFlight beta on iPhone 11 iOS 13.4.1.</sup></p>

I did also try searching in Sentry in a few different ways, `os:"iOS 12.4.5" device:iPhone7,2 dist:14.3.0.3 ` and `user.id:NUMBER_REMOVED`, and I was unable to narrow down to be able to find a crash report based on the information provided in the screenshots or the help request in Zendesk. The first search returned too many results and the second result returned zero results. Since I couldn't find a crash report for this user in Sentry using a `user.id` search, my assumption would be that they did not have crash reporting enabled before this problem started happening for them. Note: the user didn't actually verify the WP.com username they are using to sign in to the app in their help request, so I used the email address provided in the support request to do a search and find the WP.com user id for the account related to the same email they used to send in their original app store review and I also tried the username they signed the email with (a separate account exists in WP.com for both), but neither returned any crash report information.

<p style="clear:both;"><sup>* Ref: https://www.theiphonewiki.com/wiki/Models</sup></p>

Past that, the only other place I know of to try looking for crash logs for a case like this would be in the Crash Feedback section in App Store Connect for the WordPress app's Apple account. However, I checked it and found that it says, "includes feedback only from testers running iOS 13 or later." And I see that the user in this case is running iOS 12.4.5 and so we won't be able to get a crash report from them there.

In other similar cases, we did receive reports back from people saying that completely deleting the app and then re-installing did fix the problem for them. I researched and found that in iOS it's possible to offload the app and it may seem like you've completely deleted the app but offloading actually removes the app but also restores the data back from the apps store once the app is re-installed. Perhaps instructing this user to _completely_ delete the app  through the iPhone Storage settings would help? I looked on the device Settings > General > iPhone Storage > WordPress and I found the messaging on that screen backs up this idea:

> Offload App - This will free up storage used by the app, but keep its documents and data. Reinstalling the app will place back your data if the app is still available in the App Store.

> Delete App - This will delete the app and all related data from this iPhone. This action can't be undone.

<img src="https://user-images.githubusercontent.com/1119271/78813096-bf964c00-7989-11ea-8a7f-ebc5c9826e27.PNG" width="200" alt="IMG_3725">
<sup>Tested with an iPhone 11 iOS 13.4.</sup>

@rezzap if you take a look at https://github.com/wordpress-mobile/WordPress-iOS/issues/12338 can you see any reason to keep this issue open as a separate case from that one, or would you be okay to close this one as a duplicate?
