### ISSUE TITLE
[GlobalStep] iPad only - Empty Notifications tabs display a grey area where the content’s preview would normally be displayed.

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/WordPress-iOS#13746]
### Description
While viewing an empty tab in the Notifications screen, the preview are is displayed as Grey which can be slightly confusing. A message indicating there is no content to preview is expected.

### Reproduction Rate
4/4 100%

### Expected behaviour
A message indicating there is no content to be displayed should be presented.

### Actual behavior
An empty grey area fills the preview area.

### Steps to reproduce the behavior
1. Install WordPress 14.5
2. Log in to a valid account.
3. Navigate to Notifications.
4. Select a tab that has no content to be displayed.
##### Tested on the following
iPad Mini 2 (12.0.0)

#### Please see the attached screenshot for more information
<img width="270" src="https://user-images.githubusercontent.com/60415523/77663511-0bea9080-6f75-11ea-91bd-a8f46fab3d26.jpg" />

### Submitted by:
Luis Pimenta

**Comment by designsimply** [comment]
Tested and confirmed that the NoResultsView is an unflattering blank gray in the splitscreen view on iPad.

<img src="https://user-images.githubusercontent.com/1119271/77971362-b7644f80-72ab-11ea-8032-d382e7159813.PNG" width="540" alt="IMG_0250">
<p style="clear:both;"><sup>WPiOS 14.5.0.1 TestFlight beta on iPad Mini 4 (WiFi) (iPad5,1) iPadOS 13.3.1</sup></p>

Note: I tested back through 13.9.0.2 from TestFlight (that's as far back as the builds go right now) and I found that the problem happens in every release so I'm not sure if something changed in the app or if this might have been caused by an API issue somehow.

**Comment by designsimply** [comment]
Note: in testing, I found that blank grey right screen in splitscreen appears for the main notifications view on a fresh install of the app (in addition to the no results view noted above).

**Comment by ScoutHarris** [comment]
Hey @designsimply .

Looking at the code, this is not a bug. It's been this way for 3 years, and was done intentionally (https://github.com/wordpress-mobile/WordPress-iOS/commit/43bf919abc395e48ec39540f202093043c274b8b).

It's easy enough to change if we wanted I suppose, but this is by design.
