### ISSUE TITLE
[beta 14.6] Notifications: double tap within notification view no long returns to Notification list

### ISSUE THREAD

**Issue by dougaitken** [wordpress-mobile/WordPress-iOS#13839]
### Expected behavior

When in a notification view, tapping the Notification bell returns me to the main Notification list view.

### Actual behavior

In beta 14.6.0.20200406bf219ec (Appcenter release), when in the view of an individual notification, tapping the Notification bell no longer returns to that list. I need to press Back.

### Steps to reproduce the behavior

* Latest beta, tap Notifications, tap into a notification. Tap Notifications and notice that the view doesn’t change. Pressing “Back” will return you to the Notification list 

* Latest App Store release, tap Notifications, tap into a notification. Tap Notifications and notice that the view does change. Pressing “Back” arrow will also return you to the Notification list.

##### Tested on iPhone XS, iOS 13.3.1 (17D50), WPiOS beta 14.6.0.20200406bf219ec

**Comment by designsimply** [comment]
Thank you for the report! 

Fixed in https://github.com/wordpress-mobile/WordPress-iOS/pull/13844. Props @bjtitus. 🎉

<sup>(internal reference: p4a5px-2xL-p2)</sup>

@dougaitken you should see the update working in 14.6.0.20200410, I tested just now and it's working as it should for me. Let me know if you're still having any trouble at all after updating!

**Comment by dougaitken** [comment]
YAS! Thanks for confirming @designsimply
