### ISSUE TITLE
Notifications: Gutenberg comments don't show up in notifications about likes or replies to comments

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#13856]
### Expected behavior

When some likes or replies to a comment I made, I expect to see the beginning of my comment at the top of the notification about it.

### Actual behavior

When my comment was made using Gutenberg, the area in the notification where I expect to see the beginning of my comment is blank.

This issue is specific to WPiOS — it works as expected on the web and in WPAndroid.

### Steps to reproduce the behavior

1. On a site, enable Gutenberg for the site comments.
2. Leave a comment using Gutenberg.
3. From another account, like or reply to that comment.
4. In the app, check your notifications on the account you used to leave the Gutenberg comment.
5. Select the notification about the like/reply to your comment to view the notification detail.

Result: The notification is received, but the text of your comment isn't visible in the notification detail.

WPiOS (bug)|WPAndroid (expected)
-|-
<img src="https://user-images.githubusercontent.com/8658164/78901767-b7650c00-7a70-11ea-9976-f6edec9641b7.PNG" width="300px">|<img src="https://user-images.githubusercontent.com/8658164/78901551-62c19100-7a70-11ea-8deb-e04a5535207c.png" width="300px">

**Comment by lancewillett** [comment]
Possibly related to the Notifications API not handling blocks in comments well.

https://github.com/Automattic/wp-calypso/issues/41331

**Comment by designsimply** [comment]
Tested and confirmed that the beginning of the comment being replied to does not show up on comment reply detail screens in notifications using WPiOS 14.7.0.1 (TestFlight beta).

Steps to reproduce:

1. Set up a Jetpack-connected site (Jetpack because we need access to notifications).
1. Install and activate the [Block Comments](https://github.com/tomjn/block-comments) plugin.
1. Publish a new post and leave a comment on that post.
1. On the web, log in to the site as a different user or log out completely.
1. Leave a comment reply on any existing comment.
1. On the app, go to Notifications and tap on any comment reply.
1. Expect to see a snippet of the replied to comment in the header.

**Result:** a snippet of the replied to comment appears in the Notifications stream but once you tap on a comment reply to see details, the snippet is no longer there.

Notifications stream | Reply detail screen | Comments for context
--- | --- | ---
<img src="https://user-images.githubusercontent.com/1119271/80044748-b72e2d00-84c2-11ea-8409-fa608b7ae8d6.PNG" width="200" alt="IMG_3912">|<img src="https://user-images.githubusercontent.com/1119271/80044752-b9908700-84c2-11ea-9cb1-58b207b7c593.PNG" width="200" alt="IMG_3906">|<img src="https://user-images.githubusercontent.com/1119271/80044755-bc8b7780-84c2-11ea-9f68-886cd4b17a1a.PNG" width="200" alt="IMG_3909">

<p style="clear:both;"><sup>Tested with WPiOS 14.7.0.1 TestFlight beta on iPhone 11 iOS 13.4.1.</sup></p>

**Note:** the Block Comments plugin available at https://github.com/tomjn/block-comments is the precursor to testing Gutenberg Comments on P2 currently being tested internally.

**Comment by darnelldibbles** [comment]
Another report https://wordpress.com/forums/topic/all-my-comments-and-replies-are-not-coming-in-the-notification-bell-2/

**Comment by KokkieH** [comment]
We have another report [via Twitter](https://twitter.com/Sidhart38554722/status/1253056186850504709) of this happening in the Android app as well.

**Comment by rachelmcr** [comment]
@darnelldibbles & @KokkieH Sorry if the title of this issue was misleading, but this is specifically about how the notification is rendered in the iOS app. (The notification itself comes through but not all of the text in the notification detail view is rendered.) Those two reports sound like issues with notifications not coming through at all, which would be a separate issue and likely needs to be investigated as a cross-client issue.

**Comment by KokkieH** [comment]
Thanks, @rachelmcr 

It looks like this issue has instead been reported in p2EDhh-14W-p2
