### ISSUE TITLE
Unresolved Core Data save error (Derived Context): Merge policy failed - unable to complete merging on null.null

### ISSUE THREAD

**Issue by loremattei** [wordpress-mobile/WordPress-iOS#13867]
**Sentry Url**: https://sentry.io/share/issue/8c458ae1669e407594703b6b5341b2ad/
**User Count**: 514
**Count**: 4696
**First Release**: 13.4.1.1
**First Seen**: 2019-11-05T16:34:05Z
**Last Release**: 14.5.0.2
**Last Seen**: 2020-04-10T17:48:59Z
**24 Hours**: 1115
**30 Days**: 2816

**Comment by yaelirub** [comment]
Triage: priority high by impact and has been for a while. There are many tickets floating around about save error on either derived or main context. Most of them you can find here:
https://github.com/wordpress-mobile/WordPress-iOS/search?q=save+context+error&type=Issues

@mindgraffiti , are you going to tackle this during Groundskeeping?

**Comment by mindgraffiti** [comment]
@yaelirub thanks for the link! That's helpful. 

I made the mistake of thinking "the [landscape layout corrections](https://github.com/wordpress-mobile/WordPress-iOS/issues/13792) will only take a day" and thought I would get to start researching this issue today. Famous last words. 

I plan to take on this task if I complete the landscape layout issues in time.

**Comment by yaelirub** [comment]
Gotcha. Could you please comment here either way once you know?

**Comment by mindgraffiti** [comment]
@yaelirub can confirm. The landscape layouts are moving very slowly. Some of the views haven't been [edited for 3 years](https://github.com/wordpress-mobile/WordPress-iOS/tree/develop/WordPress/Classes/ViewRelated/Themes). I'm not able to look into this crash.

**Comment by designsimply** [comment]
This crash came up in a 1-start app review and I used the username to see if I could find a crash report from them in Sentry and this issue came up as a result of that search.

> Super buggy by evoskuil – Apr 26, 2020 - Version 14.6
> Gets in to a mode where it fails to update a post and will then crash on every attempt until the app is deleted and restored. The new editor cannot view posts with either the old mobile editor or the desktop. Fails to recognize certain basic edits created on the desktop version. You can first create a paragraph on the mobile app and then edit it but don’t try creating paragraphs in the reverse order.

**Comment by rezzap** [comment]
I think we have a report from a user who's having trouble with this same crash. The logs they sent include: 

>  Unresolved Core Data save error: Error Domain=NSCocoaErrorDomain Code=133020 "Could not merge changes." 

They aren't able to use the app at all at the moment because it crashes every time they try to open it. Reinstalling helps sometimes, but it's not consistent.

I tried logging in to their account from my device and it was fine though, so I'm not sure if this is consistently a problem. 

@designsimply If you have a chance can you check into that ticket to see if I missed anything in those logs? 

2921345-zen

**Comment by rezzap** [comment]
I have another with the same error in 2930589-zen

> Unresolved Core Data save error: Error Domain=NSCocoaErrorDomain Code=133020 "Could not merge changes."

Reinstall doesn't fix anything here neither.

**Comment by designsimply** [comment]
@rezzap thanks for the ping! I'm circling back to note I checked the logs on the ticket you referenced and you got exactly the right log info. We're also tracking this crash on startup in a few different places—most notably https://github.com/wordpress-mobile/WordPress-iOS/issues/12338.

<sup>(other internal references: p4a5px-2yz-p2, p4a5px-2yB-p2, p4a5px-2yE-p2, pbArwn-rq-p2)</sup>

**Comment by designsimply** [comment]
**Events in the last 90d:** 237,000
**Events in the last 11d for 14.9:** [10](https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=release&field=os&field=device&field=culprit&name=All+Events&project=1438083&query=issue.id%3A1318112961+release%3A14.9.0.4&sort=-timestamp&statsPeriod=30d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1) in 14.9 since it was released on 2020-06-01
**Users affected in the last 90d:** 19,000
<sub>https://sentry.io/share/issue/6765e6ce2527499ea2cc79dc8bd8fcc6/</sub>

The 90-day graph trending down looks quite nice! [90-day graph for issue.id:1318112961](https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=release&field=os&field=device&field=culprit&name=All+Events&project=1438083&query=issue.id%3A1318112961&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1): 

<img width="1024" alt="Screen Shot 2020-06-12 at Jun 12 6 52 03 PM" src="https://user-images.githubusercontent.com/1119271/84556102-d3d62c80-acdd-11ea-9548-a971c3f8c35f.png">

Sentry is still showing [~150 per day of these on average in recent days](issue.id:1318112961 ), but very few are showing up per release starting with 14.7.1 (likely because of @leandroalonso's fix in https://github.com/wordpress-mobile/WordPress-iOS/pull/14097 🎉). 

<img width="1024" alt="Screen Shot 2020-06-12 at Jun 12 6 57 40 PM" src="https://user-images.githubusercontent.com/1119271/84556298-ddac5f80-acde-11ea-89cb-4b83b67419ea.png">

Noting we may be able to close this one if it stops showing up in new releases and we should keep an eye on it.

**Comment by designsimply** [comment]
Still seeing a few stragglers for this one in 15.3, but the main culprit was clearly resolved in 14.7.1. 🎉

[![image](https://user-images.githubusercontent.com/1119271/89595031-b8385f80-d810-11ea-8a51-078d3c4ad6a3.png)](https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=release&field=os&field=device&field=culprit&name=All+Events&project=1438083&query=issue.id%3A1318112961+release%3A15.3%2A&sort=-timestamp&statsPeriod=14d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1)

@yaelirub @leandroalonso I think the numbers are low enough to warrant closing the issue here in GitHub. wdyt?

**Comment by leandroalonso** [comment]
@designsimply I agree! +1

**Comment by yaelirub** [comment]
Agree @designsimply ! Closing this issue.
