### ISSUE TITLE
NSInternalInconsistencyException in WordPress.SharingButtonsViewController

### ISSUE THREAD

**Issue by loremattei** [wordpress-mobile/WordPress-iOS#13890]
**Sentry Url**: https://sentry.io/share/issue/1204cb1f05f54b3e86f2c41e316242ce/
**User Count**: 141
**Count**: 840
**First Release**: org.wordpress-12.5
**First Seen**: 2019-06-04T12:49:13Z
**Last Release**: 14.5.0.2
**Last Seen**: 2020-04-13T19:26:35Z
**24 Hours**: 4
**30 Days**: 100

**Stacktrace**:
```
NSInternalInconsistencyException: UITableView delegate method tableView:targetIndexPathForMoveFromRowAtIndexPath:toProposedIndexPath: returned an invalid target index path (section: 1, row: 4) because there are only 2 rows in this section of the table view.
    at null.__exceptionPreprocess(null:null)
    at null.objc_exception_throw(null:null)
    at null.+[NSException raise:format:arguments:](null:null)
    at null.-[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:](null:null)
    at null.-[UITableView _retargetedReorderIndexPathForInitialIndexPath:proposedIndexPath:](null:null)
    at null.-[UITableView _reorderPositionChangedForCell:withScrollFactorPercentage:](null:null)
    at null.-[UITableView _draggingReorderingCell:yDelta:touch:](null:null)
    at null.-[UITableViewCell _grabberDragged:yDelta:touch:](null:null)
    at null.-[UITableViewCellReorderControl continueTrackingWithTouch:withEvent:](null:null)
    at null.-[UIControl touchesMoved:withEvent:](null:null)
...
(15 additional frame(s) were not displayed)
```

**Comment by designsimply** [comment]
**Events in the last 90d:** 1,000
**Events in the last 11d for 14.9:** [24](https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=release&field=os&field=device&field=culprit&name=All+Events&project=1438083&query=issue.id%3A1056562308+release%3A14.9.0.4&sort=-timestamp&statsPeriod=30d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1) in 14.9 since it was released on 2020-06-01
**Users affected in the last 90d:** 171
<sub>https://sentry.io/share/issue/1204cb1f05f54b3e86f2c41e316242ce/</sub>

[90-day graph for issue.id:1056562308](https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=release&field=os&field=device&field=culprit&name=All+Events&project=1438083&query=issue.id%3A1056562308&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1):

<img width="1029" alt="Screen Shot 2020-06-12 at Jun 12 7 19 39 PM" src="https://user-images.githubusercontent.com/1119271/84556712-aee3b880-ace1-11ea-90b1-f2a543791284.png">

**Comment by designsimply** [comment]
**Events in the last 90d:** 265
**Users affected in the last 90d:** 138
<sub>WORDPRESS-IOS-599: https://sentry.io/share/issue/1204cb1f05f54b3e86f2c41e316242ce/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=release&field=os&field=device&field=culprit&name=All+Events&project=1438083&query=issue.id%3A1056562308&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1">![image](https://user-images.githubusercontent.com/1119271/92022259-d742e800-ed0f-11ea-9fae-705494e04605.png)</a>

**Comment by designsimply** [comment]
<sup>(also see internal reference: paaHJt-1jm-p2)</sup>

**Comment by designsimply** [comment]
**Events in the last 90d:** 270
**Users affected in the last 90d:** 135
<sub>WORDPRESS-IOS-599: https://sentry.io/share/issue/1204cb1f05f54b3e86f2c41e316242ce/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=release&field=os&field=device&field=culprit&name=All+Events&project=1438083&query=issue.id%3A1056562308&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1">![image](https://user-images.githubusercontent.com/1119271/94749732-bf2bac00-0341-11eb-8602-1c78a07305c6.png)</a>

**Comment by designsimply** [comment]
Hmm. This issue stopped getting occurrences recorded for it on 2020-11-19.

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=release&field=os&field=device&field=culprit&name=All+Events&project=1438083&query=issue.id%3A1056562308&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1">![image](https://user-images.githubusercontent.com/1119271/101705383-09b55d00-3a44-11eb-92e4-be119217d015.png)</a>

However, a search for `NSInternalInconsistencyException` shot way up a week or so earlier on 2020-11-09.

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=release&field=os&field=device&field=culprit&name=All+Events&project=1438083&query=NSInternalInconsistencyException&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1">![image](https://user-images.githubusercontent.com/1119271/101705717-cad3d700-3a44-11eb-8bff-afbe8e5c5c5c.png)</a>

@jkmassel is this because the issue moved or because issues started getting merged/tracked differently in Sentry? Hmm. This really puzzled me and I ended up asking internally on a P2.

<sup>(internal reference: paaHJt-1jm-p2#comment-3488)</sup>

**Comment by jkmassel** [comment]
This issue is no longer being reported by Sentry
