### ISSUE TITLE
Reader: heading alignment and color are not displayed

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#13930]
Steps to reproduce:

1. Create a new post on the web.
1. Add a heading block and change the color for it in the block settings.
1. Add a paragraph.
1. Add a left-aligned heading.
1. Add a paragraph.
1. Add a center-aligned heading.
1. Add a paragraph.
1. Add a right-aligned heading.
1. Save or publish the post.
1. View the post in the Reader and check to see if the headings look correct.

**Result:** alignment and color block settings for headings aren't displayed in the Reader.

Reader in app | Safari on iOS
--- | --- 
<img src="https://user-images.githubusercontent.com/1119271/79595205-a84b1300-809b-11ea-8ee1-11c3eb602718.PNG" width="200" alt="IMG_3847"> | <img src="https://user-images.githubusercontent.com/1119271/79595215-aa14d680-809b-11ea-9db6-b5ab7b0775e3.PNG" width="200" alt="IMG_3848">

<p style="clear:both;"><sup>Tested with WPiOS 14.6.0.3 TestFlight beta on iPhone 11 iOS 13.4.1 Dark Mode.</sup></p>

**Note:** alignment (Android-only) and color (Android and iOS) are not yet supported in the editor. See wordpress-mobile/gutenberg-mobile#1880 and wordpress-mobile/gutenberg-mobile#2165 to follow progress.

**Aside:** it's quite possible color isn't expected to show in the Reader. If that is the case, please leave a comment here to explain. Thank you! cc @iamthomasbishop

**Comment by designsimply** [comment]
Also reported for Android: https://github.com/wordpress-mobile/WordPress-Android/issues/11680.

**Comment by iamthomasbishop** [comment]
>  it's quite possible color isn't expected to show in the Reader. If that is the case, please leave a comment here to explain.

I wouldn't expect styling like text color to be inherited on Reader, tbh. Reader (in my eyes) is sort of a style-neutral consumption tool, not unlike various news/RSS readers such as [Reeder](https://www.reederapp.com), [Instapaper](https://www.instapaper.com), etc — where every article is generally styled the same to bring consistency and reduce clutter in the reading experience. So on a scale from style-less to fully-styled as the site, we typically steer toward the style-less by design. I could, however, see supporting something like text-alignment because it's pretty rudimentary, although that puts us in a gray area.

With that said, I'm not opposed to exploring some other approach (similar to Google News, which goes from their index screens to the full web view which I dislike strongly 😄) but honestly at that point, we might as well just launch the user into a webview when they want to read an article 🤷‍♂️ 

Side-note: This dilemma has also informed some of my choices while designing for the mobile editors — because we don't want to get stuck "in the middle" where things _sorta_ look like the output but _not quite_, we've kept styling pretty neutral.

I'd love to hear others' opinions on the matter, so I'm cc'ing @mattmiklic @mbshakti 😄

**Comment by mattmiklic** [comment]
> Reader (in my eyes) is sort of a style-neutral consumption tool, not unlike various news/RSS readers such as Reeder, Instapaper, etc — where every article is generally styled the same to bring consistency and reduce clutter in the reading experience.

I'd agree with this — and I'd say that those kinds of apps are probably where we should look for inspiration for deciding where to draw the line between respecting user's customizations and maintaining some level of consistency within the app's reading experience. That probably doesn't include color but _might_ include alignment.
