### ISSUE TITLE
Site listing under "Me" does not restore state properly

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#1394]
1. Scroll down on the site list under "Me".
1. Hit the Home button to exit out to SpringBoard.
1. Force kill the app.
1. Relaunch the app.
1. Notice the screenshot shows the list where you left off, and then is immediately refreshed at the top of the list.

**Comment by rachelmcr** [comment]
I tested this in beta v. 5.8.0.20151204 to see if it's still an issue with the My Sites tab (now that the site list is no longer under Me). When I reopen the app, instead of opening to the site list where I left off, it opens to the site detail for the last site I worked on. I can then go back to the site list (to the top of the list).

Is that the current intended behavior? Not sure if we expect it to reopen to the site list instead of the site detail in this case.

**Comment by aerych** [comment]
I'd say still a bug and not the intended behavior.  With a few exceptions around synced content, the app should resume from where it left off.
