### ISSUE TITLE
NSInternalInconsistencyException: attempt to delete section 0, but there are only 0 sections before the update

### ISSUE THREAD

**Issue by loremattei** [wordpress-mobile/WordPress-iOS#13956]
**Sentry Url**: https://sentry.io/share/issue/ec8f4ba680aa4f608a4509ed93deaa16/
**User Count**: 54
**Count**: 116
**First Release**: 13.4.1.1
**First Seen**: 2019-11-07T10:25:58Z
**Last Release**: 14.6.0.3
**Last Seen**: 2020-04-21T03:09:43Z
**24 Hours**: 2
**30 Days**: 31

```
NSInternalInconsistencyException: attempt to delete section 0, but there are only 0 sections before the update
  File "PageListTableViewHandler.swift", line 68, in PageListTableViewHandler.refreshTableView
  File "PageListViewController.swift", line 509, in PageListViewController.draftPage
  File "<compiler-generated>", line null, in @callee_guaranteed
  File "main.swift", line 7, in main
...
(16 additional frame(s) were not displayed)
```

**Comment by yaelirub** [comment]
low by impact.
It seems like results controller sections are not being update accordingly or the results are grouped and then we return 1 section.
https://github.com/wordpress-mobile/WordPress-iOS/blob/3e51da289537324ce0cc27bcedf67db15d215091/WordPress/Classes/ViewRelated/Pages/PageListTableViewHandler.swift#L119

**Comment by designsimply** [comment]
**Events in the last 90d:** 181
**Events in the last 11d for 14.9:** [2](https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=release&field=os&field=device&field=culprit&name=All+Events&project=1438083&query=issue.id%3A1320163956+release%3A14.9.0.4&sort=-timestamp&statsPeriod=30d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1) in 14.9 since it was released on 2020-06-01
**Users affected in the last 90d:** 77
<sub>https://sentry.io/share/issue/ec8f4ba680aa4f608a4509ed93deaa16/</sub>

[90-day graph for issue.id:1320163956](https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=release&field=os&field=device&field=culprit&name=All+Events&project=1438083&query=issue.id%3A1320163956&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1):

<img width="1025" alt="Screen Shot 2020-06-12 at Jun 12 7 24 09 PM" src="https://user-images.githubusercontent.com/1119271/84556794-5234cd80-ace2-11ea-8f6a-28215de35b25.png">

**Comment by designsimply** [comment]
**Events in the last 90d:** 78
**Users affected in the last 90d:** 54
<sub>WORDPRESS-IOS-2RAW: https://sentry.io/share/issue/ec8f4ba680aa4f608a4509ed93deaa16/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=release&field=os&field=device&field=culprit&name=All+Events&project=1438083&query=issue.id%3A1320163956&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1">![image](https://user-images.githubusercontent.com/1119271/92022672-78ca3980-ed10-11ea-9026-20681cdc3969.png)</a>

**Comment by designsimply** [comment]
**Events in the last 90d:** 79
**Users affected in the last 90d:** 51
<sub>WORDPRESS-IOS-2RAW: https://sentry.io/share/issue/ec8f4ba680aa4f608a4509ed93deaa16/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=release&field=os&field=device&field=culprit&name=All+Events&project=1438083&query=issue.id%3A1320163956&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1">![image](https://user-images.githubusercontent.com/1119271/94749922-2fd2c880-0342-11eb-9314-bb0a54888e67.png)</a>

**Comment by designsimply** [comment]
<sub>WORDPRESS-IOS-2RAW: https://sentry.io/share/issue/ec8f4ba680aa4f608a4509ed93deaa16/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=release&field=os&field=device&field=culprit&name=All+Events&project=1438083&query=issue.id%3A1320163956&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1">![image](https://user-images.githubusercontent.com/1119271/101707994-a0d0e380-3a49-11eb-8963-f3787ad777b3.png)</a>

Looks stopped, but I actually think it just may have moved to a different issue although I couldn't find the exact same error in a search. Rawr.
