### ISSUE TITLE
Response status code was unacceptable: 400.

### ISSUE THREAD

**Issue by loremattei** [wordpress-mobile/WordPress-iOS#14053]
**Sentry Url**: https://sentry.io/share/issue/a6d84ed0d32e45498db06ce3c60104c2/
**User Count**: 162
**Count**: 1215
**First Release**: 27002
**First Seen**: 2020-04-15T07:08:11Z
**Last Seen**: 2020-05-05T09:37:38Z
**24 Hours**: 857
**30 Days**: 1222

```
Response status code was unacceptable: 400.

```

**Comment by loremattei** [comment]
This gets logged in Sentry, but it's not a crash, it's reported as an error, but it has an impressive amount of occurrences, so it's probably worth investigation.

**Comment by bummytime** [comment]
This error **might** be addressed with the patch from #14058 (which fixes #14052). We will keep a close eye on this in 14.8 to see if it's truly fixed.

/cc @yaelirub @frosty

**Comment by designsimply** [comment]
Sentry hasn't recorded any new cases for this since May 8 and the latest version affected according to Sentry, was WPiOS 14.8.0.0. Looks fixed in https://github.com/wordpress-mobile/WordPress-iOS/pull/14058. Props @aerych. 🎉

Here's the 30-day graph:

<img width="314" alt="Screen Shot 2020-05-19 at May 19 10 19 07 PM" src="https://user-images.githubusercontent.com/1119271/82404553-ca2f1100-9a1e-11ea-8c81-74698beebac5.png">
