### ISSUE TITLE
Editor: Editor button (FAB) sometimes appears on Stats screen

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#14114]
### Expected behavior

I expect the editor FAB (new post/page button) to only appear on the My Site screen.

### Actual behavior

Sometimes when I leave the app on the Stats screen and background it, when I come back to the app later the editor FAB appears on screen. It disappears if I leave and reopen the Stats section.

### Steps to reproduce the behavior

1. Go to My Sites > Stats.
2. Background the app.
3. After a long wait (uncertain how long - I have observed it after leaving the app overnight but never when I'm intentionally testing with only a few minutes wait) open the app again.
4. Notice the editor FAB appears in the bottom right corner.

<img src="https://user-images.githubusercontent.com/8658164/81831396-31d3f080-9535-11ea-8c46-d87dfc0766be.png" width="300px">

**Comment by ScoutHarris** [comment]
ping @bjtitus

**Comment by bummytime** [comment]
@bjtitus please see if you can fix this for 14.8 please!

**Comment by bjtitus** [comment]
Sorry, I wasn't able to get this figured out in time for 14.8. This issue is fixed in 14.9 with the [tooltips PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/14029); specifically, this change: https://github.com/wordpress-mobile/WordPress-iOS/pull/14029/commits/11beec9628bebabb511a99dd8c2844e709108517#diff-3bf33b7a7ba5c31c9dcbf9d28d3e7c90R330-R332

I identified an issue (https://github.com/wordpress-mobile/WordPress-iOS/issues/14150) in 14.9 with state restoration when navigating to or below the Blog Details Screen which makes it difficult to fully test on the current version of 14.9 (since you can't actually resume to the Stats screen, it will kick you back out to the My Sites list).

I've submitted a fix for that 14.9 restoration issue (https://github.com/wordpress-mobile/WordPress-iOS/pull/14151) with some added logic to make the FAB hide/show logic a little better aligned with appearance calls.
