### ISSUE TITLE
[GlobalStep] [iOS] Applications fails to display video on "Reader" tab.

### ISSUE THREAD

**Issue by gglobalstep** [wordpress-mobile/WordPress-iOS#14162]
**Environment:**
 iOS: iPhone 8 (v13.4.1), iPhone 11 Pro (v13.2.2), iPhone XS (v13.2.2).
Build [version]: v14.9

**Steps To Reproduce:**
 1. Install and launch the application.
 2. Tap on "Log In".
 3. Log in to the app using valid credentials.
 4. Tap on "My site".
 5. Tap on "Create Blog" symbol.
 6. Add any text at title.
 7. From footer tap on "+" to add Video block.
 8. Upload video in video block.
 9. Tap on "Publish" button.
 10. Now go to Reader tab, (Assuming your site is in "followed sites" or else Followed Sites> Manage> Enter URL)
 11. Observe that applications fails to display video on "Reader" tab.

 **Actual Result:**
Applications fails to display video on "Reader" tab.

 **Expected Result:**
Applications should display video on "Reader" tab.

**Attachment:**
[#14162.zip](https://github.com/wordpress-mobile/WordPress-iOS/files/4663236/14162.zip)

**Comment by designsimply** [comment]
I'm having trouble replicating this one reliably. I tried creating several new video posts and viewing them in the Reader using WPiOS 14.9.0.2 (TestFlight beta) and I saw one instance where the video didn't load but it loaded fine after I left the Reader and returned to it again. I wasn't able to capture the problem in a video. ([2m46s](https://cloudup.com/cW7ySsM2hee))

<p style="clear:both;"><sup>Tested with WPiOS 14.9.0.2 TestFlight beta on iPhone 6S iOS 13.3.1.</sup></p>

Could this possibly have been a problem where the video hadn't fully uploaded yet at the time the post was viewed in the Reader? Could it be related to a slow network not loading the video very quickly? I'd like to circle back to test this one again later since I cannot replicate it reliably and didn't catch the problem in a video. If you watch the video and spot something I need to do differently in the testing steps, please let me know!

Note: I can't quite tell from the #14162.zip attachment ([video](https://cloudup.com/cm8ZIOWBAnm)) whether the issue is the same as what is described in the post because when you go to the Reader, I see that you immediately do a search for "romapise" in the Reader Posts search screen and so the post titled "Video testing" would not be guaranteed to come up in a search like that one. You can click on the Site Title to see all the posts from that site, or it should appear in the main stream, or you could search for the site name or url on the Sites tab in the Search screen instead of the Posts tab.
