### ISSUE TITLE
Media: Free Photo Library no results view is cut off when the keyboard is active

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#14342]
Steps to reproduce:

1. Go to Media > + > Free Photo Library or Free GIF Library.
1. Tap the search field to make that field active (if it isn't already).
1. Observe that the NoResults view background graphic is cut off when the keyboard is present.

**Result:** Free GIF/Photo Library search screen no results background gets cut off when the keyboard is open.

<img src="https://user-images.githubusercontent.com/1119271/84955191-0b652000-b0b4-11ea-8c06-a2cf7a12243a.PNG" width="150" alt="IMG_4266"> <img src="https://user-images.githubusercontent.com/1119271/84955195-0f913d80-b0b4-11ea-99b9-bbdf2517fab3.PNG" width="150" alt="IMG_4265"> <img src="https://user-images.githubusercontent.com/1119271/84955201-115b0100-b0b4-11ea-9b3a-817d116b9779.PNG" width="150" alt="IMG_4267"> <img src="https://user-images.githubusercontent.com/1119271/84955215-17e97880-b0b4-11ea-8e6b-f9d16cd96417.PNG" width="150" alt="IMG_4268">

<p style="clear:both;"><sup>Tested with WPiOS 15.1.0.0 TestFlight beta on iPhone 11 iOS 13.5.1.</sup></p>

**Comment by ScoutHarris** [comment]
FWIW, it looks like the problem is the No Results View itself, not the media searches specifically. For example, this is the no sites view:

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-07-23 at 14 21 29](https://user-images.githubusercontent.com/1816888/88334989-d621a280-ccef-11ea-8484-a61ea50354e8.png)

The NRV should be centered vertically in the view, but it isn't anymore. If it were, I think the search views would be correct.

**Comment by ScoutHarris** [comment]
Tangentially related - I haven't fixed this because simply centering the NRV vertically in the view makes things worse on the iPad by cutting off the button. Specifically because, as noted [here](https://github.com/wordpress-mobile/WordPress-iOS/issues/14547#issuecomment-702217917), when the My Sites NRV is displayed, the view is no longer updating on rotation. 

| Now | With NRV vertically centered |
|--------|-------|
| ![Simulator Screen Shot - iPad Pro (9 7-inch) - 2020-10-08 at 11 52 31](https://user-images.githubusercontent.com/1816888/95495798-25758780-095d-11eb-8fbd-848f9b706bd7.png) | ![Simulator Screen Shot - iPad Pro (9 7-inch) - 2020-10-08 at 11 51 32](https://user-images.githubusercontent.com/1816888/95495825-2dcdc280-095d-11eb-9a4a-18e5d27cc8ca.png) |

I don't know what's causing the iPad rotation issue, but my 2 cents is to not fix the NRV vertical issue until the iPad rotation is fixed.

**Comment by ScoutHarris** [comment]
I was able to put in a [workaround](https://github.com/wordpress-mobile/WordPress-iOS/pull/15081) for the aforementioned iPad rotation issue. So I went ahead and fixed the NRV vertical alignment that will fix this Media view issue.
