### ISSUE TITLE
Feature Request: Search posts with tags

### ISSUE THREAD

**Issue by ahmet-izgi** [wordpress-mobile/WordPress-iOS#14429]
### Expected behavior
I expect to see tags on the post list and able to search for posts with tags.

### Actual behavior
Tags are not visible to the user on search or lists.

Same as wordpress-mobile/WordPress-Android#12363

**Comment by rachelmcr** [comment]
One thing to note is that searching by tag is also not supported on the web, so that would be an entirely new feature for both web and app and likely requires API changes to support it.

That said, wp-admin web does display the tag in the list of posts and you can select a tag to view all posts with that tag, so we could consider something based on that:

![Screenshot 2020-07-08 16 30 56](https://user-images.githubusercontent.com/8658164/86938616-87dda280-c138-11ea-80c6-01e78a2b86ba.png)

**Comment by ahmet-izgi** [comment]
As you mentioned for the wp-admin side, user can use the URL for listing the posts with tags:

https://address/wp-admin/edit.php?tag=second

**Comment by kean** [comment]
Implemented in 23.7.
