### ISSUE TITLE
Password update doesn't force authentication on Mobile

### ISSUE THREAD

**Issue by carladoria** [wordpress-mobile/WordPress-iOS#14515]
### Expected behavior
After changing the password in Desktop, I would expect the Mobile app to ask you to log in/authenticate again when editing a site, specifically a post. 

### Actual behavior

I was able to post a from Mobile app without the App asking me to authenticate again. 

### Steps to reproduce the behavior

1. Go to https://wordpress.com/me/security and change password (If you have double-step auth, you will be asked here to confirm with the respective code) Message that password has been changed is shown. 
2. Go to App on phone (already logged into the same account) select a site. 
3. Add a post, publish it. The post will be published without problems and without asking to log in again. 

##### Tested on [device], iOS [version], WPiOS [version]

iPhone 8, iOS 13.6

**Comment by rachelmcr** [comment]
The app's authentication for WordPress.com accounts is managed with an auth token (rather than being directly connected to password changes on the account). You can manage that authentication in your Connected Apps here: https://wordpress.com/me/security/connected-applications

We have an open issue https://github.com/wordpress-mobile/WordPress-iOS/issues/9392 related to handling and improving the experience if you revoke the app from that page. I'm going to close this issue since that's the expected flow for requiring reauthentication in the app.
