### ISSUE TITLE
Rename Contact Us to Connect App support

### ISSUE THREAD

**Issue by rezzap** [wordpress-mobile/WordPress-iOS#14616]
We receive a lot of tickets in the mobile apps with only phone number and contact details. One user followed up on such a ticket to confirm that they thought they were settings up their support for people who visit their site through the app to contact them. 

We're wondering if part of the issue here is the label 'Contact Us' that may be causing people to not realize this is for App Support. 

I'd like to be able to edit this label to make it clearer that they are contacting app support to see if this helps to reduce the incoming number of unknown support requests with contact details. 

### Steps to reproduce the behavior

Navigate to Me > Help & Support, view the 'Contact Us' button.

**Comment by elibud** [comment]
Let's rename the label to: "Contact WordPress support"

**Comment by rezzap** [comment]
I think we need to be careful to clarify that this is 'App Support' and not 'WordPress support'. We don't support the WordPress software, just the app.

**Comment by designsimply** [comment]
I have another option for consideration. How about "Start a Support Ticket"? This would be in line with the other language on the page and also give at least a small hint in the title that it's not a synchronous conversation.

Or if you're okay to specifically mention that support is only for the app, what about "Get Help with the App" on the first screen and "Start a Support Ticket" on the second screen?

Alternately, if you change it to say "Contact App Support" then would you also want to change the label just above it from "WordPress Help Center" to "App Help Center" or WordPress App Help Center"?

ftr, I am less in favor of trying to be explicit that support is only for the app because I think people are likely to ignore that anyway either because they don't know the difference or they act quickly and don't read (possibly in panic mode if they feel they need help urgently), and because I feel requests which cannot be covered by our support team can and should be redirected in a helpful way, which I think happiness engineers can do a good job with and which also helps affect App Reviews positively in my experience.

Also, here are some current screenshots for reference:

<img src="https://user-images.githubusercontent.com/1119271/89945838-39ac3b00-dbdf-11ea-9083-2a70c9695d5f.PNG" width="33%" alt="IMG_4478"> <img src="https://user-images.githubusercontent.com/1119271/89945567-c9051e80-dbde-11ea-8584-aaa97112770b.PNG" width="33%" alt="IMG_4479"> <img src="https://user-images.githubusercontent.com/1119271/89945787-25683e00-dbdf-11ea-95c0-7d614c657200.PNG" width="33%" alt="IMG_4480">

<p style="clear:both;"><sup>Tested with WPiOS 15.5.0.0 TestFlight beta on iPhone 11 iOS 13.6.</sup></p>

**Comment by elibud** [comment]
@bummytime @mattmiklic can you please come up with a naming convention that makes sense here?

**Comment by mattmiklic** [comment]
My instinct would be to go with the simplest clear option, which I think is "Contact Support." As @designsimply mentioned I don't think most users are going to make a distinction between WordPress and the "App," but I also wouldn't expect them to know what a "ticket" is right off the jump. Any objections to this?

**Comment by elibud** [comment]
Going with Contact Support for both screens one and three [here](https://github.com/wordpress-mobile/WordPress-iOS/issues/14616#issuecomment-672270551) works for me.

**Comment by bummytime** [comment]
@mattmiklic I think `Contact Support` is perfect — short and clear.

**Comment by rezzap** [comment]
I have no idea how I ended up with 'Connect App support' here, but Contact Support seems good to me also.

**Comment by guarani** [comment]
Thanks everyone, I'll change it to "Contact Support" then on screens one and three as described [here](https://github.com/wordpress-mobile/WordPress-iOS/issues/14616#issuecomment-672917817).

**Comment by guarani** [comment]
The PR is up [here](https://github.com/wordpress-mobile/WordPress-iOS/pull/14636), it changes the button title on the first screen but **not the third**. This was approved by @elibud after offline discussion about difficulties with the Zendesk SDK when attempting to change the third screen's title. More technical details in the PR.

**Comment by guarani** [comment]
@rezzap let me know if you'd like me to close this issue once [this](https://github.com/wordpress-mobile/WordPress-iOS/issues/14616#issuecomment-673122354) change is made, or leave it open to track changing the title on the third screen in the future (it's more complicated so couldn't be done now).

**Comment by guarani** [comment]
Accidentally closed via linked PR, reopening as per: https://github.com/wordpress-mobile/WordPress-iOS/issues/14616#issuecomment-673127531

**Comment by rezzap** [comment]
@guarani I think we're okay to close this as I think focusing on setting a better auto-responder or giving some options to the users to follow up within the actual contact screen should clarify what it's about instead.

**Comment by guarani** [comment]
> @guarani I think we're okay to close this as I think focusing on setting a better auto-responder or giving some options to the users to follow up within the actual contact screen should clarify what it's about instead.

Ok @rezzap, thanks for clarifying — closing now.
