### ISSUE TITLE
Contact Support: Set character minimum

### ISSUE THREAD

**Issue by msilbers** [wordpress-mobile/WordPress-iOS#14695]
We'd like to see if we can set a character minimum for when folks contact us. We get a fair amount of tickets that include things like the following:

- Hi
- Hii
- Hey
- hello
- text

If we could set a character minimum in the form to at least 6, it would help most of this (I hope!), but I can see up to 10 characters being good too. Folks should be sending us questions and their site link, and I don't think it's possible to do that in 10 characters.

mentioned in comment on p8wKgj-1ox-p2

**Comment by designsimply** [comment]
The first step for this issue should be to explore what's possible using our current implementation of the Zendesk SDK, although it has already been noted on the Android side that there's not a way to do it as an SDK consumer.

If we cannot enforce a character limit using the SDK in our current implementation, would it be possible to identify the tickets with a very short amount of text and tag them so that an auto-responder could then be triggered on the Zendesk side?

<sup>(internal reference: p8wKgj-1ox-p2#comment-8682)</sup>

Related Android issue: https://github.com/wordpress-mobile/WordPress-Android/issues/12736.

**Comment by ScoutHarris** [comment]
Hey @designsimply . What @mzorz [said](https://github.com/wordpress-mobile/WordPress-Android/issues/12736#issuecomment-683013500) on the Android issue pertains to iOS as well - `the SDK is closed in this aspect, we present the chat screen and it doesn't expose this information to us (so we can't really tell what length the messages are)`.

So there's really nothing we can do on the app side for this.

**Comment by bummytime** [comment]
**Nov 2nd, 2020 Update:** @mzorz emailed Zendesk about this and they replied that having a minimum character limit is **not** possible with any version of the Zendesk SDK.  

> If we cannot enforce a character limit using the SDK in our current implementation, would it be possible to identify the tickets with a very short amount of text and tag them so that an auto-responder could then be triggered on the Zendesk side?

@designsimply I am assuming so, but not sure. 😄 So since there's no way to see _any_ text the user entered on the app side, this would be our only option.

cc @msilbers @ScoutHarris

**Comment by bummytime** [comment]
After a quick chat with @elibud, we decided to close this issue since nothing can happen on the app side. Please re-open if this situation changes.

**Comment by designsimply** [comment]
Thank you everyone for following up on this one. Even though we couldn't fix it, it's helpful to have checked on it and to have this documented!
