### ISSUE TITLE
Reader: Facebook Embed Block

### ISSUE THREAD

**Issue by belcherj** [wordpress-mobile/WordPress-iOS#14709]
### Expected behavior

It should render

### Actual behavior

It only renders part of the embed

![image](https://user-images.githubusercontent.com/6817400/90908862-f7cf8180-e3a2-11ea-96c8-2dd5b91f700f.png)

### Steps to reproduce the behavior

1. Make post with Facebook Emebed
2. Observe in the app

##### Tested on [device], iOS [version], WPiOS [version]

iPhone 7, 13.6, 15.3

**Comment by leandroalonso** [comment]
I've spent a few hours testing that and unfortunately, IMHO, it's something that I don't think it worths fixing given the cost.

From my exploration, the problem happens in the Facebook SDK if:

1. The embed has an image
2. We're loading the page locally

About (1): the issue doesn't happen if the post is just plain text, like:

<img src="https://user-images.githubusercontent.com/7040243/92622124-15ee1a80-f29b-11ea-880d-2c353f48f810.png" width="300">

About (2): we load the Reader content locally, passing the HTML directly to the WebView. When loading the same content from a URL (using a locally server, for example) the content renders fine. There is probably a bug in the FB SDK that is causing to calculate the height wrong because of that.

Another bummer is that the FB SDK repo has been deactivated (long time ago): https://github.com/facebookarchive/facebook-js-sdk

Also, I tried using the most recent versions of the SDK and also playing with [some methods](https://developers.facebook.com/docs/reference/javascript/FB.XFBML.parse). The result was always the same: the height wasn't correct.

We could try a solution to resize the iframe but this seems too much and very error-prone. Not to take into account the amount of code this will add.

Given the context above, I think this is something we will have to live with and hope that Facebook fixes it.

@designsimply do you think we should leave this issue open?

**Comment by leandroalonso** [comment]
Given cost vs impact, I'm closing this issue.
