### ISSUE TITLE
The operation couldn’t be completed. (WordPress.MediaRequestAuthenticator.Error error 5.)

### ISSUE THREAD

**Issue by jkmassel** [wordpress-mobile/WordPress-iOS#14786]
**Sentry Url**: https://sentry.io/share/issue/4b7257b8379449ae93e223994e6c0d2d/
**User Count**: 44
**Count**: 843
**First Release**: 14.7.1.0
**First Seen**: 2020-05-14T03:30:36Z
**Last Seen**: 2020-08-27T01:13:45Z
**24 Hours**: 0
**30 Days**: 344

```
The operation couldn’t be completed. (WordPress.MediaRequestAuthenticator.Error error 5.)

```

**Comment by designsimply** [comment]
**Events in the last 90d:** 718
**Users affected in the last 90d:** 47
<sub>WORDPRESS-IOS-37R2: https://sentry.io/share/issue/4b7257b8379449ae93e223994e6c0d2d/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=release&field=os&field=device&field=culprit&name=All+Events&project=1438083&query=issue.id%3A1664596138&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1">![image](https://user-images.githubusercontent.com/1119271/92030627-2c84f680-ed1c-11ea-982a-92593a3e2796.png)</a>

Possibly related: https://github.com/wordpress-mobile/WordPress-iOS/pull/13813

**Comment by designsimply** [comment]
**Events in the last 90d:** 721
**Users affected in the last 90d:** 55
<sub>WORDPRESS-IOS-37R2: https://sentry.io/share/issue/4b7257b8379449ae93e223994e6c0d2d/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=release&field=os&field=device&field=culprit&name=All+Events&project=1438083&query=issue.id%3A1664596138&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1">![image](https://user-images.githubusercontent.com/1119271/94750582-9b696580-0343-11eb-9fd5-f16aa7f285db.png)</a>

**Comment by designsimply** [comment]
Numbers of users affected by this crash seems relatively low but I'm leaving this one open for now because it appears media-related and I think it's part of a long tail of issues which add up to cause an overall high number of media complaints we see from users. 

**Events in the last 90d:** 1,600
**Users affected in the last 90d:** 43
<sub>WORDPRESS-IOS-37R2: https://sentry.io/share/issue/4b7257b8379449ae93e223994e6c0d2d/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=release&field=os&field=device&field=culprit&name=All+Events&project=1438083&query=issue.id%3A1664596138&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1">![image](https://user-images.githubusercontent.com/1119271/101709220-50a75080-3a4c-11eb-8ff4-a7fc3be1b51d.png)</a>
