### ISSUE TITLE
EXC_BREAKPOINT: init(nibName:bundle:) > WordPress.GutenbergWebNavigationController

### ISSUE THREAD

**Issue by jkmassel** [wordpress-mobile/WordPress-iOS#14792]
**Sentry Url**: https://sentry.io/share/issue/6dea74a8ab7d4e4faffa9ddaca9ebdf2/
**User Count**: 121
**Count**: 205
**First Release**: 15.3.0.3
**First Seen**: 2020-07-28T01:40:20Z
**Last Seen**: 2020-08-28T13:10:55Z
**24 Hours**: 3
**30 Days**: 201
**LogID:** 7E53FB2F-C485-486D-A6EF-4114EC680EC5

```
EXC_BREAKPOINT: init(nibName:bundle:) > WordPress.GutenbergWebNavigationController
  File "<compiler-generated>", line null, in _unimplementedInitializer
  File "WordPress", line null, in _unimplementedInitializer
  File "GutenbergWebNavigationViewController.swift", line 3, in GutenbergWebNavigationController.init
  File "<compiler-generated>", line null, in GutenbergWebNavigationController.init
  File "GutenbergWebNavigationViewController.swift", line 12, in GutenbergWebNavigationController.init
  File "GutenbergViewController.swift", line 763, in GutenbergViewController.gutenbergDidRequestUnsupportedBlockFallback
  File "RNReactNativeGutenbergBridge.swift", line 66, in RNReactNativeGutenbergBridge.requestUnsupportedBlockFallback
  File "<compiler-generated>", line null, in RNReactNativeGutenbergBridge.requestUnsupportedBlockFallback
  File "<compiler-generated>", line null, in @callee_guaranteed
  File "main.swift", line 7, in main
...
(10 additional frame(s) were not displayed)
```

**Comment by designsimply** [comment]
The majority of these crashes appear to be happening for iOS 12.x, WPiOS 15.3.0.3, and iPhone 7 or below.

**Comment by bummytime** [comment]
@maxme and @hypest → any thoughts on this crasher?

**Comment by hypest** [comment]
`GutenbergWebNavigationController` is related to the Unsupported Blocks editing feature so, pinging @etoledom that has worked on this recently to assess.

**Comment by etoledom** [comment]
> The majority of these crashes appear to be happening for iOS 12.x, WPiOS 15.3.0.3, and iPhone 7 or below.

I confirm this is indeed a iOS12-only issue.  I can't test earlier versions but iOS 13 is not affected.
~Still looking for a solution.~ Solution found

**Comment by etoledom** [comment]
@designsimply - Should a fix for this go via hotfix on the current published version?

It does look quite ugly, but if the numbers are low, we might hotfix the current beta version instead 🤔

**Comment by designsimply** [comment]
I am in favor of fixing it for 15.6 (currently in code freeze) if it can be done by tomorrow and if it's okay with @jkmassel because unsupported block editing is an important feature. If @jkmassel thinks it's too late to fix in the 15.6 then targeting 15.7 will do.

**Events in the last 90d:** 234
**Users affected in the last 90d:** 135
<sub>WORDPRESS-IOS-38J0: https://sentry.io/share/issue/6dea74a8ab7d4e4faffa9ddaca9ebdf2/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=release&field=os&field=device&field=culprit&name=All+Events&project=1438083&query=issue.id%3A1810521175&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1">![image](https://user-images.githubusercontent.com/1119271/92032751-77543d80-ed1f-11ea-9c2f-215791c05669.png)</a>

**Comment by jkmassel** [comment]
I'm ok with this too :)

**Comment by bummytime** [comment]
Thank you @etoledom !

**Comment by hypest** [comment]
Fixed by https://github.com/wordpress-mobile/WordPress-iOS/pull/14827
