### ISSUE TITLE
Reader: Old P2s under the Automattic tab are not showing the Follow Conversation button

### ISSUE THREAD

**Issue by startuptester** [wordpress-mobile/WordPress-iOS#14883]
### Expected behavior
According to https://github.com/wordpress-mobile/WordPress-iOS/pull/14806, I should be able to "Open the comments on any P2 post in Reader and follow the conversation". 

### Actual behavior
Noticed it is not working on appstestingp2

@leandroalonso says: 
"We have a new property that says if a blog is a P2 or not (and we use it to show this button)
This flag is false for old P2s (like the apptesting). But in this case, the app should check if this P2 is under the "Automattic" tab and show the button. The latter is probably failing!" 
![image](https://user-images.githubusercontent.com/66104034/92955590-a99e2300-f422-11ea-8cb0-34d46871f4b6.png)

### Steps to reproduce the behavior
open appstestingp2 in Reader and open the comments. You'll see there is no "Follow Conversation" button. On a newer p2 like albatrossp2, it appears. 

##### Tested on [device], iOS [version], WPiOS [version]
iPadd (2019), iOS 13.7, WPiOS 15.7.0.1

**Comment by mindgraffiti** [comment]
Hey @startuptester 👋 

Can you clarify the Steps to Reproduce? 

This seems fixed in https://github.com/wordpress-mobile/WordPress-iOS/pull/14702. I can see the follow / unfollow button in our latest beta, 16.1.

I tested under two cases and verified the issue was fixed:

**Test Case 1**
1. Navigate to Reader tab
2. Select Automattic in carousel
3. Find a post from a known old p2 
4. Tap the post's comment button

The follow / unfollow button appears.

**Test Case 2**
1. Navigate to the Reader tab
2. Select Automattic in the carousel
3. Find a post from a known old p2
4. Tap on the post to navigate to the post view
5. Tap on either: the "Comments >" text button or the Comment icon

The follow / unfollow button appears.

<a href="https://user-images.githubusercontent.com/1062444/98840329-47ef3a80-240c-11eb-9ee3-945893391900.png"><img src="https://user-images.githubusercontent.com/1062444/98840329-47ef3a80-240c-11eb-9ee3-945893391900.png" width="350" /></a>

**Comment by startuptester** [comment]
Thanks @mindgraffiti! I am unable to reproduce this in the latest beta also.

**Comment by mindgraffiti** [comment]
Related: pbArwn-1n5-p2. Leaving this ticket open for now, until we know how we should handle the older internal P2s.

**Comment by mindgraffiti** [comment]
Closing in favor of #15273.
