### ISSUE TITLE
iOS 14: Crash when viewing post related to a notification

### ISSUE THREAD

**Issue by jkmassel** [wordpress-mobile/WordPress-iOS#14933]
### Steps to reproduce the behaviour
0. Be running iOS 14 and WPiOS 15.7.0.2 (the XC12 Testflight build)
1. Go to "Notifications" tab
2. Tap on the notification
3. Tap the related post.
4. The app will almost always crash

**Comment by leandroalonso** [comment]
Just adding a little bit more information here:

I wasn't able to reproduce this crash on the simulator, only on the device. The crash happens in the method [updateLeadingContentConstraint](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/ViewRelated/Reader/ReaderCommentCell.swift#L238) because `leadingContentConstraint` is `nil`:

```
2020-09-17 16:57:08.011463-0300 WordPress[2715:229584] Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value: file WordPress/ReaderCommentCell.swift, line 238
```
