### ISSUE TITLE
NSInvalidArgumentException: *** +[NSURLComponents initWithURL:resolvingAgainstBaseURL:]: nil URLString parameter

### ISSUE THREAD

**Issue by jkmassel** [wordpress-mobile/WordPress-iOS#14959]
**Sentry Url**: https://sentry.io/share/issue/a56a1be8c831473f89e936ed11c4fb1b/
**User Count**: 49
**Count**: 118
**First Release**: 15.5.0.3
**First Seen**: 2020-09-01T20:58:17Z
**Last Seen**: 2020-09-22T03:31:31Z
**24 Hours**: 3
**30 Days**: 118
**LogID:** 9A9C5397-BD89-456E-A191-23D31259D8C3

```
NSInvalidArgumentException: *** +[NSURLComponents initWithURL:resolvingAgainstBaseURL:]: nil URLString parameter
  File "Classes/Services/BlogService.m", line 763, in -[BlogService migrateRemoteJetpackBlog:forAccount:]
  File "Classes/Services/BlogService.m", line 703, in -[BlogService updateBlogWithRemoteBlog:account:]
  File "Classes/Services/BlogService.m", line 673, in -[BlogService mergeBlogs:withAccount:completion:]
  File "Classes/Services/BlogService.m", line 155, in __51-[BlogService syncBlogsForAccount:success:failure:]_block_invoke_2
...
(11 additional frame(s) were not displayed)
```

**Comment by designsimply** [comment]
**Events in the last 90d:** 149
**Users affected in the last 90d:** 69
<sub>WORDPRESS-IOS-38VX: https://sentry.io/share/issue/a56a1be8c831473f89e936ed11c4fb1b/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=release&field=os&field=device&field=culprit&name=All+Events&project=1438083&query=issue.id%3A1871364958&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1">![image](https://user-images.githubusercontent.com/1119271/94946486-7555d980-0499-11eb-98a9-6b866fefda1a.png)</a>

**Comment by designsimply** [comment]
Raising in priority because it's showing as a spike on Nov 20 and then continued to average ~100 crashes per day and also the number of different users affected is relatively large compared to other similar sized crashes we're tracking.

**Events in the last 90d:** 2,600
**Users affected in the last 90d:** 1,500
<sub>WORDPRESS-IOS-38VX: https://sentry.io/share/issue/a56a1be8c831473f89e936ed11c4fb1b/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=release&field=os&field=device&field=culprit&name=All+Events&project=1438083&query=issue.id%3A1871364958&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1">![image](https://user-images.githubusercontent.com/1119271/101846216-bf001780-3b0d-11eb-97e1-e570ddefdb77.png)</a>

**Comment by designsimply** [comment]
@jkmassel when I look at https://sentry.io/share/issue/a56a1be8c831473f89e936ed11c4fb1b/ it shows this error:

> NSInternalInconsistencyException
> Attempted to perform update with invalid index path: <NSIndexPath: 0x28164bb20> {length = 2, path = 1 - 18446744073709551615}

![image](https://user-images.githubusercontent.com/1119271/101949115-59189c00-3bb0-11eb-9416-5b3268cfde73.png)

The error shown here in this issue is totally different and starts with:

> NSInvalidArgumentException: *** +[NSURLComponents initWithURL:resolvingAgainstBaseURL:]: nil URLString parameter

Why are those so different?
