### ISSUE TITLE
NSInvalidArgumentException: nil is not a valid object ID

### ISSUE THREAD

**Issue by jkmassel** [wordpress-mobile/WordPress-iOS#14960]
**Sentry Url**: https://sentry.io/share/issue/fa5a0d83563c4b85a92aaf6cfbe1c21d/
**User Count**: 114
**Count**: 157
**First Release**: 15.3.0.3
**First Seen**: 2020-08-24T16:42:37Z
**Last Seen**: 2020-09-22T02:40:15Z
**24 Hours**: 8
**30 Days**: 157
**LogID:** 170A3571-0A7B-4AA3-987E-38C133C38B02

```
NSInvalidArgumentException: nil is not a valid object ID
  File "Classes/Services/MediaService.m", line 581, in __56-[MediaService syncMediaLibraryForBlog:success:failure:]_block_invoke
...
(10 additional frame(s) were not displayed)
```

**Comment by designsimply** [comment]
I see that this issue was given high priority but was not assigned. @bummytime may I loop you back in to get help assigning this one since it's a new crash? 

**Events in the last 90d:** 235
**Users affected in the last 90d:** 162
<sub>WORDPRESS-IOS-38VV: https://sentry.io/share/issue/fa5a0d83563c4b85a92aaf6cfbe1c21d/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=release&field=device&field=os&field=culprit&name=All+Events&project=1438083&query=issue.id%3A1871198051&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1">![image](https://user-images.githubusercontent.com/1119271/94750911-70334600-0344-11eb-93e4-3f7bd1705e46.png)</a>

**Comment by bummytime** [comment]
Current impact → First Release: 15.3.0.3; 186 Users (5-10 events/day). I am removing the high-pri status from this issue. We will potentially add this issue to a "Media improvements" project starting in the near term.

**Comment by designsimply** [comment]
Fixed in https://github.com/wordpress-mobile/WordPress-iOS/pull/15075. Props @diegoreymendez. 🎉

<sub>WORDPRESS-IOS-38VV: https://sentry.io/share/issue/fa5a0d83563c4b85a92aaf6cfbe1c21d/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=release&field=device&field=os&field=culprit&name=All+Events&project=1438083&query=issue.id%3A1871198051&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1">![image](https://user-images.githubusercontent.com/1119271/101846089-734d6e00-3b0d-11eb-9886-f83ac54f7d6c.png)</a>
