### ISSUE TITLE
NSInvalidArgumentException: Application tried to present modal view controller on itself. Presenting controller is <UISearchC...

### ISSUE THREAD

**Issue by jkmassel** [wordpress-mobile/WordPress-iOS#14961]
**Sentry Url**: https://sentry.io/share/issue/eb81e938296947be8f22886d673dc4b8/
**User Count**: 72
**Count**: 153
**First Release**: 15.5.0.3
**First Seen**: 2020-08-24T21:05:07Z
**Last Seen**: 2020-09-22T03:30:57Z
**24 Hours**: 8
**30 Days**: 153
**LogID:** 87E7FFBB-ED3F-447F-BD2E-BF6B5E355676

```
NSInvalidArgumentException: Application tried to present modal view controller on itself. Presenting controller is <UISearchC...
  File "main.swift", line 7, in main
...
(24 additional frame(s) were not displayed)
```

**Comment by jkmassel** [comment]
This one was created as part of splitting up `NSInvalidArgumentException` events that were all mashed together. This one is exclusively for the invalid search controller.

**Comment by bummytime** [comment]
Thanks @jkmassel. @frosty — any thoughts on this one?

**Comment by designsimply** [comment]
**Events in the last 90d:** 194
**Users affected in the last 90d:** 97
<sub>WORDPRESS-IOS-38VK: https://sentry.io/share/issue/eb81e938296947be8f22886d673dc4b8/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=release&field=device&field=os&field=culprit&name=All+Events&project=1438083&query=issue.id%3A1871005097&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1">![image](https://user-images.githubusercontent.com/1119271/94751181-11220100-0345-11eb-9a18-f92b4b1f1eac.png)</a>

**Comment by designsimply** [comment]
Seems this one has gained momentum starting on Nov 19th, but I am not sure if that's because of a change we've made to Sentry grouping or if it's really an upward trend. 🤨  It's certainly looks like there's an uptick but at the same time it's not showing very many crashes in 16.2 so far (31 crashed recorded in 16.2 to date). Also the overall numbers are relatively low compared to some other crashes we are tracking. I'd like to get a 2nd opinion on this one to find out if it's worth raising to high priority because of a recent uptick. @bummytime could you help me with a check on priority for this one?

**Events in the last 90d:** 557
**Users affected in the last 90d:** 298
<sub>WORDPRESS-IOS-38VK: https://sentry.io/share/issue/eb81e938296947be8f22886d673dc4b8/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=release&field=device&field=os&field=culprit&name=All+Events&project=1438083&query=issue.id%3A1871005097&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1">![image](https://user-images.githubusercontent.com/1119271/101845642-6a0fd180-3b0c-11eb-9047-62a82a362194.png)</a>
