### ISSUE TITLE
Self-hosted site username not editable

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#1497]
Username on a self-hosted site is not editable.

![usernamenoteditable](https://cloud.githubusercontent.com/assets/373903/2531105/b636f80c-b52d-11e3-8944-eff911d66b6a.png)

**Comment by hoverduck** [comment]
29Oct15 Bug Scrub -

Verified this is still an issue.

**Comment by rachelmcr** [comment]
Verified that this field is still not editable as of beta v. 5.0.20161113.

If the goal is to allow users to log out of one account on the self-hosted site and log in again as a different user, I'd argue that we should connect that with the "Remove Site" functionality rather than simply making this field editable. Could we offer a log out/in option that pre-fills the site URL but otherwise acts like the remove/add site flow?

**Comment by astralbodies** [comment]
Yeah I'm going to opt for forcing them to remove the site.
