### ISSUE TITLE
blog post content bleeds into sidebar rather than wraps on ios14 only

### ISSUE THREAD

**Issue by wiredpinecone** [wordpress-mobile/WordPress-iOS#14976]
### Expected behavior
Blog post formatted correctly so that content wraps rather than bleeds into sidebar. 

### Actual behavior
only on iOS 14:  post content bleeds into sidebar
https://translatorswithoutborders.org/blog/chatbot-uji-drc/

### Steps to reproduce the behavior
visit link on iOS14 computer/ipad.  

##### Tested on [device], iOS [version], WPiOS [version]
mac computer/ipad, iOS 14,  WordPress version 5.5.1

**Comment by designsimply** [comment]
Thanks for reporting this. I checked it out and I can see what you mean, however, I think the problem exists when using Safari on the mobile web and not with the app itself, so we will likely want to move this issue to a different location and I will research where and follow-up. Also, it may be an issue with your theme or the implementation of it and we can probably try out a test to help narrow that down. It could also be happening because of a change in Safari iOS 14, but that would likely need to be addressed at the theme level as well. Thanks for letting me know the WP version you're running, versions are always helpful to know!

I tested viewing https://translatorswithoutborders.org/blog/chatbot-uji-drc/ on the mobile web and compared it to the app and found the following:

WPiOS 15.8 Reader|Safari iPhone 11 iOS 14|Safari iPhone 6S iOS 13.7
---|---|---
![IMG_4618](https://user-images.githubusercontent.com/1119271/94186759-508faf80-fe64-11ea-93af-10f2f1be0a88.PNG)|![IMG_4619](https://user-images.githubusercontent.com/1119271/94186765-52f20980-fe64-11ea-99a4-27fabbc1db71.PNG)|![IMG_3837](https://user-images.githubusercontent.com/1119271/94186767-54233680-fe64-11ea-917d-191cbf4fe07e.PNG)

<p style="clear:both;"><sup>Tested with WPiOS 15.8.0.0 TestFlight beta on iPhone 11 iOS 14.0 and iPhone 6S iOS 13.7.</sup></p>

Next steps:

* We should try this on a test blog and verify the problem happens on another site with the latest Twenty Sixteen theme.
* Try switching themes and check to see if the problem happens with other themes or not.
* Find out where to report the issue if we can verify it's related to the theme and is not fixed in the latest version of it.

**Comment by wiredpinecone** [comment]
Thank you -- here's another screenshot showing the issue.  
In the meantime I'll try spinning up something with twentysixteen to see if it can be replicated. This site is already pretty spare in its use of plugins and styling, so I do think it may be a theme issue where additional code may be needed to support the iOS14 browser.  

![File (2)](https://user-images.githubusercontent.com/7004973/94213421-8bf1a480-fe8b-11ea-88e9-e3b411e4a083.jpg)

**Comment by wiredpinecone** [comment]
Looks like twentysixteen was last updated 6 weeks ago, which was probably not in time to capture anything from the iOS14 beta: 
https://themes.trac.wordpress.org/log/twentysixteen/

**Comment by wiredpinecone** [comment]
Hi Sheri, I will also note that the site uses the Classic Editor, which was already having a few issues via WP 5.5.   

I don't have a MacOS environment so am not able to test well. 

What I did do was install the jQuery migrate helper plugin.  Can you look at the site again and see if it made any difference? 

I also imported some posts into this site: https://pinecone.dev/
WordPress 5.5, Classic Editor, TwentySixteen, minimal plugins. 

Would you mind taking a look?  Thanks in advance.

**Comment by wiredpinecone** [comment]
@designsimply - forgot to tag you on my reply yesterday so doing it now.
