### ISSUE TITLE
Tapping blog title doesn't open blog in Following tab, instead refreshes

### ISSUE THREAD

**Issue by startuptester** [wordpress-mobile/WordPress-iOS#14992]
### Expected behavior
When I am looking through the Reader > Following, I expect to be able to tap on a title and have that blog open just like it does in Discover.

### Actual behavior
Instead there is a strange refresh of the Following page

https://cloudup.com/cHg04vMr4RK

### Steps to reproduce the behavior
1. Reader > Discover
2. Tap on a blog title
3. See that the blog opens
4. Go to the Following tab
5. Tap on any title
6. See that it refreshes the page

**Comment by designsimply** [comment]
Tested and confirmed and in my testing I found that this happens from any site stream. A site stream is a view in Reader that shows a list of posts for a given site and you can access it from anywhere in the Reader.

1. Go to Reader.
1. Tap on any site title.
1. Tap on any site title again.

Result: I expected the screen either not to respond because I'm clicking on a view that I'm already on or the view should refresh with a spinner at the top. @mbshakti do you have a preference for what should happen in this case in terms of design?

![image](https://user-images.githubusercontent.com/1119271/94473666-b5f7df00-0189-11eb-892c-d360a3f8e32a.png)
<p style="clear:both;"><sup>Tested with WPiOS 15.7.0.5 (App Store version) on iPhone 6S iOS 13.7.</sup></p>

**Comment by mbshakti** [comment]
Tapping on site title, should open up the site page. I think this is a bug

**Comment by mbshakti** [comment]
@designsimply  and @startuptester is main description (by Meaghan) and Sheri's comment about the same issue? Seems like this is about different things.

**Comment by designsimply** [comment]
Yes the comments are both about the same issue, the difference is that you can get to the site stream in different ways. The problem described is that when you tap on the site name when you are already on the site stream it reloads instead of either doing nothing or showing a message.

**Comment by leandroalonso** [comment]
I don't think this causes a huge impact on the user experience.

In a lot of apps you can through this infinite loop, but given is caused by user interaction and the user doesn't get stuck I don't think it worths adding code there to deal with this edge case.

As for the original issue description, I click on a site's name and it works as expected.
