### ISSUE TITLE
Reader Improvements: Reader Detail Design Review

### ISSUE THREAD

**Issue by emilylaguna** [wordpress-mobile/WordPress-iOS#15052]
Project Issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/14768

An issue to track design feedback items for the Reader Detail feature.

**Comment by mbshakti** [comment]
It looks and feels amazing <3 Thank you for working on this @emilylaguna :) 

Some feedback/requests:

1. [UI nit] What's the font size of the post title? Is it title 2? I think I discussed this with Leandro before, but for some reason the post title still feels small. Just wanted to double check.

2. [UI nit] What's the spacing above the topic chips? It seems a bit tight. Can we make it 16px if it isn't already so?

3. [UI nit] The comment icon fill color seems slightly darker than the rest, they should all match/be consistent in fill color. Are we using the secondary label for that as well?

4. I noticed that the "block this site" & "report this blog" are missing from the overflow menu items on the RDV header, can we add them just so the overflow menu is consistent across screens?

5. [Request] For the comment entry point, I really like the fact that it exists. However, I should have designed for the zero-state earlier & included it in the mocks because I noticed that lots of blog posts have zero comments, and the copy `0 comments >`feels like a sad state :( Only when a blog post has zero comments, can we have the copy say something different like that `Comments >`? That way we don't attach the `0` to it and the lack of comments doesn't feel prominent for those blog posts.

**Comment by mbshakti** [comment]
Sharing some bugs in a separate comment.

6. When I tap on a topic or site from the RDV, I'm taken to the respective site/topic page (as expected). However, the back button copy is replaced with the name of the blog post. Is it expected? I'm including this here because this only happens when I navigate to a topic/site page from the RDV.

<img width="674" alt="Screen Shot 2020-10-07 at 12 50 23 PM" src="https://user-images.githubusercontent.com/6350997/95362157-b1bf7600-089b-11eb-8294-f4187a57e3ac.png">

7. Related to the above issue, there's also seems to be a slow transition of the text that doesn't feel expected:
![Kapture 2020-10-07 at 12 52 47](https://user-images.githubusercontent.com/6350997/95362494-28f50a00-089c-11eb-9a11-ddd846812518.gif)

8. When I tap on a blog post > go the RDV > go back to my main feed, the search icon is now black.
<img width="381" alt="Screen Shot 2020-10-07 at 12 55 19 PM" src="https://user-images.githubusercontent.com/6350997/95362647-6063b680-089c-11eb-9f02-ef3a1afd8636.png">

9. In dark mode, the RDV header icons turn black so they disappear

![Kapture 2020-10-07 at 12 56 38](https://user-images.githubusercontent.com/6350997/95362825-a6207f00-089c-11eb-9d62-f4754f006289.gif)

**Comment by emilylaguna** [comment]
> 1. [UI nit] What's the font size of the post title? Is it title 2? I think I discussed this with Leandro before, but for some reason the post title still feels small. Just wanted to double check.

Yep, it's using `title2` for iPhone and `title1` on iPad

> 2. [UI nit] What's the spacing above the topic chips? It seems a bit tight. Can we make it 16px if it isn't already so?

The spacing above the chips is currently at 16px

> 3. [UI nit] The comment icon fill color seems slightly darker than the rest, they should all match/be consistent in fill color. Are we using the secondary label for that as well?

Good catch. Added a screenshot for tracking. 
<img width="398" alt="Screen Shot 2020-10-07 at 2 44 30 PM" src="https://user-images.githubusercontent.com/793774/95373905-7ec4b480-0892-11eb-87e9-2cecb2d4aebc.png">

> 4. I noticed that the "block this site" & "report this blog" are missing from the overflow menu items on the RDV header, can we add them just so the overflow menu is consistent across screens?

Can Do!

> [Request] For the comment entry point, I really like the fact that it exists. However, I should have designed for the zero-state earlier & included it in the mocks because I noticed that lots of blog posts have zero comments, and the copy 0 comments >feels like a sad state :( Only when a blog post has zero comments, can we have the copy say something different like that Comments >? That way we don't attach the 0 to it and the lack of comments doesn't feel prominent for those blog posts.

Sounds good.

**Comment by mbshakti** [comment]
From the new build, just two small nits:

>The spacing above the chips is currently at 16px

If it's already 16px, can we bump it to 20px? I feel the space between the topic chips & header icons are too tight, and just needs to breath a bit. 

One other thing I *just* noticed was that there seems to be a difference in border size/stroke size/color in the bottom sticky bar (on RDV) & main nav bar (on main Reader feed/across the app). Attached screenshot for reference. Can we match the style to the main nav bar? It looks thinner/lighter.

<img width="1248" alt="Screen Shot 2020-10-09 at 3 25 59 PM" src="https://user-images.githubusercontent.com/6350997/95623744-cc345380-0a43-11eb-836a-84d000cd4f01.png">
