### ISSUE TITLE
NSInternalInconsistencyException: Invalid indexPath

### ISSUE THREAD

**Issue by jkmassel** [wordpress-mobile/WordPress-iOS#15092]
**Sentry Url**: https://sentry.io/share/issue/30aed83802a5493e8ad4238fe8eea923/
**User Count**: 230
**Count**: 341
**First Release**: 13.6.0.3
**First Seen**: 2019-12-01T10:58:40Z
**Last Seen**: 2020-10-13T09:28:07Z
**24 Hours**: 7
**30 Days**: 285
**LogID:** 199EE8E5-7E49-4758-8F0E-AB5EDC6136D5

```
NSInternalInconsistencyException: Invalid indexPath
  File "NotificationsViewController.swift", line 921, in NotificationsViewController.selectRow
  File "NotificationsViewController.swift", line 221, in NotificationsViewController.traitCollectionDidChange
  File "<compiler-generated>", line null, in NotificationsViewController.traitCollectionDidChange
  File "main.swift", line 7, in main
...
(27 additional frame(s) were not displayed)
```

**Comment by yaelirub** [comment]
Low by numbers

**Comment by designsimply** [comment]
**Events in the last 90d:** 869
**Users affected in the last 90d:** 561
<sub>WORDPRESS-IOS-2S3M: https://sentry.io/share/issue/30aed83802a5493e8ad4238fe8eea923/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=release&field=device&field=os&field=culprit&name=All+Events&project=1438083&query=issue.id%3A1365600703&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1">![image](https://user-images.githubusercontent.com/1119271/101848288-549da600-3b12-11eb-81cd-28f30f6faeca.png)</a>

This looks like it stopped on Nov 20 but that's really weird because a search for the terms in the error like this `"NSInternalInconsistencyException" "Invalid indexPath"` shows that crashes with those terms started on Sep 15 and have had a steady trend upward since then. Also, something fishy might be going on with Sentry but I am not sure what yet.

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=release&field=device&field=os&field=culprit&name=All+Events&project=1438083&query=%22NSInternalInconsistencyException%22+%22Invalid+indexPath%22&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1">![image](https://user-images.githubusercontent.com/1119271/101848553-fcb36f00-3b12-11eb-822e-c4afd0af7c4f.png)</a>

Upon further review… it looks like https://github.com/wordpress-mobile/WordPress-iOS/issues/15368 was filed as a duplicate and so I'll close this issue in favor of the new one.
