### ISSUE TITLE
C++ Exception: __NSCFConstantString

### ISSUE THREAD

**Issue by jkmassel** [wordpress-mobile/WordPress-iOS#15242]
**Sentry Url**: https://sentry.io/share/issue/5562d24d0206485899f420ba523e33f4/
**User Count**: 150
**Count**: 218
**First Release**: 15.3.0.3
**First Seen**: 2020-08-23T22:34:52Z
**Last Seen**: 2020-11-06T11:17:09Z
**24 Hours**: 1
**30 Days**: 215
**LogID:** FE17B01E-0629-47E7-865C-D8364F165E82

```
C++ Exception: __NSCFConstantString

```

**Comment by jkmassel** [comment]
This looks like a crash in React Native on a background thread.

**Comment by designsimply** [comment]
Closing because the number of crashes has gone down to almost nothing and because there are no recorded cases in Sentry for this crash in any 16.* release.

**Events in the last 90d:** 260
**Users affected in the last 90d:** 176
<sub>WORDPRESS-IOS-38S8: https://sentry.io/share/issue/5562d24d0206485899f420ba523e33f4/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=release&field=os&field=device&field=culprit&name=All+Events&project=1438083&query=issue.id%3A1855480254&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1">![image](https://user-images.githubusercontent.com/1119271/101949843-7bf78000-3bb1-11eb-9cea-86be32d4f191.png)</a>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=release&field=os&field=device&field=culprit&name=All+Events&project=1438083&query=issue.id%3A1855480254+release%3A16.%2A&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1">![image](https://user-images.githubusercontent.com/1119271/101950085-ea3c4280-3bb1-11eb-9b25-7e9e70d35341.png)</a>
