### ISSUE TITLE
EXC_BREAKPOINT: initWithManagedObjectContext:

### ISSUE THREAD

**Issue by jkmassel** [wordpress-mobile/WordPress-iOS#15240]
**Sentry Url**: https://sentry.io/share/issue/ab3f3820cc104070aa2548d5c064c2cf/
**User Count**: 185
**Count**: 290
**First Release**: 15.9.0.2
**First Seen**: 2020-10-19T19:57:40Z
**Last Seen**: 2020-11-06T16:53:26Z
**24 Hours**: 43
**30 Days**: 295
**LogID:** FEA5FB7F-0C4F-418F-BD24-B00E86C800A7

```
EXC_BREAKPOINT: initWithManagedObjectContext:

...
(69 additional frame(s) were not displayed)
```

**Comment by jkmassel** [comment]
It looks like this is a typical Core Data crash, but only applies to iOS 14.2, which doesn't have debug symbols yet. For this reason, the stack trace in Apple's frameworks isn't symbolicated, so I think this _might_ be a duplicate – if so, the events on it will drop to zero once Sentry has iOS 14.2 debug symbols.

**Comment by designsimply** [comment]
> I think this might be a duplicate – if so, the events on it will drop to zero once Sentry has iOS 14.2 debug symbols.

I am closing this issue as not actionable because of the comment mentioning it might be a duplicate and events will drop to zero once Sentry has debug symbols and because the Sentry link provided https://sentry.io/share/issue/ab3f3820cc104070aa2548d5c064c2cf/ is not working 😞 and because the best looking match I could find for it in a search for `initWithManagedObjectContext` in Sentry returned a couple of issues which have already been fixed or posted in separate issues.

Without a working link to something in Sentry, there's really not much to go on here!
