### ISSUE TITLE
Screen flickers when creating new post and freezes when adding a picture

### ISSUE THREAD

**Issue by reginabally** [wordpress-mobile/WordPress-iOS#15255]
Reported in the app review:

> The app does not probably work on iPhone XS and iPad Pro 9.7. When you press the plus button the screen flickers and moves the icons off the screen on the iPhone. The blog post freezes when you try to add a picture blog and can only be unlocked by uploading the post. Please fix.

##### Reported on iPhone XS and iPad Pro 9.7, WPiOS 16.0

Unable to reproduce this on iPhone SE, iOS 14.1, WPiOS 16.0 so I've requested the user to reach out to us.

Date of review: Nov 6, 2020

**Comment by designsimply** [comment]
Thanks for reporting this @reginabally!

Would you mind having a look at https://github.com/wordpress-mobile/gutenberg-mobile/issues/1696 and let me know if you think that matches with the screen flicker behavior they're describing?

For the image upload problem, I know it's from an App Review but we would still need more info than what I can see here in order to investigate further. I'm sure you asked them to contact support already. If they do contact the support team and are able to provide more information, please create a separate issue for that case. It would be helpful to note type of site and exactly what screen they're on when trying to add a picture (i.e. sounds like the image block in the editor but it would be good to confirm this). Thank you again!

**Comment by reginabally** [comment]
Hi @designsimply! Thanks for taking a look at this!

It looks like the user reached out to us at the iOS forums [here](https://ios.forums.wordpress.org/topic/serious-bug-in-ios-app-when-pressing-sign) with the video recording.

I've uploaded the video and this is the link: https://d.pr/v/b7Cbse/UJDpsReWh4

The video was recorded on iPhone XS with IOS 14.1 and GBoard. We're still asking them for more information (e.g. type of site). For now, we've asked them to try a fresh installation of the app and see how it goes.

**Comment by hypest** [comment]
Thanks for the report!
@etoledom , can you have a look please to see if you make something out? Thanks!

**Comment by etoledom** [comment]
I know there have been changes to the bottom-sheet to make it grow and have navigation. @Tug's team sure will have a better insight about what the issue might be and how to solve it.

**Comment by Tug** [comment]
Indeed, might be related to https://github.com/WordPress/gutenberg/pull/26204
@dratwas Could you have a look?

**Comment by dratwas** [comment]
>@dratwas Could you have a look?

Sure! :)

**Comment by dratwas** [comment]
Hey @Tug, I tried it in a few configurations but I couldn't reproduce that :( Maybe there are some additional things that are required to make it happen.

What i have tested so far:
## iOS 14.1 - WPiOS 16.0
- iPhone XS
- iPhone 11 Pro
- iPad Pro 9.7

## iOS 14.1 - WPiOS 16.0 + GBoard
- iPhone XS
- iPhone 11 Pro
- iPad Pro 9.7

## iOS 14.1 - WPiOS 16.1.1 (from Appstore)
- iPhone XS
- iPhone 11 Pro
- iPhone X

## iOS 14.1 - WPiOS 16.1.1 (from Appstore) + GBoard
- iPhone XS
- iPhone 11 Pro
- iPhone X

## iOS 14.1 - WPiOS 16.2 (from TestFlight)
- iPhone XS
- iPhone 11 Pro
- iPhone X

## iOS 14.1 - WPiOS 16.2 (from TestFlight) + GBoard
- iPhone XS
- iPhone 11 Pro
- iPhone X

I checked all of them with Free and Business plan.

However, I observed something weird on the video with the issue. The keyboard doesn't slide up/down when appearing/disappearing and the toolbar slides. Can we get information about keyboard settings? I'm not a GBoard user and couldn't find the option to turn off the slide animation :( The second weird thing is the animation of the toolbar when changing focus from the title to the paragraph block. The toolbar shouldn't jump as it is on the video. It might be related to the `keyboardWillHide` and `keyboardWillShow` events. I can not reproduce this jumping toolbar as well.


@reginabally
> For now, we've asked them to try a fresh installation of the app and see how it goes.

Do we have some new information about that? Could we ask them to try the app with the default iOS keyboard instead of GBoard?

**Comment by reginabally** [comment]
> Do we have some new information about that? Could we ask them to try the app with the default iOS keyboard instead of GBoard?

@dratwas The user hasn't replied to us yet. I'll nudge them and ask them to reach out to us through email for easier communication.

**Comment by dratwas** [comment]
Hey @reginabally, do we have some new information about that issue?

**Comment by reginabally** [comment]
Hi @dratwas Unfortunately, we didn't receive any update from the user through the forums as well as on Zendesk.

**Comment by fluiddot** [comment]
I tried to reproduce this issue by installing the GBoard but I couldn't it so probably it’s already solved, the inserter menu is displayed properly and the image block works as expected.

_Tested on iPhone 11, iOS 14.2, WPiOS 17.0 (17.0.0.6)._

@reginabally did the user give any update? If not I think we could close this issue and in case we receive another ticket similar to this one then re-open it.

**Comment by reginabally** [comment]
Hi, @fluiddot Thanks for following up. We didn't hear back from the user still so I'll close this issue for now.
