### ISSUE TITLE
NSInvalidArgumentException: cannot access fetched objects before -performFetch:

### ISSUE THREAD

**Issue by jkmassel** [wordpress-mobile/WordPress-iOS#15334]
**Sentry Url**: https://sentry.io/share/issue/72a403e40c524643a61091b3a399ca43/
**User Count**: 99
**Count**: 171
**First Release**: 15.3.0.3
**First Seen**: 2020-09-03T15:26:12Z
**Last Seen**: 2020-11-19T05:10:22Z
**24 Hours**: 3
**30 Days**: 87
**LogID:** 0318CFF4-E9B3-47A0-AD56-0F6D832056FE

```
NSInvalidArgumentException: cannot access fetched objects before -performFetch:
  File "PostListViewController.swift", line 503, in PostListViewController.tableView
  File "<compiler-generated>", line null, in PostListViewController.tableView
  File "Classes/Utility/WPTableViewHandler.m", line 367, in -[WPTableViewHandler tableView:cellForRowAtIndexPath:]
  File "main.swift", line 7, in main
...
(20 additional frame(s) were not displayed)
```

**Comment by renanferrari** [comment]
I'm not totally sure about this one, but going by the Sentry logs this seems to be an issue around the `PostListViewController` class. 

@bjtitus Would you mind taking a look at this? It seems like you have worked around this area of the codebase recently, so you probably have the necessary context to evaluate this better than me.

I'm labeling this issue as medium priority ([high severity, low impact](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/docs/issue-triage.md#prioritization)) but feel free to change it as you see fit.

**Comment by designsimply** [comment]
This issue is not new and has really really low occurrences averaging ~1 per day over the last few weeks.

Labeling as low priority and closing because I want to use GitHub to track more urgent cases compared to this one. Please re-open if the numbers increase.

<sub>WORDPRESS-IOS-38WK: https://sentry.io/share/issue/72a403e40c524643a61091b3a399ca43/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=release&field=os&field=device&field=culprit&name=All+Events&project=1438083&query=issue.id%3A1875331641&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1">![image](https://user-images.githubusercontent.com/1119271/101953661-fa572080-3bb7-11eb-8bf6-2334a3274714.png)</a>
