### ISSUE TITLE
NSInternalInconsistencyException: All view controllers in a navigation controller must be distinct

### ISSUE THREAD

**Issue by jkmassel** [wordpress-mobile/WordPress-iOS#15337]
**Sentry Url**: https://sentry.io/share/issue/b2cea328234f42d0849166c9fcf6b1eb/
**User Count**: 112
**Count**: 419
**First Release**: 15.8.0.2
**First Seen**: 2020-10-13T07:14:04Z
**Last Seen**: 2020-11-19T04:03:58Z
**24 Hours**: 33
**30 Days**: 411
**LogID:** DD90FEF2-FFDB-4C15-AC38-910EC4BE7E42

```
NSInternalInconsistencyException: All view controllers in a navigation controller must be distinct ((
  File "WPSplitViewController.swift", line 511, in WPSplitViewController.splitViewController
  File "<compiler-generated>", line null, in WPSplitViewController.splitViewController
  File "<compiler-generated>", line 482, in WPSplitViewController.splitViewController
  File "main.swift", line 7, in main
...
(71 additional frame(s) were not displayed)
```

**Comment by renanferrari** [comment]
Hey @ScoutHarris, would you mind looking into this? It seems like you have worked around the area of the codebase that is coming up in the logs and would have the necessary context to better evaluate the issue.

I'm labeling this issue as medium priority ([high severity, low impact](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/docs/issue-triage.md#prioritization)) but feel free to change it as you see fit.

**Comment by ScoutHarris** [comment]
Hey @renanferrari .

Split view is used by almost everything on iPad or split view iPhones. Typically, it's not split view itself, but how it's being used. In this case, looking at the breadcrumbs for this issue in Sentry, this is related to Notifications:

```
NSInternalInconsistencyException: All view controllers in a navigation controller must be distinct ((
    "<WordPress.NotificationsViewController: 0x13a87a000>",
    "<UIViewController: 0x13ed24150>",
    "<WordPress.NotificationsViewController: 0x13a87a000>",
    "<UIViewController: 0x13ed24150>"
))
```

And given it was first seen "a month ago in release 15.8.0.2", it pre-dates my changes. It looks like @leandroalonso did some work with `NotificationsViewController` about that time. Maybe he can take a look?

**Comment by renanferrari** [comment]
@ScoutHarris Thanks for the help with these issues, really appreciate it! 🙇

**Comment by leandroalonso** [comment]
I'll take a look!

**Comment by leandroalonso** [comment]
Even though this report is new, the crash has been there for at least 3 months (based on Sentry data).

I was looking into `WPTabBarViewController.m` and the `NotificationsViewController` instance is kept (which can explain how the same `NotificationsViewController` is added twice) but I'm not sure _how_ that might happen. I tried calling `reloadSplitViewControllers` twice but not crash at all.

@frosty do you have any idea how that can happen? Basically, the app is crashing because two instances of the same `NotificationsViewController` is being added to a `UINavigationController` (alongside another `UIViewController`). Do you know how that can happen?

**Comment by frosty** [comment]
Hmm, I'm not sure either 🤔 have we been able to reproduce this?

**Comment by designsimply** [comment]
> I was looking into WPTabBarViewController.m and the NotificationsViewController instance is kept (which can explain how the same NotificationsViewController is added twice) but I'm not sure how that might happen. 

It's a long shot but… what about if you open notifications then browse to a post and tap the share button at the top?

Note: this crash appears to have stopped getting cases recorded for it in Sentry as of 2020-11-20 🤔 but I think it moved because I see there are still crashes coming up if I do a search for `"All view controllers in a navigation controller must be distinct"` shows a steady increase of crashes for that in the latest release (16.2 which was released 11 days ago on 2020-11-30):

<sub>WORDPRESS-IOS-394A: https://sentry.io/share/issue/b2cea328234f42d0849166c9fcf6b1eb/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=release&field=os&field=device&field=culprit&name=All+Events&project=1438083&query=issue.id%3A1953889486&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1">![image](https://user-images.githubusercontent.com/1119271/101955068-5d49b700-3bba-11eb-9323-119d80286f27.png)</a>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=release&field=os&field=device&field=culprit&name=All+Events&project=1438083&query=%22All+view+controllers+in+a+navigation+controller+must+be+distinct%22&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1">![image](https://user-images.githubusercontent.com/1119271/101955879-dac1f700-3bbb-11eb-85db-cbdec9f1f07c.png)</a>

**Comment by aerych** [comment]
@designsimply @jkmassel is this still a thing?  The sentry links seem to 404 now.  If it's still happening can we update with links to the current sentry issue being tracked? (Or close if resolved?)

**Comment by salimbraksa** [comment]
Closing this issue as it was [last seen in wordpress `v20.9`](https://a8c.sentry.io/discover/homepage/?display=daily&field=title&field=event.type&field=project&field=user.display&field=timestamp&field=release&name=All+Events&project=1438083&project=5716771&query=level%3Afatal+%22All+view+controllers+in+a+navigation+controller+must+be+distinct%22&sort=-release&statsPeriod=90d&yAxis=count%28%29) and the latest version at the time of writing this comment is `v24.3`.
