### ISSUE TITLE
NSInvalidArgumentException: -[UIBarButtonItem bounds]: unrecognized selector sent to instance 0x108522960

### ISSUE THREAD

**Issue by jkmassel** [wordpress-mobile/WordPress-iOS#15336]
**Sentry Url**: https://sentry.io/share/issue/8d716ba403784433b92767d53341cdb2/
**User Count**: 177
**Count**: 337
**First Release**: 15.3.0.3
**First Seen**: 2020-08-28T05:13:48Z
**Last Seen**: 2020-11-19T04:47:40Z
**24 Hours**: 4
**30 Days**: 123
**LogID:** BB7B96B1-371B-4DC1-831F-06BAC9F84045

```
NSInvalidArgumentException: -[UIBarButtonItem bounds]: unrecognized selector sent to instance 0x108522960
  File "ReaderPostMenu.swift", line 86, in ReaderPostMenu.showMenuForPost
  File "ReaderDetailCoordinator.swift", line 283, in ReaderDetailCoordinator.showMenu
  File "Classes/ViewRelated/Reader/Detail/ReaderDetailCoordinator.swift", line 485, in ReaderDetailCoordinator.didTapMenuButton
  File "ReaderDetailViewController.swift", line 366, in ReaderDetailViewController.didTapMenuButton
  File "<compiler-generated>", line 365, in ReaderDetailViewController.didTapMenuButton
  File "main.swift", line 7, in main
...
(22 additional frame(s) were not displayed)
```

**Comment by renanferrari** [comment]
This seems to be related to the issue fixed by #15262. @yaelirub Would you mind looking into this and making sure I'm not mistaken?

**Comment by renanferrari** [comment]
@jkmassel Btw, the Sentry link seems to be broken for some reason. This is what I see when I open it:

<img width="600" alt="Captura de Tela 2020-11-19 às 12 23 50" src="https://user-images.githubusercontent.com/830056/99686164-173d7f80-2a62-11eb-9b76-5257c96eda1e.png">

**Comment by yaelirub** [comment]
@renanferrari , though the Sentry link is 404 so I can't look at the details, it does seem like its the same crash we fixed in https://github.com/wordpress-mobile/WordPress-iOS/pull/15262

**Comment by renanferrari** [comment]
@yaelirub Sorry for pinging you again, but you mind looking into #15331 as well? It seems to be related to this one.

I'm labeling this issue as medium priority ([high severity, low impact](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/docs/issue-triage.md#prioritization)) but feel free to change it as you see fit.

**Comment by designsimply** [comment]
It may have moved to [WORDPRESS-IOS-39EY](https://sentry.io/share/issue/1447123445254e3ab9eefb4d85020ca1/) which shows a different error: 

> NSInvalidArgumentException
> -[UIBarButtonItem _addGeometryChangeObserver:]: unrecognized selector sent to instance 0x11562e9a0

But a lot of the file names and line numbers match with the error showing in this GitHub issue, i.e. `"ReaderDetailCoordinator.swift", line 283`.

However, I am going to close this one with an ask to re-open it only if the numbers increase later because that new issue in Sentry appears to have been limited to release 16.0.0.6 and is currently coming up with really low numbers of occurrences.

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=release&field=os&field=device&field=culprit&name=All+Events&project=1438083&query=issue.id%3A2042869319&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1">![image](https://user-images.githubusercontent.com/1119271/101951403-2d97b080-3bb4-11eb-9b34-7afca3940ee1.png)</a>
