### ISSUE TITLE
NSInternalInconsistencyException: Tried to set <UIBarButtonItem: 0x104b43840> target=0x105330c00 action=didTapMenuButton: image=<UI...

### ISSUE THREAD

**Issue by jkmassel** [wordpress-mobile/WordPress-iOS#15331]
**Sentry Url**: https://sentry.io/share/issue/a01eba2c7df6405c9d4e4dfc6f4ac9b0/
**User Count**: 342
**Count**: 700
**First Release**: 16.0.0.3
**First Seen**: 2020-10-27T22:44:50Z
**Last Seen**: 2020-11-19T05:35:22Z
**24 Hours**: 45
**30 Days**: 698
**LogID:** 17DFB57D-C021-4F5A-9B80-359B13FFF0F5

```
NSInternalInconsistencyException: Tried to set <UIBarButtonItem: 0x104b43840> target=0x105330c00 action=didTapMenuButton: image=<UI...
  File "ReaderPostMenu.swift", line 85, in ReaderPostMenu.showMenuForPost
  File "ReaderDetailCoordinator.swift", line 290, in ReaderDetailCoordinator.showMenu
  File "Classes/ViewRelated/Reader/Detail/ReaderDetailCoordinator.swift", line 485, in ReaderDetailCoordinator.didTapMenuButton
  File "ReaderDetailViewController.swift", line 366, in ReaderDetailViewController.didTapMenuButton
  File "<compiler-generated>", line 365, in ReaderDetailViewController.didTapMenuButton
  File "main.swift", line 7, in main
...
(30 additional frame(s) were not displayed)
```

**Comment by renanferrari** [comment]
This seems related to #15336. I'm labeling it as medium priority ([high severity, low impact](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/docs/issue-triage.md#prioritization)).

**Comment by designsimply** [comment]
Closing because the Sentry URL provided is showing zero new cases recorded since 2020-11-20. I am not sure what happened here, but there have been several issues like this that either dropped off completely on 2020-11-20 or they spiked. My expectation is that if this is still a problem that it was moved to another Sentry issue and if the numbers warrant it then a new issue will be opened for this case by a release manager in the future.

**Events in the last 90d:** 717
**Users affected in the last 90d:** 351
**Noteworthy:** 98.88% of recorded cases were from 16.0.0.6
<sub>WORDPRESS-IOS-397Z: https://sentry.io/share/issue/a01eba2c7df6405c9d4e4dfc6f4ac9b0/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=release&field=os&field=device&field=culprit&name=All+Events&project=1438083&query=issue.id%3A1985336148&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1">![image](https://user-images.githubusercontent.com/1119271/101950414-7babb480-3bb2-11eb-9b19-90437cdc75bb.png)</a>
