### ISSUE TITLE
Quick Start message overlaps + button

### ISSUE THREAD

**Issue by startuptester** [wordpress-mobile/WordPress-iOS#15350]
### Expected behavior
The message should not overlap the button.  This has been since the move from that top corner button to a FAB in 16.1. 

### Actual behavior

![IMG_1962](https://user-images.githubusercontent.com/66104034/99730581-ec5f2580-2a79-11eb-9894-344cdfade544.PNG)
![IMG_1963](https://user-images.githubusercontent.com/66104034/99730588-eff2ac80-2a79-11eb-83b2-452a152382a7.PNG)

### Steps to reproduce the behavior
1. Login with an email that has no site created and accept Quick Start guidance
2. Follow the guidance for Create A New Page
3. On the Site Pages screen, the message overlaps the button AND on the new layout picker modal, the message persists.

**Comment by yaelirub** [comment]
@bjtitus , can you please take a look at this? For a quick fix I recommend we either show the notice higher than the FAB, or reduce the height and font of the notice.

I think I've seen this issue of the notice covering the FAB in other places too so maybe we should think of a different way or style for presenting the instructions

**Comment by bjtitus** [comment]
I think we can fix this particular problem most easily by adding the `newPage` quick start tour item to this handler:
https://github.com/wordpress-mobile/WordPress-iOS/blob/e6040a25fd617d6cc3b552b7f99c3e8cf43dd998/WordPress/Classes/ViewRelated/System/Floating%20Create%20Button/CreateButtonCoordinator.swift#L202-L216

There is a larger problem with the bottom notices in general, though, for which the FAB probably still needs to be moved.
I'll take a look at both options this week.

**Comment by bjtitus** [comment]
So this issue is a bit different than the "Publish a Post" quick start since we show "Publish a Post" on the Blog Details screen but "Create a new page" after navigating into Site Pages. Handling it in the same way doesn't work because the FAB is shown after the tooltip gets added so there are some timing issues to contend with.

I wonder if we could remove the "Select Site Pages to continue" and add the "Select + to create a new page." to the blog details page to match the New Post quick start item. This would solve the timing issue that was giving me some grief.

### Current Flow

Tap "Create a new page" from "Customize Your Site" Quick Start:

<a href="https://user-images.githubusercontent.com/3250/100648503-3d82db00-32fe-11eb-93da-477291c82ce0.jpeg"><img src="https://user-images.githubusercontent.com/3250/100648503-3d82db00-32fe-11eb-93da-477291c82ce0.jpeg" width="300"></a>

You must navigate to the Site Pages first even though the FAB does have a "Site Page" option in the list:

<a href="https://user-images.githubusercontent.com/3250/100648941-ed584880-32fe-11eb-9d56-3cc1e3d9967f.PNG"><img src="https://user-images.githubusercontent.com/3250/100648941-ed584880-32fe-11eb-9d56-3cc1e3d9967f.PNG" width="300"></a>

The "Publish a Post" option shows a tooltip directly on the blog details screen without having to navigate into Blog Posts:

<a href="https://user-images.githubusercontent.com/3250/100648669-7d49c280-32fe-11eb-81bb-8a558504473d.jpeg"><img src="https://user-images.githubusercontent.com/3250/100648669-7d49c280-32fe-11eb-81bb-8a558504473d.jpeg" width="300"></a>

@osullivanchris Do you have thoughts on whether it'd be ok to cut out the step to navigate to the Site Pages screen before showing the FAB tooltip for a new page?

**Comment by osullivanchris** [comment]
A few things here

**1. 'Choose a Layout' flow**
In the second screenshot provided by @startuptester - the tooltip is still shown on the 'Choose a Layout' page. The tooltip should either go away, or we should say 'Choose a layout' in another tooltip, or something. We keep falling into this trap of introducing new features and not considering how they impact Quick Start. If the flow is changed, we need to update the Quick Start flow to match.

**2. Tooltips blocking Floating Action Button**
In general we move up the Floating Action Button. You can see that happening correctly in most of Quick Start iOS. We do it on Android too. @startuptester has shown one example where we fail to do this. As @yaelirub mentioned there are others. One is when you publish a post. Although, its less pivotal then.

**3. The Quick Start flow to create a page, or create a post.**
- In 'Create a post' - we point to the Floating Action Button
- In 'Create a page' - we point to the menu item

As @bjtitus mentions, we could point to the Floating Action Button in both cases. We arbitrarily did each one way on releasing the feature, so in theory the user could learn to create things both by tapping the FAB, or navigating. Then the user would also see where their posts/pages live. I have no evidence this actually works though. We were also probably cautious about promoting the FAB at the time in case users had problems with it. But it seems to work fine. So its not a risk to point to the FAB as we thought.

**Comment by startuptester** [comment]
@bjtitus is there an update on this one?

**Comment by startuptester** [comment]
Gave it medium priority because it's a NUX flow, but it can still be navigated.

**Comment by bjtitus** [comment]
I think the simplest solution for now would be to move the 'Create a Page' Quick Start to point to the FAB just like 'Create a Post' does. I think a separate issue should be created to address the problems around the FAB not moving for some of the tooltips since that's still a problem with the Post status ones.

I'll submit a PR to make that change tomorrow.

**Comment by yaelirub** [comment]
@frosty , I reopened the issue has it came up as a bug in the experience walkthrough. 
Lets please give it priority as part of the quick start work

**Comment by frosty** [comment]
Sure, we can re-review this as we begin to work on the new Quick Start experience on iOS.

**Comment by yaelirub** [comment]
Actually, @frosty , this need to fix this as soon as possible. Can you make sure to fix this for the upcoming release?

**Comment by frosty** [comment]
Closing this for now as it should be addressed by #15775.
