### ISSUE TITLE
[NotificationsViewController.selectRow] NSInternalInconsistencyException: Attempted to perform update with invalid index path: <NSIndexPath: 0x283a1b9a0> {length = 2, path...

### ISSUE THREAD

**Issue by jkmassel** [wordpress-mobile/WordPress-iOS#15368]
**Sentry Url**: https://sentry.io/share/issue/0fdb6fedd3d44625bf944ffb7c306193/
**User Count**: 616
**Count**: 803
**First Release**: 14.8.0.3
**First Seen**: 2020-09-04T04:34:54Z
**Last Seen**: 2020-11-23T18:22:01Z
**24 Hours**: 216
**30 Days**: 763

```
NSInternalInconsistencyException: Invalid indexPath
  File "NotificationsViewController.swift", line 910, in NotificationsViewController.selectRow
  File "NotificationsViewController.swift", line 211, in NotificationsViewController.traitCollectionDidChange
  File "<compiler-generated>", line null, in NotificationsViewController.traitCollectionDidChange
  File "main.swift", line 7, in main
...
(70 additional frame(s) were not displayed)
```

**Comment by leandroalonso** [comment]
@jleandroperez pinging you here cause you're our notifications master, sir!

I was thinking that perhaps we can just check if the indexPath is valid before updating it? I'm just not sure if that would leave the app in a weird state somehow. Thoughts?

**Comment by jleandroperez** [comment]
@leandroalonso Hey there!! long time no see!!

As far as I understand, it's crashing in this API right?

```
    func selectRow(for notification: Notification, animated: Bool = true,
                   scrollPosition: UITableView.ScrollPosition = .none) {
        selectedNotification = notification

        if let indexPath = tableViewHandler.resultsController.indexPath(forObject: notification), indexPath != tableView.indexPathForSelectedRow {
            DDLogInfo("\(self) \(#function) Selecting row at \(indexPath) for Notification: \(notification.notificationId) (\(notification.type ?? "Unknown type")) - \(notification.title ?? "No title")")
            tableView.selectRow(at: indexPath, animated: animated, scrollPosition: scrollPosition)
        }
    }
```

**Invalid Index Path** makes me think that the `resultsController.indexPath(forObject:)` invocation succeeds, but the TableView is unaware of such path.

I'd say that the table (for whatever reason) got Out of Sync with the NSFetchedResultsController. I would suspect of:

- This method being executed in a BG thread?
- A `reloadData` invocation happening somewhere

Note that, it's possible, at that point the TableView is already in a broken state. You could probably detect such scenario (by checking if the IndexPath is out of bounds), and, as you mentioned, perhaps invoke `reloadData`.


P.s.: Mother of god, when did this ViewController get 1800 LOC!!!

**Comment by designsimply** [comment]
Raising to high priority because it's showing a high number of users affected. I don't think it's a new issue though 🤔  I think this issue is a continuation of https://github.com/wordpress-mobile/WordPress-iOS/issues/15092 which came to a full stop on Nov 20 and this one picked up steam at the exact same time. Something seems to have gotten rejiggered in Sentry.

**Events in the last 90d:** 4,300
**Users affected in the last 90d:** 2,300
<sub>WORDPRESS-IOS-38WR: https://sentry.io/share/issue/0fdb6fedd3d44625bf944ffb7c306193/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=release&field=device&field=os&field=culprit&name=All+Events&project=1438083&query=issue.id%3A1876553907&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1">![image](https://user-images.githubusercontent.com/1119271/101848748-82cfb580-3b13-11eb-9459-583f885d81e3.png)</a>

**Comment by salimbraksa** [comment]
This issue was addressed in this [PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/17955), but the fix resulted in a new bug:

- [NSInternalInconsistencyException: Requested the number of rows for section (2) which is out of bounds.](https://a8c.sentry.io/discover/results/?environment=production&environment=appStore&field=title&field=release&field=environment&field=user&field=timestamp&name=NSInternalInconsistencyException%3A+Invalid+update%3A+invalid+number+of+rows+in+section+0.+The+number+of+rows+contained+in+an+existing+...&project=1438083&project=5716771&query=level%3Afatal+%22NotificationsViewController.selectRow%22&sort=-release&statsPeriod=90d&yAxis=count%28%29)

The app crashes in `selectRow` method, likely due to an attempt to get the number of rows of a section that doesn't exist.

![CleanShot 2024-03-07 at 01 01 51](https://github.com/wordpress-mobile/WordPress-iOS/assets/9609223/35b521d8-3354-43d1-bdd3-20de63794fa7)

```swift
tableView.numberOfRows(inSection: indexPath.section)
```

I think the app crashes if the given `indexPath.section` doesn't exist.

I've assigned you this issue @dvdchr since you've worked on it before, but feel free to un-assign yourself if you're not planning to continue working on it.

**Comment by jkmassel** [comment]
This only happens in very old versions of the app, so it can be closed.
