### ISSUE TITLE
NSInternalInconsistencyException: Invalid update: invalid number of rows in section 1. The number of rows contained in an existing ...

### ISSUE THREAD

**Issue by jkmassel** [wordpress-mobile/WordPress-iOS#15367]
**Sentry Url**: https://sentry.io/share/issue/ee3fd209a355449c814bcbe746c67567/
**User Count**: 745
**Count**: 869
**First Release**: 15.3.0.3
**First Seen**: 2020-09-01T19:20:13Z
**Last Seen**: 2020-11-23T18:28:28Z
**24 Hours**: 223
**30 Days**: 821

```
NSInternalInconsistencyException: Invalid update: invalid number of rows in section 1. The number of rows contained in an existing ...
  File "Classes/Utility/WPTableViewHandler.m", line 634, in -[WPTableViewHandler controllerDidChangeContent:]
  File "main.swift", line 7, in main
...
(33 additional frame(s) were not displayed)
```

**Comment by designsimply** [comment]
2,900 users affected since 2020-11-20 is a lot, so I'm raising to high priority.

**Events in the last 90d:** 4,800
**Users affected in the last 90d:** 2,900
**Noteworthy:** `UIPageViewController` is the culprit for 100% of cases (it's rare to see that showing 100% the same thing)
<sub>WORDPRESS-IOS-38W5: https://sentry.io/share/issue/ee3fd209a355449c814bcbe746c67567/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=release&field=os&field=device&field=culprit&name=All+Events&project=1438083&query=issue.id%3A1872232676&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1">![image](https://user-images.githubusercontent.com/1119271/101957299-6c326880-3bbe-11eb-9b1b-c3fb64e76f4d.png)</a>

**Comment by designsimply** [comment]
Please also see the notes in https://github.com/wordpress-mobile/WordPress-iOS/issues/12671 in case they're helpful. The error looks very similar to this one and the graph for the other drops out where this one picks up… on 2020-11-20.

**Comment by jkmassel** [comment]
This only happens in very old versions of the app, so it can be closed.
