### ISSUE TITLE
The Page List does not automatically refresh when the editor closes

### ISSUE THREAD

**Issue by antonis** [wordpress-mobile/WordPress-iOS#15535]
### Expected behavior
The Page List automatically refreshed when a page title is edited or a new page is created.

### Actual behavior
The Page List does not automatically refresh when a page title is edited or a new page is created.

#### New page
1. From My Site press the Pages button or scroll down and select Site Pages from the list
1. Create a new page
1. Close the editor and save/publish the post
1. Notice the the page list does not include the new post
1. Manually refresh the list (pull) to see the new post

#### Edit page page
1. From My Site press the Pages button or scroll down and select Site Pages from the list
1. Open a page
1. Change the title
1. Close the editor and save the post
1. Notice the the page list does not reflect the change in the title
1. Manually refresh the list (pull) to see the update

**Comment by irfano** [comment]
This is still valid.

https://user-images.githubusercontent.com/2471769/186753507-cd56e7de-a2f6-4ae4-884e-e31a6c07e5db.mp4

**Comment by fluiddot** [comment]
This issue is related to https://github.com/wordpress-mobile/WordPress-iOS/issues/20647. The fact that the Page list is not automatically refreshed leads to a crash when saving the page's content and opening the same page while is being uploaded.

A potential solution has been shared in https://github.com/wordpress-mobile/WordPress-iOS/issues/20647#issuecomment-1603357554.

**NOTE:** Fixing this issue would likely also solve https://github.com/wordpress-mobile/WordPress-iOS/issues/16370.

**Comment by kean** [comment]
It was fixed in 23.9. The screen now uses the same exact code as Posts.
