### ISSUE TITLE
Invisible videos when added with the video blocks on the app

### ISSUE THREAD

**Issue by reginabally** [wordpress-mobile/WordPress-iOS#15595]
It was originally reported in 3611720-zen that the videos added through the video blocks on the app didn't show up on the site. The video playback control is visible and the video audio can be heard but the actual video isn't displaying.

I was able to replicate this by uploading the video downloaded from the reported site as well as a video recorded using my iPhone SE.

### Expected behavior

I would expect the videos added through a video block on the app can be played and viewed on the site.

### Actual behavior

I can only see the video playback control and hear the audio but not able to view the actual video.

### Steps to reproduce the behavior

1. Record a short video with an iPhone
2. Go to My Site > Blog Posts and create a new post
3. Add a video block and upload the video recorded in Step 1
4. Publish the post
5. Visiting the post will see the video playback control without the actual video

Note: The same behavior is observed if I uploaded the video to the Media library before adding the video to a post with a video block on the app.

Test page: https://premiumtestsite20190311.blog/2021/01/07/video-upload-test/

The same video is working properly when it was added through the video block on Calypso: https://premiumtestsite20190311.blog/2021/01/07/video-test-calypso/

**Comment by startuptester** [comment]
Thanks for reporting @reginabally! I want to make sure I understand correctly...

The video works if you press the play button right? The problem you are reporting is that no thumbnail appears?

**Comment by reginabally** [comment]
> The video works if you press the play button right? The problem you are reporting is that no thumbnail appears?

When I pressed the play button, the audio of the video can be heard but the actual video isn't displaying. I've tested on both Firefox and Chrome browsers.

![Screen Capture on 2021-01-09 at 12-48-28](https://user-images.githubusercontent.com/40906847/104083386-10203a00-5279-11eb-8b65-86cf20d60354.gif)


Were you able to play the video on the test page I linked above: https://premiumtestsite20190311.blog/2021/01/07/video-upload-test/?

**Comment by hypest** [comment]
cc'ing @frosty, @yaelirub  to help having someone check on this, thanks!

**Comment by hypest** [comment]
FWIW, I checked the uploaded video in the test site (https://premiumtestsite20190311.blog/2021/01/07/video-upload-test/) by trying to play it via the Media library in wpadmin and got mixed results. It plays in one player but not the other, see the screenshot below:

<img width="1436" alt="Screenshot 2021-01-11 at 13 29 57" src="https://user-images.githubusercontent.com/1032913/104177748-f23a0d00-5411-11eb-817e-154b1ecf4af4.png">

**Comment by leandroalonso** [comment]
I just tested these posts in:

* Safari in iOS
* Reader

Although there is no thumbnail at all, the video plays just fine.

I wasn't able to watch the video in Chrome and Firefox though. I can hear the video, but not see it.

One thing to note. In the case where I can't see the video, there's no custom player, just the `<video>` tag being used:

<img width="764" alt="Screen Shot 2021-01-11 at 14 49 13" src="https://user-images.githubusercontent.com/7040243/104219037-59f55580-541c-11eb-9b49-0a5e304a4b48.png">

Here on the other hand there's a custom player (from VideoPress) and the video is actually inside an `iframe`:

<img width="777" alt="Screen Shot 2021-01-11 at 14 49 19" src="https://user-images.githubusercontent.com/7040243/104219098-6a0d3500-541c-11eb-898b-e33b73131842.png">

I'm not sure what could lead to these two distinct behaviors.

**Comment by eduardozulian** [comment]
Another case in 3624089-zen 

I was able to reproduce this with the user's video (on both FF and Chrome; Safari worked fine) but not with my own videos. 

***

For context, we can find similar cases happening on WordPress.com sites with desktop uploads as well: p1577694454336500-slack-C03TY6J1A

**Comment by eduardozulian** [comment]
As a note, it should be possible to embed these non-working videos if we use the `[wpvideo]` shortcode.

**Comment by yaelirub** [comment]
Hey @leandroalonso and  @eduardozulian. Thanks for looking into this 🙏 
This issue was flagged as high priority as users keep reporting it. 
Do you have any solution in mind?

**Comment by leandroalonso** [comment]
@yaelirub I guess the issue comes down to video decoding/codecs. Firefox and Chrome are simply not able to execute this format for some reason and I fear that there isn't much we can do about it.

For example, try to open this link directly using Chrome and/or Firefox:

https://videos.files.wordpress.com/GUmpiRPk/img_0062.mov

Chrome will just download the file (instead of playing) and Firefox will try to play it but with the issue: no video, and just audio.

When I upload the same video through Gutenberg web, the video is processed and then displayed using VideoPress: https://charlietest12345.blog/2021/01/18/video-test/

There's even a message about the video conversion: 

<img width="685" alt="Screen Shot 2021-01-18 at 20 42 13" src="https://user-images.githubusercontent.com/7040243/104971827-bb926280-59ce-11eb-867e-52e02d49ae55.png">

Then, since the video is converted to a better format and uses the VideoPress player, it works just fine.

I might be wrong here but it seems that by uploading from the app the video doesn't have this "conversion" phase? (ccing @hypest)

**Comment by hypest** [comment]
👋 @roundhill ! Could use your insight here. Any chance that above videos wouldn't be playable correctly when the upload happens from mobile, perhaps because a conversion step is missed somehow?

**Comment by roundhill** [comment]
Hi everyone! If you hear the video but don't see it, that's because your device/browser doesn't support the video codec to play it back. HEVC playback only works on certain devices: https://support.apple.com/en-us/HT207022

This is one of the reasons that we transcode videos for VideoPress uploads, so that they will playback on most devices. @eduardozulian's idea to use the video shortcode would be ideal here.

There's also an endpoint you can use to get the status of a video's transcode, like: 

https://public-api.wordpress.com/rest/v1.1/videos/kUJmAcSf

There's a `finished` boolean for when the transcode process has finished, and an array of files that gives you the status for each video resolution. For example:

`"files_status":{"hd":{"mp4":"CONVERTING"},"dvd":{"mp4":"DONE"},"std":{"mp4":"DONE","ogg":"ERROR"}}`

Hit me up with any questions!

**Comment by hypest** [comment]
Thanks for the insight there @roundhill!

About the shortcode option since it's both you and @eduardozulian bringing it up, would that be a Gutenberg block actually? Do y'all refer to the `shortcode` block perhaps, or instead to try and use a shortcode as the implementation of the `Video` block on mobile?

**Comment by roundhill** [comment]
Hmm yeah I guess you can't just use the shortcode on mobile. Are you able to render an iframe? VideoPress supports oembed, so you could pass something like this to the oembed endpoint which will give you back the iframe code:

https://public-api.wordpress.com/oembed/1.0?url=https://videopress.com/v/kUJmAcSf&for=mobilegutenberg

**Comment by hypest** [comment]
> Are you able to render an iframe? 

Assuming you're talking about the editing experience, that's would be a "no". We actually don't render the video at all while in the editor... only a preview-like placeholder is there for the user to launch the preview in an external  browser.

I start to think that this can be another manifestation of the issue that Core and Calypso are not actually using the same block for Video, with Calypso overriding the Core one on the fly.

Checking the markup from @reginabally's tests ([video-upload-test](https://premiumtestsite20190311.blog/2021/01/07/video-upload-test/( versus [video-upload-calypso](https://premiumtestsite20190311.blog/2021/01/07/video-test-calypso/), I see they are quite different:

### Calypso editor
```
<!-- wp:video {"guid":"IMHcie6W","id":958,"src":"https://premiumplantestsite20190311.files.wordpress.com/2021/01/img_4713-3.mov","className":"wp-block-embed is-type-video is-provider-videopress wp-embed-aspect-16-9 wp-has-aspect-ratio"} -->
<figure><div class="wp-block-embed__wrapper">
https://videopress.com/v/IMHcie6W?preloadContent=metadata
</div></figure>
<!-- /wp:video -->
```
### Mobile app editor
```
<!-- wp:video {"autoplay":false,"id":958,"loop":false,"muted":false,"playsInline":false,"src":"https://videos.files.wordpress.com/IMHcie6W/img_4713-3.mov"} -->
<figure class="wp-block-video"><video controls src="https://videos.files.wordpress.com/IMHcie6W/img_4713-3.mov"></video></figure>
<!-- /wp:video -->
```

(Related _and long_ past discussion in pafL3P-pg-p2)

@mtias, do we have anything newer on the effort to revise the Calypso Video block implementation?

**Comment by rossanafmenezes** [comment]
Just got another case here 3899007-zen

Same issue, works on Safari and Apple devices but on ay other device you get the audio only. The shortcode using the Shortcode block in the app works, however the option to copy the video shortcode from the media library is not available in the app. You need to copy it from the browser. So maybe we should think about adding this option to the mobile media library?

**Comment by mtias** [comment]
@hypest yes, but I don't know the status of it or if it was punted cc @roundhill

**Comment by eduardozulian** [comment]
Another report in 3938544-zen

**Comment by kavyagokul** [comment]
Another one in 26144052-hc

**Comment by kavyagokul** [comment]
Also in 29703387-hc

**Comment by hypest** [comment]
👋 @reginabally, can you try the issue again, but with the latest of the WPiOS app (v17.7 beta at the time of writing)? In a recent version (v17.4) we shipped [a conversion fix for videos captured on iOS](https://github.com/wordpress-mobile/WordPress-iOS/pull/16548) and I wonder if it fixes the issue here too, thanks!

**Comment by reginabally** [comment]
Thanks for the update, @hypest! I've just tested this, the video added through the app is visible! 🎉

Test post: https://premiumtestsite20190311.blog/2021/07/02/test-video-block-in-the-app/
