### ISSUE TITLE
Search bar font is very difficult to see in Help Center

### ISSUE THREAD

**Issue by startuptester** [wordpress-mobile/WordPress-iOS#15727]
### Expected behavior
I want to search in Help Center for a topic

### Actual behavior
It's difficult to see this font clearly (more-so on the actual phone than the screenshot)
![IMG_DEC8D954C666-1](https://user-images.githubusercontent.com/66104034/106068891-997b9d00-60be-11eb-90a3-ed149c72f347.jpeg)

### Steps to reproduce the behavior
1. In Help & Support menu, tap on WP Help Center
2. Type something in the search bar

**Comment by illusaen** [comment]
This unfortunately is a bit more complex of a problem than it first seemed. 

The `WPStyleGuide` sets the `UITextField`'s `appearance` proxy to gray for all `UISearchBar`s. This can't be overridden via setting `tintColor` without setting the proxy again.

* If I set the appearance proxy, it will modify all other `UISearchBar`s.
* If I put the Zendesk view controller into a custom parent view controller (thus allowing me to set the appearance proxy for `UISearchBar` instances in that VC only), the navigation bar disappears since it's the parent's navbar that's shown.
* I can't access `viewDidAppear` code in the Zendesk VC.

Other options:
1. Refactor all other search bars in the app to be in a custom VC and have `WPStyleGuide` set that as the container proxy.
2. Refactor all other search bars to set `tintColor` in `viewDidAppear`.
3. Refactor the UIAppearance proxy to set a color according to a variable that's set depending on the VC you're on?

**Comment by ScoutHarris** [comment]
This view is created by the Zendesk SDK. We simply display what Zendesk provides. My 2 cents - I don't think we should hack our way around this. 🤞 Zendesk will fix it in a future release.

**Comment by startuptester** [comment]
That makes sense to me. I agree with @ScoutHarris

**Comment by illusaen** [comment]
Yep it is, but you can actually customize the view controller via the appearance proxies. Unfortunately the colors aren't unified across the app :)

**Comment by aerych** [comment]
Closing this one. We're no longer using the Zendesk view as of https://github.com/wordpress-mobile/WordPress-iOS/pull/16515.  Instead we show the FAQs at https://apps.wordpress.com/mobile-app-support/ .
