### ISSUE TITLE
Large Titles: Main Issue

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#15750]
Implement the new UI for Large Titles, White Headers.

## Feature Availability

The feature branch for this project is `feature/large-headers`.
This feature is also hidden behind feature flag `newNavBarAppearance`.

## New Blog Details Header View

`NewBlogDetailHeaderView` is a new view that replaces `BlogDetailHeaderView`.  It has some UI changed and includes a new site picker, since the list of sites is no longer shown as part of the split view.

Reference design (courtesy of @osullivanchris):

![image](https://user-images.githubusercontent.com/1836005/106460912-cf2fd580-6472-11eb-89dc-b25656c3ce19.png)

### UI / UX

- [x] Change App Heading fonts to New York Large semibold (see image above).
- [x] Make sure Large Titles are set to 34pt (see image above).
- [x] The link (and the icon next to the link) in the new blog details view (right below the site title) should open the site when tapped (see image above).
- [x] [Add a divider to the nav bar when scrolling](https://github.com/wordpress-mobile/WordPress-iOS/pull/15281#issuecomment-768223247).
- [x] [Add padding in between the bottom of the new blog details view and the list below it](https://github.com/wordpress-mobile/WordPress-iOS/pull/15281#issuecomment-768223247).
- [x] Once done with the changes above, iterate with @osullivanchris on the design.

### Known Issues:

- [x] `NewBlogDetailHeaderView` [should not ignore the safe area](https://github.com/wordpress-mobile/WordPress-iOS/pull/15281#pullrequestreview-577465352).
- [x] [Split view issues on iPad](https://github.com/wordpress-mobile/WordPress-iOS/pull/15281#pullrequestreview-577465352).
- [x] [Disable the split view detail view dimming when the feature flag (`newNavBarAppearance`) is ON](https://github.com/wordpress-mobile/WordPress-iOS/pull/15281#pullrequestreview-577465352).
   - This shouldn't happen now that the primary split view pane contains just a BlogDetailViewController.

### Color updates
- [Remove usages or WordPress Blue](https://github.com/wordpress-mobile/WordPress-iOS/issues/15852)
- [Replace usages of Pink with equivalent shades of Blue](https://github.com/wordpress-mobile/WordPress-iOS/issues/15853)
- [Replace app icon WordPress Blue with new Blue](https://github.com/wordpress-mobile/WordPress-iOS/issues/15854)

### Possible future improvements

- Update nav bar background color in dark mode to match tabs [[ref](https://github.com/wordpress-mobile/WordPress-iOS/pull/16132#issuecomment-816821857)]
- Tweak the spacing between the site title and URL
![](https://user-images.githubusercontent.com/50576199/111808968-68546780-88cc-11eb-9687-2dfeae9bd1e9.png)
- Make Reader large title collapsable
   - Currently not possible due to the view hierarchy in the Reader section of the app – a tableview or scrollview must be the topmost view in the VC.
- Removing dividers when there are tabs below them to create one large visual header. The current divider doesn't seem to behave consistently – in Reader Topic view, and My Site > Stats it doesn't appear, but on My Site > Blog Posts it appears when scrolling down.
- Aligning the site picker chevron with the 'me' icon
- On Pro Max devices in landscape, the spacing of quick actions could be improved
- The My Sites list sometimes appears pushed down slightly, with a static loading indicator
- Search bars don't fit in brilliantly now that they're grey and nav bars are white.
- Scroll My Site to top after deleting site

**Comment by diegoreymendez** [comment]
cc @Gio2018, @frosty, @osullivanchris

**Comment by diegoreymendez** [comment]
@frosty - I see you moved this forward and that all checkboxes are ticked.  Can this issue be closed or are there pending action items?

**Comment by frosty** [comment]
@diegoreymendez Many of the future improvements could do with implementing at some point – I can prioritize the list, but we can move them to a new issue if you think that might be best.

**Comment by diegoreymendez** [comment]
@frosty No it's fine, I was only wondering if this needed closure.  Thanks for the update.

**Comment by osullivanchris** [comment]
Hey was just referring back to our list here and there's also a couple of small buggy things with the Notifications tab which I will try to describe. Hard to capture on video, so ping me for a demo if unclear.

**1. When returning to the top of the tab, the header remains in collapsed state**
- scroll through your notifications
- header collapses to small version as expected
- when lower on the list, you can double tap on the tab (bell icon) to bring you back up to the top
- I expect it to bring me to the top with the large title
- Instead, it is still collapsed, so I can't get back to the big header unless I scroll up manually
Not a huge issue. Maybe some people would even expect it.

**2. When re-launching the app, the notifications header is often in the collapsed state**
- If I open the app, I expect to see the header in default large state
- Understandably, if I had it open in collapsed state and switched apps and back, it would remain in collapsed state.
But the following is a scenario I observed
- Go to notifications tab
- Scroll down, header collapses
- Scroll back up to the top, see large title again
- Close the app
- Re-open the app
- Header is in collapsed state, rather than large state as I would expect

**Comment by diegoreymendez** [comment]
Hey @osullivanchris.  Thanks for the feedback.  I'll be reviewing this next week and spawn issues.

**Comment by osullivanchris** [comment]
Another small issue here. 

When I designed the new header, the Quick Actions sit on the background with no background colour of their own, only a border.

Since we changed the background colour of the header in dark mode, the Quick Actions now have a different background colour.

Can we either change the Quick Actions circles to have no background colour, or if thats not possible to have the same colour as the background behind them? See light mode for comparison.
<img width="1226" alt="Screenshot 2021-05-05 at 10 57 56" src="https://user-images.githubusercontent.com/50576199/117124869-c1029580-ad90-11eb-94d0-0798899acc9d.png">

**Comment by osullivanchris** [comment]
When you scroll, and the large header collapses, a grey background colour is shown in the area that scrolls away beneath the fixed header.

I'm actually unsure if this is desirable or not. Wasn't my intention, but not a major bug. Any opinions? 

https://user-images.githubusercontent.com/50576199/117125037-f8714200-ad90-11eb-9d0e-ba6499cd6618.MP4


![IMG_1091](https://user-images.githubusercontent.com/50576199/117125252-31111b80-ad91-11eb-855b-f18c56ff173c.PNG)

**Comment by mattmiklic** [comment]
> When you scroll, and the large header collapses, a grey background colour is shown in the area that scrolls away beneath the fixed header.

This may be because the default system behavior is for the minimized header to use a system material background. You can see this in Mail; the large title toolbar uses a transparent background, inheriting the white background of the page. But as you scroll up, the system material fades in (which is a light gray color). 

We eventually want to use system materials for toolbars so if this is the default behavior we may want to leave it as is rather than doing something custom.

**Comment by diegoreymendez** [comment]
Thanks for the clarification @mattmiklic

**Comment by diegoreymendez** [comment]
The quick action button background is fixed.

The bullets listed in this issue include a lot of different changes we may or may not want to tackle as part of this issue / project.  I'd suggest we open issues for any remaining work that's important, and close this high-level issue.

Can I ask you for your opinion on this @frosty, @Gio2018 ?

**Comment by Gio2018** [comment]
> The quick action button background is fixed.
> 
> The bullets listed in this issue include a lot of different changes we may or may not want to tackle as part of this issue / project. I'd suggest we open issues for any remaining work that's important, and close this high-level issue.
> 
> Can I ask you for your opinion on this @frosty, @Gio2018 ?

100 % agree!!
