### ISSUE TITLE
Adopt `NSPersistentContainer`

### ISSUE THREAD

**Issue by jkmassel** [wordpress-mobile/WordPress-iOS#15831]
`NSPersistentContainer` is the recommended way forward for Core Data – we should fully adopt it inside of `ContextManager` to manage our contexts for us.

**Comment by crazytonyli** [comment]
This issue has been resolved, hasn't it? Because I see `ContextManager` is [using `NSPersistentContainer`](https://github.com/wordpress-mobile/WordPress-iOS/blob/921c7178e07f134a2f0ba14134c9bd1d5beb9f3f/WordPress/Classes/Utility/ContextManager.m#L201).

**Comment by crazytonyli** [comment]
NVM, I see there are some details about this in the RFC 😅

**Comment by crazytonyli** [comment]
@jkmassel This adoption seems like quite a big change to me, considering it changes how we fundamentally interact with the database, also the potential complications around how database changes are merged among the main context and derived contexts. IMO, it might be worthwhile to keep the current implementation in the app, alongside the new way of using `NSPersistentContainer`, so that we can have a switch to use the new approach during development or beta testing and rollback easily if needed. Hopefully, doing this allows us to test the new approach extensively and gives us more confidence in releasing it in production. What do you think?
