### ISSUE TITLE
Site Creation flow: flicker when switching between mobile and desktop view

### ISSUE THREAD

**Issue by startuptester** [wordpress-mobile/WordPress-iOS#16122]
reported by @jd-alexander 

### Expected behavior
preview loads cleanly

### Actual behavior
When I selected a design and clicked Preview there would be a flicker from the mobile layout to the desktop layout during loading. 

https://user-images.githubusercontent.com/66104034/111557962-60bd8300-8753-11eb-90cb-43868ea2a4aa.MP4

Noticed on iPad and iPhone 12 in WPiOS 16.9 beta

**Comment by chipsnyder** [comment]
@antonis @mkevins since you two were each working in this area recently do you know of any ways we could smooth out this transition?

**Comment by startuptester** [comment]
I had this come up in a different place in the 17.0 beta

https://cloudup.com/cVF8cpFMyeR

**Comment by mkevins** [comment]
I have a feeling this may be related with the approach we are using to set the viewport width (in JS). I'll look to see if there's an easy win here for improving this.

**Comment by twstokes** [comment]
To troubleshoot I added an animation and put the simulator in slow-mo mode and determined the flicker is due to how the `WKWebView` handles the viewport width change - it instantly paints the content aligned to the leading edge before its container catches up. When the animation isn't implemented, it has the opposite effect - it paints after its container is resized.

It doesn't help that we're reloading the same page on every change, so I want to see if that's necessary - it would certainly help responsiveness if we could avoid that.

https://user-images.githubusercontent.com/2092798/151905645-19bbe183-2de8-4657-bd92-ee33af9bc8ff.mov
