### ISSUE TITLE
My Site screen cannot be refreshed after being added to a site

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#16241]
### Expected behavior

After someone adds me to a site, the app should allow the user to access the newly linked site (e.g. by pull-to-refresh on the My Site screen).

### Actual behavior

I have the app open and currently have no sites. I'm added to someone else's site. In the app the My Site screen doesn't allow me to access the newly associated site. I can't pull-to-refresh, and switching between tabs doesn't make the app refresh the screen.

### Steps to reproduce the behavior

1. Create a brand new account and skip the site creation flow, which lands you on the My Site screen
2. Invite your new account to an existing site (this might be done on a different device)
3. Accept the invite
4. In the app, notice that the My Site screen shows a "no data" type screen and there is no way to pull-to-refresh or otherwise refresh the screen

**Comment by frosty** [comment]
@osullivanchris Do you have any thoughts about a fix for this? We could do something like refresh the user's list of sites every time the user navigates to the 'empty' My Site screen?

**Comment by osullivanchris** [comment]
We have pull to refresh on the other two main tabs. Would it be weird to add pull to refresh on My Site? We will probably need it in future if we show dynamic content on the My Site tab.

Otherwise yeah I think you could refresh each time just for the people with no sites. Don't think that changes anything visually.
