### ISSUE TITLE
Remove Cancel button from Prologue with a connected self hosted site 

### ISSUE THREAD

**Issue by startuptester** [wordpress-mobile/WordPress-iOS#16260]
### Expected behavior
No cancel button squishing the top text 

### Actual behavior
![image](https://user-images.githubusercontent.com/66104034/114078206-e4a3f000-9865-11eb-965d-63130ebcb537.png)

### Steps to reproduce the behavior
1. With only a self hosted site connected, go to Log In

**Comment by ScoutHarris** [comment]
Hey @startuptester . The Cancel button is shown here as that is the only way to exit this flow (although, it is rather large, but that's another issue). I think instead the carousel needs to adjust per the height of the button view. @Gio2018 ?

**Comment by Gio2018** [comment]
Hey @ScoutHarris and @startuptester 

>  the carousel needs to adjust per the height of the button view

Yes. 

And we can also work on the proper sizing of the cancel button. @frosty @osullivanchris what's your opinion in regard to this case?

**Comment by osullivanchris** [comment]
@Gio2018 thanks for the ping. I wasn't aware of the view so I didn't consider it in the prologue screen designs. I can see a few options
- make the text or image smaller for this case
- instead of a cancel button, put an 'x' or back chevron at the top of the screen
- maybe in this case (the user hasn't just opened the app), the user doesn't need the full carousel pitching WordPress to them. We could have a simpler version with just one branded message, and no swiping. Allows us to hide the dots to save space. Or even just design something custom and smaller in the content area for this case.

**Comment by kean** [comment]
This view was removed.
