### ISSUE TITLE
Webviews: Not in logged in state when viewing blog posts through Reader

### ISSUE THREAD

**Issue by reginabally** [wordpress-mobile/WordPress-iOS#16278]
It was reported in 3851270-zd-woothemes that the user was requested to log in when they tried to like a blog post with a mapped custom domain of a WordPress.com site when visiting it through the Reader in the app.

### Expected behavior

It was expected that the user is able to "Like" or "Comment" on the post since they're logged in to the app.

### Actual behavior

A log-in screen shows up when the user was trying to "Like" the post on the webview.

### Steps to reproduce the behavior

1. Go to Reader and look for a post published on a WordPress.com (Simple) site with a mapped domain
2. On the posts page on Reader, tap three dots and select Visit
3. Tap "Like" button. A pop-up with a login screen will be displayed.

The same behavior can be seen when tapping a Notifications to view the post on Reader, and visit the post from the Reader.

Video recording (from Notifications --> Reader --> Webview): https://d.pr/v/oNJBaJ/f3thxyEXij

##### Tested on iPhone SE, iOS 14.4.2, WPiOS 17.0

**Comment by aerych** [comment]
I dug into this a little bit more and reproduced the same behavior described by the user and illustrated in the above linked video. (I tested with mobile.blog and data.blog). 

What is interesting is that this _almost_ works and is _almost_ the behavior we'd expect after the recent changes on the web addressing third party cookies with likes.  
- Tapping the like button in the web view opens a new screen prompting the user to log in, which I believe is the expected behavior now.
- After logging in the screen that opened remains but we'd expect it to dismiss so the user is back to the original web view. 
- Back in the original web view we'd expect the like button to work, but it doesn't until we tap the refresh button to reload the page.  After refreshing the like button _does_ work. 

So it seems we need to do a couple of things:
- Ensure the second webview dismisses after login. 
- Ensure the original webview is updated with the auth cookies after logging in.  Reloading / refreshing the page seems to do the trick but I wonder if there is another option that would avoid a screen flicker (or any waiting when on slower connections).

**Comment by reginabally** [comment]
> Tapping the like button in the web view opens a new screen prompting the user to log in, which I believe is the expected behavior now.

When we view the site in the web view through View Site or the View option on My Site > Blog Posts, we don't see the login screen and we can Like posts without the need to log in. Why would it have different behavior when viewing the post in the web view through the Reader?

**Comment by aerych** [comment]
> When we view the site in the web view through View Site or the View option on My Site > Blog Posts, we don't see the login screen and we can Like posts without the need to log in. 

I'm not sure at this point, but it's something we can look more into.

I just tried with the current app store build with one simple site, and one simple site with a mapped domain.  In both cases I was not logged in when previewing a post or clicking view site.  

On the simple site, attempting to like opened a new window prompting me to login.  

On the simple site with the mapped domain I had some difficulty. At first was shown an error screen at first (something about r-login).  When I tried a second time I was able to tap a very small link to go back to the site's home page--something I missed the first time.  The r-login error suggests there was a remote login attempt made as the site loaded.  The third time I tried I was able to view the site but tapping a like button opened and closed a window.  After refreshing the page I was able to like a post (consistent with the behavior captured in the video linked in the issue description).
