### ISSUE TITLE
[UX + L10n issue] Action buttons on comments (esp. "Unapprove")

### ISSUE THREAD

**Issue by AliSoftware** [wordpress-mobile/WordPress-iOS#16311]
### Expected behavior

When I open a comment in the app and look at the action buttons at the bottom of the comment, I expect those buttons to have readable label and clear intent.

### Actual behavior

1. Some buttons have their text truncated in some locales (below: French locale)
2. The "Unapprove" button meaning is unclear (at least to me). First impression that this button gave me is that I accidentally unapproved the comment I was reading and it ended up in an Unapproved state (instead of suggesting me the comment had been auto-approved and clicking the button would unapprove it, which I guess is the real intent)

<img src="https://user-images.githubusercontent.com/216089/114866516-f3554e80-9df3-11eb-88c6-145ce099aca3.jpg" alt="Screenshot of the screen showing a comment, with French locale, with the Unapprove button circled" width="40%" height="40%" />

### Steps to reproduce the behavior

 - Set your phone (or app) locale to French (iOS Settings > WP Internal (or WordPress) > Locale > French)
 - Open the app, go to the notifications list screen and tap on any notification about a comment ("XXX a commenté sur YYY" / "XXX a répondu à votre commentaire le …")
 - On the screen showing the comment, notice that both "Unapprove" and "Trash" buttons have truncated text ("Désa…rouver" and "Dépla…beille")
 - Also notice that the "Désa…rouver" button is checked, but uses a verb (to describe action) not a word (to describe state), which I personally find confusing and is also not in line with buttons like "Indésirable" ("Spam") which indicate state

Note: I only checked and observed those truncations in French, because that's the locale my phone is in. I suspect other locales (especially ones with longer words on average, like German) are likely to have a similar truncation issue.

### Suggestions / Personal take

Decision on UX and wording is probably best to be decided with UX and Design folks, but I figured I'd still drop my personal take on this:

 - I suggest to replace "Dépla…beille" (I'm assuming "Déplacer vers la corbeille" is the expected full copy?) with the translation **"Supprimer"** (litt. "Delete")
 - I feel is it would make sense to have all the buttons with **state toggle** (like "Approve/Unapprove", "Spam" and "Like/Liked" to be labelled with _past tense_ or _state_ (rather than using the _action_ that would happen if you click on the button), and only use **infinitive verbs** for **action buttons** ("Trash", "Edit") (†)
  - Which suggests using "**Approve/Approved**" – similar to how we already use "Like/Liked" for the like button – rather than using "Approve/Unapprove".
  - This should make the UX clearer (at least to me) but also would lead to a French translation like "Approuvé" which would fit, unlike "Désapprouver" which is too long (and besides, whose translation is closer to "disapprouve" than "unapprove" and thus has slightly different meaning than the original)

<details><summary>(†) my rationale for this "past tense" vs "infinitive"</summary>

For "toggle" buttons, since the button has an "ON" and "OFF" state, using an infinitive/action verb when the button is "ON" often makes it unclear if:
 - that is the action that the button "will do if you tap it now that state is ON"
 - or this is the action the button "does/represents 'in general', and since current state is ON that action already happened

For example, if a button is labelled "Like" (infinitive form of the verb) but a blue state suggesting it's toggled on, should that be understood by the user as:
 - "if you tap this button right now, you will Like the content" (because the infinitive form tells you what this will do when you tap),
 - or as "this is a button indicating the _general_ 'Like' status; it's turned on right now, so tapping it will turn it off and Unlike the content"

This is often unclear and in any case can lead to confusion. In contrast, using "Liked" when the button is on (which is what we're already doing or the Like button, but I'm suggesting we do for "Approved" as well) makes it clear that it represents the state, and that tapping the button will "unlike" (because this is not an infinitive form suggesting "this is what tapping this button while in its current state will do")
</details>

### Test Environment

Tested on:
 - iPhone 11 Pro
 - iOS 14.4.2
 - WPiOS 17.1 (both AppStore and WPInternal), but the issue has been here for a while, so not new to those versions.

**Comment by diegoreymendez** [comment]
Ping @osullivanchris any idea if anyone from the design team could review this issue?

**Comment by osullivanchris** [comment]
@diegoreymendez thanks for the ping!

I think there's always a risk with a layout with 5 actions. No matter what the labels are, there's going to be times when it runs out of space. I'd be inclined to have a max of 4 actions, going to an overflow thereafter. Or, having a list view of actions rather than horizontal layout.

As it happens I think @mattmiklic has been working on a new layout for this where the actions are sticky at the bottom of the view, and use colours to make them more distinct. So I'll hand this over to him. Good to bring up the truncation and translation issues ahead of the new design too.

Re; the copy it sounds like @AliSoftware has thought through the use of past tense quite well, I'm inclined to agree with the assessment. And obviously he knows better on the French. Perhaps you could get editorial involved for a review on those suggestions.

**Comment by mattmiklic** [comment]
Thanks for the ping @osullivanchris and thanks @AliSoftware for the report; this is useful for me as I'm working on Comments now. 

Regarding the tense, this is something I'm planning on doing already, switching to an "Approved" label instead of "Unapprove", which doesn't make sense with the checkmark icon. So the labels will be Approve/Approved, Spam/Spammed, Trash/Trashed, Like/Liked. 

Regarding the overflowing text, I wonder if we can engineer it so the text shrinks (with a minimum size set) before it truncates.  It'd also be good to look at the translations and re-word any that are too long.

<img width="1635" alt="Screen Shot 2021-05-17 at 1 47 26 PM" src="https://user-images.githubusercontent.com/1396552/118534509-50a42e80-b717-11eb-81fe-8feed24f1e28.png">

**Comment by diegoreymendez** [comment]
> Regarding the overflowing text, I wonder if we can engineer it so the text shrinks (with a minimum size set) before it truncates. 

Definitely.  The shrinking works with a percentage of the full size version of the text.  The biggest possible value is 100% and means the text can't shrink at all.

I've done this for the blog header view in the blog details screen, using some percentages we came up with together with @osullivanchris.  I've used 75% for the blog title when using regular font sizes, and 50% on the same title when using accessibility font sizes (these are the biggest 4 font sizes in accessibility settings).  The rationale was that when the text was larger, allowing it to shrink further makes sense because the layout can become really hard to deal with, otherwise.

I'd encourage us to think of standard percentages and rules for using those percentages, so we can standardize across our screens.

Please let me know if you need any help with this!

**Comment by ScoutHarris** [comment]
The moderation bar has been replaced with https://github.com/wordpress-mobile/WordPress-iOS/issues/17200.
