### ISSUE TITLE
Missing Hebrew translations

### ISSUE THREAD

**Issue by startuptester** [wordpress-mobile/WordPress-iOS#16376]
![IMG_3347](https://user-images.githubusercontent.com/66104034/116140454-96c81e00-a694-11eb-8172-270fee91a23a.jpeg)
![IMG_3346](https://user-images.githubusercontent.com/66104034/116140459-9891e180-a694-11eb-96b4-0c3d2f29d117.PNG)

**Comment by SiobhyB** [comment]
Thank you for your testing, @startuptester! The highlighted strings in the new alt text component are still awaiting Hebrew translations for both iOS and Android: 

* **iOS:** https://translate.wordpress.org/projects/apps/ios/dev/he/default/?filters%5Bstatus%5D=untranslated
* **Android:** https://translate.wordpress.org/projects/apps/android/dev/he/default/?filters%5Bstatus%5D=untranslated

As Hebrew is one of our "Magnificent 16" (i.e. one of the 16 languages we endeavour to always translate our products into), I believe that these will be translated soon as part of the i18n team's routine work:

* PCYsg-1vr-p2
* PCYsg-vtV-p2 

These are in GlotPress, ready to be translated, so I don't think there's anything more to do from a code standpoint. It seems a matter of timing and waiting for these translations to be deployed.
 
For `Site Title`: that's generally the default title that's given to a site when it's first created, so I have a feeling that's placeholder text rather than an untranslated string (that text would default to the site's URL if the site title field is empty).

**Comment by frosty** [comment]
Thanks @SiobhyB – I also confirmed that technically there's nothing wrong in the app by manually adding a French translation and ensuring it was displayed:

<img width="300" alt="Screenshot 2021-04-28 at 11 42 39" src="https://user-images.githubusercontent.com/4780/116391318-eafb0b80-a816-11eb-9d25-f7ff744d055f.png">

I'm going to close this issue as it's just a case of waiting 🙂
