### ISSUE TITLE
Account Creation: no way to change name

### ISSUE THREAD

**Issue by startuptester** [wordpress-mobile/WordPress-iOS#16380]
### Expected behavior
On this iPad change username screen, you can select on of the suggestions, but there is no save or back buttons, so you are stuck

### Actual behavior

![img_2096-1](https://user-images.githubusercontent.com/66104034/116147655-37bad700-a69d-11eb-8faf-468c5c1d6174.png)

### Steps to reproduce the behavior
Download the app and create a new account as a completely new user
Change the selected name to one of the suggestions

**Comment by diegoreymendez** [comment]
Some findings:

- This is not specific to the iPad, and can in fact be reproduced using an iPhone.
- This issue is specific to Light Mode, and is not reproducible in Dark Mode.
- The actual issue is that the button and title are white, and cannot be seen.
- The top-right help button currently does nothing, so we may want to hide it.
- The "Change username" screen is sometimes opened twice, although I haven't been able to figure out what triggers this behavior.

## iPhone

| Light | Dark |
| --- | --- |
| <img src="https://user-images.githubusercontent.com/1836005/116237252-474f2400-a760-11eb-803e-030504ad9a24.png" width=300> | <img src="https://user-images.githubusercontent.com/1836005/116237514-9e54f900-a760-11eb-83cb-238bd6a2148a.png" width=300> |

## iPad

| Light | Dark |
| --- | --- |
| <img src="https://user-images.githubusercontent.com/1836005/116238198-5edadc80-a761-11eb-9c49-50a3a1079c3f.png" width=400> | <img src="https://user-images.githubusercontent.com/1836005/116238163-54204780-a761-11eb-9d9f-0021656673c6.png" width=400> |

@osullivanchris - Is there anything else we want to address in this screen? (Signup for new user > Change Username)
