### ISSUE TITLE
Unable to scroll in the editor in landscape on iPhone

### ISSUE THREAD

**Issue by thebud15** [wordpress-mobile/WordPress-iOS#16476]
### Expected behavior

To be able to scroll up and down while editing a post or page in iPhone landscape mode

### Actual behavior

When using the editor in landscape mode on the iPhone, some of us HEs were unable to scroll up and down.

### Steps to reproduce the behavior

1. Start a post or page.
2. Add some filler content to the post/page (such as some arbitrary text or block(s)
3. Turn the iPhone landscape and try to scroll up/down

https://user-images.githubusercontent.com/29046778/117868669-b6dc0d80-b24e-11eb-9ba0-27c692fd0b76.MP4

#####
We replicated this issue on 10S Max (iOS 14.4.2) , 12 Pro Max (iOS 14.5.1) and 12 Mini (iOS 14.4.2). We were able to properly scroll on an iPhone 6 (iOS 14.5.1), though.

**Comment by startuptester** [comment]
Able to repro on 17.3.0.1 on iPhone 12 Pro

**Comment by hypest** [comment]
Replicated on an iPhone 11 Pro Max, iOS 14.4 simulator, WPiOS 17.3 (DEV).

**Comment by antonis** [comment]
I was able to replicate this on an iPhone 11 Pro Max iOS 14.4 simulator but not on an iPhone SE 2020 device with the same iOS version.
Apart from the inability to scroll the **editor toolbar is also gone** in landscape mode.

![Simulator Screen Shot - iPhone 12 Pro - 2021-05-12 at 15 59 17](https://user-images.githubusercontent.com/304044/117982166-67750a80-b33e-11eb-82f2-c2c15bb9c15e.png)

~The bug seems to be introduced in `17.2` which is currently live.~ Not sure about this since I cannot reproduce consistently.

As @geriux pointed out the `KeyboardAvoidingView` seems to get in the way covering the whole screen.
|Debug view|Xcode layout inspection|
|---|---|
|![debug](https://user-images.githubusercontent.com/304044/117982212-7360cc80-b33e-11eb-8aca-adb3877dec03.png)|![xcode](https://user-images.githubusercontent.com/304044/117982214-765bbd00-b33e-11eb-9e89-2fafa83ac97d.png)|

This might be related with https://github.com/wordpress-mobile/WordPress-iOS/issues/16470

**Comment by antonis** [comment]
After further investigating this the issue is reproduced at least on iOS `14.2` and `14.4` with **fresh installs** of the app.

We have consistently reproduced the issue with the following steps both on simulator and real devices:
1. Uninstall a previous version of the app (if exists)
2. Install a fresh copy of the app
3. finish the Login login flow
4. Create a new post and add a few paragraph blocks with small text
5. **Rotate the device**
6. **Notice** that **scrolling is disabled** and the **editor toolbar is missing** 💥  
7. **Kill** the app and **Start** the app again
8. Follow the **steps 1 - 5**
9. **Notice** that the issue is never reproduced again 🚶 

Note that the issue seems to be reproducible only on devices with notch (not on iPhone 6, 8, SE)

**Comment by startuptester** [comment]
iPhone 12 Pro, iOS 14.5.1, WPiOS TestFlight install of 17.3.0.1

I do not have to follow most of the steps above. 
This is not a fresh install. 

1. Create a post from the FAB
2. Add a title, add some text to paragraph block 
3. rotate device 
I cannot scroll. 

One thing I noticed was that it wasn't happening until I logged out and back in again, then it happens every time until I kill the app.

**Comment by antonis** [comment]
I drafted a [solution](https://github.com/WordPress/gutenberg/pull/31795) that seems to fix the issue without any side effects.

> One thing I noticed was that it wasn't happening until I logged out and back in again, then it happens every time until I kill the app.

@startuptester observation above may reveal another aspect of this. The problem may be occurring due to a keyboard setting customisation on the native iOS side during login (e.g.  OTP screen) that is not reset afterwards. I will investigate another approach based on this an report back.
