### ISSUE TITLE
Jetpack: Jetpack screens for Stats and Notifications should be consistent

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#1651]
They should be visually similar and both offer an option to install. 
Notifications:
![jetpack_notes](https://cloud.githubusercontent.com/assets/1435271/2831121/be5d6a3c-cfb5-11e3-9b2a-09047d12ef3a.jpg)

Stats:
![jetpack_stats](https://cloud.githubusercontent.com/assets/1435271/2831124/c19de6ea-cfb5-11e3-9b65-a4fd8795854c.jpg)

**Comment by jleandroperez** [comment]
Let's match both, Stats + Notifications logged out UI!.

FWIW, Stats "Connect to Jetpack" UI looks like this (4.8):

![screen shot 2015-01-02 at 4 15 50 pm](https://cloud.githubusercontent.com/assets/1195260/5598778/ac9b66b6-929a-11e4-88d9-ac95c6369c0a.png)

**Comment by jleandroperez** [comment]
@astralbodies + @aerych: question for you guys. Behavior for `Stats` + `JetpackSettingsViewController` is:

- If the selected blog already has jetpack, it'll ask for wpcom credentials.
- Otherwise, it'll show the UI with the *install* button (which in turn will hit wp-admin).

Now, this makes sense in Stats, because you already picked a blog to begin with. However, the Notifications flow is quite different: you never picked up any blog.

What do you guys think? It feels a bit redundant to recreate the UI we've already got in 'Me', just to pick the right blog you wanna hook up.

Thanks in advance!

**Comment by aerych** [comment]
We're going to need a new blog picker for some planned future changes.  Is this an opportunity to break new ground?

**Comment by aerych** [comment]
@jleandroperez Alternatively, have you looked at `BlogSelectorViewController`?

**Comment by jleandroperez** [comment]
@aerych will take a look, thanks!.

Only huge detail is that... in order to determine whether you should render an *Install* button, or Jetpack Credentials, you must first pick a blog. So maybe the first screen should say... 'Select a Blog' ?

We could implement a nice modal blog picker, if the BlogSelector doesn't match this use case!

**Comment by aerych** [comment]
> Only huge detail is that... in order to determine whether you should render an Install button, or Jetpack Credentials, you must first pick a blog. 

Maybe the work flow is a screen explaining that Notifications requires Jetpack and a button to select a blog. Then showing the picker when that button is pressed.

**Comment by jleandroperez** [comment]
@aerych thank you sir! i'll build a prototype, that's what i had in mind.

**Comment by koke** [comment]
We've been working on a new jetpack screen in #2847, so this issue is probably obsoleted by that one

**Comment by aerych** [comment]
> so this issue is probably obsoleted by that one

@koke can we close this one?

**Comment by koke** [comment]
Actually #3628 :smile: 
That screen will still need some :heart: but it will be only in notifications, so no inconsistencies there :wink:

**Comment by jleandroperez** [comment]
@koke *pure* awesomeness!!
