### ISSUE TITLE
Stats bars flickering when changing tabs

### ISSUE THREAD

**Issue by osullivanchris** [wordpress-mobile/WordPress-iOS#16689]
- Open a site with real data/viewers
- go to My Site -> stats
- change between different tabs (weeks, months, years)
- when I change from months -> years in the video, it shows an empty state for a second
- then when it gets to the new selection (years) it shows the months data for a second, then changes to years
- suggestion: don't show the months data again, as I have already moved through an empty loading/skeleton state and lost that months context. Hide until the years data has loaded.

https://user-images.githubusercontent.com/50576199/122032461-8d6f4e00-cdc7-11eb-99f7-2351db2a21c0.mov

**Comment by staskus** [comment]
Note: Such flickering may be solved [by caching improvements](https://github.com/wordpress-mobile/WordPress-iOS/issues/17904).

**Comment by staskus** [comment]
Flickering is being addressed by table view optimization work:
- https://github.com/wordpress-mobile/WordPress-iOS/pull/22542
- https://github.com/wordpress-mobile/WordPress-iOS/pull/22592
- https://github.com/wordpress-mobile/WordPress-iOS/issues/22720

> then when it gets to the new selection (years) it shows the months data for a second, then changes to years

This issue is addressed by making improvements within Traffic tab.

I'm closing the issue.
