### ISSUE TITLE
Blogging Reminders in landscape mode

### ISSUE THREAD

**Issue by ravishanker** [wordpress-mobile/WordPress-iOS#17078]
### Expected behavior
Blogging Reminders flow bottom sheets are expected to rotate in landscape mode

### Actual behavior
Bottom sheets are not rotating in landscape

### Steps to reproduce the behavior
Site -> Settings -> Blogging Reminders -> when either a prologue or days and time selection screen opens, rotate the device to landscape mode.  Notice that the bottom sheets do not rotate.  It is same on epilogue screen too.

##### Tested on [device], iOS [version], WPiOS [version]
iPhone Xs, iOS 14.6, WPiOS 18.1

**Comment by illusaen** [comment]
So it's completely possible to make blogging reminders landscape capable, but it looks really bad because there's not enough space.

Looking at other navigation flow controllers, it seems like we tend to support portrait only for iOS but all on iPad.

Do we want to do that here or rework a bit of the UI constraints on the blogging reminders page to work in landscape as well?

![simulator_screenshot_A0C617E7-35A0-4528-97B0-E26694944B3F](https://user-images.githubusercontent.com/13263478/131713729-2b6371d4-32d3-4ae9-a2fd-d8ca508ce9a5.png)

**Comment by Gio2018** [comment]
Closing this one as landscape is not supported on iPhones for Blogging Reminders
