### ISSUE TITLE
Post hero image in landscape mode

### ISSUE THREAD

**Issue by ravishanker** [wordpress-mobile/WordPress-iOS#17098]
### Expected behavior
Hero image on post screen in landscape mode needs to be shown full height and transparent behind navigation options as in portrait mode

### Actual behavior
Hero image on post screen in landscape mode is not shown full height and not transparent behind navigation options 
<table><tr>
<td><img width=320 src="https://user-images.githubusercontent.com/990349/131414213-39678a78-0494-46ad-ac88-79fca834aaef.jpg" /></td>
<td> <img width=320 src="https://user-images.githubusercontent.com/990349/131414323-a28f4712-1fc9-43d5-a892-987142aec294.jpg" /></td>
</tr></table>

### Steps to reproduce the behavior

- Go to reader
- Open a post with a header image in portrait mode see that it is shown in full and transparent behind navigation
- Rotate, notice that the image is not full length and navigation bar in black on top of the image

##### Tested on [device], iOS [version], WPiOS [version]
iPhone Xs, iOS 14.6, WPiOS 18.1

**Comment by kean** [comment]
It looks like it was fixed in https://github.com/wordpress-mobile/WordPress-iOS/pull/23897. I can't repro it:

<img width="910" alt="Screenshot 2024-12-18 at 1 21 40 PM" src="https://github.com/user-attachments/assets/af13c526-a0b1-4cf2-9fba-0c87d9ae7586" />

The size is now the same across all images and no longer depends on image dimensions.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
