### ISSUE TITLE
مشروع١

### ISSUE THREAD

**Issue by AbdullahZahaiyan** [wordpress-mobile/WordPress-iOS#17295]
مشروع١

**Comment by designsimply** [comment]
Closing because there is not enough information to go on and it looks like this may have been posted by mistake. If you would like to submit a bug about the WordPress iOS app, please [create a new issue](https://github.com/wordpress-mobile/WordPress-iOS/issues/new) and please make sure to include the following details: 

* Expected behavior
* Actual behavior
* Steps to reproduce the problem
* List your device, iOS, and app versions.
