### ISSUE TITLE
Empty Stats: Error when fetching all-time stats for the first time

### ISSUE THREAD

**Issue by momo-ozawa** [wordpress-mobile/WordPress-iOS#17367]
Ref: p5T066-2L3-p2#comment-10478

### Expected behavior
There should not be an error when fetching all-time stats for the first time

### Actual behavior
`An error occurred` message is displayed

### Notes
This may not be a regression for Empty Stats (18.5), since I've noticed the same error in 18.4

### Steps to reproduce the behavior
1. Do a fresh install of WPiOS
2. Go to the Stats page
3. Notice the `An error occurred` message is displayed for All-Time Stats on the Insights tab

##### Tested on iPhone 12 Pro, iOS 15.0.2, WPiOS 18.4, WPiOS TestFlight 18.5

**Comment by nikola-milicevic** [comment]
I can confirm this is not a regression in 18.5 since it can be reproduced with sites with zero views in 18.4 as well.

### Debugging

I have found the problematic [line](https://github.com/wordpress-mobile/WordPressKit-iOS/blob/c5e11d569989e6782330200121545832c2a3b3d5/WordPressKit/Insights/StatsAllTimesInsight.swift#L27) in WPKit-iOS:
`let bestViewsDayString = statsDict["views_best_day"] as? String`

`StatsAllTimesInsight` decoding fails since `statsDict["views_best_day"]` contains an empty string (`""`), and the next [line](https://github.com/wordpress-mobile/WordPressKit-iOS/blob/c5e11d569989e6782330200121545832c2a3b3d5/WordPressKit/Insights/StatsAllTimesInsight.swift#L28) fails since the date cannot be generated.
`let bestViewsDay = StatsAllTimesInsight.dateFormatter.date(from: bestViewsDayString)`

So, `init` fails and the error is returned.

### Suggested solution

Provide a default value (`Date()`) for `bestViewsDay`. I have tried that solution and it works without introducing any unintended side effects during my testing.

@momo-ozawa @leandroalonso Let me know what you think about this solution.

**Comment by leandroalonso** [comment]
> Let me know what you think about this solution.

Sounds good to me!
