### ISSUE TITLE
Empty Stats: first nudge shown again after all the nudges are dismissed

### ISSUE THREAD

**Issue by momo-ozawa** [wordpress-mobile/WordPress-iOS#17371]
### Expected behavior
Nudges should not be shown again after all the nudges are dismissed.

### Actual behavior
The first nudge is shown again after all the nudges are dismissed.

### Steps to reproduce the behavior

1. Do a fresh install of WPiOS
2. On My Site select a site with more than 30 views 
3. Dismiss the Customize Insights card, then go back to My Site
4. On My Site select a site with less than 30 views
5. Go to Stats
6. Dismiss the first empty stats nudge, then go back to My Site
7. Go to Stats
8. Dismiss the second empty stats nudge, then go back to My Site
9. Go to Stats
10. Complete the Reader Discover nudge flow, then go back to My Site
11. Go to Stats
12. Notice that the first empty stats nudge is shown again

https://user-images.githubusercontent.com/6711616/138917534-04ec1400-37dd-456f-8331-339e8fa88221.mp4

### Notes
This is likely a regression in Reader Discover, which has not been released yet.  I tested on 18.5 TestFlight by dismissing publicize / completing blogging reminders, and it works as expected.

**Comment by leandroalonso** [comment]
I did a small investigation and it seems that the issue is in [this](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsTableViewController.swift#L220) line:

`insightsToShow = insightsToShow.filter { $0 != .growAudience || $0 != .customize }`

If we change it to use `&&` operator, it works just fine:

`insightsToShow = insightsToShow.filter { $0 != .growAudience && $0 != .customize }`

The reason is that the `||` operator don't filter the `.growAudience` from the original `insightsToShow`:

```
(lldb) po insightsToShow
▿ 5 elements
  - 0 : WordPress.InsightType.growAudience
  - 1 : WordPress.InsightType.latestPostSummary
  - 2 : WordPress.InsightType.todaysStats
  - 3 : WordPress.InsightType.allTimeStats
  - 4 : WordPress.InsightType.followersTotals
```

I think we can go ahead and merge this small fix in the current [opened PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/17354) but before that, I want to double-check with @nikola-milicevic if that seems reasonable.

**Comment by nikola-milicevic** [comment]
@leandroalonso Sounds good, tested it with success, thanks for finding this!
