### ISSUE TITLE
Double rotation from My Site screen lands on Stats screen

### ISSUE THREAD

**Issue by mkevins** [wordpress-mobile/WordPress-iOS#18021]
### Expected behavior
When I rotate the phone to landscape orientation, and then back to portrait orientation, I expect to be in the same screen I started with.

### Actual behavior
When I rotate the screen to landscape, and back to portrait, I land on the Stats screen (which is visible in landscape as pasrt of a split screen view).

### Steps to reproduce the behavior
1. Go to My Site screen
2. Rotate the device to landscape (observe the split screen view w/ Stats on the right side)
3. Rotate the device back to portrait
4. Observe that we are now on the Stats screen instead of the My Site screen.

### Video

https://user-images.githubusercontent.com/8507675/155477128-e087f8a2-d627-4c7c-9f0f-8d76cceead5a.mov

**Comment by momo-ozawa** [comment]
## Investigation

From the documentation on WPSplitViewController, this behavior seems intentional.

https://github.com/wordpress-mobile/WordPress-iOS/blob/a08cc72e4bfb15d4fa88c06c549c16941fb2a64a/WordPress/Classes/ViewRelated/System/WPSplitViewController.swift#L22-L28

In the `splitViewController(_:collapseSecondary:onto:)` delegate method, you can see that the secondary vc is added on to the primary vc's stack if the `detailNavigationStackHasBeenModified == true`.

https://github.com/wordpress-mobile/WordPress-iOS/blob/a08cc72e4bfb15d4fa88c06c549c16941fb2a64a/WordPress/Classes/ViewRelated/System/WPSplitViewController.swift#L510-L512

`detailNavigationStackHasBeenModified` is set to `true` when `showDetailViewController` is called -- i.e. when the user has manually changed the selection in the primary pane. 

https://github.com/wordpress-mobile/WordPress-iOS/blob/a08cc72e4bfb15d4fa88c06c549c16941fb2a64a/WordPress/Classes/ViewRelated/System/WPSplitViewController.swift#L272-L281

## Next steps

We can leave this as is, or we can modify `WPSplitViewController` to always show the primary vc when collapsing a split vc. What do you think, @tiagomar?

@frosty Tagging you in case I'm overlooking something, looks like you worked on `WPSplitViewController` a while back.

**Comment by tiagomar** [comment]
Hey @momo-ozawa ! =)

Yeah, it seems like it is working as expected when moving from split to single view and I don't think we need to make any changes on that. We probably want to understand if the split view should be displayed on an iPhone in the first place though. 

This issue was reported on an iPhone 11, but I don't see the split view on my iPhone 13 (the same with my Android app). Would that be what we want? I would advocate for consistency across different models but I would like to hear from the UX designers.

**Comment by frosty** [comment]
Thanks @momo-ozawa. It's a little hard to remember, but I feel like you're correct that this behaviour was intentional. The right hand pane is an extra level down the hierarchy and it's possible that the user could've interacted with it (for example scrolled to view some specific content), so I think it makes sense to keep that content visible.

**Comment by momo-ozawa** [comment]
Hi @tiagomar! 👋 

> We probably want to understand if the split view should be displayed on an iPhone in the first place though.

This is because we show split view based on size classes, instead of iPhone vs iPad. 

Currently My Site is configured to display in split view mode if the landscape [size class](https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/adaptivity-and-layout/) is **regular width** (as opposed to **compact width**). All iPad models have a regular width regardless of portrait vs landscape orientation. Some iPhone models have a regular width in landscape orientation.

> This issue was reported on an iPhone 11, but I don't see the split view on my iPhone 13
 
iPhones have different size classes for landscape width depending on the model:
 
- [iPhone 11 is regular width in landscape](https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/adaptivity-and-layout/) -> displayed in split view
- [iPhone 13 is compact width in landscape](https://useyourloaf.com/blog/iphone-13-screen-sizes/) -> not displayed in split view

> The right hand pane is an extra level down the hierarchy and it's possible that the user could've interacted with it (for example scrolled to view some specific content), so I think it makes sense to keep that content visible.

That makes sense @frosty, thanks for the feedback!

**Comment by mkevins** [comment]
Just adding my thoughts about the split view: I kind of like that it is possible on my device (it's a neat feature, imo). I'm still a bit confused why this behavior is expected after returning to portrait, though. In the steps I used to encounter this issue, I did not interact with the stats view (I didn't tap or scroll), so is this still expected, given those conditions?

**Update:**

I'm no longer observing this on `trunk` (on commit: cb14f1ccfd00b8aa0238018fbfb899beebdf32f7). Was this somehow already addressed? Now, when I rotate back to portrait, I always land on the My Site screen, _even after interacting with the Stats pane in the split view_. :thinking:

**Comment by momo-ozawa** [comment]
> In the steps I used to encounter this issue, I did not interact with the stats view (I didn't tap or scroll), so is this still expected, given those conditions?

@mkevins I have a hunch on why this might be happening. Did you launch the app in landscape mode? If you did, then `BlogDetailsViewController.showInitialDetailsForBlog` triggers `WPSplitViewController.showDetailViewController`, which causes the secondary vc to be displayed when returning to portrait.

Some videos below of the flows I tested:

<details>
  <summary>Launched in portrait, rotated to landscape then back to portrait → My Site displayed</summary>

  https://user-images.githubusercontent.com/6711616/158301248-f30d1b85-6e21-4903-bc70-955f05a9764e.mp4
</details>

<details>
  <summary>Launched in portrait, rotated to landscape, tapped Stats row, then rotated back to portrait→ Stats displayed</summary>
 
   https://user-images.githubusercontent.com/6711616/158300965-78363b9f-bf94-4bd4-8ecf-5f73041c36b3.mp4
</details>

<details>
  <summary>Launched in landscape, rotated to portrait → Stats displayed</summary>
 
  https://user-images.githubusercontent.com/6711616/158300631-fe0dfd5a-2e1b-4289-8ec5-ded455552d48.mp4
</details>

I do think it's strange that if you launch in landscape then rotate to portrait, then the secondary vc is displayed -- I'll look into fixing this case.

**Comment by mkevins** [comment]
> I have a hunch on why this might be happening. Did you launch the app in landscape mode?

@momo-ozawa I think you nailed it! I just tried again, and I had to first swipe away the app. Indeed launching in landscape brings the behavior noted in this issue. Nice work tracking that down! :tada: 

Fwiw, the behavior persists afterwards, seemingly no matter how many times I change the orientation.
