### ISSUE TITLE
I18n: Some textual content remains in English when using WordPress app in PT-BR language

### ISSUE THREAD

**Issue by brcavallaro** [wordpress-mobile/WordPress-iOS#18161]
### Expected behavior
While using the WordPress app in iOS devices configured with PT-BR language, textual content should be translated accordingly.

### Actual behavior
Some textual content remains in English when using WordPress app in PT-BR language (iOS device, iPhone XS).
> I just explored the content of `Blog Post` creation. There might be much more untranslated content. Please, let me know if you'll need me to run another session to explore this even more and provide a complete report.

| Adding images | Text options | Paragraph placeholder | Paragraph settings |
| --- | --- | --- | --- |
|![Adding images](https://user-images.githubusercontent.com/2813972/158925074-6a3d256b-47ae-4d34-b6bf-23e06ff3db2d.jpg)|![Text options](https://user-images.githubusercontent.com/2813972/158925025-a1893ab7-e862-40a7-9544-40e2ea81c0bd.jpg)|![Paragraph placeholder](https://user-images.githubusercontent.com/2813972/158925032-21c77a51-845f-474c-8553-dc4fb17b1506.jpg)|![Paragraph settings](https://user-images.githubusercontent.com/2813972/158925034-54e598fb-e7ed-4de8-9ee2-2f9ef59afd9b.jpg)|

| `Block removed` toast | Color labels | Font sizing options | General placeholders |
| --- | --- | --- | --- |
|![Block removed toast](https://user-images.githubusercontent.com/2813972/158925036-0b5b9b5a-7c0d-44b1-98c4-ae76f5e54a48.jpg)|![IColor labels](https://user-images.githubusercontent.com/2813972/158925037-59d06dd1-ec74-429e-896e-3382e92bcd2d.jpg)|![Font sizing options](https://user-images.githubusercontent.com/2813972/158925042-0f415be6-8957-4cc4-be9a-fe998592974c.jpg)|![General placeholders](https://user-images.githubusercontent.com/2813972/158925045-bddbd6a5-d81c-4999-a398-02d2cb2d4332.jpg)

### Steps to reproduce the behavior

1. Switch the device's default language to PT-BR
2. Navigate throughout the app exploring proper translation

**Comment by hypest** [comment]
Thanks for opening this ticket @brcavallaro !

👋 @fluiddot, you probably have some insights on the translations side of things, can you check out this ticket? Thanks!

**Comment by fluiddot** [comment]
> 👋 @fluiddot, you probably have some insights on the translations side of things, can you check out this ticket? Thanks!

Sure, I'll take a look as soon as possible.

**Comment by fluiddot** [comment]
I've done a quick investigation, and the issue is related to the locale identifier used for loading the localizations in WordPress-iOS before passing them to Gutenberg ([reference](https://github.com/wordpress-mobile/WordPress-iOS/blob/480f42b5403e5c74cf4eaab94fbad3995c46d197/WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController%2BLocalization.swift#L28-L34)). For some reason, when using PT-BR language the locale identifier retrieved is `PT` instead of `PT-BR`. We have way less translations for `PT` language than `PT-BR`, so it makes sense that we see more strings untranslated.

**[WordPress for iOS GlotPress project](https://translate.wordpress.org/projects/apps/ios/dev/):**

<img width="934" alt="Screenshot 2022-03-22 at 11 25 04" src="https://user-images.githubusercontent.com/14905380/159460386-46b3f009-a91d-4026-98fa-14946a0d45ac.png">

We should investigate further how to retrieve the proper locale identifier for this case.

**Comment by hypest** [comment]
Thanks for investigating @fluiddot!

Aha, sounds like we shouldn't be opting for the region-less locale if the one for the region (_Brazil_ in this case) is in a better translation coverage, right?

**Comment by fluiddot** [comment]
> Aha, sounds like we shouldn't be opting for the region-less locale if the one for the region (Brazil in this case) is in a better translation coverage, right?

Exactly, we should retrieve `PT-BR` localizations in this case. As outlined in [this comment](https://github.com/wordpress-mobile/WordPress-iOS/issues/18161#issuecomment-1074997093), I found it unexpected that [this line](https://github.com/wordpress-mobile/WordPress-iOS/blob/480f42b5403e5c74cf4eaab94fbad3995c46d197/WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController%2BLocalization.swift#L29) returns `PT` even  when setting the device's language to `PT-BR`. As far as I checked, we don't have a logic that opts for the region-less version when retrieving the localizations file, so I'm wondering if we're taking the wrong identifier for this purpose 🤔 .
