### ISSUE TITLE
Unexpected result of Bin action in notification menu

### ISSUE THREAD

**Issue by draganescu** [wordpress-mobile/WordPress-iOS#18257]
### Expected behavior

![Screenshot 2022-04-01 at 16 08 27](https://user-images.githubusercontent.com/107534/161273231-4fdb4d90-db14-4646-9639-f8e534920274.png)

Tapping the big red Bin button, I expected to delete the notification not the actual comment I was notified about.

Even so, given that I am deleting other people's content I should have been prompted for confirmation. Ideally IMO I would just hide this power from the notification menu 😁 

### Actual behavior

I deleted the comment that I was notified about instead of the notification.

### Steps to reproduce the behavior

1. Get a notification on a P2 where you are editor
2. Swipe left on the notification
3. Tap bin
4. The comment or post gets deleted, right away

##### Tested on [device], iOS [version], WPiOS [version]
Latest iOS

**Comment by develric** [comment]
Linking a relevant slack conversation here for more context `p1648800394324479-slack-automattic`

**Comment by mattmiklic** [comment]
Just to repeat my suggestion from the Slack thread -- I think changing the button label to include the word "Comment" could make it clearer to the user what action they're about to perform: `Trash comment` or `Bin comment` should remove the ambiguity.

We provide an Undo here which I think is preferable to a confirmation dialog for [these reasons](https://goodui.org/#8). Adding a confirmation dialog would require two taps and a bit of cognitive friction to accomplish the desired task, which would sort of defeat the purpose of the swipe shortcut (because tapping once to open the comment and tapping `Trash` on the moderation bar would be the same number of steps/taps).

**Comment by yaelirub** [comment]
I suggested adding a confirmation for deleting, I understand its not the preferred design practice.
Sounds like the current undo option is not intuitive enough per the reports here. Even if the comments can be restored, deleting ones comment it still a stressful experience like some people shared in the Slack thread. If you think “Trash Comment” is sufficient, lets do that

**Comment by mattmiklic** [comment]
It sounds like the primary problem is that the user might think they're trashing a notification, rather than the actual comment itself. Changing the label to `Trash comment` seems like it would fix that.

Another alternative is removing the swipe shortcut. Maybe it would be safer if the user only moderated after tapping into the notification so they have the full context and it's easier to undo accidental actions. Also, not all notifications have a shortcut and I've heard some confusion over why that's the case.

Those two options seem like better choices to me. But if we did add a confirmation step it should be an action sheet, following the example of deleting a draft in the Mail app:

<img width="753" alt="Screen Shot 2022-04-01 at 4 50 25 PM" src="https://user-images.githubusercontent.com/1396552/161340243-4b43658e-d904-44be-997a-1bfc34bd0ad5.png">

**Comment by develric** [comment]
>Another alternative is removing the swipe shortcut. Maybe it would be safer if the user only moderated after tapping into the notification so they have the full context and it's easier to undo accidental actions. Also, not all notifications have a shortcut and I've heard some confusion over why that's the case.

AFAIU we do not track the actions that are taking place from the shortcuts, so we do not have at hand numbers to measure if the moderation shortcut is used much or not. I somewhat think this could be a case of `less is more`, so could make sense to me to remove the shortcut (but would probably like to know if it's heavily used by users or not). Unless we want to just remove the shortcut (let me know your thoughts in case), I would possibly go this way:

- we change the label to clarify that the action is taking place on a comment; 
- we also add tracking of single actions (we are interested in the comment moderation shortcut usage)
- we review numbers for the comment moderation shortcut and decide if we can remove it or if we need other actions

Caveat: putting the above in place per se should be quick, but keeping in mind the release lifecycle, the data will start to collect in like 3 weeks.

@yaelirub , @mattmiklic wdyt? 🙇 (cc @ScoutHarris )

**Comment by mattmiklic** [comment]
That sounds just fine to me. FWIW I also wouldn't be opposed to removing it and just seeing if we get any feedback about it. Since trashing a comment is destructive it seems like something that doesn't need a shortcut. We could leave the options to approve/unapprove from the shortcut though.

**Comment by develric** [comment]
>FWIW I also wouldn't be opposed to removing it and just seeing if we get any feedback about it. Since trashing a comment is destructive it seems like something that doesn't need a shortcut. We could leave the options to approve/unapprove from the shortcut though.

Hey @mattmiklic 👋 , after discussing with @yaelirub about this, your suggestion seems reasonable so we are going to remove the Trash action from those shortcuts but keep the non-destructive Approve/Unapprove.

cc @ScoutHarris (should be a quick enough task to cover in this way, so hopefully we can cover it before the code freeze 🙇 ....also I would maybe consider adding those shortcut actions tracking regardless if it's not too complicated for any reason, so we get some more knowledge about the actions in general; my 2 cents 🙇  )
