### ISSUE TITLE
QuickStart for Existing Users V2: General UI changes

### ISSUE THREAD

**Issue by hassaanelgarem** [wordpress-mobile/WordPress-iOS#18389]
## Description

The UI changes will apply to both old and new tours

Ref: pbArwn-40S-p2
Design Ref: pbArwn-4kz-p2

## Tasks

- [x] Display notice with more guidance when all tours are completed #18519
- [x] Investigate modifying the notification sent from the backend #18551
    - It should read "Next Steps" instead of "Quick Start"
    - It already reads "Next Steps" in Android (Ref: pdcxQM-Jw-p2#comment-584)

**Comment by momo-ozawa** [comment]
### Descoped

- Replace the blue progress circle with a green checkmark
- Remove completed section, strikethrough tour items at their position

The items above have been descoped since the new Quick Start designs (pbArwn-4wS-p2) would override them. For more context follow the conversation here: p1651573706679109/1651520982.502339-slack-G0151398PFU
