### ISSUE TITLE
Blogging Reminder bottom sheet not always shown after publishing 1st post on site

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#18696]
### Expected behavior

When publishing the first post on a site, the Blogging Reminders bottom sheet should appear.

### Actual behavior

When publishing the first post on a site, in about 1 out of 3 times, the Blogging Reminders bottom sheet does not appear.

### Steps to reproduce the behavior

1. Create a site
2. Publish a post
3. Check if Blogging Reminders bottom sheet appears
4. Repeat steps 1 to 3 until you notice the bottom sheet doesn't appear after publishing a post

##### Tested on iPhone 11, iOS 15.3.1, WPiOS 19.9 beta

h/t to @tiagomar for reporting this issue!

**Comment by guarani** [comment]
Looking at the app's Activity Log, when Blogging Reminders is surfaced I see:
1. `editor_closed` event, then
2. `blogging_reminders_flow_start` event

However, when it is not shown, I see no more events after the `editor_closed` event. It looks to me like in these scenarios, the `BloggingRemindersFlow.present` method is not getting called.

**Comment by guarani** [comment]
The severity of this issue seems medium, but the impact low (only one report, from @tiagomar, so far). So I've given this a low priority.

**Comment by guarani** [comment]
I ran into this again today. After creating a new site, the blogging reminders prompt (bottom sheet) is not always shown after the first or the second post is published. In my test, on the third post published I saw the blogging prompt. 

Looking at the logic [here](https://github.com/wordpress-mobile/WordPress-iOS/blob/0517d3d6d68f5e1052ca3020318150fe45f7bfcc/WordPress/Classes/ViewRelated/Blog/Blogging%20Reminders/BloggingRemindersFlow.swift#L18-L20) it seems (I'm not 100% certain) that the prompt should be shown on the 1st post published.

**Comment by twstokes** [comment]
This is failing for me because `post.isPublished()` is returning `false` and the `guard` [returns here](https://github.com/wordpress-mobile/WordPress-iOS/blob/217aced93289649861e65d03ff6610b16fb6e778/WordPress/Classes/ViewRelated/Post/EditPostViewController.swift#L288).

I can get Blogging Reminders to show on the first try if I publish outside the editor, e.g. My Site -> Posts -> Drafts -> More -> Publish Now, because I think [this path is taken instead](https://github.com/wordpress-mobile/WordPress-iOS/blob/217aced93289649861e65d03ff6610b16fb6e778/WordPress/Classes/ViewRelated/Post/PostEditor%2BPublish.swift#L558).
