### ISSUE TITLE
[iOS] Stats: Insights tab show different numbers on iOS, Android and Web

### ISSUE THREAD

**Issue by staskus** [wordpress-mobile/WordPress-iOS#19337]
#### Created issues:
- https://github.com/wordpress-mobile/WordPress-iOS/issues/19345
- https://github.com/wordpress-mobile/WordPress-Android/issues/17211
 
### Inside views & visitors details view:

- iOS: Although Sept 19 - Sept 25 are selected, the diagram starts from Sept 17 (incorrect) 🔴
- iOS. Shows 825, the correct number for a 7 day period (correct) ✅
- Android: The diagram and selection starts on Sept 19 (correct) ✅ 
- Android: Shows 814, the wrong number (incorrect) 🔴
- Web: Starts Sept 19 and shows 782 (correct) ✅

<img width="1310" alt="image" src="https://user-images.githubusercontent.com/4062343/191920867-66820ea3-294a-411e-90d1-327c2bf8c7ee.png">

### Inside views & visitors details view (If we pick the previous week):

- iOS shows 924 (correct) ✅
- Android shows 950 (incorrect) 🔴
- Web shows 924 (correct) ✅

<img width="1306" alt="previous week" src="https://user-images.githubusercontent.com/4062343/191935760-6134c0fb-9780-4953-a53f-df32457fc8f1.png">

### In Insights tab:

- iOS shows 825 (correct number for 7-day period) ✅
- Android shows 1026 (incorrect number for 7-day period) 🔴
- Either naming of "This week" is misleading or the graph should only represent this week.

<img width="795" alt="image" src="https://user-images.githubusercontent.com/4062343/191921701-369b1361-c206-49d1-9044-782422b48922.png">

### Counting day by day

- If we add all days one by one from Monday (Sept 19 to Today), we get 782. It matches what the Web is showing
- If we add all days one by one for one week period (Sept 17 to Today), we get 825. It matches what iOS is showing.

#### Created issues:
- https://github.com/wordpress-mobile/WordPress-Android/issues/17212
- https://github.com/wordpress-mobile/WordPress-iOS/issues/19355

#### Stats:

- Web: Starts Sept 19 and shows 57 (correct - it only shows unique visitor numbers) ✅
- iOS: Although Sept 19 - Sept 25 are selected, the diagram starts from Sept 17 (incorrect) 🔴
- iOS. Shows 131 (incorrect - it adds up all the daily visitors for the last 7 days) 🔴
- Android: The diagram and selection starts on Sept 19 (correct) ✅ 
- Android: Shows 125 the wrong number (incorrect) 🔴

<img width="1300" alt="insights tab visiors" src="https://user-images.githubusercontent.com/4062343/191939864-4aab5dc5-a99c-4eb9-9a30-c4367f150776.png">

### Inside views & visitors details view (If we pick the previous week):

All platforms differ in numbers:
- Web (Sept 12 to Sept 28), 106 ✅
- iOS (Sept 12 to Sept 18), we get 192 (incorrect - it adds up all the daily visitors for the last 7 days)  🔴
- Android (Sept 12 to Sept 28), 199 (doesn't match day by day numbers) 🔴

<img width="1316" alt="different number of visitos of the week" src="https://user-images.githubusercontent.com/4062343/191938264-0b8bea97-acbd-44c6-8633-7d01802014c5.png">

### In Insights tab:

- Web shows 57 (correct) ✅. Web doesn't just add all the daily numbers, [it only counts unique visitors](https://wordpress.com/support/stats/)
- iOS shows 131  (incorrect) - iOS adds up all the daily visitors creating visitor duplicated 🔴
- Android shows 174 (incorrect) 🔴

#### Created issues:
- https://github.com/wordpress-mobile/WordPress-iOS/issues/19356
- https://github.com/wordpress-mobile/WordPress-Android/issues/17213

#### Stats:
- iOS and Android match
- Web doesn't match

💡 Do we pick up a little bit different start date based on the time zone? Or is there any other issue here?

<img width="1310" alt="image" src="https://user-images.githubusercontent.com/4062343/191946437-f9d8e4db-92a1-4e4f-8ad3-b8dc485a94b8.png">

## Different percentages (by one, most probably different rounding) https://github.com/wordpress-mobile/WordPress-iOS/issues/19346
![Image](https://user-images.githubusercontent.com/4062343/191748785-4f2a947e-b3cc-49c9-b1fc-4df15d7cca8c.png)
![Image](https://user-images.githubusercontent.com/4062343/191748897-5fddec41-f845-4d6f-88d3-f2206c69e46c.png)

## This year - inconsistent rounding. Some places we have decimals on iOS, on other places on Android https://github.com/wordpress-mobile/WordPress-iOS/issues/19346
![Image](https://user-images.githubusercontent.com/4062343/191749686-e5697e39-05c3-486c-a2c7-2fe1153c6668.png)

## Top follower numbers different
![Image](https://user-images.githubusercontent.com/4062343/191749315-d2607fd3-7b65-4536-8d7a-a6ed5d8ba712.png)

**Note:** not worth fixing since there'll be a change in the design https://github.com/wordpress-mobile/WordPress-iOS/issues/18602

## Posting activity in different colors

![Image](https://user-images.githubusercontent.com/4062343/191749810-ac84b4c0-a775-448d-9d4b-2b345ba10625.png)

**Comment by guarani** [comment]
Thanks for creating this issue @staskus!

> Different number of views of the week

Tapping on each data point on the chart gives the daily total for views on that chosen day. Summing these manually gives the weekly total. This matches the total for "this week" that's shown on iOS, but it doesn't match on Android.

> Different number of visitors of the week

Same difference as with views. 

> Different percentages (by one, most probably different rounding)

Could be rounding. For the "Most Popular Time" card, the percentages shown on Android match those on the web while iOS is different. For the "Total Comments" card, when I looked at this for a particular site, there were six comments this week and none last week. On Android, it showed up as an infinity percent increase "+6 (∞%)". On iOS, it showed up as a zero percent increase "+6 (0%)". Instead we could show "+6" or "+6 (n/a %)", but the former feels more correct because a % change shouldn't be provided if the previous period was zero. The latter is also harder to localize.

> This year - inconsistent rounding. Some places we have decimals on iOS, on other places on Android

Since this is a presentation issue (not a data issue like some of the above differences), it's not crucial that this match. It would be nice for iOS, Android, and the web to match. However, due to space constraints, it might make sense that mobile uses K to abbreviate thousands while the web doesn't as seems to be the case here. Other differences (e.g. whether to round 0.8 to 1) seem like they should be consistent across all platforms.

> Top follower numbers different

Looking at the numbers for the time someone's been a follower, it looks like Android is rounding up (e.g. the ceil() function is applied to the number). So a follower who's been around for 7 months and 5 days is shown as "8 months" on Android. iOS seems to handle this as I would expect and shows "7 months".

> Posting activity different colors

On Android, it looks like the week starts on Sunday. On iOS, it looks like the week starts on Monday (same as the web). When I look at which days have more posts (darker green), I see differences between all platforms (iOS is different from Android and Android is different from the web).

**Comment by staskus** [comment]
Thank you for your insights, @guarani! 

> Since this is a presentation issue (not a data issue like some of the above differences), it's not crucial that this match.

That's a good point.

> Other differences (e.g. whether to round 0.8 to 1) seem like they should be consistent across all platforms.

Yes, agree. 

---

All in all, I'll review it a bit further and compare it to the web as well. I imagine it could result in a couple of changes on iOS and a couple of changes on Android.

**Comment by staskus** [comment]
Fixing these issues on iOS:

- [ ] "This week" views and visitors: Although "This week" is selected, we show 7-day period diagram and numbers. We should be showing numbers and a diagram for this week only. 
- [ ] "Most Popular Time" percentages rounding (check other cards as well)
- [ ] Don't show 0% increase if the previous period was empty
- [ ] Make this year rounding consistent with Android

**Comment by staskus** [comment]
I created 2 issues to address on iOS:
- https://github.com/wordpress-mobile/WordPress-iOS/issues/19345 - wrong time ranges for Views & Visitors
- https://github.com/wordpress-mobile/WordPress-iOS/issues/19346 - number rounding & presentation issues

I'm closing this issue as it served as an investigation.

**Comment by guarani** [comment]
Are there any additional bug reports here that we should capture in separate issues? I see mentions of web and Android issues, but I'm not sure if they've been captured or may be lost when this issue is closed.

**Comment by staskus** [comment]
> Are there any additional bug reports here that we should capture in separate issues? I see mentions of web and Android issues, but I'm not sure if they've been captured or may be lost when this issue is closed.

I'll create additional issues and will reference them here.

**Comment by staskus** [comment]
Additional issues:

- https://github.com/wordpress-mobile/WordPress-Android/issues/17211
- https://github.com/wordpress-mobile/WordPress-Android/issues/17212
- https://github.com/wordpress-mobile/WordPress-iOS/issues/19355
- https://github.com/wordpress-mobile/WordPress-iOS/issues/19356
- https://github.com/wordpress-mobile/WordPress-Android/issues/17213

**Comment by guarani** [comment]
Thanks @staskus!
