### ISSUE TITLE
[Jetpack-iOS] Crash on tapping any buttons on Domains screen

### ISSUE THREAD

**Issue by ravishanker** [wordpress-mobile/WordPress-iOS#19351]
### Expected behavior
Buttons like **Search for domain** or **Add a domain** should open **Search domains** screen

### Actual behavior
Crashes on tapping **Search for domain** or **Add a domain** buttons

### Steps to reproduce the behavior
- Install Jetpack iOS v20.8 beta
- Navigate to MySite > Menu > Domains
- Tap on **Search for domain** or **Add a domain** buttons
- Notice if it crashes

##### Tested on iPhone Xs, iOS 16, WPiOS 20.8(pr19332-105308f)

https://user-images.githubusercontent.com/990349/192399967-439380da-731c-4efa-9118-8d5599be51d1.MP4

**Comment by hassaanelgarem** [comment]
@ravishanker What is the role of the account you're testing with on `dayonep2.wordpress.com`?

**Comment by vanessamaartinstt** [comment]
Hi @hassaanelgarem ! I'm able to consistently reproduce the crash while searching for domains on JP iOS 20.9. The activity logs are attached.

Site address: vanessamaartins.wordpress.com
Device: Iphone 12 Pro Max
iOS Version: 16.0.2

Please let me know if I can provide any further information.

[JP Crash Logs.docx](https://github.com/wordpress-mobile/WordPress-iOS/files/9719360/JP.Crash.Logs.docx)

**Comment by staskus** [comment]
This bug is only reproducible on iOS 16.

The crash happens with an error message:

``
UIViewControllerRepresentables must be value types: DomainSuggestionViewControllerWrapper
``

I couldn't find a lot of [information or discussions about it online](https://developer.apple.com/forums/thread/709433) but the error is self-explanatory. We need to turn `DomainSuggestionViewControllerWrapper` from `class` into `struct`.

@Gio2018 I saw you worked on the original issue, maybe you would be interested to take a look?

**Comment by Gio2018** [comment]
Hey there @staskus , sure I can take a look between today and next week!

**Comment by staskus** [comment]
> Hey there @staskus , sure I can take a look between today and next week!

Perfect, thank you!

**Comment by Gio2018** [comment]
Here's the [fix](https://github.com/wordpress-mobile/WordPress-iOS/pull/19463)
Note that I tested this on the App Store released version and the crash did not seem to occur. For this reason I am targeting trunk and not updating the RN.
