### ISSUE TITLE
[iOS] Stats: Views and Visitors card always show outdated cached totals first

### ISSUE THREAD

**Issue by staskus** [wordpress-mobile/WordPress-iOS#19430]
Once `Views and Visitors` caches total numbers, it doesn't update the cache, always showing the same numbers before loading most recent numbers.

https://user-images.githubusercontent.com/4062343/195125867-ded61ece-4592-4e2e-bd88-7db899aa5348.mov

## Expected behavior

Once the totals are updated, they should be cached and shown immediately after coming back to stats.

### Steps to reproduce the behavior

1. Enable state revamp feature flag
2. Open Stats
3. Add Views & Visitors card
4. Come back to menu and return to Stats
5. Notice total numbers changing every time

**Comment by guarani** [comment]
Is this the bug 🐛 from https://github.com/wordpress-mobile/WordPress-iOS/pull/19400#issuecomment-1270627234 under the "Stats showing data for previously selected site" section? It looks different because this issue shows the screen displaying stale data from the correct site before automatically updating to show the correct data, while the issue I reported seems to show data from a previously selected site.

**Comment by guarani** [comment]
Sorry, I just realized this is a different bug and https://github.com/wordpress-mobile/WordPress-iOS/issues/19424 is what I was referring to.

**Comment by staskus** [comment]
Might be related 5691292-zd-woothemes
