### ISSUE TITLE
Draft list is not updated correctly when publishing a post from the Drafts tab

### ISSUE THREAD

**Issue by vanessamaartinstt** [wordpress-mobile/WordPress-iOS#19550]
### Expected behavior
Draft list should be updated correctly to reflect the number of posts that remains in the Drafts tab.

### Actual behavior
When publishing a draft post from Drafts tab, the draft list shows only 3 drafts after publishing. It’s resolved by refreshing the list manually.

### Steps to reproduce the behavior
1. Go to My Site > Posts > Drafts (You need to have five or more draft posts available)
2. Select one of the drafts and tap on ... More > Publish Now > Publish
3. Notice that the list only shows 3 drafts 

##### Tested on [device], iOS [version], WPiOS [version]
Device: Iphone 14 Pro Max
iOs Version: 16.1
WP/JP version: 21.1

https://user-images.githubusercontent.com/107848100/199350087-6a46fef5-3dd4-4751-9613-5a2f65c88453.MP4

**Comment by alpavanoglu** [comment]
I think I have trapped this issue in a small area but I wasn't able to resolve it. Most of the code here is 8 years old and `WPTableViewHandler`, the possible culprit, seems to be in use throughout the codebase.

What is happening here is [this line](https://github.com/wordpress-mobile/WordPress-iOS/blob/ee94c3547852873ab0b2a5039dfc038b960dc912/WordPress/Classes/Utility/WPTableViewHandler.m#L685) is being called more than necessary. When a draft post is published, that line is called once which is reasonable. But then it gets called until the remaining number is 3. So if we had 9 draft posts and we publish one (now 8), that line gets called an additional 5 more times so the resulting number is 3.

Also number of items in the `resultsController` is 3 right when we open this screen rather than the correct number 9. Then it syncs with backend and updates.

**Comment by kean** [comment]
This flow has been re-implemented and it now works as expected, closing.
