### ISSUE TITLE
Jetpack Share Extension: Site list not accurate if WordPress and Jetpack are both installed 

### ISSUE THREAD

**Issue by hassaanelgarem** [wordpress-mobile/WordPress-iOS#19591]
### Expected behavior
Jetpack extensions to be fully separated from the account signed into the WordPress app. The site list displayed should always be from the account signed into the Jetpack app. 

### Actual behavior
The site list displayed is from the app that was most recently launched.

### Steps to reproduce the behavior
Install & run Jetpack
Sign in using account A
Install & run WordPress
Sign in using account B
Go to photos
Select a photo
Tap on the share button
Select Jetpack
Observe that the site list displayed is the one from account B not account A.

**Comment by guarani** [comment]
I have this a priority, medium priority, because while the functionality is related to the editing experience it only affects sharing content from outside the editor and depends on having both apps installed. Also, there's a workaround which is to open the app you wish to share to, then go back and share the content (e.g. a photo).

Having a priority helps us assess whether 21.3, which includes this fix, can be skipped (given the migration-related features will land in 21.4).
