### ISSUE TITLE
The time label in a comment notification should take you to the comment.

### ISSUE THREAD

**Issue by sendhil** [wordpress-mobile/WordPress-iOS#1961]
Currently if you tap on the time label at the bottom left of a comment notification it doesn't do anything. This should take you to the comment in question so as to be consistent with the way it works on the WordPress.com Reader.

**Comment by jleandroperez** [comment]
I'm closing this issue since it's no longer relevant:

- As per WPiOS 4.7, we display on top the header of the post. Tapping on it leads to the related post.
- Time label has now the BlogURL of the user who posted. Tapping on it opens a webView, and renders the blog.

We'll be updating the Notification Header's behavior in #2549, so it leads to the related comment instead.

Thanks @sendhil!
