### ISSUE TITLE
Stats widgets should indicate how fresh their stats are

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#19705]
### Expected behavior

Widgets should indicate how fresh the data they're displaying is.

### Actual behavior

Widgets don't indicate how old the data they're displaying is.

### Steps to reproduce the behavior

1. Install the app
2. Add a Stats widget and configure it for a site
3. Notice there is no indication of how old the data that is being displayed is

### Additional information

Apple's Human Interface Guidelines suggest this: 

>  If people are likely to check your widget more frequently than you can update it, consider displaying text that describes when the data was last updated.

https://developer.apple.com/design/human-interface-guidelines/components/system-experiences/widgets/

h/t @staskus for suggesting this

**Comment by tadija** [comment]
Hi @wargcm, after discussing this issue with design team we came to a conclusion that this task should probably be discarded. Expectation is that widgets are always showing the latest information anyway, so it might not be appropriate to display the “Updated” message, since we already show an error message if there was a failed data fetch.

**Comment by jkmassel** [comment]
Closing given:

> this task should probably be discarded
