### ISSUE TITLE
[Jetpack migration flow] Improve flow for users who aren't signed into WordPress

### ISSUE THREAD

**Issue by twstokes** [wordpress-mobile/WordPress-iOS#19715]
### Expected behavior
Not prompting the user repeatedly.

### Actual behavior
User is prompted with the same view in step 4.

_Video courtesy of @salimbraksa._

https://user-images.githubusercontent.com/9609223/205391077-3695afdb-d94b-4811-b104-74c1a8f96be4.mp4

### Steps to reproduce the behavior
1. Clean install the WordPress app (21.3) and don't authenticate.
2. Clean install the Jetpack app and load it.
3. Expect: UI to be shown explaining to the user they can open WordPress.
4. Tap "Open WordPress".

**Comment by salimbraksa** [comment]
I marked this as **Low Priority** because I think  It's very unlikely the user would end up in that situation. And even if they do, it's pretty obvious that they should be logged in WordPress for the migration to work.

**Comment by dvdchr** [comment]
WordPress will bounce the user back to Jetpack regardless of the result when receiving the export intent from Jetpack. The logic of how that intent is handled is located here:

https://github.com/wordpress-mobile/WordPress-iOS/blob/c65dcb364f927e055934bee3bd621021bf68e020/WordPress/Classes/Utility/Universal%20Links/Migration/WordPressExportRoute.swift#L19-L33

Some thoughts:
- We can make WP not redirect when the export process fails, but it will be confusing when the error is due to unsynced local drafts. WP will sit at My Site (or the last tab the user was in) when this happens. We'd probably need to show a message of some sort.
- We can make WP not redirect only when the user is logged out. But currently, the export process isn't running after the user logs in, so we'd need to pass some intent or completion block that runs after all the post-login sync processes have been completed. 
  - Problem 1: The sync process is happening separately in each tab. They are currently not consolidated; there is no single point where we are sure everything has been synced. So we'll probably have to note what resources are downloaded post-login and make them broadcast an `NSNotification`. Finally, we'll have an object that subscribes to these notifications and accepts being subscribed by processes that want to run after all the post-login syncs are completed.
  - Problem 2: What happens when the sync process is ongoing? We'd need to show something that says "loading" to the user. For example, in p1670012281780969/1669952702.309569-slack-C046L7LPV0F Chris suggested that we show our splash screen while the export process is running (and that'll include the hypothetical sync.
  - Problem 3: What if the sync process fails? We'll probably need to show a message of some sort.

I'm probably overthinking things here 😅 , but let me know if you have simpler ideas to work around this issue! I'm also fine with letting this be for now since, as Salim said, this situation would be unlikely.

**Comment by twstokes** [comment]
This should be resolved by https://github.com/wordpress-mobile/WordPress-iOS/pull/19787.
