### ISSUE TITLE
Reader doesn't remove posts from unfollowed blogs

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-iOS#1982]
If a feed is unfollowed from the web app, it's cached posts remain in the iOS app.

[related Android issue here](https://github.com/wordpress-mobile/WordPress-Android/issues/1619)

**Comment by aerych** [comment]
I think the changes in #1976, plus how we're back filling content makes any lingering posts remaining after a sync less of an issue.  I'm also reluctant to add a special case just to clean up posts for the following feed.  Since the reader squad is still thinking about ways to improve reader content syncing, let's defer this until we come to a decision.

**Comment by kurzee** [comment]
Oldie, closing, can reopen if something changes on back end or we really feel like adding a special cleanup case.
