### ISSUE TITLE
Jetpack Activity Log: Private published posts can't be previewed

### ISSUE THREAD

**Issue by azollafox** [wordpress-mobile/WordPress-iOS#19856]
### Expected behavior
When I tap Activity Log> Post Modified> Post title for both public, private and draft posts a preview of the post should show

### Actual behavior
When I tap on the page title of a publicly published or draft post modification in the Activity Log entry it shows me a preview of the page. This does not work for a private page or post. I can even scroll down to when the post was a draft in the activity log and successfully open the preview.

### Steps to reproduce the behavior
1. Publish a private post
2. Find the "post modified" activity in the activity log and try to tap the post title.

**Comment by azollafox** [comment]
reported in 5815943-zen

**Comment by twstokes** [comment]
I couldn't get this view to appear for any of my sites and found that [this function is returning `false`](https://github.com/wordpress-mobile/WordPress-iOS/blob/546f9bc224c67a6b9825db8fc64b3a9cab541e41/WordPress/Classes/Utility/Universal%20Links/Routes%2BReader.swift#L147) because the values are incorrect:

```
(lldb) po values
▿ 5 elements
  ▿ 0 : 2 elements
    - key : "post_year"
    - value : "edit"
  ▿ 1 : 2 elements
    - key : "post_day"
    - value : "200489770"
  ▿ 2 : 2 elements
    - key : "post_name"
    - value : "275"
  ▿ 3 : 2 elements
    - key : "post_month"
    - value : "0"
  ▿ 4 : 2 elements
    - key : "matched-route-url"
    - value : "https://wordpress.com/edit/0/200489770/2053"
```

The previous expectation for a `.wpcomPost` was `/:post_year/:post_month/:post_day/:post_name` but the URLs I'm seeing are like `/edit/0/200489770/2053`. Setting this to medium because it looks like potentially there was a backend change that may affect more than just these previews.
