### ISSUE TITLE
Classic Block: Adding Images: App crashes when image permissions are not allowed

### ISSUE THREAD

**Issue by joashrajin** [wordpress-mobile/WordPress-iOS#19965]
### Expected behavior

A warning should be given that image permissions need to be set

### Actual behavior

The app crashes

### Steps to reproduce the behavior

- Ensure the JP/WP app has photo permissions set to None
- Try to edit a page which has a classic block on it, press the '+' button to add an image
- Notice the crash

Recording: 

https://user-images.githubusercontent.com/16253818/214021597-55d398ac-1027-4a47-be7d-9bc6bc3cea3e.MP4

**Comment by mokagio** [comment]
No PR has been linked to this issue, so I assume it hasn't been fixed yet or it hasn't been deemed urgent enough to address?

Anyways, I'll move the milestone to 21.8 because I'm about to start the 21.7 code freeze. Feel free to revert if necessary.

**Comment by mokagio** [comment]
I'll move the milestone to 21.9 because I'm about to start the 21.8 code freeze. Feel free to revert if necessary.

**Comment by mokagio** [comment]
I'll move the milestone to 22.0 because I'm about to start the 21.9 code freeze. Feel free to revert if necessary.

**Comment by mokagio** [comment]
I'll move the milestone to 22.1 because I'm about to start the 22.0 code freeze. Feel free to revert if necessary.

**Comment by mokagio** [comment]
I'll move the milestone to 22.2 because I'm about to start the 22.1 code freeze. Feel free to revert if necessary.

@salimbraksa @joashrajin any input on the impact and urgency of this crash? We've been pushing it to the next milestone for a number of releases. If it's low priority at the moment, maybe we should remove the milestone and track it someplace else. I see it's already part of a project, so it won't get forgotten even if we remove the milestone or move it to [Someday](https://github.com/wordpress-mobile/WordPress-iOS/milestone/14)

**Comment by mokagio** [comment]
I'll take the lack of reply to my [question](https://github.com/wordpress-mobile/WordPress-iOS/issues/19965#issuecomment-1493488954) two weeks ago as a yes on moving this to [Someday](https://github.com/wordpress-mobile/WordPress-iOS/milestone/14) instead of pushing it to the next milestone every release cycle.

**Comment by joashrajin** [comment]
@mokagio sorry for missing your ping. Yes, I don’t think this is a high priority issue
