### ISSUE TITLE
`WordPress.AuthenticationService.RequestAuthCookieError.wpcomCookieNotReturned`

### ISSUE THREAD

**Issue by mokagio** [wordpress-mobile/WordPress-iOS#19987]
**Sentry Url**: https://sentry.io/share/issue/e8265df05e8144e49c3b708e4ec39f57/
**User Count**: 3
**Count**: 18
**First Release**: 21.5.1.0
**First Seen**: 2023-01-24T08:02:18.290650Z
**Last Seen**: 2023-01-24T23:47:45Z
**24 Hours**: 18
**30 Days**: 18

```
WordPress.AuthenticationService.RequestAuthCookieError.wpcomCookieNotReturned
```

**Comment by irfano** [comment]
This should be related to https://github.com/wordpress-mobile/WordPress-iOS/issues/18556. The error is the same, but the reason could be different since the screen is different.

**Comment by staskus** [comment]
I agree, @irfano.

Yes, it looks related. There're many similar logs like this, but I'm not familiar with the actual issue. As I understand, it's not a crash, it's just logged as a crash.

@mokagio I'm removing a "Crash" label.

**Comment by guarani** [comment]
> This should be related to #18556.

I think you're right. I remember this issue, I added the logging in https://github.com/wordpress-mobile/WordPress-iOS/pull/14650 and looking at the Sentry stack trace it's calling the code from that PR:

| <img width="877" alt="Screenshot 2023-01-25 at 16 11 36" src="https://user-images.githubusercontent.com/1898325/214662358-9fc8f283-3fa7-4908-a250-9a34e01d65fb.png"> |
| - |

Which is this code:

https://github.com/wordpress-mobile/WordPress-iOS/blob/ab73d0f03289b2119226e6e18dde07a1dbedc1cd/WordPress/Classes/Services/AuthenticationService.swift#L101-L104

I'll go ahead and close this and make a PR to change the logging to use a message instead of an error as mentioned in https://github.com/wordpress-mobile/WordPress-iOS/issues/18556#issuecomment-1130691894.

**Comment by mokagio** [comment]
> 'll go ahead and close this and make a PR to change the logging to use a message instead of an error

For future reference: https://github.com/wordpress-mobile/WordPress-iOS/pull/19996

**Comment by mokagio** [comment]
Thanks @guarani !
