### ISSUE TITLE
Remove Zendesk library from WordPress target

### ISSUE THREAD

**Issue by staskus** [wordpress-mobile/WordPress-iOS#20110]
For the next milestone after the `wordpress_support_forum_remote_field` flag is enabled, we should remove Zendesk and all related classes from the WordPress variant and do not ship it with the WordPress app.

Android ticket: https://github.com/wordpress-mobile/WordPress-Android/issues/17931

**Comment by guarani** [comment]
We should make sure the WP app's acknowledgments don't show Zendesk anymore (this might happen naturally after removing it from the relevant target).

**Comment by sla8c** [comment]
@guarani @staskus I’ve tried a number of things but my local working copy is a mess and I don't have anything worth creating a draft for.  To summarise the main issue this isn't a simple task as there are `UIView` extensions that were taken advantage of all throughout the iOS codebase, and these extensions actually belong to the Zendesk libraries and unknowingly all these years the WordPress iOS developers have been using these Zendesk UIView extensions everywhere so it can have a very large impact on the app :disappointed:

Synopsis of what I did:
 * I moved the `ZendeskSupportSDK` pod dependency from `WordPress` target to the `Jetpack` target in the podfile
 * I removed `ZendeskUtils.swift` from `WordPress` target membership in the XCode project
 * I tried various approaches to fix compile errors and used compiler directives to see if I could wrap `#if JETPACK` around different issues when appropriate
 * I eventually stumbled upon the fact that UIView extensions like this one belong to `ZendeskCommonUISDK` pod `CommonUISDK.swift` more specifically this function: 
` @_Concurrency.MainActor public var safeBottomAnchor: NSLayoutYAxisAnchor { get } (line 1734)`

and this function is used in at least 11 files

I was thinking how to approach this next.  I think one possibility is to perhaps take a phase approach and change WordPress app's dependency from `ZenDeskSupportSDK` to `ZendeskCommonUISDK` as the first step and maybe the first PR

The second step and perhaps next PR would be to re-write extensions from `ZendeskCommonUISDK` and add them to the WordPress codebase; I think this is a 2nd PR because doing this would potentially cause conflicts with Jetpack's target which still uses `ZenDeskSupportSDK` and of course we can't see what this function is actually doing in `ZendeskCommonUISDK`

Just jotting my thoughts + notes for future!

**Comment by guarani** [comment]
> To summarise the main issue this isn't a simple task as there are `UIView` extensions that were taken advantage of all throughout the iOS codebase, and these extensions actually belong to the Zendesk libraries and unknowingly all these years the WordPress iOS developers have been using these Zendesk UIView extensions everywhere so it can have a very large impact on the app 😞

Wow! This is definitely a surprise 😆 This issue seems doesn't seem low effort despite having a low impact for the end user, so we could ship without it I think. Thanks for looking into this @sla8c!

**Comment by guarani** [comment]
I removed the `Support Forum` label to remove this from the scope of the forum project. I added the Zendesk label since this is more about Zendesk and less about the forum project.

**Comment by staskus** [comment]
Thanks @sla8c for the analysis! That is definitely unexpected!

> I was thinking how to approach this next. I think one possibility is to perhaps take a phase approach and change WordPress app's dependency from ZenDeskSupportSDK to ZendeskCommonUISDK as the first step and maybe the first PR

The second step and perhaps next PR would be to re-write extensions from ZendeskCommonUISDK and add them to the WordPress codebase; I think this is a 2nd PR because doing this would potentially cause conflicts with Jetpack's target which still uses ZenDeskSupportSDK and of course we can't see what this function is actually doing in ZendeskCommonUISDK

This plan makes sense to me. Doing it step by step will help avoid some regressions. We'll need to identify all the places the extensions are used and make sure it continues behaving the same way. 👍

**Comment by irfano** [comment]
After [deciding to show Zendesk to some users on WP](https://github.com/wordpress-mobile/WordPress-iOS/issues/20154), this issue is no longer necessary.
However, the comments here will be very helpful if we decide to remove the library in the future. Thank you for your investigation, @sla8c! 
I believe we can now close this issue.

---
**Update:** The decision to use Zendesk has changed. It's [decided](https://github.com/wordpress-mobile/WordPress-iOS/issues/20240) not to use Zendesk on WordPress.
