### ISSUE TITLE
Jetpack app doesn't load WordPress.com post if WordPress app is installed

### ISSUE THREAD

**Issue by twstokes** [wordpress-mobile/WordPress-iOS#20293]
### Expected behavior
Posts are loaded in Jetpack if the WordPress app is installed.

### Actual behavior
Posts aren't loaded in Jetpack if the WordPress is installed.

https://user-images.githubusercontent.com/2092798/224146846-fd4f6419-0c82-40e8-9e97-a6bcd9e21e77.mp4

### Steps to reproduce the behavior
1. Install the WordPress app (version may matter, but I used 21.9)
2. Install Jetpack 21.8
3. In Safari, load this URL: https://twstokes.wordpress.com/2023/03/09/here-is-a-post/
4. Expect to see a banner at the top prompting to "Open in the Jetpack app"
5. Tap "OPEN" on the banner
6. Observe that the post isn't loaded in the Jetpack app
7. Uninstall the WordPress app
8. Repeat steps 3 - 5
9. Observe that the post is loaded in the Jetpack app

**Comment by fluiddot** [comment]
That's interesting, based on the [Universal links configuration](https://wordpress.com/.well-known/apple-app-site-association), the Jetpack app should be prioritized when opening a WPCOM link 🤔. I checked the [Apple documentation](https://developer.apple.com/library/archive/documentation/General/Conceptual/AppSearch/UniversalLinks.html) and having the Jetpack app in the first positions should work:
> Because the system evaluates each path in the paths array in the order it is specified—and stops evaluating when a positive or negative match is found—you should specify high priority paths before low priority paths. Note that only the path component of the URL is used for comparison. Other components, such as the query string or fragment identifier, are ignored.

**Comment by dvdchr** [comment]
👋🏼 @fluiddot. Previously, there was an infinite redirection problem between WP and JP due to the app bouncing the link to Safari if it couldn't process the link > the counterpart app catches the intent > does the same thing, and bounces the link again. 

To fix this, I tried to disable the "bounce" logic when both apps are installed, but an implementation bug led to this issue 😅. The universal link actually works and opens the Jetpack app first, but due to the bug, the app didn't deeplink into the feature. This has now been addressed in #20304.

On that note, since #20304 is now merged to `release/21.8.2`, I'm closing this issue for now. 🙂
