### ISSUE TITLE
Crash when logging in

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#20592]
### Expected behavior

The app shouldn't crash when logging in.

### Actual behavior

The app crashes when logging in with one of my WP.com accounts (not all of them).

### Steps to reproduce the behavior

1. Log in with the affected account
2. The account has SMS-based 2FA, so enter the code when it arrives
3. Notice the app crash

> **Note**: I ran into this on while testing https://github.com/wordpress-mobile/WordPress-iOS/pull/20589 but couldn't reproduce this on `trunk`.

### Additional info

Here's a screenshot of the crash stacktrace:
<img width="1000" alt="Screenshot 2023-04-24 at 16 01 21" src="https://user-images.githubusercontent.com/1898325/234107813-840a99d8-5c0c-4f19-8a5f-6b80a998647f.png">

**Comment by staskus** [comment]
The issue can be reproduced on `trunk` and is related to the implementation of `BlogDashboardPersonalizationService` 
<img width="933" alt="image" src="https://user-images.githubusercontent.com/4062343/234272187-156b1223-2c00-42c5-b4ac-4cce761b724a.png">

As I understand, the crash happens we try to access the `CoreData` value from another context. We call `updatePromptSettingsFor:blog` within the `performAndSaveUsingBlock` which requires to access the blog indirectly using `context existingObjectWithID:blogObjectID`.

However, in `updatePromptSettingsIfNecessary` of `BloggingPromptSettings` we call `BlogDashboardPersonalizationService.setEnabled(enabled, for: .prompts)`, which ends up in `BlogDashboardService fetchLocal` which accesses `blog.dotComID`.

The crash only happens sometimes since `updatePromptSettingsIfNecessary` has an if condition. I noticed that the issue is reproducible when I join a new P2, and then we log into the account. In this instance `service.hasPreference` is `false` and the crash happens.

```
    private func updatePromptSettingsIfNecessary(siteID: Int, enabled: Bool) {
        let service = BlogDashboardPersonalizationService(siteID: siteID)
        if !service.hasPreference(for: .prompts) {
            service.setEnabled(enabled, for: .prompts)
        }
   }
```

### Steps to reproduce:

1. On the web, add a new site into account (join a P2)
2. Open Jetpack account
3. Log into the same account
4. Notice a crash happening
5. You can confirm in the debug console that the crash happens for the blog that was just added

CC: @guarani 

### Solution

1. First, implement a quick fix: immediately disable `service.setEnabled` functionality based on `personalizeHomeTab` feature flag
2. Then, fix an issue by correctly accessing the `blog` and/or by having a different approach for updating these settings

**Comment by staskus** [comment]
The issue can be reproduced on `trunk` and is related to the implementation of `BlogDashboardPersonalizationService` 
<img width="933" alt="image" src="https://user-images.githubusercontent.com/4062343/234272187-156b1223-2c00-42c5-b4ac-4cce761b724a.png">

As I understand, the crash happens we try to access the `CoreData` value from another context. We call `updatePromptSettingsFor:blog` within the `performAndSaveUsingBlock` which requires to access the blog indirectly using `context existingObjectWithID:blogObjectID`.

However, in `updatePromptSettingsIfNecessary` of `BloggingPromptSettings` we call `BlogDashboardPersonalizationService.setEnabled(enabled, for: .prompts)`, which ends up in `BlogDashboardService fetchLocal` which accesses `blog.dotComID`.

The crash only happens sometimes since `updatePromptSettingsIfNecessary` has an if condition. I noticed that the issue is reproducible when I join a new P2, and then we log into the account. In this instance `service.hasPreference` is `false` and the crash happens.

```
    private func updatePromptSettingsIfNecessary(siteID: Int, enabled: Bool) {
        let service = BlogDashboardPersonalizationService(siteID: siteID)
        if !service.hasPreference(for: .prompts) {
            service.setEnabled(enabled, for: .prompts)
        }
   }
```

### Steps to reproduce:

1. On the web, add a new site into account (join a P2)
2. Open Jetpack account
3. Log into the same account
4. Notice a crash happening
5. You can confirm in the debug console that the crash happens for the blog that was just added

CC: @guarani 

### Solution

1. First, implement a quick-fix: immediately disable this functionality based on `personalizeHomeTab` feature flag
2. Then, implement a proper fix by correctly accessing the core data value or approaching `updatePromptSettingsIfNecessary` in a different way

**Comment by guarani** [comment]
Thanks for the investigation, @staskus! 

> You can confirm in the debug console that the crash happens for the blog that was just added

Indeed I can reproduce on `trunk` only after getting added as an editor to a P2. I don't understand yet why after adding myself to a P2 and doing a clean install, it crashes, but after doing another clean install it no longer crashes. The clue might be in your PR for this issue which I haven't reviewed yet.

I'll go back to reviewing https://github.com/wordpress-mobile/WordPress-iOS/pull/20589 first and then come back here.

**Comment by staskus** [comment]
@guarani 

> I don't understand yet why after adding myself to a P2 and doing a clean install, it crashes, but after doing another clean install, it no longer crashes

Yes, it's an interesting case. It can only crash when `BlogDashboardViewModel` is initialized and has registered for for `.blogDashboardPersonalizationSettingsChanged` notification. When we add a new P2, it looks like some of the syncing finishes after the `BlogDashboardViewModel` is initialized, causing it to observe the notification, and call `loadCardsFromCache` from a background thread. I haven't tracked down myself why and how the synchronization process differs if we're added to a new P2.
