### ISSUE TITLE
Clicking on Paragraph Block Settings Does Not Show Settings

### ISSUE THREAD

**Issue by igotdes** [wordpress-mobile/WordPress-iOS#20618]
### Expected behavior

After clicking Settings (gear icon) on a Paragraph block, the block's settings should come up.

### Actual behavior

The Paragraph block's settings aren't appearing.

https://user-images.githubusercontent.com/74066241/235048303-10d48bbc-9335-4822-8478-b5b92f291261.mov

### Steps to reproduce the behavior

1. Click on Settings (gear icon) on a Paragraph block
2. No settings appear

##### Tested on iPhone SE 2022, iOS 16.4.1, Jetpack iOS / WordPress iOS 22.2

- First reported on an iPad using Jetpack iOS 22.1 (#6231774-zen)

### Additional Information

- Settings for other blocks don't appear to have the same issue
- Tested previous versions of the app, and until version 22.0.1.0, the Paragraph block settings still appear

**Comment by igotdes** [comment]
Also reported in #6235202-zen:

- iPad 10.5 Pro and on iPhone 12 Pro Max
- 22.1

**Comment by geriux** [comment]
Hey there 👋 there was a regression in the latest release related to the Text and Background color settings which was [already addressed](https://github.com/WordPress/gutenberg/pull/49917) and it will ship to users in the next version `22.2` which should start rolling out on May 1st.

As for other settings not showing up (in the example video) like Font size and line height, those settings are only available for block-based themes and users with the Gutenberg plugin activated.

Once the Text and Background color fix ships, the Bottom sheet won't show up empty anymore since those are the default settings that are always available.

Let us know if you have any questions! Thanks!

**Comment by igotdes** [comment]
Thanks for quickly looking into this, @geriux! I switched my test site to using the Twenty Twenty-Three theme and went back to version 22.1 of the app, and I can confirm that the bottom sheet is no longer empty after clicking settings for a Paragraph block.
