### ISSUE TITLE
Update tracks events

### ISSUE THREAD

**Issue by ovitrif** [wordpress-mobile/WordPress-iOS#20652]
Task to make sure the following events are tracked when creating new sites with paid domains:

```py
# 🔵 Tracked: enhanced_site_creation_accessed, Properties: {"source":"my_site"}
🔵 Tracked: enhanced_site_creation_domain_purchasing_experiment, Properties: {"variation":"control"}
…
# 🔵 Tracked: enhanced_site_creation_domains_accessed
🔵 Tracked: enhanced_site_creation_domains_selected, Properties: {"chosen_domain":"*.*","search_term":"*","domain_cost":"*"}
…
# 🔵 Tracked: site_created
🔵 Tracked: domains_purchase_webview_viewed, Properties: {"origin":"site_creation"}
# 🔵 Tracked: webview_displayed
🔵 Tracked: domains_purchase_domain_success, Properties: {"origin":"site_creation"}
…
# 🔵 Tracked: enhanced_site_creation_preview_ok_button_tapped
```

Note: the commented out events (ie. starting with `#`) are not relevant and shouldn't require changes.

**Comment by ovitrif** [comment]
For reference check the Android PR:
- https://github.com/wordpress-mobile/WordPress-Android/pull/18390

**Comment by mokagio** [comment]
I'm going to bump this and the [associate PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/20663) to milestone 22.5 because the work hasn't been approved yet and my understanding is that this is still part of a work-in-progress feature, so it doesn't need to be part of a release build just yet.

Feel free to revert if I missed something. Thanks.

**Comment by ovitrif** [comment]
This task is done, implementation was merged with this PR:
- #20663
