### ISSUE TITLE
Plans on JP: Update UI tests

### ISSUE THREAD

**Issue by staskus** [wordpress-mobile/WordPress-iOS#20720]

**Comment by guarani** [comment]
Closing this because I think https://github.com/wordpress-mobile/WordPress-iOS/pull/20728 solved this issue and we're tracking the update needed to get UI tests to reach the result screen in https://github.com/wordpress-mobile/WordPress-iOS/issues/20790.

Please feel free to re-open if needed @staskus 🙇
