### ISSUE TITLE
Core Data: crash triggered from `NullBlogPropertySanitizer`

### ISSUE THREAD

**Issue by iangmaia** [wordpress-mobile/WordPress-iOS#20847]
### Steps to reproduce the behavior

This was a crash found via Xcode's Organiser. It has a similar stack trace as https://github.com/wordpress-mobile/WordPress-iOS/issues/20840, just with `NullBlogPropertySanitizer.sanitize()` being part of the call stack.

Organiser backtrace:
![Screenshot 2023-06-13 at 10 45 19](https://github.com/wordpress-mobile/WordPress-iOS/assets/2152244/1a446469-9eaa-40ff-9c38-96881bad82bf)

Pointing to code:
![Screenshot 2023-06-13 at 10 44 12](https://github.com/wordpress-mobile/WordPress-iOS/assets/2152244/81d48c76-a6cc-4c4a-815d-48ff3e7dff65)

**Comment by crazytonyli** [comment]
Great find!

The app [fires an event](https://github.com/wordpress-mobile/WordPress-iOS/blob/e4db21b30a9fa50809d26493b670e7b39b9fabbe/WordPress/Classes/Services/NullBlogPropertySanitizer.swift#L52) after the "sanitization" is completed. I searched this event in Tracks, and there are only a handful each day. I also searched if this event was sent from Matt's device, and didn't find any. So I think this may not be one of Matt's crashes.

However, the stacktrace is interesting. It shows the "sanitization" work was done asynchronously from [its only call site the `ContextManager` initialiser](https://github.com/wordpress-mobile/WordPress-iOS/blob/e4db21b30a9fa50809d26493b670e7b39b9fabbe/WordPress/Classes/Utility/ContextManager.swift#L96).

Just by looking at the `ContextManager`'s initialiser and [the documentation around the sanitization code's intention](https://github.com/wordpress-mobile/WordPress-iOS/blob/e4db21b30a9fa50809d26493b670e7b39b9fabbe/WordPress/Classes/Services/NullBlogPropertySanitizer.swift#L3), I think it's best to make sure the sanitization work is done before any other Core Data query, otherwise other parts of the app _may_ (probably not likely) see an unexpected null blog property.

**Comment by iangmaia** [comment]
Good points, @crazytonyli!

> I also searched if this event was sent from Matt's device, and didn't find any. So I think this may not be one of Matt's crashes.

Depending on when and how often the crash happens, it could be that any event call doesn't get the chance to be sent to any server and is just scheduled (likely also persisted) to be sent later 🤔 but indeed, this isn't necessarily [that crash](https://github.com/wordpress-mobile/WordPress-iOS/issues/20840).

**Comment by crazytonyli** [comment]
@iangmaia Do you think we can mark this issue a duplication of https://github.com/wordpress-mobile/WordPress-iOS/issues/20840? My gut feeling is the root cause is corrupted Core Data models, and the `sanitize` function happened to lead to a crash due to the corruption, but it's not necessarily the cause.

**Comment by iangmaia** [comment]
> @iangmaia Do you think we can mark this issue a duplication of #20840? My gut feeling is the root cause is corrupted Core Data models, and the `sanitize` function happened to lead to a crash due to the corruption, but it's not necessarily the cause.

Yes, I agree it's not necessarily the cause. I think it is hard to be 100% certain here, I wouldn't mark it as duplicate of #20840. The stack trace is almost identical, but #20840 might also have different causes (data corruption / fault in multi-threaded data changes).
