### ISSUE TITLE
Plans on JP: Dashboard card is not listed under 'Personalize your home tab'

### ISSUE THREAD

**Issue by tiagomar** [wordpress-mobile/WordPress-iOS#20931]
### Expected behavior
Once the card is hidden, the user should be able to add it back.

### Actual behavior
Once the card is hidden, the user has no way to add it back.

<img width="200" alt="image" src="https://github.com/wordpress-mobile/WordPress-iOS/assets/42008628/9eca5def-b096-4f2e-9041-3ac3f6a894ca">

### Steps to reproduce the behavior
1. Select proper site and user so the card is displayed.
2. Tap `Personalize your home tab`
3. ❌ Notice the card is not listed.

**Comment by guarani** [comment]
👋 Thanks for catching this, @tiagomar! ❤️ 
I think we could fix this on `trunk` and target 22.7 (which is cut Monday) because unhiding a card seems like an infrequent use case. I agree with the Medium priority here.

**Comment by ravishanker** [comment]
This card is an advertisement, unlike other cards on personalization tab that are task related. It doesn’t need to be there at all. Don’t expect users to unhide it either.

**Comment by guarani** [comment]
Fair point @ravishanker. 
Do you have any objections to closing this @tiagomar?

**Comment by staskus** [comment]
@guarani, @ravishanker 

Let's leave it for the next sprint to make a decision.

@ravishanker has a point that this card serves more as a removable advertisement rather than a helper card. With the current implementation of `Personalize Home Tab` picker, the `Plans` option would always appear, regardless of site being eligible to purchase plans or not. If we had a multiple combination of different type of "ad" cards that would be shown in different circumstances, it wouldn't make sense to list them all as an option in `Personalize Home Tab` picker. It's a very different case from `Today's stats` or `Blogging prompts`.

**Comment by kean** [comment]
Agree on the above – closing.
