### ISSUE TITLE
Stats: Data shown for incorrect period after navigating back and returning

### ISSUE THREAD

**Issue by staskus** [wordpress-mobile/WordPress-iOS#21099]
For example, Insights tab can sometimes show the data for a year period, while the Year tab can show data for a week period until reloaded.

### Steps to reproduce the behavior

https://github.com/wordpress-mobile/WordPress-iOS/assets/4062343/9e8ba34e-1d8d-4bb5-8548-95101d9e6ec4

**Comment by kean** [comment]
The changes made in [#21067](https://github.com/wordpress-mobile/WordPress-iOS/pull/21067), which is (going to be) the most recent change to the stats, do not affect the issue. The issues reproduces both before and after the changes.

**RCA**

- When you open the screen, `StatsPeriodStore` starts with a `.period` query with a period `.month`
- Change the period unit to `.year`
- Open any details screen; the screen adds another active query to the store
- Close the details screen
- The newly added query to removed, and the `processQueries` on `StatsPeriodStore` is called again, but it's called with the same query that it was initialized with (with a period `.month` and not with `.year` as expected)

**Comment by staskus** [comment]
**Bonus**

After switching between a period (month) and insights tab, then it's enough to keep tapping "Insights" for the issue to be continuously reproduced.

https://github.com/wordpress-mobile/WordPress-iOS/assets/4062343/f7193c4d-ea9b-4cd0-bcf3-9fd6a1bd91be

**Comment by staskus** [comment]
> The newly added query to removed, and the processQueries on StatsPeriodStore is called again, but it's called with the same query that it was initialized with (with a period .month and not with .year as expected)

`StatsPeriodStore` iterated through `activeQueries`. `activeQueries` contain a list of queries whose receipts are retained. My hypothesis is that receipts are retained by both `insights` and `period` tabs, creating this issue. I haven't checked the hypothesis yet.

**Comment by jostnes** [comment]
It seems like this issue is more easily reproducible when using `xcode-15.1` (PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/22270) as seen in the `testYearsStatsLoadProperly() in StatsTests` UI test failing every other time because it did not load the correct data (example builds: [1](https://buildkite.com/automattic/wpios-macv2-test/builds/31), [2](https://buildkite.com/automattic/wpios-macv2-test/builds/33), [3](https://buildkite.com/automattic/wpios-macv2-test/builds/32))

I was also able to reproduce this on a real device (though not as easy to reproduce), seen below on the `Years` tab where different data is displayed for the same account:

Incorrect stats:
<img src="https://github.com/wordpress-mobile/WordPress-iOS/assets/17252150/3d85ad0c-429c-4258-855f-51e37def24d2" width="50%" height="50%" />

Correct stats:
<img src="https://github.com/wordpress-mobile/WordPress-iOS/assets/17252150/b86f3408-65cb-4c1e-b4b8-eb2bde1f91f5" width="50%" height="50%" />

**Comment by staskus** [comment]
@guarani 

I'm doing thorough testing of the Traffic tab (https://github.com/wordpress-mobile/jetpack-issue-repo/issues/12) and I can confirm that this is not resolved. As correctly pointed out (https://github.com/wordpress-mobile/WordPress-iOS/issues/21099#issuecomment-1635122443), it's related to issues with Store queries. The issue is fairly easy to reproduce with a new Traffic tab, I plan to fix it as soon as possible.

Example repro steps:

1. Open Stats
2. Open Insights
3. Confirm the data is displayed as expected
4. Open Traffic
5. Switch to By Year -> By Month -> By Year
6. Exit Stats
7. Open Stats
8. Open Insights
9. Incorrect data is loaded

**Comment by guarani** [comment]
Thanks for checking! I can also reproduce. 

> The issue is fairly easy to reproduce with a new Traffic tab, I plan to fix it as soon as possible.

This is an existing bug and it doesn't affect the Traffic tab, so leaving it outside the Traffic tab project makes sense. If you'd like to tackle it this week, I still think it makes sense to leave it off the Traffic tab project board.

**Comment by staskus** [comment]
> If you'd like to tackle it this week, I still think it makes sense to leave it off the Traffic tab project board.

You're right. Let's leave it outside the project scope. I'll do it only if everything else is finished.

**Comment by staskus** [comment]
Unfortunately, it looks like this issue affects the Traffic tab as well:

https://github.com/wordpress-mobile/WordPress-iOS/assets/4062343/0d64f5f5-34b6-4b53-a010-ba93fdcf8ec2

I will try to make a fix today, it would be good to get it into 24.4
