### ISSUE TITLE
Me – Handle the no-sites scenarios in Jetpack

### ISSUE THREAD

**Issue by kean** [wordpress-mobile/WordPress-iOS#21272]
TBD

**Comment by momo-ozawa** [comment]
Hey @kean, we still show the bottom tab on JPiOS after tapping "Not right now" 

https://github.com/wordpress-mobile/WordPress-iOS/assets/6711616/57803b5b-b73c-4996-b501-8b06168bc42b

**Comment by kean** [comment]
Yeah, it seems like a defect me and Annmarie also discovered when testing these flows earlier this week. It sometimes shows the tabs; sometimes, it doesn't. Sometimes it pre-selects the Reader; sometimes it doesn't.

**Comment by momo-ozawa** [comment]
Oh! I didn't realize that was happening for JPiOS. I've come across the same issue on WPiOS though.

**Comment by momo-ozawa** [comment]
> Yeah, it seems like a defect me and Annmarie also discovered when testing these flows earlier this week. It sometimes shows the tabs; sometimes, it doesn't. 

@kean @zwarm I haven't been able to reproduce this on JPiOS - can you? 

AFAIU the correct behavior would be to show the bottom tabs after tapping "Not right now". What do you think?

**Comment by zwarm** [comment]
> AFAIU the correct behavior would be to show the bottom tabs after tapping "Not right now". What do you think?

I'm not entirely sure, Android isn't showing bottom tabs, but maybe it is and I just haven't hit upon the correct scenario. Let's ask @osullivanchris what his thoughts are.

**Comment by osullivanchris** [comment]
I was saying in other threads that I think its good to show the bottom tabs to people without a site. In fact it came up in our review with Pablo yesterday - why not let people start with consumption (reader) and create things later if they want to. Its not a great experience today but its valid in theory.

Let me check I understand the flow here
- login with an account with no site
- full screen is shown suggesting adding a site (and this is the screen we've been talking about redesigning)
- if I tap not now I go through to the app with tabs, reader selected
- What happens if I tap My Site? Do I see step 2 again?

**Comment by momo-ozawa** [comment]
Hey @osullivanchris 

> What happens if I tap My Site? Do I see step 2 again?

Nope - you see a different variant of an empty My Site screen

Post-login | Post-"not right now"
-- | --
<img src="https://github.com/wordpress-mobile/WordPress-iOS/assets/6711616/2a139937-0c25-4fe5-aa49-ded63bb015a6" width=200> | <img src="https://github.com/wordpress-mobile/WordPress-iOS/assets/6711616/e2b330a1-a55a-4057-858c-2cc0f4c24475" width=200>

> I was saying in other threads that I think its good to show the bottom tabs to people without a site.

Sounds good! It sounds like Android isn't doing this currently; I'll create a task on the Android board

I want to clarify that I think the post-"not right now" behavior should be different between JP and WP
- JP: Show bottom tabs
- WP: Hide bottom tabs since tabs are going away eventually, but show a Me entry point somewhere on the empty sites screen so the user can log out

**Comment by momo-ozawa** [comment]
Also, @kean @zwarm - can you share the condition to repro the issue you mentioned with tabs sometimes being hidden? I still haven't been able to repro on JPiOS.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
