### ISSUE TITLE
EXC_BREAKPOINT: initWithBlog: > release

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#21407]
**Sentry Url**: https://sentry.io/share/issue/675510a26e4c446c81647777a471ada9/
**User Count**: 41
**Count**: 56
**First Release**: 22.8.0.3
**First Seen**: 2023-07-24T07:58:36Z
**Last Seen**: 2023-08-23T23:28:55Z
**24 Hours**: 3
**30 Days**: 56
**LogID:** 0B5570D0-8593-4EB5-AB44-A79B0ED83DD1

```
EXC_BREAKPOINT: initWithBlog: > release
  File "<compiler-generated>", line null, in failure
  File "WordPressOrgRestApi+WordPress.swift", line 32, in apiBase
  File "<compiler-generated>", line null, in apiBase
  File "WordPressOrgRestApi+WordPress.swift", line 38, in WordPressOrgRestApi.init
  File "<compiler-generated>", line null, in WordPressOrgRestApi.init
  File "Blog.m", line 889, in -[Blog wordPressOrgRestApi]
  File "BlockEditorSettingsService.swift", line 30, in BlockEditorSettingsService.__allocating_init
  File "<compiler-generated>", line null, in BlockEditorSettingsService.__allocating_init
  File "<compiler-generated>", line 24, in BlockEditorSettingsService.__allocating_init
  File "PageListViewController.swift", line 70, in PageListViewController.editorSettingsService.getter
  File "PageListViewController.swift", line 69, in PageListViewController.editorSettingsService.getter
  File "PageListViewController.swift", line 259, in PageListViewController.fetchEditorSettings
...
(1 additional frame(s) were not displayed)
```

**Comment by guarani** [comment]
👋 @SiobhyB, I came across this crash today. It's got three crashes in `23.0` and relates to the page list or the Gutenberg editor. 
While this is a Sentry issue for the JP project, there are a couple of separate WP Sentry issues (although they don't have any events in 23.0): https://a8c.sentry.io/issues/?query=is%3Aunresolved+message%3A%22initWithBlog%3A+%3E+release%22&referrer=issue-list&statsPeriod=14d

**Comment by guarani** [comment]
I went ahead and assigned you here (I wasn't sure who else to assign while following the crash triage guidelines PCYsg-vRg-p2. Please let me know if there's a better way to approach these issues. I also assigned you to the Sentry issue for JP so that it's easy to see that someone is looking at this issue.

**Comment by guarani** [comment]
👋 @geriux, looping you in here since I see you're also on the crash-fixing effort and @SiobhyB is out of the office. Do you know what's needed to triage this?

**Comment by geriux** [comment]
> 👋 @geriux, looping you in here since I see you're also on the crash-fixing effort and @SiobhyB is out of the office. Do you know what's needed to triage this?

Hey there! I took a quick look but I haven't been able to find the culprit. From what I've seen from a quick search, it looks like it's happening within the `BlockEditorSettingsService` which handles getting the site's theme data and other settings from Gutenberg. 

In `22.8` these events started to be reported. With this version, [we introduced some changes ](https://github.com/wordpress-mobile/WordPress-iOS/pull/21029)related to `GutenbergSettings`  I wonder if it's related. cc @crazytonyli do you think it might be related?

**Comment by crazytonyli** [comment]
My gut feeling is the `GutenbergSettings` changes are not related to this issue. This issue appears to be: the `apiBase` function (called by [this code](https://github.com/wordpress-mobile/WordPress-iOS/blob/trunk/WordPress/Classes/Services/BlockEditorSettingsService.swift#L26-L34)) doesn't expect it to be called with a WordPress.com blog. I'm not familiar with Gutenberg, do you know in what ways would this issue be caused by failing to change gutenberg settings?

@guarani do you remmeber how this crash occurred? Upon launch, resume from the background, or tapping some button?

**Comment by guarani** [comment]
Hey folks! Thanks for taking a look.

> @guarani do you remmeber how this crash occurred? Upon launch, resume from the background, or tapping some button?

I didn't experience this crash, I created this GitHub issue from a Sentry issue while crash monitoring for JP 23.1.

**Comment by crazytonyli** [comment]
I think I may have found the cause (at least one potential cause) of this crash. Let me know if you can reproduce this crash following these steps:
1. Pull the latest trunk code. This is important, because I recently worked on a related issue: https://github.com/wordpress-mobile/WordPress-iOS/pull/21375 and we need the changes in that PR here.
2. Build and run the app from Xcode.
3. Sign in using a WordPress.com account from the app.
4. On your computer, open wordpress.com, sign in using the same user.
5. Still on your computer, go to [the Connected Applications webpage](https://wordpress.com/me/security/connected-applications) and disconnect "WordPress for iOS" app.
6. Back to the app, you may see a Sign In screen keeps showing up. IMPORTANT: Ignore them by click the "Cancel" button.
7. Navigate to the pages list (i.e. My Site -> Menu -> Pages), and you should see this exact crash at the `apiBase` function in your Xcode.

-----

What happened in the steps above are [the logged in account's `authToken` was set to nil when it becomes invalid](https://github.com/wordpress-mobile/WordPress-iOS/blob/12582f7d21051961ee43c9693961c0f4ad51fc33/WordPress/Classes/Models/WPAccount.m#L173). When the `authToken` is nil, you [can not create a `wordPressComRestApi` from `WPAccount`](https://github.com/wordpress-mobile/WordPress-iOS/blob/12582f7d21051961ee43c9693961c0f4ad51fc33/WordPress/Classes/Models/WPAccount.m#L167). That means [this `BlockEditorSettingsService` code](https://github.com/wordpress-mobile/WordPress-iOS/blob/12582f7d21051961ee43c9693961c0f4ad51fc33/WordPress/Classes/Services/BlockEditorSettingsService.swift#L26-L34) would go to the `blog.wordPressOrgRestApi` branch which causes the precondition in `apiBase` function to fail and crash.

If that is indeed the cause of this crash, I'm curious what the cutsomers did that causes the token becoming invalid. IMO, disconnecting the app from the "Connected Applications" webpage is unlikely something customers would do.

**Comment by crazytonyli** [comment]
BTW, I saw some authentication related logs from [this crash](https://a8c.sentry.io/issues/4352026163/events/ef4f8d179d204d53ab55f07d87f277de/?project=5716771)'s app log (id: 0B5570D0-8593-4EB5-AB44-A79B0ED83DD1, which you can view using the encrypted log tool on MC):

> Error Domain=WordPressKit.WordPressComRestApiError Code=2 "An active access token must be used to query information about the current user."
> ...
> Feature announcements error: unable to fetch remote announcements - Response status code was unacceptable: 401.

So, the customer may have an invalid token in their app.

**Comment by guarani** [comment]
> Let me know if you can reproduce this crash following these steps:

I can reproduce this. Nice find, @crazytonyli! 💯 The stack trace does look like the one from this issue. While we're not certain how the user invalidated their token, it looks like we have a way to trigger the crash.

@geriux, do you have any thoughts on this? It looks like this is related to `fetchEditorSettings` in `PageListViewController`, which looks to be part of the site editor. 

I'm going to assign this to you @geriux and remove the `Requires Triage` label, since the crash triage process calls for me to assign someone, but please let me know if there's a better way for me to handle this 🙇

**Comment by guarani** [comment]
Added my take on priority due to 8 occurrences in 23.0 and the understanding that it's rare for users to have an invalid access token: Low priority 

Please feel free to adjust if needed 👍

**Comment by geriux** [comment]
> @geriux, do you have any thoughts on this? It looks like this is related to `fetchEditorSettings` in `PageListViewController`, which looks to be part of the site editor.

We recently added the functionality to open the Site editor through a WebView and now we fetch those settings when accessing the Page List, maybe we'd need to consider something else in the logic there? 

I didn't work on the implementation as it involves the native side of the app, but maybe @wargcm has some thoughts about it?

**Comment by wargcm** [comment]
It just appears to be a downstream call from initializing the service, so there isn't much we can do in the view controller.

All the calls in that chain are nullable, so I'm not certain why there's a `precondition` there rather than a `guard` in that function. I can create a PR that switches it to a `guard`.

**Comment by crazytonyli** [comment]
I don't intend to diverge the conversation. But, I feel like there is a bigger issue here. When auth token becomes invalid, the app presents a sign in form so that we can re-authenticate and get a valid auth token. However, user can dismiss the sign in form (see step 6 in https://github.com/wordpress-mobile/WordPress-iOS/issues/21407#issuecomment-1692640168) and continues to use the app without a valid auth token. Should we even allow that? IMO, in this scenario, we should only offer two path forward: sign in or sign out.

**Comment by wargcm** [comment]
@crazytonyli It might be done this way to allow users access to their self-hosted sites still? This is just a guess though. We can probably still handle it better than what we're currently doing.
