### ISSUE TITLE
Teach DTCoreText's layouter how to wrap text around an image. 

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#2202]
DTCoreText doesn't currently support wrapping text around an image.  @Cocoanetics has apparently attempted this in the past without success. https://github.com/Cocoanetics/DTCoreText/issues/438

Let's see if we have any luck.

**Comment by S2V** [comment]
@astralbodies, pls add commit reference, or link where I can see your implementation.

**Comment by astralbodies** [comment]
@s2v I'll see if I can find the implementation, but it's simple when you're using an image inside of a text attachment and then set the paragraph styles appropriately.

**Comment by S2V** [comment]
@astralbodies , yeap, I understand. For example as described here : http://www.raywenderlich.com/50151/text-kit-tutorial? But I am interested in your implementation in the context WEB -> NATIVE IOS.

**Comment by astralbodies** [comment]
It looks like the visual editor branch got whacked. I'll see if I can find another pointer to it somewhere and repush. I never got to start the HTML -> attributed string conversion implementation other than using the basic implementation Apple provided in iOS 7. We ended up stopping because the support for bulleted and numbered lists wasn't available and I don't think it is yet in iOS 8.

**Comment by aerych** [comment]
Closing. Our expectation is to eventually replace DT with a TextKit solution.
