### ISSUE TITLE
Lists confused when switching between usernames

### ISSUE THREAD

**Issue by andrealeebishop** [wordpress-mobile/WordPress-iOS#2222]
If I am logged in as myusername (2fa, app specific password), go to Settings and sign out, then sign in as mytestusername (no 2fa, no app specific password) it will show me my the settings from the other account including: added sites, blogs followed, tags followed.

**Comment by rachelmcr** [comment]
I tested this in the latest 5.8 beta and can no longer reproduce the issue. Logging out of a WordPress.com account and logging in with a different account shows me the correct sites, blogs followed, tags followed, etc. Any self-hosted sites I've added remain in the app, but that is expected behavior. Closing as resolved.
