### ISSUE TITLE
[iOS] Connect plans card on site domain to upgrade flow

### ISSUE THREAD

**Issue by ravishanker** [wordpress-mobile/WordPress-iOS#22244]
Connect plans card on site domain to upgrade flow same as dashboard card flow
- hook up **Upgrade to a plan** button to dashboard card flow
- Update title of `Search for a domain` to  **Just search for a domain** 
- Update to latest designs

**Comment by mokagio** [comment]
I'm going to bump this to the next release because we'll be code freezing [24.0](https://github.com/wordpress-mobile/WordPress-iOS/milestone/265) today and this hasn't been reviewed yet.

If these changes cannot wait two weeks and it's important that it makes it into this release, let me know and we'll organize a new beta once ready.

**Comment by mokagio** [comment]
I'm going to bump this to the next release because we'll be code freezing [24.1](https://github.com/wordpress-mobile/WordPress-iOS/milestone/267) today and this hasn't been reviewed yet.

If these changes cannot wait two weeks and it's important that it makes it into this release, let me know and we'll organize a new beta once ready.

**Comment by staskus** [comment]
Closing this issue, the changes were done in another task.
