### ISSUE TITLE
[iOS] Add tracking to plans card on site domain

### ISSUE THREAD

**Issue by ravishanker** [wordpress-mobile/WordPress-iOS#22245]
- Tag plans card on site domain with tracking
- Update RELEASE_NOTES

For e.g.
"domains_dashboard_get_plan_tapped"

**Comment by mokagio** [comment]
I'm going to bump this to the next release because we'll be code freezing [24.0](https://github.com/wordpress-mobile/WordPress-iOS/milestone/265) today and this hasn't been reviewed yet.

If these changes cannot wait two weeks and it's important that it makes it into this release, let me know and we'll organize a new beta once ready.
