### ISSUE TITLE
Site Creation: Re-enable site creation on the WordPress app

### ISSUE THREAD

**Issue by hassaanelgarem** [wordpress-mobile/WordPress-iOS#22368]
### Description

Right now, site creation is disabled for new and existing users on the WordPress app. The goal of this task is to enable site creation for new users on the WordPress app.

### Existing Flow Recording

https://github.com/wordpress-mobile/WordPress-iOS/assets/25306722/562e7b46-f581-4ebf-9d34-95f8cee04201

### Acceptance Criteria
- Site creation should be enabled for users with no sites on the WordPress app regardless of the feature removal phase.
- Features removal modal should be shown right after site creation.
- Users with one or more sites should be prompted to use the JP app for new site creations (current behavior).
- Plan sales should be disabled on the WordPress app.
- The Jetpack app site creation flow should not be affected.

### Related Links
pe7hp4-4k-p2

**Comment by mokagio** [comment]
I'm going to bump this to the next release because we'll be code freezing [24.1](https://github.com/wordpress-mobile/WordPress-iOS/milestone/267) today and this hasn't been reviewed yet.

If these changes cannot wait two weeks and it's important that it makes it into this release, let me know and we'll organize a new beta once ready.
