### ISSUE TITLE
Improve support for larger text sizes on the Traffic tab

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#22729]
On the new Stats Traffic tab, larger text sizes result in a couple of issues:
- the date picker strip doesn't increase in height (even as its contents do, resulting in clipped text)
- the chart labels don't increase in font size

<image src="https://github.com/wordpress-mobile/WordPress-iOS/assets/1898325/0d1c795d-8a75-427b-9d98-cbd2e309e14f"  width="250" />

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by staskus** [comment]
> the chart labels don't increase in font size

@guarani that was intentional since there's very little space to increase font sizes, especially on the horizontal axis. Also, if we allow to expansion of text on the vertical axis and shrink the chart, the horizontal axis would become even narrower.  🤔

Similar chart within Apple Health app doesn't increase bar chart font sizes as well:

https://github.com/wordpress-mobile/WordPress-iOS/assets/4062343/76a37250-d150-4f97-a893-e96463594ae3

What we can allow without breaking the layout is a slight increase in font sizes when dynamic type changes.

**Comment by guarani** [comment]
I wondered about the possibility of making the y-axis labels go from:

200, 150, 100, 50, 0 

to 

200, 100, 0

to make room for the font size. Doing this on the x-axis wouldn't make much sense, though, so I think now it isn't a good idea to pursue. 


> Also, if we allow to expansion of text on the vertical axis and shrink the chart, the horizontal axis would become even narrower. 🤔
> 
> Similar chart within Apple Health app doesn't increase bar chart font sizes as well:

Good points!

> What we can allow without breaking the layout is a slight increase in font sizes when dynamic type changes.

Ok, I'll check out the PR 🙇

**Comment by staskus** [comment]
> I wondered about the possibility of making the y-axis labels go from <..> to make room for the font size

That's a good idea! 👍 Tried it here https://github.com/wordpress-mobile/WordPress-iOS/pull/22734#issuecomment-1971330889
