### ISSUE TITLE
Unable to password protect posts using the Jetpack app for iOS

### ISSUE THREAD

**Issue by alinclamba** [wordpress-mobile/WordPress-iOS#23438]
Issue reported by user here: 8340301-zd-a8c

### Expected behavior

When selecting the "Password Protected" option for a post and entering a password, the post should remain password protected and not revert to public.

### Actual behavior

After selecting "Password Protected" and entering a password, the post setting automatically reverts to public, preventing the post from being password protected.

### Steps to reproduce the behavior

I don't have access to an iOS device, but I asked for help on Slack and @kean tested this but couldn't replicate it. 
↳ Slack convo: p1721644322961629-slack-C06NXHR5WQ1

##### Tested on [device], iOS [version], Jetpack iOS / WordPress iOS [version]

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by bizanimesh** [comment]
The user has v25.2 installed and still sees the issue.

**Comment by alinclamba** [comment]
I tested iOS 17.6.1 and JP 25.2 on iPhone but couldn't replicate the issue. I requested the user to share a video screen capture for further clarification.
Discussion moved to p1724026558252239-slack-C06NXHR5WQ1

**Comment by alinclamba** [comment]
**Update:** 

After setting a password, they instinctively tapped the back arrow at the top left of the screen instead of the "Save" button. Since the back arrow doesn’t currently save the changes, their settings weren’t applied. It turns out that on their iPad in landscape mode, the "Save" button is obscured by the on-screen keyboard, which led to the misunderstanding. I was able to replicate this behavior on an iPhone in landscape orientation as well, which is likely a common scenario for iPad users.

**Suggestion:**

Given this, should we consider modifying the back button behavior to function like the "Save" button, ensuring that changes are saved automatically? This could help prevent similar confusion for other users in the future.

**Comment by dcalhoun** [comment]
Great research identifying how this occurs for users. 👏🏻 I'm capturing a screenshot of the relevant UI for reference. 

<details><summary>Password-protected post UI</summary>

![Password-protected post UI](https://github.com/user-attachments/assets/e37fcb8b-343e-4dd9-a42e-7a1e8ca48333)

</details>

> Given this, should we consider modifying the back button behavior to function like the "Save" button, ensuring that changes are saved automatically? This could help prevent similar confusion for other users in the future.

I suggest we follow Apple's lead, implementing a flow design similar to network proxy settings. Rather than having a single option (Password protected) function differently from the remaining options (Public, Private), we make all options require the same steps. I imagine a consistent flow would mitigate user confusion. 

1. Select an option. 
2. Complete any required information (save button disabled until required information provided). 
3. Persist (Save) or discard (Back) the changes.

<details><summary>iOS network proxy setting recording</summary>

https://github.com/user-attachments/assets/14301e43-22d2-4327-897d-b9b5ec6fac10

</details>

**Comment by kean** [comment]
> iOS network proxy setting recording

This looks like a perfect fit for this user scenario. I'm assigning it to myself and will address it some time soon. It's a simple change.
