### ISSUE TITLE
Implement methods to properly strip Javascript code from an HTML string.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#2371]
Right now `WordPressAppDelegate.m` handles `wordpress://newpost` URLs by stripping all HTML code.  This is because we currently have no reliable mechanism to strip HTML strings from all javascript code.
- [ ] We'd need to replicate in iOS something like what is offered by [kses.php](https://core.trac.wordpress.org/browser/tags/4.0/src/wp-includes/kses.php#L0).
- [ ] We'd also need to re-allow the content field in `wordpress://newpost` to have HTML tags after stripping all javascript code.

**Comment by kurzee** [comment]
@diegoreymendez is this still a thing?

**Comment by diegoreymendez** [comment]
Yep, this is still a thing @kurzee.

You can see an explanation of the current issue [here](https://github.com/wordpress-mobile/WordPress-iOS/issues/2369).

My opinion, though, is that we could remove `wordpress://newpost` support entirely.  I'm not even sure if that's used for anything in particular.

Thoughts @aerych, @koke? (since you guys may have a better background on why it exists)

**Comment by aerych** [comment]
> My opinion, though, is that we could remove wordpress://newpost support entirely. I'm not even sure if that's used for anything in particular.
Thoughts @aerych, @koke? (since you guys may have a better background on why it exists)

We sort of did it because we could, just to have a very simple way for other apps to share something to the WordPress app.  We never really promoted the feature out side of a couple of forum posts afaik. 

My two cents: our share extension trumps `wordpress://newpost` and we could deprecate/remove that feature as long as it doesn't have any internal dependencies.

**Comment by diegoreymendez** [comment]
Closing this in favor of #6138.
