### ISSUE TITLE
"Your tags" shows incorrect dates and doesn't refresh

### ISSUE THREAD

**Issue by dzver** [wordpress-mobile/WordPress-iOS#23813]
### Expected behavior
When clicking my tags, the latest posts should be either latest, or should show how old they are

### Actual behavior
When clicking my tags, I see some old posts, sometimes from yesterday, but showing they're 20 seconds old

https://github.com/user-attachments/assets/58b84702-1f83-4d1b-817d-9c5b799e1455

### Steps to reproduce the behavior
1. Go to My tags
2. Don't use the app for some time, in the case of the screenshot - 4h
3. Return to the app and do something that's not Reader
4. Go to Reader
5. See old posts with inaccurate dates

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by kean** [comment]
Hey, I'm going to close this if you don't mind since this screen is removed in 25.5. 

You will not be able to either quickly access the individual tags or view all posts based on your interests in Discover / Latest.

<img width="320" alt="Screenshot 2024-11-15 at 8 00 12 AM" src="https://github.com/user-attachments/assets/61119509-5350-49d5-9064-2d8707fc0121">

<img width="320" alt="Screenshot 2024-11-15 at 8 00 08 AM" src="https://github.com/user-attachments/assets/e5b720b2-d699-4fbc-9ac2-3acaef61f4de">

Btw, if you want to give it a try, the most up-to-date build can be downloaded from here https://github.com/wordpress-mobile/WordPress-iOS/pull/23788#issuecomment-2465901587.
