### ISSUE TITLE
Right nav button on mail composer needs to be styled. 

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#2507]
The cancel and send buttons are difficult to see. 

https://cloudup.com/cstqz3LFTz4

**Comment by cyrilchandelier** [comment]
This problem seems to be resolved already (see screenshot), tested on both iOS 7 & 8.

![screen shot 2015-05-03 at 3 38 17 pm](https://cloud.githubusercontent.com/assets/820515/7445396/30cb525a-f1b1-11e4-9bf2-13477108ef63.png)

The status bar for its part is always reset to the default black color when user opens a MFMailComposeViewController (same thing happens in the view controller used for text messages)

**Comment by aerych** [comment]
Looks like this was a dup of #2762, and was fixed in #2763.
Closing.
