### ISSUE TITLE
Categories is sometimes missing items from the list. 

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#2573]
We've received a few reports that categories are missing from the iOS app. In some cases an incomplete list is described, in other cases the list is blank.   While testing a user's blog I saw different lists of categories depending on if I tested in the Simulator (current develop branch) or on a real device (v4.4 & v4.5). Querying the xmlrpc endpoint with XML-RPC Client yields results that matched the device.

Documenting here since there seems to be something going on but its not clear what. 

See forum threads:
http://ios.forums.wordpress.org/topic/app-cant-see-my-catagories?replies=14 
http://ios.forums.wordpress.org/topic/categories-not-updating-on-ipad?replies=3

**Comment by meremagee** [comment]
error from user - https://cloudup.com/ciZzpXxxGAl
_pw-protected link for sensitive info but wanted it tied to the thread._

**Comment by mahangu** [comment]
https://automattic.helpshift.com/admin/issue/19965/

This user seems to be having the issue as well.

**Comment by rachelsquirrel** [comment]
We have another report of this in Helpshift:
https://automattic.helpshift.com/admin/issue/33344/

**Comment by druesome** [comment]
Same user as Rachel's came back to ask about the status of this.  Issue #38573

**Comment by ChrissiePollock** [comment]
Another one - 56388-h

**Comment by kurzee** [comment]
This is likely related to: https://github.com/wordpress-mobile/WordPress-iOS/issues/6120, will try and tackle with `6.8`.

**Comment by oguzkocer** [comment]
Another one #143910-h

**Comment by catehstn** [comment]
@kurzee did your PR address this? @rachelmcr can you repro?

**Comment by kurzee** [comment]
@catehstn this might be a bit different, I'll retest this one when I get back, probably a similar fix at least.

**Comment by kurzee** [comment]
This issue is partially fixed in the recent https://github.com/wordpress-mobile/WordPress-iOS/pull/6414

However, we don't have a pull-to-refresh for categories view in Post Options. So if a user is actively managing categories on the web, the won't be able to pull in their categories for a self-hosted site until relaunching the app or one of the main syncs fires off.

I'm going to add a manual pull-to-refresh on categories in the Post Options to allow a user to pull in their known changes as needed.
