### ISSUE TITLE
New color palette — tap highlight

### ISSUE THREAD

**Issue by drw158** [wordpress-mobile/WordPress-iOS#2589]
The tap highlight color should ideally be using one of our grays in the style guide. Right now, it's not.

 ![screen shot 2014-10-15 at 1 40 11 pm](https://cloud.githubusercontent.com/assets/618551/4651272/c4ea252e-549a-11e4-9bf6-c922ba76b687.png)

**Comment by mattmiklic** [comment]
On iPhone, the selected color is designed to be subtle; a high-contrast change would be startling since the effect is only visible briefly, between when the user's finger touches the menu item and when they let go and the screen animates. In the Settings app, you can see the default grey color used for the selected state.

On iPad, the selected color is designed to stand out. Because the selected menu item acts as an anchor to establish where a user is in the list, it uses a high-contrast, saturated background color.

You can see screenshots of these two states in the Settings app here: https://cloudup.com/cxD9cnFjpoq

For our app, I've created a suggested example of selected states for iPhone and iPad. Following the example of the Settings app, the iPhone treatment is subtle, only changing the background color to `lightGrey`.  On iPad it's more pronounced; using `grey` as the background instead of a saturated blue so as to avoid competing with the large expanse of blue in our title bar. It also matches the treatment in Calypso.

![selectedstate-ipad](https://cloud.githubusercontent.com/assets/1396552/22667447/cae00a7c-ec8a-11e6-808f-059cf30ca674.png)

![selectedstate-iphone](https://cloud.githubusercontent.com/assets/1396552/22667451/ce7bceaa-ec8a-11e6-93ed-ea816d2fd553.png)

The only change on iPhone is to the background. But on iPad, this would necessitate swapping the color of the menu icon and text when the state is selected. We should look into whether this presents any potential hazards for implementation.

**Comment by designsimply** [comment]
I tapped a notification on my iPhone 6S using WP Internal 12.4.0.20190506 and it looks like the tap highlight color is `#d9d8da`.

<img src="https://user-images.githubusercontent.com/1119271/57660969-265a8c00-75a6-11e9-8d28-8c905d7e65f8.png" width="270" alt="tap-highlight-color">

@nheagy may we close this issue in favor of https://github.com/wordpress-mobile/WordPress-iOS/issues/11683 which is the issue for moving to the new Classic Bright color palette?

**Comment by nheagy** [comment]
@designsimply I referenced this one from #11683, so that I keep track of it. Close away!

**Comment by nheagy** [comment]
Should be fixed in #12077
