### ISSUE TITLE
Bad layout after dismissing Helpshift

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#2852]
If you fail to login a couple times, tap Contact Us, then cancel, the layout on LoginViewController breaks:

![helpshift-glitch](https://cloud.githubusercontent.com/assets/8739/5206576/dabe73fe-75a2-11e4-97ee-9eeef9d09a06.gif)

**Comment by jstart** [comment]
Tried to reproduce and realized this issue had been fixed by calling
    [[NSNotificationCenter defaultCenter] removeObserver:self];
in viewWillDisappear.

The issue was that the loginViewController was listening for the keyboard hide notification and when helpshift dismisses the keyboard, it was adjusting the loginViewController.  Now, it won't be called because we remove observer.

@koke Think this issue should be closed?

**Comment by koke** [comment]
Yep, it seems resolved, thanks
