### ISSUE TITLE
Improve handling of permission errors

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#2939]
For example, I have a test account that has an author role on a wpcom site.  The wpcom site shows up in my site list as expected but if I try to view the comments I see this: 

![ios simulator screen shot dec 16 2014 10 40 59 am](https://cloud.githubusercontent.com/assets/1435271/5465601/0f727baa-8560-11e4-8d69-3dc520deaa71.png)

Let's improve this experience!

**Comment by rachelmcr** [comment]
I checked how this works in the latest beta (5.8.0.20151124) and it does a little better. Instead of a popup error, the comments screen shows this:

![2015-11-27 12 50 06](https://cloud.githubusercontent.com/assets/8658164/11441588/91b60162-9505-11e5-8a31-d3de06232ebf.png)

It would still be nice to show a more specific message there. (I noticed that it can be a bit confusing when as an author I can see a comment notification on the notifications tab, but when I go to comments I get that "No comments yet" message.)

**Comment by ScoutHarris** [comment]
The behavior is still the same, but with new and improved UI!

<kbd>![comments](https://user-images.githubusercontent.com/1816888/112554008-2d9a7580-8d8b-11eb-899d-1f109f7c6b2a.png)</kbd>

**Comment by ScoutHarris** [comment]
This should be resolved with the Unified Comments project, specifically this task https://github.com/wordpress-mobile/WordPress-iOS/issues/16685.
