### ISSUE TITLE
Reader: Duplicated post preview in list but detail shows correct post.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#3050]
We've had one report where the post list showed the same post twice, one right after the other.  Tapping one displayed the detail for the post, tapping the other showed the detail for a different post, ostensibly the post that should have been previewed but was showing the duplicate content instead. 
Refreshing fixed the list. 
This is a weird state since a pull to refresh or a backfill would both refresh the list.  
Theory: perhaps the issue has something to do with competing MOCs.

**Comment by diegoreymendez** [comment]
I'm not sure about this particular case but this scenario can be triggered by:

1. Creating a post while online and trying to publish it
2. At the list of posts showing the local post, reconnect
3. Open the post and publish again

In this case it's a sincronization issue on our end.

**Comment by lancewillett** [comment]
I'm seeing duplicates in Reader today with Jetpack sites (and also in WordPress desktop app — but not wpcalypso in Chrome desktop).

**Steps to repeat:**
1. With my `lancewillett` user, log in to iOS app and open Reader.
2. Scroll down to see https://chrishardie.com/ and https://ethitter.com/ sites are showing 2 and 3 posts each instead of just one, per post.

iOS 9.3.1, iPhone 6+, app version 6.1.020160406

<img src="https://cloud.githubusercontent.com/assets/66797/14365986/72f874c6-fcc5-11e5-8410-dc2b59bb2d7a.jpg" width="480" />

<img src="https://cloud.githubusercontent.com/assets/66797/14365987/72f8c250-fcc5-11e5-9c0b-1e80f95eec31.jpg" width="480" />

<img src="https://cloud.githubusercontent.com/assets/66797/14365985/72f7b7a2-fcc5-11e5-9c9c-e91d00d2109d.jpg" width="480" />

WordPress desktop app, OS X:

![screen shot 2016-04-07 at 13 25 09](https://cloud.githubusercontent.com/assets/66797/14366002/864f3bc2-fcc5-11e5-931f-3d7629be4501.png)

**Comment by aerych** [comment]
> I'm not sure about this particular case but this scenario can be triggered by:
> 
>     Creating a post while online and trying to publish it
>     At the list of posts showing the local post, reconnect
>     Open the post and publish again
> 
> In this case it's a synchronization issue on our end.

@diegoreymendez Can you confirm you were seeing duplicates in the *Reader* and not the blog post list under this scenario?

**Comment by aerych** [comment]
Looks like the incident @lancewillett reported is due to something squirrelly in the wpcom REST API.  We'll tackling it from that end.

**Comment by diegoreymendez** [comment]
@aerych - Sorry I missed the `Reader` tag entirely, and only read the text assuming it was a blog's list of posts for the editor.  Ignore my comment, or feel free to remove it.
