### ISSUE TITLE
Add a message informing the user they will lose any local drafts on sign out

### ISSUE THREAD

**Issue by sendhil** [wordpress-mobile/WordPress-iOS#3164]

**Comment by rachelmcr** [comment]
The app currently (last checked in beta version 6.6.0.20161012) displays this message on WordPress.com sign out:

> Disconnecting your account will remove all of [username]'s WordPress.com data from this device.

And this message when removing a self-hosted site:

> Are you sure you want to continue?
> All site data will be removed from your iPhone.

It might be helpful to explicitly mention local drafts and edits there, rather than the generic "data." There is also an issue about the wording ("Disconnect" versus "Log out") in https://github.com/wordpress-mobile/WordPress-iOS/issues/6016.

**Comment by rachelmcr** [comment]
This just came up in support, where a user was concerned about losing their data based on the current logout message:

> Just tried to log out of Wordpress and got a pop up message saying that I would lose all my Wordpress data. Please explain. I want to log out and keep my content. Bizarre message to get for a standard task. 

Internal ref: 196309-h

**Comment by koke** [comment]
We've been discussing this (p4a5px-2bV-p2), and decided to show a simple confirmation if there are no local changes/drafts:

> Log out of WordPress

If there are any changes that would be lost, then we'd show this message:

> You have changes to X posts that haven’t been uploaded to your site and are only saved on this device. Logging out now will delete those changes. Log out anyway?
