### ISSUE TITLE
Release WPTabBarController when needed

### ISSUE THREAD

**Issue by jleandroperez** [wordpress-mobile/WordPress-iOS#3211]
Right now, the app will always have a valid *WPTabBarController* instance alloc'ed. This is true even for fresh installs (in which you get to glimpse, for less than a second, the tabBar view, and then the Login shows up).

Let's review + update the flows, so that:
- [ ] WPTabBarController is not a singleton, but an instance retainted by the App Delegate.
- [ ] Upon logout, the view is effectively released. This will prevent any sign out from account A / sign into account B crashes.
- [ ] Review and cleanup WordPressAppDelegate code that handles the flows. Remove unneeded snippets, and make sure that the TabBar is alloc'ed only when needed.

**Comment by oguzkocer** [comment]
I'd argue that it'd be more a cleaner solution if we keep it as a singleton and have a `reset` function which would dump everything and recreate them as necessary. Another alternative is to nullify the singleton and then re-create it when necessary. I'd like to avoid adding a dependency to AppDelegate everywhere the `WPTabBarController` is used. I hope that makes sense!

**Comment by diegoreymendez** [comment]
There seems to be no disadvantage in having this class be instantiated normally and then access our instance through something like `[WordPressAppDelegate tabBar];`.

The problem with singletons is how they can create undesired artificial constraints.  They are tempting to use because they seem to simplify code design considerably, but in doing so force limitations in how they can be consumed (for example the fact that you can't have multiple instances for unit testing).

I think we'd be overcomplicating the design if we want to avoid releasing an object (that doesn't need to exist anymore) but opting to then call `[WPTabBarController reset];` to achieve the same result releasing that object would have had in the first place.

The only special consideration is to make sure these changes are done early in the development cycle of the version they'll be released in, so that they can be properly tested.

**Comment by jleandroperez** [comment]
Closing this one, for now. I'll definitely get back to it (and probably port WPTabBar to Swift) once the new Notifications tasks are wrapped up.

Thanks gentleman!
