### ISSUE TITLE
Wrong translation in french in post creation

### ISSUE THREAD

**Issue by cyrilchandelier** [wordpress-mobile/WordPress-iOS#3578]
This is a very small problem and I don't know if this is the right place to say it, but I've seen a wrong translation in the french version:
![screen shot 2015-04-25 at 9 05 40 pm](https://cloud.githubusercontent.com/assets/820515/7334273/00bf1344-eb8f-11e4-9d43-0a044ef05205.png)

```Article``` is the french translation of ```Post``` when speaking about a post, but this button looks more like the action of posting and should be ```Publier``` (which means ```Publish```).

**Comment by cyrilchandelier** [comment]
Also I looked into the code, and there is only two occurrences of the "Post" localized string (in WPPostViewController), it's not shared between screens, so it should be easy to modify.

**Comment by rachelmcr** [comment]
Thanks for pointing out this error! All of the app's translations are managed through GlotPress on WordPress.org here:

https://translate.wordpress.org/projects/apps/ios/dev/fr/default

Here is a direct link to that string "Post" and all of its past translations, including your suggestion that I just added:

https://translate.wordpress.org/projects/apps/ios/dev/fr/default?filters[status]=either&filters[original_id]=94824&sort[by]=translation_date_added&sort[how]=asc

The new translation "Publier" will need to be approved by one of the project's validators before it is used in the app.

We should also add better context to that string, to clarify that it is a verb and not a noun. That issue is being tracked in #4368 so I'm going to go ahead and close this issue. (The translation will be corrected once it is approved and launched in a future release.)
