### ISSUE TITLE
SSL Certificate Verification

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#3601]
We probably want to start verifying the SSL certificate for *.wordpress.com connections. Instead of blindly trusting a valid certificate as being valid enough, we should really be storing the expected certificate (or certificates if its changing soon) in the app bundle. This can help mitigate man in the middle attacks.

**Comment by koke** [comment]
It should be as easy as b76824239561c865ef1839ebe328f34df2e9e652

What worries me about certificate pinning is older versions of the app that can't upgrade.

Let's say we roll this out in 5.1. Then 5.2 comes out dropping support for iOS7, so there's a bunch of users stuck in 5.1 with pinning enabled. In October 15, the `*.wordpress.com` certificate expires and the app stops working with no way to fix or update.

**Comment by astralbodies** [comment]
We could put logic in that if the locally stored certificate is expired that we allow traffic to pass. Not necessarily ideal but could be a workaround.

**Comment by koke** [comment]
Then I can spoof your [NTP](https://en.wikipedia.org/wiki/Network_Time_Protocol#Security_concerns) traffic, tell your phone that it's 2017, make it ignore the local certificates, and proceed to MITM :smile:

**Comment by astralbodies** [comment]
You just like making me cry. :cry:

**Comment by kurzee** [comment]
Was intrigued with this, created an approach in #3622 that essentially verifies the local cert prior to pinning. Future versions stuck with an expired cert would just resort to not using pinning.

**Comment by diegoreymendez** [comment]
@astralbodies, @koke, @kurzee, @sendhil - Why not offer a manual toggle in our app settings to turn certificate pinning on / off (with the default being ON)?

That would allow the user to decide and keep using the app if the certificate expires.

There's still the possibility that someone may maliciously toggle this off, but that would require physical access to the device, or an exploit to get remote access to it, but security is about layers.

This solution would still be better than having no pinning at all.

Thoughts?

**Comment by kurzee** [comment]
@diegoreymendez I think one road-block was maintaining the right certs in the app, may not be worth exploring further if too much of a headache: https://github.com/wordpress-mobile/WordPress-iOS/pull/3622#issuecomment-104039624

**Comment by sendhil** [comment]
@diegoreymendez I like that solution...

**Comment by koke** [comment]
I don't like the idea of adding a toggle to deactivate pinning. I think most people won't know what it's for. Is it better than no pinning at all? Probably. But it also feels like avoiding the problem instead of solving it. Maybe the solution is pinning the public key instead of the certificate.

**Comment by diegoreymendez** [comment]
> I don't like the idea of adding a toggle to deactivate pinning. I think most people won't know what it's for.

We see a lot of critisism for companies that design their products around the concept that "people don't understand" so complex features have to be stripped out.

I don't think we should have this mindset.

We can try to make sure the feature is well documented, wherever it's placed.  The rest would be up to the user.

If you think about it, it's not very different from how web browsers handle sites with expired / incorrect certificates.

> Is it better than no pinning at all?

It is indeed better than no pinning at all because the default will be to have certificate pinning turned ON, regardless of if users understand what it is or not.

If they turned it off they'd be exactly where we're now.

> But it also feels like avoiding the problem instead of solving it. Maybe the solution is pinning the public key instead of the certificate.

If we do have a concrete alternative on the table that we can implement, I wouldn't mind discussing it.

Can you provide more details about what you mean by pinning the public key?  How would that process work?

**Comment by diegoreymendez** [comment]
Since there's no agreement or discussion moving forward for this feature, I'm closing it.

We can reopen if / when there's more interest.
