### ISSUE TITLE
Clean up support screen. 

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#3659]
Let's reorder the rows in the support screen for better grouping, and update the code to match our code style guide. 

Let's make the new section/row order:

FAQ section
- Contact Us (live chat) / Forums (forums)
- Help Center (faqs)

Feedback section (If present)
- E-mail Support 

Activity section
- About
- Version
- Anon Usage
- Activity Logs
- Extra Debug

**Comment by aerych** [comment]
WIP branch: https://github.com/wordpress-mobile/WordPress-iOS/tree/issues/3659-clean-up-support

**Comment by aerych** [comment]
Hiya @oguzkocer,
If you get some free time would you mind taking a peek at the changes so far in the branch, especially regarding helpshift and see if anything looks wrong?
(Its a work in progress so things are still a bit messy.)

**Comment by oguzkocer** [comment]
Hey @aerych, I've had a quick look at the changes and nothing really major jumped up. I have noticed a few small things that we might want to change but since it's a WIP branch, I will wait for the PR to mention them (if they are still there that is).

The changes look really good in general, things are much more readable & maintainable this way. I especially liked the table view data construction :+1: I am not sure if it makes much sense, but I'd at least consider extracting that to a helper class, so the data construction is all at one place and the controller is a lot smaller. We can also consider moving some of the Helpshift stuff like `prepareAndDisplayHelpshiftWindowOfType` & `newHelpshiftUnreadCountLabelWithCount` to `HelpshiftUtils`.

I am sorry if I mentioned something you were already working on! Let me know when you want me to have another look :)

**Comment by aerych** [comment]
Thanks Oguz! I have some higher priority items I need to get through but I'll get back to this one soon.

**Comment by SergioEstevao** [comment]
@aerych are you planning to go back to this?

**Comment by aerych** [comment]
I'd like to at some point unless someone else would like to take over.  I'll un-assign until I can find the bandwidth.

**Comment by jleandroperez** [comment]
### Update(s) on this one:
- @koke already prettified `SupportViewController`'s code. No more magic numbers, we already have enum's in place
- @astralbodies moved the `About` screen to `App Settings`

I'll be pushing, shortly, few changes to align the row ordering with the issue's description.

Thanks everyone!

**Comment by jleandroperez** [comment]
On second thoughts... @aerych, moving `Contact Us` to the first row may suggest that the first thing to do is to mail support, and we may want to direct them to the Help Center first.

Plus, if we arrange `Anon Usage / Activity Logs / Extra Debug`, the row details will get a `Switch / Chevron / Switch`, which looks a bit odd imho.

Do you think it'd be okay if we close this one instead?

Thanks!

### Current:
![current](https://cloud.githubusercontent.com/assets/1195260/20712548/3b6ff638-b623-11e6-8ad7-d0b7568d0e38.PNG)

### Suggested:

![suggested](https://cloud.githubusercontent.com/assets/1195260/20712559/464a747a-b623-11e6-8d4f-33a8af2b2b1b.PNG)

**Comment by astralbodies** [comment]
Before we close, lets take a look at the Android app to make sure we don't have any glaring differences. 😄

**Comment by aerych** [comment]
> Do you think it'd be okay if we close this one instead?

For sure.  It looks like the issues I wanted to sort out have been long since addressed.

**Comment by jleandroperez** [comment]
@astralbodies by glaring difference you mean... something like this?

(Please note that... there's no `Extra Debug` nor `Anon Tracking` toggle in Android).

![screenshot_20161130-170126_1024](https://cloud.githubusercontent.com/assets/1195260/20769091/562e2178-b71f-11e6-859e-cce9831255ca.png)

**Comment by jleandroperez** [comment]
(Thanks @mzorz for the screenshot!! ^)

**Comment by jleandroperez** [comment]
Closing this one. Discussed briefly over P2 with @drw158, we'll actually need to align Android with iOS.

Thanks everyone!
