### ISSUE TITLE
Post list author filter doesn't play nice with Jetpack

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#3726]
When a Jetpack site uses REST, the post `authorID` (self hosted ID) won't match the account `userID` (wp.com ID).

The good news is that we’re already calling `sites/$site/users` from `checkMultiAuthorForBlog:` and that includes `ID` (self hosted) and `linked_user_ID` (wp.com), so we _just_ need to store that and add some extra logic

**Comment by aerych** [comment]
@koke gonna grab this one unless you'd planned to take it

**Comment by koke** [comment]
All yours :wink:

**Comment by aerych** [comment]
`The good news is that we’re already calling sites/$site/users from checkMultiAuthorForBlog: and that includes ID (self hosted) and linked_user_ID (wp.com), so we just need to store that and add some extra logic`

Was thinking through this. Since a blog can have any number of authors I don't think calling the sites/$site/users endpoint is a good approach. I think it would be better to include the linked wpcom user ID in the author dictionary returned by a post object.

**Comment by aerych** [comment]
This isn't currently supported on the web so I think we'll just disable it for now and revisit after the API is patched.

**Comment by aerych** [comment]
Closed in #3801
