### ISSUE TITLE
"Publish immediately" for scheduled post is not working

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-iOS#3732]
Looks like we have an issue with publishing a scheduled post immediately. To repro:

* Open a scheduled post to edit
* Open post options
* Change the "Scheduled for" date to "Publish Immediately"
* Exit the options screen and save the post
* View the site or reopen the post for editing...note the published data and status are unchanged.

Video of it here: https://cloudup.com/cZzeh-XqqSz

/cc: @aerych since we have chatted about this in the past

ref: https://github.com/wordpress-mobile/WordPress-iOS/issues/1600

**Comment by aerych** [comment]
Candidate regression from the post list changes but not sure. I'll take this one and dig into it.

**Comment by aerych** [comment]
I went back and tested this in 5.2 and produced the same behavior.  Interestingly, this only happens on blogs hosted at wpcom. Posts on self-hosted blogs publish immediately as expected.  Yay for no regression, but the bug remains.

It looks like the issue is differences in the xmlrpc and rest remote service.  The xmlrpc remote checks for a nil date on an existing post, and if detected assigns the current date.  The rest remote does not do this. 

Patch coming.
