### ISSUE TITLE
Sharing: Would be nice to have a way to share a link to a post from posts in My Sites

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#3792]
We've never had a way to share a link from the posts or pages feature, and it would be nice to have.  The best place might be the "detail" screen that precedes the active editor.

**Comment by rachelmcr** [comment]
A user recently requested this kind of feature (an easy way to copy a URL and/or share a post directly from the list of posts in My Sites).

Since sharing in the Reader happens by tapping the three dots in the top right on the card, I wonder if we could use that same action here? Alternately, perhaps we could add an easy way to share the post after tapping "View" on a particular post.

**Comment by rachelmcr** [comment]
This came up again recently — a user noted that when you go to My Sites > Blog Posts > View a post, there is no way to open the post in Safari, copy a link to the post, or share it to social media.

**Comment by diegoreymendez** [comment]
I was trying one possible solution for this and realized there's some design work to do here.  A video showing an explanation of the situation can be seen [here](https://cloudup.com/cF5Rie7xiZx).

Would you mind giving me your opinion on how to approach this @mattmiklic?

Also /cc @aerych

**Comment by mattmiklic** [comment]
I think this approach to how we treat the actions on post cards is probably reaching its natural limits here, as evidenced by how rough three pages of buttons feels to navigate through. 

That's a bit of a more involved discussion though since the current implementation matches the Calypso /posts/ design. Instead I'd recommend not adding it to this list screen.

What about adding it to the top bar of the next screen, after tapping a post to open it full-screen?

![share-ios](https://cloud.githubusercontent.com/assets/1396552/14034238/a59cf222-f1f7-11e5-9292-5889f2c7d1bc.png)

**Comment by diegoreymendez** [comment]
@mattmiklic - I feel it should be possible to get the sharing link without necessarily going into the post.

Also - the top bar may get a bit overcrowded.  See this image:

<img width="386" alt="screen shot 2016-03-25 at 1 09 51 pm" src="https://cloud.githubusercontent.com/assets/1836005/14048111/e5abd962-f28a-11e5-9a5a-1301aba1b855.png">

That said - let me know if you still want to add the button there and I'll take care of it.  Just double checking before moving forward.

**Comment by mattmiklic** [comment]
> Also - the top bar may get a bit overcrowded. See this image:

When you enter editing mode, I wouldn't show the Share button anymore, because it doesn't really make sense to share something that hasn't been saved. I'd actually be in favor of removing the preview button while editing, since it's not a real preview and the visual editor is just as good or better, but that's probably a separate issue.

I don't think it makes sense to include a Share icon in the list view for two reasons -- because those cards are already overloaded with options, and because I think it makes more sense to share something as you're viewing the content of the post, not just a headline and excerpt.

**Comment by diegoreymendez** [comment]
Aight, moving forward then.  Thanks @mattmiklic!

**Comment by diegoreymendez** [comment]
@mattmiklic - It still feels like we have too many buttons in edit mode.  I was thinking that maybe having a single "..." button in the top right corner could make sense.

It would activate an action sheet showing the different options.

Another alternative is to remove the preview button as you suggested although that could feel like a regression to some of our users?  /cc @aerych for comments on this.

<img width="487" alt="screen shot 2016-03-28 at 4 39 44 pm" src="https://cloud.githubusercontent.com/assets/1836005/14088072/b3f81306-f503-11e5-92c3-7ff8ffa876a4.png">

**Comment by aerych** [comment]
> @mattmiklic - It still feels like we have too many buttons in edit mode. I was thinking that maybe having a single "..." button in the top right corner could make sense.

I thought Matt was saying to *not* show a Share button while in edit mode.

> Another alternative is to remove the preview button as you suggested although that could feel like a regression to some of our users? /cc @aerych for comments on this.

I get the point about the preview not being "real" (at least not in certain circumstances), but rather than remove it I'd like to see us do something better.

**Comment by diegoreymendez** [comment]
> I thought Matt was saying to not show a Share button while in edit mode.

My bad.  For some weird reason I was doing the exact opposite.

**Comment by mattmiklic** [comment]
> I thought Matt was saying to not show a Share button while in edit mode.

Correct :) So the options on the first screen would be [share] [preview] [edit], then if you enter editing mode, [share] would disappear and the options would be [preview] [settings] [post].

**Comment by diegoreymendez** [comment]
@mattmiklic - Do you happen to have this icon in 30x30 size?  When using the 44x44 version I have it looks thinner than it should be.

<img width="386" alt="screen shot 2016-03-29 at 2 30 35 pm" src="https://cloud.githubusercontent.com/assets/1836005/14117382/d5db44fe-f5ba-11e5-9da2-52fb93c22fe2.png">

**Comment by mattmiklic** [comment]
@diegoreymendez I took a look at the icons this morning -- instead of making a new 30x30 icon, I'd recommend switching the existing eye and gear icons to use standard gridicons instead of the custom ones that are being used now.

I made a new branch to try them out: https://github.com/wordpress-mobile/WordPress-iOS/tree/try/gridicons-in-editor

They'll need to be sized and colored in code (30px, white) but I think this would be a better approach since it gets us closer to standardizing on gridicons.

**Comment by mattmiklic** [comment]
> They'll need to be sized and colored in code (30px, white)

Actually let's see how they look at 32px; that should eliminate any fuzziness and I think will still fit on the toolbar nicely.

**Comment by diegoreymendez** [comment]
@mattmiklic - I've changed the icons in your branch to white.  At 24px they look nice, but at 32px the upscaling makes them look kinda bad IMHO.

You can check it out in the same branch you used (`try/gridicons-in-editor`).

**Comment by diegoreymendez** [comment]
@mattmiklic - I guess I missed these are vector graphics.  I've talked with @frosty and I'll probably use a new framework he's working on to get the image in the appropriate size and color.

**Comment by mattmiklic** [comment]
@diegoreymendez I just took a look at the branch; I was wrong earlier -- I'm pretty sure that Gridicons should look right at their standard 24px in that toolbar. I just tried mocking it up and 24px looks right.

In the branch, I noticed that all of the icons in the toolbar are fuzzy now, including the back chevron, though if you remove the resizing you're doing now that may be fixed.

**Comment by mattmiklic** [comment]
A couple of screenshots for comparison:

Toolbars with 24px icons, @2x:
![toolbars](https://cloud.githubusercontent.com/assets/1396552/14209503/68394678-f7f2-11e5-8f0f-5c0c3f9efeae.png)

Zoomed-in view of icons. Dashed red outline shows 24x24 icon boundaries.
<img width="1337" alt="screen shot 2016-04-01 at 10 12 46 am" src="https://cloud.githubusercontent.com/assets/1396552/14209517/759f9ac4-f7f2-11e5-899a-192dfe4b09e1.png">

**Comment by diegoreymendez** [comment]
Fixed.
