### ISSUE TITLE
Multiple comments with NSLocalizedString aren't in GlotPress

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#3829]
On occasion we use the same string in multiple places and the comment provided in NSLocalizedString isn't identical.

```
/* Displayed when the user views trashed pages in the pages list and there are no pages
   Displayed when the user views trashed posts in the posts list and there are no posts */
"Everything you write is solid gold." = "Everything you write is solid gold.";
```

This causes an issue in GlotPress where the comment does not show up for the translators. Determine if this bug is in GlotPress or our uploader script. We should also probably comb through the script to make sure we're using identical comments. Until we use unique identifiers for our strings this is going to be an issue.

**Comment by rachelmcr** [comment]
List of localizable strings is here:
https://github.com/wordpress-mobile/WordPress-iOS/blob/a82053907b06f7e08e3c210d729738ae9a818cb0/WordPress/Resources/en.lproj/Localizable.strings

Until we can identify/resolve the underlying issue here, I can look through strings with multiple comments and propose changes so the same comment is used for that string everywhere. Note: This won't resolve issues where the same string needs to be translated differently for different contexts, like the string "Post" which can be a noun or a verb:

```/* Placeholder title for ReaderPostDetails.
   Publish button label. */
"Post" = "Post";```
