### ISSUE TITLE
Videos inserted by the mobile app on .org site are not using the video shortcode

### ISSUE THREAD

**Issue by SergioEstevao** [wordpress-mobile/WordPress-iOS#3911]
@SergioEstevao the fixed worked well. I did uncover another issue on non-jp .org sites. If you upload a video from the device, a <video> tag is inserted into the post. If you insert a video from wp-admin, a shortcode is used.

![napkin 9 06-22-15 10 41 11 am](https://cloud.githubusercontent.com/assets/154014/8285786/3bd4f8ea-18cb-11e5-85e4-ce2dec94e319.png)

I am not sure if this is an issue really...but in Chrome I did notice this in the visual editor:

![napkin 8 06-22-15 10 36 16 am](https://cloud.githubusercontent.com/assets/154014/8285797/5bfff494-18cb-11e5-8fcb-494b923c86f3.png)

The shortcode movie appears and the <video> tag movie is a small dot. Note, it doesn't seem to affect the published post from a reader's perspective. We can probably make a separate issue for this since it is out of scope of this PR.

**Comment by rachelmcr** [comment]
I confirmed that uploading a video from the device on a .org site (Jetpack or non-JP) results in a video tag instead of a shortcode.

I couldn't reproduce the second issue in Chrome/visual editor with the small dot. The video shortcode shows a nicer embed preview, but the video tags do display a placeholder image:

<img width="793" alt="screen shot 2015-12-17 at 4 21 08 pm" src="https://cloud.githubusercontent.com/assets/8658164/11883706/52263136-a4da-11e5-9fbf-67e358e141c7.png">

Device: iPhone 6, iOS 9.2
App: beta 5.9.0.20151216

**Comment by aforcier** [comment]
This has been addressed on Android, though not yet fully tested (video uploads haven't been implemented yet).

The ZSS editor has been modified to convert `[video]` shortcodes to `<video>` tags for display and back to shortcodes when the HTML is being extracted.

Ref: https://github.com/wordpress-mobile/WordPress-Android/pull/3626 ([this commit](https://github.com/wordpress-mobile/WordPress-Android/commit/edded6ff8bbfdd36fdd2160c3c07094226aac80a))
