### ISSUE TITLE
What Post Status Transitions does this use?

### ISSUE THREAD

**Issue by voltronik** [wordpress-mobile/WordPress-iOS#4053]
Hi, 

I develop a plugin called [Better Notifications for WordPress](https://wordpress.org/plugins/bnfw/) which sends notifications when new posts are published, amongst many other things. 

It seems that the iOS app (possibly the Android app too) when writing a post, is storing it offline and then, unless you save it to a draft specifically, is sending it directly to WordPress without using the draft_to_publish post status transition. 

Are you able to tell me what [post status transition](https://codex.wordpress.org/Post_Status_Transitions) you're using in the iOS app and, if possible, why this particular one is used over the standard draft_to_publish? 

Thanks! 
Jack

**Comment by voltronik** [comment]
Just wondered if there was any word on this? Can anyone help?

**Comment by aerych** [comment]
Hi Voltronik. App behavior is limited to what is supported by the API used to communicate with the a blog. You might take a look at the inner workings of the WordPress [XML-RPC API](https://codex.wordpress.org/XML-RPC_WordPress_API) and see if the hook you're looking for is implemented there.  Also be aware that users of the iOS app (and eventually Android app) who have installed the Jetpack plugin can use the [WordPress.com REST API](https://developer.wordpress.com/docs/api/) instead of XML-RPC.  Finally, there is also the new [WP API](http://v2.wp-api.org/) that may eventually replace XML-RPC.
If a particular API is not implementing the status transition you need you might consider submitting a patch for it.

**Comment by voltronik** [comment]
Looking at this again, I still can't work out what post status transition you're using for both brand new posts and posts that have been saved in the app first, then published. Can you tell me?

**Comment by aerych** [comment]
Hi @voltronik. On self-hosted blogs, new posts are created by calling the `metaWeblog.newPost` XML-RPC API method. The XML-RPC API (and REST API for that matter) does not provide the app with a means of specifying a post status transition when creating the new post.  You'll need to look at what the XML-RPC API and the `metaWeblog.newPost` method is doing "under the hood" to see if there is a default post status transition.

**Comment by voltronik** [comment]
Ok, thanks, Think i've found it.
