### ISSUE TITLE
Failed image upload error message

### ISSUE THREAD

**Issue by rachelsquirrel** [wordpress-mobile/WordPress-iOS#4075]
When WordPress.com users reach the maximum capacity of their Media Library they can no longer upload images. The app doesn't explain why they can't upload images and only says "Failed". It would be great to let these users know that they either need to buy more space or free up some space in their Media Library first.

Here's what they see currently.

<img width="214" alt="slack-imgs com" src="https://cloud.githubusercontent.com/assets/7946521/8964140/cd343266-361b-11e5-874c-dcc8a79a3fea.png">

**Comment by rachelmcr** [comment]
This came up again today in Helpshift issue 80518. It very unclear to the user why the image upload fails in cases like this, especially because there's no way to manage the media library directly in the app or in Calypso.

**Comment by SergioEstevao** [comment]
@rachelmcr @rachelsquirrel @mattmiklic @astralbodies 

So I did a bit of research of the possible reasons for a failed upload, and they can be basically one of these:
 1. The HTTP upload request, timeouts or failed because of connectivity issues
 1. The media file format is not supported by the server, this is now minimised because we check for supported file types and if the server doesn't support it we convert to jpg or mov
 1. There isn't enough disk space/quota for the upload to succeed 

For each of these errors we get different error messages from the server and depending if they are coming from a WP.com or a WP.org site. Here are some examples:

**WP.org**
<img width="423" alt="screen shot 2016-02-03 at 12 38 03" src="https://cloud.githubusercontent.com/assets/651601/12784058/c7907c02-ca7c-11e5-8a79-6e4b836f7bac.png">


**WP.com**
<img width="423" alt="screen shot 2016-02-03 at 00 17 19" src="https://cloud.githubusercontent.com/assets/651601/12783902/e81de866-ca7b-11e5-876a-a2d085bcde7c.png">

As you can see each server type returns a different message, WP.com doesn't localise the error message, WP.org translate the error message depending of the site language.
I don't think it's a good idea to show the  message  that comes back from the server but instead show our own localised app message.

I dig a bit more and it's actually possible to distinguish between the errors using the error codes returned:

WP.com 

Server Error Code: upload_error
HTTP Error Code
400 -> Invalid file type
500 -> Not enough space

WP.org

HTTP Error Code
401 -> Not enough space
500 -> Invalid file type

So my plan is to add code to make the distinction between errors and show a message, my questions now are:

- What is the text of the message that we want to show to the user for each case?
- How to show the message?
  - Directly in the image, like the Failed message? Keep in mind that for some small images, the message may not fit inside the image
  - Keep the failed message, and only show it on a action sheet that is presented when you tap the image
  - Show the failed message in the image and in the action sheet?

<img width="423" alt="screen shot 2016-02-03 at 13 29 42" src="https://cloud.githubusercontent.com/assets/651601/12784024/a0112032-ca7c-11e5-8e4e-40c124519e78.png">

**Comment by rachelmcr** [comment]
>I don't think it's a good idea to show the message that comes back from the server but instead show our own localised app message.

Yes, I definitely agree.

>What is the text of the message that we want to show to the user for each case?

A few ideas that came to mind:

1. HTTP error code: "The app could not connect to your site to upload this media."
2. Invalid file type: "Your site does not support this media file format."
3. Not enough space: "Your site is out of space for media uploads."
4. Anything else we haven't anticipated: "The app couldn't upload this media."

I wouldn't put it only in the image, since as you mentioned the message may not fit (especially for short images like panoramas, for example), so the action sheet seems logical to me.

But I'd defer to @mattmiklic / you on the wording and where to display those messages.

Also, once Plans are in the app, we might want to offer WordPress.com sites a smooth way to upgrade if they are out of space.

One last thought: Do you think it would make sense to also give an option on the action sheet to contact support for more help? I'm thinking of cases where a file repeatedly fails to upload and the user might need more help identifying the exact error and getting guidance to fix it. (Like the "Contact us" link that starts a new Helpshift conversation when a user has a failed login attempt.) Not sure if that would just add clutter and draw attention away from the other actions, though.
