### ISSUE TITLE
iOS 5.5: Unable to login to share posts

### ISSUE THREAD

**Issue by JasonSnow-Mad** [wordpress-mobile/WordPress-iOS#4247]
In the most recent release, if you 'View' a post, and select the Sharing buttons, the login screen appears, but selecting 'Sign In' does not load the next page.

Tested and confirmed with Twitter and Facebook share buttons.

The page seems to attempt to send data and then stops, with the button disabled.

**Comment by rachelmcr** [comment]
I confirmed this issue from My Sites > Blog Posts > View > Tap a sharing button on the post. However, it seems that the best solution is to improve the native sharing options, as suggested in #3792, rather than focusing on the sharing buttons in the in-app browser.

I'm leaving this issue open, but will mark it low priority in favor of other solutions.

**Comment by rachelmcr** [comment]
To resolve #3792, a sharing button was added to the editor's preview. I'm closing this issue now that the Blog Posts section has an option to share posts within the app (rather than the in-app browser).
