### ISSUE TITLE
Facebook video doesn't render in "My Sites > View Site", but does in "Blog Posts > [post] > View" 

### ISSUE THREAD

**Issue by mdrovdahl** [wordpress-mobile/WordPress-iOS#4295]
Steps to reproduce:

1. create a new post with post content: ```https://www.facebook.com/zuck/videos/10102371249389011/```
2. publish post
3. select blog from "My Sites" in WP iOS app
4. select "View Site" and see blank space where video should be
5. close webkit window
6. select Blog Posts > [post] > View and see video rendered within post

**Comment by mdrovdahl** [comment]
FWIW, that post also renders properly in Mobile Safari.

**Comment by mdrovdahl** [comment]
Oops, accidental close. Reopening with screenshots attached (view site, preview, mobile safari). 
![view site doesn't work](https://cloud.githubusercontent.com/assets/474467/10032408/cd380b4c-6137-11e5-8468-9d8354148f61.PNG)

![preview works](https://cloud.githubusercontent.com/assets/474467/10032382/a34afeb6-6137-11e5-92a1-7c91d37fd4eb.PNG)

![mobile safari works](https://cloud.githubusercontent.com/assets/474467/10032415/d85b1e06-6137-11e5-92d6-d574e8cbf9a8.PNG)

**Comment by pypt** [comment]
I think this is because Facebook returns `application/xhtml+xml` MIME type for one of the video resources, `https://m.facebook.com/plugins/video.php?...`, and thus forces strict XHTML parsing for the page. However, Facebook returns an invalid XHTML document for that page (based on UIWebView's HTTP `User-Agent`) which UIWebView refuses to load with *Frame Load Interrupted* error.

To replicate:

1. Open desktop Safari, set your user agent to the one that looks like coming from UIWebView, e.g.:

        User-Agent: Mozilla/5.0 (iPad; U; CPU OS 4_3_2 like Mac OS X; en-us) AppleWebKit/533.17.9 (KHTML, like Gecko) Mobile

2. Go to one of the resources that Facebook's embed code tried to load:

        https://m.facebook.com/plugins/video.php?allowfullscreen=true&app_id=249643311490&channel=https%3A%2F%2Fs-static.ak.facebook.com%2Fconnect%2Fxd_arbiter%2FwjDNIDNrTQG.js%3Fversion%3D41%23cb%3Df3b81eeab8%26domain%3Dpypt.wordpress.com%26origin%3Dhttps%253A%252F%252Fpypt.wordpress.com%252Ffc8ea70d%26relation%3Dparent.parent&container_width=288&href=https%3A%2F%2Fwww.facebook.com%2Fzuck%2Fvideos%2F10102371249389011%2F&locale=en_US&sdk=joey

    (this shouldn't contain my Facebook credentials, but if it does, please don't hack me.)

3. Shake head at the XML error:

    ![](http://i.imgur.com/vgo8Yko.png)

4. Now set the user agent to the one that mobile Safari might use:

        User-Agent: Mozilla/5.0 (iPad; U; CPU OS 4_3_2 like Mac OS X; en-us) AppleWebKit/533.17.9 (KHTML, like Gecko) Version/5.0.2 Mobile/8H7 Safari

5. Open the page again, confirm that Zuck's video is playing fine.

I've tried setting user agent via `User-Agent` key in `NSUserDefaults`, seems to work too.

You should probably try [reporting it to Facebook](https://developers.facebook.com/bugs/) first, and if it doesn't work, setting your own, mobile Safari-like UA in the app.

**Comment by pypt** [comment]
Also, I believe Facebook videos work in *Blog Posts > [post] > View* because resources are being loaded via HTTP, not HTTPS, on that view.

**Comment by pypt** [comment]
I somehow managed to miss the fact that WordPress-iOS sets its own HTTP User-Agent. Also, Facebook's video now sends back `text/vnd.wap.wml` MIME type instead of the XHTML one from yesterday.

The problem still seems to be in the User-Agent header, so I'd like to propose changing it to a more detailed one which merely appends `wp-iphone/<version>` string to the UIWebView's default user agent header instead of rewriting it (see my pull request).

While changing UA might have some implications on poorly written browser detection libraries (e.g. the ones that expect `wp-iphone` string to be at the start of the UA), sending out an extended User-Agent could help prevent some future problems with server-side browser detection.

Facebook video with the new UA:

![](http://i.imgur.com/c3hGhLU.png)
