### ISSUE TITLE
i18n: String for "Post" lacks necessary context for translation

### ISSUE THREAD

**Issue by utopianism** [wordpress-mobile/WordPress-iOS#4368]
hi, i found an i18n translation wrong:

if ([self.post.status isEqualToString:PostStatusPublish]){
            buttonTitle = NSLocalizedString(@"Post", @"Publish button label.");
  }

here "Post" should be "发布"  in Localizable.String(Chinese(Simplified))

<img width="373" alt="abc" src="https://cloud.githubusercontent.com/assets/13003542/10694608/b1ec5a66-79d1-11e5-839b-7c854f52e5ce.PNG">

**Comment by rachelmcr** [comment]
Thanks for pointing out this error! All of the app's translations are managed through GlotPress on WordPress.org here:

https://translate.wordpress.org/projects/apps/ios/dev/zh-cn/default

Here is a direct link to that string "Post" and all of its past translations, including your suggestion that I just added:

https://translate.wordpress.org/projects/apps/ios/dev/zh-cn/default?filters[status]=either&filters[original_id]=94824&sort[by]=translation_date_added&sort[how]=asc

The new translation "发布" will need to be approved by one of the project's validators before it is used in the app.

I am leaving this issue open, because we should also improve the context for that string to clarify that it is a verb, not a noun. (Current context is just a repeat of the string "Post.")

**Comment by rachelmcr** [comment]
This is a more complicated case than I thought. There are two "Post" strings in the app, one that's a verb and one that's a noun.

The verb is the publish button label:
> buttonTitle = NSLocalizedString(@"Post", @"Publish button label.");
Sources:
https://github.com/wordpress-mobile/WordPress-iOS/blob/8f231977c4ebb0337ede7657a38bd64b90f0a288/WordPress/Classes/ViewRelated/Post/WPPostViewController.m#L1287
https://github.com/wordpress-mobile/WordPress-iOS/blob/8f231977c4ebb0337ede7657a38bd64b90f0a288/WordPress/Classes/ViewRelated/Post/WPLegacyEditPostViewController.m#L508

The noun is a placeholder title:
> self.title = self.post.postTitle ?: NSLocalizedString(@"Post", @"Placeholder title for ReaderPostDetails.");
Source:
https://github.com/wordpress-mobile/WordPress-iOS/blob/4d63a17c9b1707d0369405eab79fdc7d65ef88ed/WordPress/Classes/ViewRelated/Reader/ReaderPostDetailViewController.m#L350

As a result, there is a single translatable string that can't be translated correctly for the two different contexts:
https://github.com/wordpress-mobile/WordPress-iOS/blob/a74033d7b5b745911b316b3a955447287b46bc8a/WordPress/Resources/en.lproj/Localizable.strings#L1353

In addition, neither comment is pulled in to GlotPress to provide information for translators who are translating the string.

We need to abstract the strings to allow for different contexts (e.g. "noun" and "verb") so the same string can be translated differently according to context.

**Comment by rachelmcr** [comment]
This is related to #3829 — when the same string has multiple comments, the different comments aren't being pulled into GlotPress or used to differentiate the strings. I'm going to close this issue, as this specific string will be fixed once that issue is resolved.
