### ISSUE TITLE
Update Tab Bar Icons to Match Latest on Web

### ISSUE THREAD

**Issue by sendhil** [wordpress-mobile/WordPress-iOS#4546]
Reference - https://github.com/Automattic/wp-calypso/pull/631

**Comment by oguzkocer** [comment]
@mattmiklic Would it be possible for you to export the new icons for iOS or do you know who I should ping for it? I've uploaded the current icons here for reference: https://cloudup.com/cL0mPOlDtoS @3x versions are 75x75 pixels.

**Comment by mattmiklic** [comment]
Yes, sure can, and thanks for uploading the existing icons so I can compare. Let me just confirm that no other changes are happening before they are committed on the web side.

**Comment by oguzkocer** [comment]
Sounds good, thanks a lot :)

**Comment by mattmiklic** [comment]
The new icons are 32px x 32px (except for New Post, which is larger because of its background) and remove the text labels from the tab bar, to match what we're doing on the web and Android. Here's a mockup:

![ios](https://cloud.githubusercontent.com/assets/1396552/11814233/b3c738d6-a313-11e5-87f6-30ef9be0d7dd.png)

Here are measurements for laying out the new icons on the tab bar:

<img width="1603" alt="screen shot 2015-12-15 at 10 05 50 am" src="https://cloud.githubusercontent.com/assets/1396552/11814235/bda98b38-a313-11e5-9096-f9b8c13d3a21.png">

Here's the new icons in their default color:

[tab-me.pdf](https://github.com/wordpress-mobile/WordPress-iOS/files/62627/tab-me.pdf)
[tab-mysites.pdf](https://github.com/wordpress-mobile/WordPress-iOS/files/62626/tab-mysites.pdf)
[tab-newpost.pdf](https://github.com/wordpress-mobile/WordPress-iOS/files/62625/tab-newpost.pdf)
[tab-notifications.pdf](https://github.com/wordpress-mobile/WordPress-iOS/files/62628/tab-notifications.pdf)
[tab-reader.pdf](https://github.com/wordpress-mobile/WordPress-iOS/files/62629/tab-reader.pdf)

And here they are in the mediumBlue highlight color, if you need them (I'm not sure if we're changing the color in code or using separate images):

[tab-me-active.pdf](https://github.com/wordpress-mobile/WordPress-iOS/files/62630/tab-me-active.pdf)
[tab-mysites-active.pdf](https://github.com/wordpress-mobile/WordPress-iOS/files/62631/tab-mysites-active.pdf)
[tab-newpost-active.pdf](https://github.com/wordpress-mobile/WordPress-iOS/files/62634/tab-newpost-active.pdf)
[tab-notifications-active.pdf](https://github.com/wordpress-mobile/WordPress-iOS/files/62633/tab-notifications-active.pdf)
[tab-reader-active.pdf](https://github.com/wordpress-mobile/WordPress-iOS/files/62632/tab-reader-active.pdf)

**Comment by mattmiklic** [comment]
Non-selected icons:
[tab-me.pdf](https://github.com/wordpress-mobile/WordPress-iOS/files/62655/tab-me.pdf)
[tab-mysites.pdf](https://github.com/wordpress-mobile/WordPress-iOS/files/62656/tab-mysites.pdf)
[tab-newpost.pdf](https://github.com/wordpress-mobile/WordPress-iOS/files/62654/tab-newpost.pdf)
[tab-notifications.pdf](https://github.com/wordpress-mobile/WordPress-iOS/files/62657/tab-notifications.pdf)
[tab-reader.pdf](https://github.com/wordpress-mobile/WordPress-iOS/files/62658/tab-reader.pdf)

Selected icons:
[tab-me.pdf](https://github.com/wordpress-mobile/WordPress-iOS/files/62659/tab-me.pdf)
[tab-mysites.pdf](https://github.com/wordpress-mobile/WordPress-iOS/files/62661/tab-mysites.pdf)
[tab-newpost.pdf](https://github.com/wordpress-mobile/WordPress-iOS/files/62660/tab-newpost.pdf)
[tab-notifications.pdf](https://github.com/wordpress-mobile/WordPress-iOS/files/62663/tab-notifications.pdf)
[tab-reader.pdf](https://github.com/wordpress-mobile/WordPress-iOS/files/62662/tab-reader.pdf)

I believe that Xcode should be able to export the 2x, 3x, etc. versions automatically from PDFs, but let me know if you have any trouble and I'll export them as PNGs manually.
