### ISSUE TITLE
Geolocation details has wrong bottom bar style

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#4597]
Title has it.  Another one we need to update.

![simulator screen shot dec 18 2015 11 13 20 am](https://cloud.githubusercontent.com/assets/1435271/11902590/76e91cd8-a578-11e5-8958-2f5cfc4e9ba7.png)

**Comment by SergioEstevao** [comment]
@aerych what do you think to just move the icons to the top right of the navigation bar?

**Comment by aerych** [comment]
I'd worry some about users tapping the delete button when they were trying to reload. Might be worth experimenting with.  Maybe @mattmiklic would have some other ideas?

**Comment by mattmiklic** [comment]
Don't think I'll have time to mock this up before the holiday break I'm afraid -- but off the top of my head, I'd think about moving Refresh into the toolbar, but making "Remove Location" a destructive button (red text, white background, centered, full width) below the map.

**Comment by SergioEstevao** [comment]
@mattmiklic even if we have the trash button on the navigation bar we still do the confimarion of the removal with the action sheet.

Another thing to take in account with the removal button on the bottom is the iPAD it will be a big button.

Other option is to put the relocation button on the left near the back button and the trash on the right of the navigation bar.

**Comment by mattmiklic** [comment]
Took a little time today to think this through. The trash button doesn't really make sense to me, since nothing is being moved into a trash or being deleted; it's really more of an on/off switch. So I tried a new design, using a toggle switch in the post settings menu. When it's disabled, the map is not shown. When it's enabled, the map is shown similar to the current design. When you tap it, you open a full-screen map with no bottom bar, and a sync icon in the upper right corner.

This has the benefit of being clearer (a text label and familiar toggle switch instead of a potentially confusing trash icon) and it answers the question of where we put the functionality. I also think it would work well on the iPad layout.

I've also renamed the header from "Geolocation" to "Location" to match the label we use in Calypso. We'd need to update the label in Site Settings as a result.

![location](https://cloud.githubusercontent.com/assets/1396552/12929744/64248e7c-cf42-11e5-84ff-fac6f1ac3732.png)

**Comment by SergioEstevao** [comment]
@mattmiklic This is looking great! I will implement like that for now.

Bu just one question, is there any reason for us to only allow the use of the current location? Did we ever consider the possibility of the user select a location manually? By moving the pin or searching for a location? Maybe @aerych or @sendhil now something about this?

**Comment by aerych** [comment]
> Did we ever consider the possibility of the user select a location manually

We totally need to do this :)  Would especially be great for folks who have trouble with their GPS and could then just enter an address and adjust the pin position as needed.

**Comment by sendhil** [comment]
Allowing users to move around their location sounds neat to me.

**Comment by SergioEstevao** [comment]
Create a new issue https://github.com/wordpress-mobile/WordPress-iOS/issues/4808 to allows changing the location manually.

**Comment by mattmiklic** [comment]
@SergioEstevao One small addition here; let's add the standard disclosure indicator to the row that contains the address, so the user knows that they can tap it to edit the location.

<img width="787" alt="screen shot 2016-02-09 at 8 10 48 pm" src="https://cloud.githubusercontent.com/assets/1396552/12936143/6558e668-cf69-11e5-9d48-aac5a1f64a27.png">

**Comment by SergioEstevao** [comment]
@mattmiklic 

While trying to sort this out I find out some usability issues, so what do we do for these scenarios:

- The user opens settings, geo location is on but the post still doesn't have a location so we show them the location switcher
- When the user switches user location to on, we try to find the location but then an error occurs because of one of these scenarios:
  - location updates are disabled for the app because the user changed the setting
  - location request fails, because user is offline or inside the Tube/Subway or something similar
 
Do we still show the map? and show an error message there? Just show an alert?

Another thing that is strange at the moment, is that if geolocation is on for the site, the moment you open the editor for a new post we immediately start a location request, so if you then open post settings you can see the switch on the disables state and then switch to the Enabled state by itself because the location request completed.

I understand the idea of doing the location request immediately but it can be very confusing for the user, specially when it's the first time, and permission needs to be granted by him. He should only do it if permission was already granted before and if location is working correctly.

ping @aerych @sendhil

**Comment by SergioEstevao** [comment]
I had a look on Calypso, and on there we never try go the location automatically, it always need to be triggered by the user and they also allow to search for locations manually.

**Comment by mattmiklic** [comment]
> I had a look on Calypso, and on there we never try go the location automatically, it always need to be triggered by the user and they also allow to search for locations by entering place names.

I think we should follow this convention in the native apps then, too. That way it's always turned on/off in response to the user's action.

> The user opens settings, geo location is on but the post still doesn't have a location so we show them the location switcher
> When the user switches user location to on, we try to find the location but then an error occurs because of one of these scenarios...

I should probably mock something up for these two states. I'll take a look at this tomorrow.

**Comment by mattmiklic** [comment]
I took a look at this today, and here's what I came up with:

![location](https://cloud.githubusercontent.com/assets/1396552/13022806/9dbc7282-d1b1-11e5-94c2-035253303639.png)

Once I started digging into this, I realized there was a state where the user has turned on their location, but it could not be automatically determined and they haven't chosen one themselves. But the toggle switch is still set to "on." So I think I may need to re-think the toggle switch as the solution here. I can look further at this next week, but let me know if you have any comments.

**Comment by SergioEstevao** [comment]
@mattmiklic I worked a bit on this today, and I did it a bit different:

When you enable the location by clicking on the switch I show a cell that says "Finding your location...". But if the location request fails by any reason I show an alert explaining why and then when the user clicks OK I put the switch back to off.

<img width="393" alt="screen shot 2016-02-12 at 23 44 57" src="https://cloud.githubusercontent.com/assets/651601/13023785/238d8144-d1e4-11e5-9ff2-7392b688f2d5.png">
<img width="393" alt="screen shot 2016-02-12 at 23 45 10" src="https://cloud.githubusercontent.com/assets/651601/13023787/28b4526a-d1e4-11e5-8bdf-c0e231b45cef.png">

**Comment by mattmiklic** [comment]
> But if the location request fails by any reason I show an alert explaining why and then when the user clicks OK I put the switch back to off.

I think this is fine, the only issue I see with this is that if the user's location couldn't be determined, there's no way for them to get to the map screen to search for and choose a location manually.

Could the modal alert's two options be 'Cancel' and 'Search' (or something similar)? The user could tap cancel to switch off the location, or Search to open the detail screen and search for one manually.

**Comment by SergioEstevao** [comment]
@mattmiklic yes we can add the "Search" option I will do that on the specific PR for adding search.

Besides this two other things:

 - What is the font style, size and color that you are using for the coordinates label?
 - Do you think we could have a better icon for the refresh current location the two arrows don't look very clear, in iOS it's normally used the arrow... do we have anything standard for WordPress?

**Comment by mattmiklic** [comment]
> Do you think we could have a better icon for the refresh current location the two arrows don't look very clear, in iOS it's normally used the arrow... do we have anything standard for WordPress?

Yeah, instead of the refresh icon, I think we could use the location icon. I think that's more in line with the kind of icon (though ours is a gridicon, obviously) that the native Maps app uses to re-center the map on your current location.

[gridicons-location.pdf](https://github.com/wordpress-mobile/WordPress-iOS/files/131638/gridicons-location.pdf)

**Comment by mattmiklic** [comment]
> What is the font style, size and color that you are using for the coordinates label?

Open Sans Semibold, 11pt, all caps. `grey`.
