### ISSUE TITLE
Revise the sign in error title

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-iOS#4717]
The app currently displays a `Sorry, we can't log you in.` message when, for example, the username or password is incorrect.

That message feels a bit aggressive (almost like "we _won't_ log you in" and its "we" part doesn't suit well for a self-hosted site anyway.

Perhaps a "Sign in was unsuccessful," or "An error has occurred" message would be more suitable.

**Comment by catehstn** [comment]
@rachelmcr - do you have a suggestion for better wording here?

**Comment by rachelmcr** [comment]
This is a tough one. Personally, I like the clarity of the message "Sorry, we can't log you in." More generic errors seem unhelpful — what about just removing the title and focusing on the exact error message?

If we want to replace it: I find that the current wording tends to lead users to think the problem is on the app's end (especially because of the word "we"), even when the problem is on the site's end (e.g. the site doesn't accept the username/password), so if we change the wording I'd suggest focusing on that aspect of it.

Some ideas:

- "Login was unsuccessful" (I'd suggest for "login" rather than "sign in" for consistency)
- "Login Error"
- "There was a problem logging you in."

**Comment by mattmiklic** [comment]
> I find that the current wording tends to lead users to think the problem is on the app's end (especially because of the word "we")

Yeah, I think anthropomorphizing the app with "we couldn't" probably doesn't help.

I looked at a few outside examples to see what works well. On Facebook, entering an email that isn't associated with an account gives you a specific error: "The email you've entered doesn't match any account. Sign up for an account." If you get your email right, but password wrong, the error is "The password you've entered is incorrect. Forgot password?" I like that these errors give proactive suggestion to fix the problem.

Calypso has a good error for an incorrect password: "The password you entered for the email or username [username] is incorrect. Lost your password?" If the username is wrong, the error isn't quite as good: "Invalid email or username. Lost your password?" A better one might be "The username you entered could not be found." In our case, what to suggest is trickier; because the username could be wrong because they're self-hosted and trying to sign in to dotcom, or because they just mistyped it.

**Comment by rachelmcr** [comment]
We also have specific errors, that appear under the more general error title. For example, in the case of an incorrect username/password combo:

![2017-01-23 14 12 12](https://cloud.githubusercontent.com/assets/8658164/22207280/7567430e-e176-11e6-89ec-aa2213cce058.png)

@mattmiklic Do you think it might be worth just removing the general `Sorry, we can't log you in` title and focusing instead on the specific error message (and how we might improve that with calls to action or changes in the wording there)?

**Comment by nheagy** [comment]
That sounds like a good plan to me, @rachelmcr 

Is any of this worth some quick usability tests?

**Comment by mattmiklic** [comment]
>  Do you think it might be worth just removing the general Sorry, we can't log you in title and focusing instead on the specific error message (and how we might improve that with calls to action or changes in the wording there)?

Yep, 👍 to that. Just dropping the "sorry" line and having a single line with a more specific error would help. Adding proactive suggestions on how to fix the problem is something I'd get analytics on but I don't know if it'd be as compelling as a user test.
