### ISSUE TITLE
Reader: Preview sites from "Followed Sites" list

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#4742]
It would be so lovely to be able to preview the posts on a site from the "Followed Sites" list in the reader's menu. It could be the same as the "Site Details" view you get when tapping on a post in the reader, but this way you could see the posts on any site you follow (including sites that haven't posted recently, or whose post is buried further down in the reader and can't be quickly found again).

I find myself looking for this feature once every week or two. A user also recently requested this feature (in an app review).

@aerych It looks like this was initially proposed in #2150 and intended to be added per #3030, but #3248 didn't include it (only implementing the preview from the reader, not the followed sites list). Was there a reason for not adding site detail/preview to the followed sites list as well?

**Comment by aerych** [comment]
The menu as it currently exists is going away with #4094, so adding new functionality doesn't really make sense.  The updated menu should support previewing a site.  No ETA on this as the iOS reader is currently taking a backseat to some other feature work. 

> Was there a reason for not adding site detail/preview to the followed sites list as well?

I'm fuzzy on the details but I remember that time was a factor as work on the reader was being suspended in order to work on other things (similar to the situation today).  Enabling site previews from the menu was not a trivial change so the priority was given to previewing sites a user was not already following.

**Comment by aerych** [comment]
Closing.  Will be handled in #4094

**Comment by rachelmcr** [comment]
Thanks for clarifying! Adding new functionality now definitely doesn't make sense given the plan to change the menu down the road. I'll look forward to the updated menu when more work is done on the iOS reader.

**Comment by aerych** [comment]
Cool :)  The menu refresh is very high on my wish list.  I think its going to be a coin toss between it and comments as to which we'll do first.

**Comment by rachelmcr** [comment]
I'll go see if I can find a two-headed coin for that coin toss ... :D
