### ISSUE TITLE
Allow users to set the post location manually

### ISSUE THREAD

**Issue by SergioEstevao** [wordpress-mobile/WordPress-iOS#4808]
Instead of only relaying on the device location to set post location allows users to set the location of a post by introducing manually a location.

**Comment by mattmiklic** [comment]
UI I think could be fairly simple, adding a search bar like this:

<img width="798" alt="screen shot 2016-02-09 at 8 01 06 pm" src="https://cloud.githubusercontent.com/assets/1396552/12935970/fc408a92-cf67-11e5-952f-05711af4b02a.png">

Since you can already pan and zoom the map, it would be nice if you could tap and hold on it to drop a pin (to use as the location), but that's not essential.

**Comment by SergioEstevao** [comment]
@mattmiklic there is no standard UI interface for search results in MapKit, so I was planning to do something similar to what Apple Maps does, on search? A simple table view bellow the search bar?

**Comment by mattmiklic** [comment]
> I was planning to do something similar to what Apple Maps does, on search? A simple table view bellow the search bar?

Perfect; I think that's the best pattern to follow.

**Comment by SergioEstevao** [comment]
Me and @mattmiklic discusses a bit about this feature and decide to do the following:

- Change the on switch for location for a "Set location " like “set featured image” link style
- This opens a new view from the bottom, so we can put “Remove” in the upper left corner, “Done” in the upper right. This is clearer than the trash icon, and makes it more obvious that you are setting a location than a back button.
- Current location is the top item when you tap the search bar
- The last one shows the location once it’s been set in the post settings screen.

![location](https://cloud.githubusercontent.com/assets/651601/13140071/d2ffb2ae-d627-11e5-8a4e-13470540c01f.png)

**Comment by SergioEstevao** [comment]
@mattmiklic The issue of doing it modal it's that all other screen on setting are using the push paradigm should we change them all? Also if use modal we shouldn't use the chevron when we already have a location.
What about keeping the push navigation but use a remove label on the top right?

**Comment by mattmiklic** [comment]
> What about keeping the push navigation but use a remove label on the top right?

The reason I designed it that was was so that the options would be "Remove" and "Done" (or Save if you like) instead of "Back" and "Remove" -- I think the first set of buttons is clearer and more obvious. I think the Featured Image setting could work the same way. Good catch about the chevron, we should remove that from the location row if we go with this layout.

If there's a technical reason to use a Back button and put Remove in the upper right corner instead, that's ok.

**Comment by SergioEstevao** [comment]
We can still use push navigation and replace Back for Done or Save...

**Comment by SergioEstevao** [comment]
We should create another ticket to redesign or restyle the post settings screen... it's a bit of a mix UI at the moment.
