### ISSUE TITLE
Calypsoification - Domain Search

### ISSUE THREAD

**Issue by alexcurylo** [wordpress-mobile/WordPress-iOS#4882]
Task list for implementing the first version of Calypso Domain Search/Management features:
- [ ] Add WPcom domain management APIs to Site Management service
  (Pending final design/feature specifications for first version:)
- [ ] Display currently owned domains for user management
- [ ] Activate search with list of suggested domains
- [ ] Perform search and display results
- [ ] Collect registration information for selected domain
- [ ] Purchase domain via IAP (or other allowable methods)
- [ ] Implement analytics for shipping feature set

**Comment by rachelmcr** [comment]
The ability to search for and register a custom domain is implemented for the Business plan (released in https://github.com/wordpress-mobile/WordPress-iOS/pull/10490). Since there are no longer plans to implement domain purchase for now, or immediate plans to expand domain registration flows, I'm going to close this issue. We can reopen it or create a new issue for future domain projects.
