### ISSUE TITLE
Inserted images are not set as attachments or have dimensions

### ISSUE THREAD

**Issue by apeatling** [wordpress-mobile/WordPress-iOS#4942]
When inserting an image into a post, the image is not properly attached to the post so meta data can be accessed. The image also is set without any dimensions in the HTML tag. This is causing a problem in the browser, where images cannot be displayed in the posts list for a site in Calypso.

See this issue for more details: https://github.com/Automattic/wp-calypso/issues/3954

### Steps to reproduce the behavior

Create a new post in the editor and upload a single image. Publish the post. Go to Calypso in the browser and look at your /posts page for the site. You will notice the image does not show for the post in the list. This is because there is no attachment data to fetch the size of the image, and there's no dimensions set on the image.

##### Tested on [device], iOS [version]

Latest beta, and stable. iOS 9.3 public beta latest, iPhone 6 Plus

**Comment by rralian** [comment]
Here's the data for an example affected post:

![affected post](https://cloudup.com/cHLO_nSZ3xA+)

**Comment by sendhil** [comment]
cc @SergioEstevao

**Comment by SergioEstevao** [comment]
I went to investigate this a bit, and remember myself what where the issues that we had with attaching media to posts in mobile.

When we create a post in mobile, it only exists locally in the device and it doesn't have an id until we press the save button.

So while we are writing the content of the post and attaching images to it, these images are created and send to the server but without any related post id, because we still don't know what this will be.

After we save the post, we finally get the post id, but there isn't any way to update the post directly to say all the media ids that are attached to it. 

The only way to update them is to do a call to the media endpoint to update each individually media with the parent ID, this can involve some extra calls or a big batch call but it's possible, should this be a priority? 

@apeatling @sendhil @rralian

**Comment by apeatling** [comment]
This is a really obvious bug when looking at your posts list on the web, so it would be good to see it fixed as soon as it makes sense. /cc @astralbodies mind if we prioritize this one and get it cleared up?

**Comment by SergioEstevao** [comment]
I dig it up a bit more and find out that we didn't have the notion of parent post on the media table for the iOS database. This will need some work for sure. @astralbodies Do you mind if I tackle this next week?

**Comment by sendhil** [comment]
@SergioEstevao i think it's fine to work on it for the next release. Given the likely core data changes lets target 6.2.

**Comment by diegoreymendez** [comment]
Remember to tag closed issues for the release they're delivered in.  It's a minor thing that helps a ton with the release notes.

Thanks!
