### ISSUE TITLE
ServiceRemoteXMLRPC causing crash with nil objects being inserted

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#5199]
Crash report: http://crashes.to/s/6f88b62a61c

Looks like we're trying to insert a nil object into an array and its causing a sporadic crash. Will probably do a 6.1.1 release to address this.

**Comment by koke** [comment]
`defaultXMLRPCArguments` and me are old friends. I don't know how many times I've _fixed_ this, and it's starting to feel like this:

![kitty-whack-a-mole1](https://cloud.githubusercontent.com/assets/8739/14815376/58dc3812-0bab-11e6-84d5-ee741bc1d7a8.gif)

I think the underlying problem is #687 (but not just for wp.com), and we can keep patching this to prevent a crash, but that won't stop the error.

IMO, the `ServiceRemoteXMLRPC` initializer should fail with a `nil` username or password, which means  the services would get a `nil` remote, and their callback blocks would never be called, so the refresh controls would spin forever and the user would have no idea of what's going on.

Just preventing the crash would be as simple as this:
https://gist.github.com/koke/4ed944677570308f0b0c139d545fea7b

Change the `nil` to an empty string and the crash is gone. This will probably mean that the user will start getting "Invalid username or password" alerts. That sounds better than a crash, but doesn't really address why the password was missing.

**Comment by astralbodies** [comment]
@koke Is this something you want to try to patch?

**Comment by koke** [comment]
I can do it but I'm a bit overwhelmed right now with PR reviews, if this is urgent feel free to patch it. The gist link I posted in my previous comment should at least get rid of the crash.

**Comment by koke** [comment]
I've done the PR against 6.2 since I think it's going out very soon. Let me know if we want to patch 6.1 instead

**Comment by koke** [comment]
Some more insight, as this might not be just a self hosted issue:

If the wp.com OAuth2 token is gone from the keychain, the app launches, tab bar loads. If you have VC restoration and you were looking at the site details last, viewDidLoad triggers a syncBlog, syncBlog tries to get a remote, checks blog.restApi, which looks at account.restApi, which returns nil, because there's no auth token.
So it uses XML-RPC, but it doesn’t have username or password because we don't store those for wp.com blogs, and it crashes.
