### ISSUE TITLE
Reader: Can't select/copy/define text in a Reader article in WPiOS app

### ISSUE THREAD

**Issue by alisterscott** [wordpress-mobile/WordPress-iOS#5204]
### Expected behavior

I expect to be able to select any text in a Reader article to copy it, or use the iOS in built 'define' feature which I often use to understand what words mean that I don't know. This works as expected on the Calypso Reader in iOS Safari

### Actual behavior

Select/copy/define is disabled in the WPiOS Reader

### Steps to reproduce the behavior

1. Open WPiOS Reader
2. Try to highlight a word or sentence by holding down

##### Tested on [device], iOS [version], WPiOS [version]

iPhone 6+, iOS 9.3.1, WPiOS 6.2 beta, also tested WPiOS 6.1. 

##### How this appears in Mobile Safari

![Mobile Safari Highlight](https://cloud.githubusercontent.com/assets/128826/14801213/0bc42da2-0b8b-11e6-835f-f8fa324eb8eb.jpg)

##### Doesn't work in WPiOS app

![ios app](https://cloud.githubusercontent.com/assets/128826/14801302/a15d20bc-0b8b-11e6-95af-ac5eed6851db.jpg)

**Comment by aerych** [comment]
Hi @alisterscott 
This isn't a bug, but an unfortunate limitation due to the library, DTCoreText, that we're using to render rich text in the reader. 
We very much want to replace this with a more modern solution that supports text selection.  We have a replacement in the works called WPTextKit, but it still needs a bit of work before its ready but its on our radar.
