### ISSUE TITLE
BlogListViewController bypassing site list with multiple sites

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#5230]
### Expected behavior

Logging into the app or tapping the tab bar item for My Sites should show the list of sites when more than one site configured.
### Actual behavior

Logging into the app is causing the first site in the list to be selected showing the blog details and not the blog list.
### Steps to reproduce the behavior
1. Log into the app with a .com account having multiple sites.
2. Tap on My Sites if not already selected.
3. First blog is selected.
##### Tested on iPhone 6s Plus Simulator, iOS 9.3, WPiOS develop

cc: @sendhil only because I see you wrote the original feature `shouldBypassBlogListViewControllerWhenSelectedFromTabBar`

**Comment by frosty** [comment]
@astralbodies I've just been looking into this. Currently the app attempts to push the site detail for either the last used site, or first site in the list. It's a pretty simple fix to prevent that behaviour, as we can just remove some code. However, I just wanted to check what you think the 'correct' behaviour should be – should we always just show the sites list when the app launches, or should we ever take a user back into site details for a site if they had it open when the app was quit?

**Comment by astralbodies** [comment]
@frosty Ahha okay that makes some sense. I'd find out from @mattmiklic from his perspective what the best UX is in this case. I found it somewhat jarring.

**Comment by mattmiklic** [comment]
> However, I just wanted to check what you think the 'correct' behaviour should be – should we always just show the sites list when the app launches, or should we ever take a user back into site details for a site if they had it open when the app was quit?

This is interesting, because I just tested it and the behavior I encountered wasn't the same as what was originally described in the issue.

- If I disconnect from a WordPress.com account using the link on the Me screen, and then immediately log back in, I'm taken back to the Me screen.
- If I disconnect from a WordPress.com account using the link on the Me screen, and then force quit the app, then log back in, I'm taken to my list of sites.

I tried deleting the app and re-installing, and when I logged in, I was taken to my list of sites. So I wonder if this behavior has changed since the ticket was originally opened?

I actually think the behavior described in the ticket is the best behavior, though, because it would match the experience of logging in to Calypso on the web. There, we automatically take users to the Reader, but if they tap on the My Sites icon, the first thing they see is the menu for their primary site, not their list of sites.

**Comment by hoverduck** [comment]
I'm seeing the same behavior as @mattmiklic above, a fresh login is taking me to my list of sites first.  So that meets with the initial intent of this bug report, but is different from what you see in Calypso web (per the last block of Matt's comment above).

So do we close the ticket as fixed, or use it to drive the change to match the web behavior and default you to your primary site?

**Comment by mattmiklic** [comment]
If it's a trash pickup-level of work I'd say there are benefits to matching the UX of Calypso wherever possible. If it's more involved, maybe it should wait until our project related to login; it may have effects on where we end up deciding to send people after a successful login.

**Comment by hoverduck** [comment]
Thanks @mattmiklic.  I've added the Login label so it can be addressed under that project.

**Comment by kurzee** [comment]
Quick note on this one, if we do change this behavior away from defaulting to showing blog details, we will have to switch around when and where the "big sync" is called. Currently it's called once the blog details is selected or auto-selected, which syncs blog details, settings, categories, post formats, etc. Ref: https://github.com/wordpress-mobile/WordPress-iOS/pull/6461#issuecomment-275362001

**Comment by aerych** [comment]
Closing as the behavior in the app appears to have been fixed since this was last commented on.  The site detail is shown after logging in as described https://github.com/wordpress-mobile/WordPress-iOS/issues/5230#issuecomment-223694295
