### ISSUE TITLE
XML-RPC: Consider adding referrer headers to XML-RPC requests from the app.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#5263]
Apparently some hosts are blocking XML-RPC requests that do not include an HTTP referrer. 
See: https://ios.forums.wordpress.org/topic/xml-rpc-is-is-safe?replies=5#post-14635

**Comment by koke** [comment]
We can evaluate adding a `Referrer` header, as we've done other tweaks in the past to make the app work with badly configured hosts. 

From [RFC 7231](https://tools.ietf.org/html/rfc7231) (HTTP/1.1):

> Some servers use the Referer header field as a means of
   denying links from other sites (so-called "deep linking") or
   restricting cross-site request forgery (CSRF), but not all requests
   contain it.

> If the target URI was obtained from a source that does not have its
   own URI (e.g., input from the user keyboard, or an entry within the
   user's bookmarks/favorites), the user agent MUST either exclude the
   Referer field or send it with a value of "about:blank".

We could try sending `about:blank`, although I have this feeling that hosts blocking requests with no `Referrer`, will require it to match the site's domain.

> The basic protection rule implemented on the Webserver denies any POST request
without a valid local Referrer in order to prevent brute-force login attacks.

Overall, I think this is a badly configured host making the wrong assumptions about how the web works. We shouldn't deviate from the standard just to make it work. I'd close this as _wontfix_.

**Comment by aerych** [comment]
> Overall, I think this is a badly configured host making the wrong assumptions about how the web works. We shouldn't deviate from the standard just to make it work. I'd close this as wontfix.

A valid point, and its probably not sustainable for us to accommodate all the random things hosts can do to cause conflicts with the app.  

However, I'd like us to see if this is a wide spread practice. If it is I think it would make sense to add a referrer.

**Comment by koke** [comment]
>  I'd like us to see if this is a wide spread practice

It's a single data point, but in all these years, it's the first time I hear of this one 😄

**Comment by hoverduck** [comment]
@aerych / @koke - This ticket is 8 months old with no traffic, so I'm guessing you haven't discovered that this is a widespread practice.  I'm closing, but feel free to re-open if it's still something you want to add.

**Comment by aerych** [comment]
+1 to close
