### ISSUE TITLE
Crash on Blog Settings with possible malformed Jetpack site data

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#5304]
### Expected behavior

Viewing site settings shows the proper screen.
### Actual behavior

Site settings crashes upon viewing the screen.
### Steps to reproduce the behavior
1. There is some precursor on the Jetpack side that may be related to Post Status being renamed which is causing this crash to happen.
2. View Site settings.
3. Crash.

Crash reports: http://crashes.to/s/9326ba10dac

**Comment by krogsgard** [comment]
I tested three .org sites and one .com site, and it only happens on one .org site, (Post Status). There is another issue occurring as well, where Jetpack got confused at the creation of a staging site and the name is messed up there, so I'm not sure if maybe that's related somehow.

**Comment by hoverduck** [comment]
@astralbodies I wasn't able to reproduce this on my .org sites...do you know if it's still a problem, or have any idea on better repro steps?

Tagging with [Pri] High because it's a crash, but if there's no way to reproduce it and nobody's seen it in the last 8 months we  can probably downgrade/close.

**Comment by astralbodies** [comment]
I'm not seeing the crash anymore through Fabric/Crashlytics so I think it's resolved. Closing!
