### ISSUE TITLE
Sharing from WPiOS to social media does not link to post

### ISSUE THREAD

**Issue by kristarella** [wordpress-mobile/WordPress-iOS#5426]
### Expected behavior

It is now possible to use the iOS text selection tools, including sharing, within post previews in the app. As such, I expected the sharing dialog to include the text I selected, and for the resulting social post (e.g., Facebook or Twitter posts) to include the link to my WordPress post.
### Actual behavior

When sharing to Facebook the sharing dialog was empty but allowed me to type what I wanted. The Facebook post did not link back to the post.
When sharing to Twitter the sharing dialogue contained the selected text. The Tweet did not link to the post.
### Steps to reproduce the behavior
1. in WordPress iOS go to Blog Posts > View
2. double-tap to select some text
3. tap Share
4. choose Twitter or Facebook from icons
5. post to chosen network
##### Tested on iPhone 5s, iOS 9.3.2, WPiOS 6.2

May be connected to https://github.com/wordpress-mobile/WordPress-iOS/issues/5198
and/or https://github.com/wordpress-mobile/WordPress-iOS/issues/5200

**Comment by rachelmcr** [comment]
You're using the "Share" text that appears above the selected text (as opposed to the sharing icon) right? This is what I mean:

![2016-05-31 12 22 59](https://cloud.githubusercontent.com/assets/8658164/15672835/f1c40326-272a-11e6-9dda-7e83d2a0f8ee.png)


As mentioned in https://github.com/wordpress-mobile/WordPress-iOS/issues/5200#issuecomment-214860857 the default behavior for tapping share on a selected chunk of text does not include the original reference URL or web page URL. (Also worth noting that this differs from that issue in that we're sharing from WPiOS to a different app, versus sharing from other apps to WPiOS, so we're relying on their sharing extensions as opposed to ours.)

I tested using the sharing icon in the top right of the post preview, instead of that Share text, and although the selected text wasn't included it consistently included the link to the post (tested sharing to Facebook and Twitter).

**Comment by rachelmcr** [comment]
Closing as this is the default behavior for this action and not connected to the WPiOS share extension.
