### ISSUE TITLE
Copy paste from Tweetbot fails 

### ISSUE THREAD

**Issue by simonwheatley** [wordpress-mobile/WordPress-iOS#5606]
### Expected behavior

I copy a link from Tweetbot and am able to paste it into the WordPress iOS app on iPhone. 

### Actual behavior

The paste fails.

### Steps to reproduce the behavior

1. Use the "copy link" in the share dialog for an individual tweet
2. Open a new post in the WordPress app
3. Paste (no text is pasted)
4. Open a new tweet in Tweetbot 
5. Paste the link 
6. Copy the link 
7. Paste successfully into the WordPress app

##### Tested on [device], iOS [version], WPiOS [version]

iPhone 6s, latest WordPress app, iOS 9.3.2

**Comment by frosty** [comment]
I think this is the same issue we were having with Safari URLs, which should have been fixed by this PR: https://github.com/wordpress-mobile/WordPress-Editor-iOS/pull/825

I just tested with the latest internal build of WPiOS and I was able to paste a link successfully. @simonwheatley could you confirm – were you using the latest App Store version? I think the fix probably hasn't made it into the App Store build yet.

**Comment by simonwheatley** [comment]
This is fixed in my latest update.
