### ISSUE TITLE
Blog Posts: Preview for self-hosted site without Jetpack returns a 404 error

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#5693]
### Expected behavior

I expect to be able to preview blog posts on self-hosted sites without Jetpack.
### Actual behavior

If I try to preview a post (using the Preview link in the Blog Posts list, or the preview eye icon in the editor), I end up on the WP Admin login screen with an authentication error:

> ERROR: The password you entered for the username [self-hosted username] is incorrect. Lost your password?
### Steps to reproduce the behavior
1. Add a self-hosted site without Jetpack to the app
2. Create a draft post in the site
3. Save the draft to the site's server (not a local draft)
4. Tap the "Preview" link in the Blog Posts list. Result: Instead of a preview you see the site's login screen
5. Open the draft in the editor again and tap the preview icon. Result: Instead of a preview you see the site's login screen
### Screenshots

![self-hosted post preview](https://cldup.com/45RjnFUfRZ.thumb.png)
##### Tested on iPhone 6, iOS 9.3.2, WPiOS 6.4.0.20160707.1

I also tested this in the latest stable version 6.3, and the same bug occurs there so this is not a new issue in 6.4.

**Comment by rachelmcr** [comment]
This also occurs on self-hosted sites with Jetpack if you add the site as a self-hosted site first and then log in to WordPress.com.

Tested on iPhone 6, iOS 10.1.1, WPiOS 6.7.0.20161115

**Comment by rachelmcr** [comment]
I retested this issue with a self-hosted site on WPiOS 6.8.0.20170112. I no longer get an authentication error, but I get an unauthenticated view of the site and so the screen returns a 404 error instead of a post preview.

**Comment by koke** [comment]
I just tested this with a non-Jetpack self hosted and it worked for me. Maybe there is an extra step or condition for this to happen? Tested on `develop` and 6.8.0.20170112

On Jetpack connected sites, this is a known issue, and a hard one to tackle since we don't have the site's credentials to authenticate the web view.

**Comment by koke** [comment]
I just found out about `frame-nonce`, which is what calypso uses for previews on Jetpack sites.
https://github.com/Automattic/jetpack/pull/4692

We could replace `WPURLRequest` with it for previews. Some notes on what I know so far:
- `frame_nonce` is included in a site's `options` dictionary, although I'm seeing `0` for my Jetpack sites. It looks like it's `0` on `sites/$site` but it's present on `me/sites`.
- We could cache it, but we'd need to be careful with expiration. It's probably best to refresh the nonce on each preview, or at most prefetch it when you load the editor.
- If we need to request a nonce from the preview screen, it might be good to have a "Loading" indicator.

**Comment by koke** [comment]
Documenting what I know about previews so far:

Getting previews right is kind of hard. 🙄 

We have so many different permutations to take care of that it's really hard to reason about this. The current code in `PostPreviewViewController` doesn't help much with that, so I was planning to refactor all the logic into something testable, and leave the View Controller to take care of little more than setting up the web view and handling the share button (should we even have a share button on previews?).

## State

There are a few variables in place:

- If the post is published, or if it's "private" (draft/scheduled/privately published). Published posts can be viewed by everyone (unless it's a private blog), but the rest need authentication.
- If the post has local changes. This includes new drafts that are not even on the server yet. Granted, the scope of this issue was about feature parity for self hosted, but we also want to improve previews in general #5686. I'd bet most of the times you hit preview is because you just changed something (locally).
- If the blog is private or public. Private blogs require authentication to view any post. I haven't tested if nonces work on private blogs, or we'll need cookies.
  
## Authentication
  
We also have two (you could argue three) different authentication methods:

- Launch a request to `wp-login.php` with either a username/password or an OAuth2 token, and get cookies. This works for wp.com (token), non-Jetpack self-hosted (password), but not for Jetpack sites, as you can't make their `wp-login.php` accept a token, and we don't have the password.
- Include `frame_nonce` in the URL. This is only exposed for wp.com and Jetpack sites, although with some API quirks that I've reported already.

Frame nonces are included in the site options, and expire every day. This doesn't mean you are guaranteed that the token you just get will last for 24 hours, your request may have just happened seconds before renewal. Since there's a good chance that the app refreshed the site info recently if you are previewing a post, we'll be optimistic and assume we have a good nonce if we even have one. A preview that needs a nonce and receives an invalid/expired one will return a 404, so we can capture that and force a refresh of the nonce.

For cookie authentication, we check `HTTPCookieStorage` for cookies for the post URL, and look if there's a `wordpress_logged_in` that matches the `username`. If there is a cookie we assume it to be valid. Similar to the nonce case, if it fails it will return a 404, so we could get new cookies then.

I'd favor `nonces` when available, but we could also do cookies if a nonce fails and the site supports it.

## Autosaves

Also, as mentioned in #5686 I learned that we have an `autosaves` endpoint that would allow us to preview changes to already published posts without making those changes definitive.

In that case, we'd be showing "real" previews for everything except changes to published posts for non-Jetpack sites, which is still a lot better than what we have now. And future WP-API improvements could allow us to do that as well.

The last time we tried autosaves it had so many bugs that we had to roll it back. This is not a trivial thing to do, but we should at least give it another try, or make it work for drafts.

## How to preview

When a user taps preview, quite a few things need to happen:

- Do we need to save the post (has local changes)?
- Does previewing this post need authentication? Do we have the credentials we need?
- If we need to save or get credentials (any network request other than the preview) show a loading UI. This might take a few requests.
- Save the post if needed, get the permalink URL.
- Do we have credentials?
  - Yes: Load preview
    - Failure: Refresh credentials, then try to load again
      - Failure: if nonce failed and we can do cookies, try that. (Go back to "Do we have credentials?")
  - No: Refresh credentials, try to load.
    - Failure: if nonce failed and we can do cookies, try that. (Go back to ==
- Failure: show a "simple" preview with a notice on top explaining why we can't do a real preview.
  
This got a bit complicated. I'm considering not doing the cookie fallback for nonces to simplify a bit.

But also, if we know beforehand we need to save and get credentials, I'd love to parallelize those requests, although we can simplify there as well.

I haven't figured out the right design for this yet, but since I've been thinking about this for a couple days and won't likely look at it again at least until next week, I wanted to dump all my thoughts on it so far.
