### ISSUE TITLE
Re-do Editor Navbar Links

### ISSUE THREAD

**Issue by sendhil** [wordpress-mobile/WordPress-iOS#5849]
Right now the Nav Bar is a little crowded with the Preview button hangout up there along with the settings and the Post button.
![image](https://cloud.githubusercontent.com/assets/437043/17570948/4a66038e-5f03-11e6-8311-8e9499483d75.png)

Lets simplify it by getting rid of the Preview button and putting it as well as other options underneath an "..." button similar to:
![image](https://cloud.githubusercontent.com/assets/437043/17570983/5d202914-5f03-11e6-9d82-3eaab7a22b12.png)

**Comment by sendhil** [comment]
@frosty want to tackle this one?

**Comment by frosty** [comment]
HECK YES!

**Comment by frosty** [comment]
@sendhil I've just pushed up a PR for this, but I put the Post / Update / Save option into the menu itself, and after some discussion I'm not sure that's the best option.

Do you have any opinion on whether that action should stay out of the menu, and also on which order the `...` and `Update` should appear? Both feel to me like they should be the rightmost option.

**Comment by frosty** [comment]
Also ping @mattmiklic?

**Comment by mattmiklic** [comment]
> any opinion on whether that action should stay out of the menu

I think you're right, that post/update/save is the primary action here, and it should remain visible at all times. 

> which order the `...` and Update should appear?

I'd say that the `…` always goes on the right. I agree that the primary action also sorta feels like it should be on the right, but I think the ellipsis might look out of place if it precedes the text button, rather than following it.
