### ISSUE TITLE
Reader: Tapping Reader button in bottom nav bar twice now opens Reader menu

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#5933]
### Expected behavior

In version 6.4, tapping the Reader button in the bottom navigation bar opens the Reader. Tapping it a second time scrolls you to the top of the Reader. That same behavior is expected in the latest beta.

### Actual behavior

In version 6.5 beta, tapping the Reader button opens the Reader. Tapping it a second time, however, opens the Reader menu instead of scrolling to the top.

This is consistent with other sections of the app (for example, tapping "My Sites" twice takes you back to the site list) but is confusing for users who are used to the behavior from previous versions. Is this the intended behavior for that Reader navigation button?

### Steps to reproduce the behavior

1. Open the app, go to the Reader, and scroll down in the list of posts
2. Navigate to another part of the app (not the Reader)
3. Tap the Reader button in the bottom navigation bar to open the Reader again
4. Tap the Reader button again

Result: The Reader menu opens

##### Tested on iPhone 6, iOS 9.3.5, WPiOS 6.5.0.20160826

h/t Hafiz for [raising this issue](https://make.wordpress.org/mobile/2016/08/29/call-for-testing-wordpress-for-ios-6-5/#comment-19181)

**Comment by aerych** [comment]
Thanks @rachelmcr  and Haviz. This is actually intended behavior tho perhaps a bit surprising for the usecase Haviz mentioned in the comment.

In 6.4 and earlier, the post list was the starting point for the Reader. If you tapped the Reader's tab while looking at the list, it would scroll you back to the top. However if you were previewing viewing a tag (a list), or a site (a list), or viewing a post detail, tapping on the Reader's tab would take you back to the starting post list, not scroll you to the top of the visible screen. From this perspective, the starting list was the odd man out.

In 6.5, the menu is now the starting point for the Reader. Tapping the Reader tab when viewing the menu will scroll you to the top of the menu.  Tapping the Reader tab on any other screen will return you to the Reader's starting point -- now the Menu. 

This is a desired behavior in that it allows users to quickly return to the menu after having navigated through multiple screens (eg. Menu > Topic > Preview Site > Preview Tag > Post Detail > Comments) rather than having to repeatedly tap the back button. 

User's can still scroll to the top of the current screen by tapping on the status bar.
