### ISSUE TITLE
Editor: Launching the editor when all sites are toggled off launches the Sign-in controller.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#6031]
To reproduce: 
- Sign in to wpcom and have no self-hosted blogs in the app. 
- Edit the My Sites list and toggle off all your wpcom sites and click Done. The list should be empty.
- Tap the middle tab to launch the editor. 
  Rather than seeing the editor, the app shows the Sign in screen.  Maybe it would make more sense to show the site picker, or just open the editor defaulting to the user's primary blog.  
  Now try this:
- On the _empty_ My Sites screen, tap the search field. Not that all your sites appear while search results are empty. 
- Tap on one of your blogs in the search results to view its details screen.
- Now tap the editor tab.  Note that the editor launches as normal.

**Comment by bummytime** [comment]
Closing because this behavior has been updated (tested on `develop` branch):

> Tap the middle tab to launch the editor.
Rather than seeing the editor, the app shows the Sign in screen. Maybe it would make more sense to show the site picker, or just open the editor defaulting to the user's primary blog.

In this situation, tapping the middle tab launches the editor with the customer's primary site selected.

> On the empty My Sites screen, tap the search field. Not that all your sites appear while search results are empty.

No longer an issue:

![simulator screen shot - iphone x - 2018-02-02 at 16 26 21](https://user-images.githubusercontent.com/154014/35757673-e0fa79e2-0835-11e8-9cb1-4b47f8e86077.png)
