### ISSUE TITLE
Sign in: Self-hosted sign in form enables button without entering a URL.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#6033]
To reproduce: 
- Go to the self-hosted sign in screen. I did this while already signed in to wpcom via the My Sites screen. 
- Enter a user name and password but leave the Site Address field empty. 
- Notice that the Add Site button enables as soon as there is text in both the username and password field.

**Comment by catehstn** [comment]
Is this to allow users to sign into .com with no site, @rachelmcr ? It's unclear that insisting on site to enable the button is the correct behavior here.

**Comment by rachelmcr** [comment]
Since it's the self-hosted ("Add self-hosted site") login screen, I'd expect the site field to be required, especially if you are already logged in to a .com account in the app and you are adding a self-hosted site.

The .com login screen already omits the site address field (so you can log in without entering a site address). I don't know how many people end up logging in to .com accounts from the self-hosted login screen, so we might want to consider/measure that if we're concerned about limiting that behavior.

**Comment by aerych** [comment]
This was actually fixed in #6378 :)
