### ISSUE TITLE
Posts: Wrong (inaccurate) confirmation message after updating a post

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#6079]
### Expected behavior

After updating a published post, I expect the confirmation message to say "Updated!" to let me know the update action was successful.
### Actual behavior

After updating a published post, the confirmation message says "Published!"

As [reported by Ryan](https://test.wordpress.com/2016/10/06/session-notes-editor-customizer-undo-ays-vscroll-macnchrome-iphone-7/):

> When I hit the Update button for an already published post, I get Published as a confirmation. This makes me question the status of the post.

![image](https://cloud.githubusercontent.com/assets/8658164/19442265/ad7eefe6-9480-11e6-9ebc-371c048475ea.png)
### Steps to reproduce the behavior
1. Publish a post, or choose an already published post
2. Open the published post in the editor
3. Make a change to the post
4. Tap Update to update the published post with your changes

Result: After the editor closes, a "Published!" message appears.

Similar issue when restoring a scheduled post from the trash: https://github.com/wordpress-mobile/WordPress-iOS/issues/4969

**Comment by bummytime** [comment]
**Update:** As of 02/15/17, the latest on `develop` behaves in the following way:

If the post is a draft, it correctly displays "Saving..." and "Saved" in the hud.

<img width="459" alt="napkin 36 02-15-17 11 08 01 am" src="https://cloud.githubusercontent.com/assets/154014/22985849/5966249e-f36f-11e6-8816-36826cb17137.png">

If the post is already published, the hud incorrectly says "Publishing..." instead of "Updating...":

<img width="569" alt="3" src="https://cloud.githubusercontent.com/assets/154014/22985882/70d14d0c-f36f-11e6-82ec-271e060ec09a.png">

There no longer is a confirmation message says "Published!" post update as noted in the original issue above.  

FWIW, the Aztec VC does correctly state, "Updating...":
