### ISSUE TITLE
Help users solve login issues without contacting support

### ISSUE THREAD

**Issue by nheagy** [wordpress-mobile/WordPress-iOS#6099]
When a user encounters a problem logging into their site using the app, they are given very little guidance beyond the links to "Contact Us" or "Need Help?" on the error screen. Ideally the app could suggest common solutions to be tried before they contact support.

This may be well-addressed by #6075. However, we could also improve detection of errors like missing XMLRPC access on self-hosted sites or attempts to login to WordPress.com with a username that doesn't exist.

Will need more consideration to become a concrete plan.

**Comment by rachelmcr** [comment]
>Ideally the app could suggest common solutions to be tried before they contact support.

I think this is key. Our error message overall still tend to be notifications about errors rather than solution-oriented. Implementing deep linking to our FAQs (#5552) would make it possible to link directly to FAQs from the error screens if we want to provide more detailed solutions right away.

A couple specific things that I think might help with username/password issues:

1. If the user gets an "incorrect username/password" error through the WordPress.com login form, rather than an immediate "Contact Us" link we could have: a) a link to the password reset and  b) a prompt to make sure they're on the right login screen (i.e. a message that this is for WordPress.com/Jetpack login).
2. If the user gets an "incorrect username/password" error through the self-hosted login form, we could try linking them directly to their site's password reset page (if we can detect it) or to a FAQ with more information (possibly even the [Codex page](https://codex.wordpress.org/Resetting_Your_Password).

**Comment by aerych** [comment]
Closing this one for now.  The updated login flow includes improved messaging with this aim.  We can reopen if necessary.
