### ISSUE TITLE
Notifications: up/down navigation arrows

### ISSUE THREAD

**Issue by kwonye** [wordpress-mobile/WordPress-iOS#6140]
Right now the mobile web has up/down arrows to go the the next/previous notification without having to go back to the notifications list. We're going to be adding that to the mobile apps.

![img_0561](https://cloud.githubusercontent.com/assets/1158819/19863843/0b51177a-9f53-11e6-932e-021d48f1e8a0.png)

(note that Apple Mail has something similar) 

![img_0768](https://cloud.githubusercontent.com/assets/1158819/19863878/2e86e472-9f53-11e6-96db-3178a75fd308.PNG)

**Comment by jleandroperez** [comment]
As discussed, since the `Navigation Arrows` would be located in the NavBar (and thus, would collide with the `Edit` button), we'll shift that action to the bottom Actions Bar, as seen in the following shot:

![simulator screen shot nov 9 2016 16 12 00](https://cloud.githubusercontent.com/assets/1195260/20151137/d4be49ca-a697-11e6-8b39-476219022ffd.png)

cc @mzorz
