### ISSUE TITLE
Post List: Enable the author filter for Jetpack powered sites.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#6149]
Currently the Post List only shows the author filter if a blog is hosted at WordPress.com.  This was due to some limitations with the XML-RPC API and (iirc) some missing API support with Jetpack when the feature was originally written. 

Let's see if recent API improvements can let us perform a reliable multi-author check for Jetpack powered self-hosted blogs and, if so, enable the author feature for those blogs as well.

**Comment by elibud** [comment]
@maxme @oguzkocer @tonyr59h do you currently support this on Android? Want to get an issue opened if not?
For what I've found out so far we should be able to implement this, it's not straight forward but it is possible.

**Comment by tonyr59h** [comment]
@elibud we don't have that filter on Android yet. We've got wordpress-mobile/WordPress-Android#5884 open to track it, but it's not in the scope of the #betterjetpackxp project.

**Comment by elibud** [comment]
@tonyr59h now that you mention that, this particular issue was not on our master list, so maybe I should ignore it for now 🤔

**Comment by elibud** [comment]
Potentially this is something we can tackle since we should be able to know the `userID` of the self-hosted site user. We could get it here: `v1.1/sites/SITE_ID/users` with some dark magic to identify which one of the ones returned there is the current user in the app. I think this is something we want to consider when rethinking our flow for adding a JP site since we may need that information for other use cases. This particular ticket is not on our master list of issues and I think it will probably be easy to fix if we consider storing that info when adding the site. @koke @maxme What do you think?

**Comment by koke** [comment]
I think I'd expect more multi-user sites that are Jetpack than WordPress.com, so this could be a nice addition for them if it is easy enough.

I haven't looked too deep into this, but I think all the filtering is done server-side through the API, which makes me think that it might just work by not limiting it to wp.com hosted sites, and if it doesn't it might be an API bug.

**Comment by elibud** [comment]
@koke for what I could see we do all the filtering client side, but I may be missing something here...

**Comment by koke** [comment]
I tried a few things so far without much success:

- Implementing a new `sites/$site/posts/mine` endpoint. That works fine, but we still need to be able to filter locally.
- Adding an `author` link to `meta` so we can include the `author` object in the response (including the `linked_user_id`) so we can easily retrieve that. This works fine on wp.com but throws an error on Jetpack sites. 

I believe we're back to square one: when we send the `checkMultiAuthor` request to `sites/$site/users`, we can match `linked_user_ID` to the current account, and return the `ID` so we can filter by that.
