### ISSUE TITLE
Notifications: 'Detached' notification on 6.7

### ISSUE THREAD

**Issue by frosty** [wordpress-mobile/WordPress-iOS#6214]
I was using the latest 6.7 release on my iPhone 7 at the weekend, and after pulling to refresh the notifications list the topmost notification became 'detached':

![img_4950](https://cloud.githubusercontent.com/assets/4780/20481367/a12bc2a4-afde-11e6-9ccc-2c1fc06a2fa6.png)

When the list finished loading, the notification then appeared in two places:

![img_4951](https://cloud.githubusercontent.com/assets/4780/20481368/a1e86346-afde-11e6-9323-ecff612767e4.png)

I then switched to the different filtered sections using the segmented control, and the notification stayed in position at the top of each of them. Here, it floated above the others:

![img_4952](https://cloud.githubusercontent.com/assets/4780/20481402/cd4fe66c-afde-11e6-8113-73e1763cff86.png)

And here, it seemed like it was in the first section, but its content was cut off vertically:

![img_4953](https://cloud.githubusercontent.com/assets/4780/20481404/d29fb11a-afde-11e6-8f3f-f30dcec72a4f.png)

cc @jleandroperez

**Comment by jleandroperez** [comment]
Closing this one since there seems not to be much we can do. Reviewed the tableView code, we're not doing any weird hacks (+ we've even reverted from autosizing cells to explicit calculation).

I've been seeing this kind of glitch all over the system (just got the screenshot pasted below, yesterday).

Seems to be an SDK issue. Thanks for filing this @frosty!!!

![img_5787](https://cloud.githubusercontent.com/assets/1195260/20537431/ea5a8292-b0cb-11e6-942c-458978e9dc98.PNG)
