### ISSUE TITLE
Media: Clear Cache

### ISSUE THREAD

**Issue by jleandroperez** [wordpress-mobile/WordPress-iOS#6252]
### Details:
Support request from a user: 

```
I have a heavy-image self hosted site and my wordpress app uses sometimes over 1gb of space on my iPhone. To clean this up I have to uninstall it and then install it again... could you make a button to clean the cache of the app without uninstalling it?
```

@SergioEstevao can you please confirm if this is something we're not currently handling?
Thanks!

**Comment by SergioEstevao** [comment]
At the moment we are not cleaning the images cache for media. 
For me the best way to handle this is to add something to app/media settings that allow users to clear the cache.
Even better will be to have a setting to say the maximum space allowed and clean the image cache from time to time, preferably older images first...

**Comment by oguzkocer** [comment]
That sounds like a great plan @SergioEstevao!

**Comment by koke** [comment]
> For me the best way to handle this is to add something to app/media settings that allow users to clear the cache.

Sorry I'm late to the conversation, but why do we keep those images anyway? For images uploaded from the device, we should clear them when they're uploaded. For images "cached" from the media library we should store them in `NSCachesDirectory` instead of `NSDocumentDirectory` and let iOS handle purging.

**Comment by SergioEstevao** [comment]
@koke you are probably right, since I started working on media, the images where being stored in the Documents folder, they where not even being exclude from backups. 
The main reason to cache them was to avoid repeated downloads of the same image every time we go to the library. So you are probably right the best place to keep them should be NSCachesDirectory the only exception I see is for images that are already assigned to a Media object but that media object is still not uploaded to the server ( failed uploads, or remove image from a post).
