### ISSUE TITLE
WPAuthTokenIssueSolver Issues

### ISSUE THREAD

**Issue by jleandroperez** [wordpress-mobile/WordPress-iOS#6318]
### Details:
Found this glitch while trying to spot a "Missing Dotcom Account" glitch. Steps below:

1. Log into a dotcom account
2. Hack [this spot](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/Utility/WPAuthTokenIssueSolver.m#L74) so that it always returns *true*
3. Launch the app. You'll get the Reauth Screen

Note that the navigationBar style is off. Hit the top left button. Verify that there's an AlertController that shows up, and disappears on its own.

**Comment by diegoreymendez** [comment]
@jleandroperez: How did you become aware of this issue?

A little background on why I'm asking this:

This class was added to solve an old issue with keychain information becoming corrupted due to the account IDs changing.  Since then, account IDs have been replaced with a UUID that we use to look up the account information in the keychain.  So while this class was useful for restoring lost information back when that issue was present, it should no longer be necessary now.

The reason I was asking how you become aware of this issue is that to my best knowledge there are no scenarios that can trigger `hasAuthTokenIssues` returning `true` anymore.

**Comment by jleandroperez** [comment]
Closing this one since, as discussed over DM, not worth the hazzle. `WPAuthTokenIssueSolver` was added over a year and a half ago, we should probably nuke it, rather than maintaining it.

Will keep on digging for the Missing Dotcom Account glitch, though.

Thanks @diegoreymendez!
