### ISSUE TITLE
Notifications: Missing Gravatars

### ISSUE THREAD

**Issue by jleandroperez** [wordpress-mobile/WordPress-iOS#6320]
We recently got a report over Lookback. Apparently, some Gravatars seem to be missing. Screenshot below.

@koke again and again and again, thanks **SO MUCH**

<img width="283" alt="screen shot 2016-12-12 at 14 01 18" src="https://cloud.githubusercontent.com/assets/1195260/21108313/8d1721f0-c073-11e6-81fc-94e362cc7f1f.png">

**Comment by koke** [comment]
Some leads:
- I'm seeing gravatar returning 503 errors so that's why gravatars might fail to download
- For some reason the app is requesting 2000x2000 px gravatars, which might be triggering those 503s
- Once a gravatar has failed, the app won't try to set the avatar again unless the cell is reused
