### ISSUE TITLE
Reader Comment: State restoration break attachment layout

### ISSUE THREAD

**Issue by kurzee** [wordpress-mobile/WordPress-iOS#6344]
### Steps to reproduce the behavior

1. Open my recent Swift 3 reader post on `develop`, since the comments merge.
2. Background the app with comments open.
3. Restore to the comments state.
4. Notice broken attachment images.

##### Tested on [device], iOS [version], WPiOS [version]
iPad Simulator Air 2 10.2

<img width="377" alt="screen shot 2016-12-17 at 5 01 23 pm" src="https://cloud.githubusercontent.com/assets/1873422/21290300/b4251756-c47a-11e6-83f7-90316ebc0377.png">

**Comment by aerych** [comment]
This looks to have been caused by a bad edit when I updated the comments refresh for swift 3 compat. The delegate methods had their signature changed. Since they are optional there was no warning about it. The calls to refresh cell height after images load are failing silently.  Easy fix thankfully.

**Comment by kurzee** [comment]
>The calls to refresh cell height after images load are failing silently. Easy fix thankfully.

Nice!
