### ISSUE TITLE
Site Picker: Search bar should be pinned/locked to the top of the screen

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#6468]
### Expected behavior

The search bar should be pinned or locked to the top of the screen while you scroll through the site picker.

### Actual behavior

The search bar disappears as you scroll down in the site picker.

### Steps to reproduce the behavior

1. Open the My Sites tab
2. Tap "Switch Site" to view the site picker
3. Note the search bar at the top of the screen, and then start scrolling through the site list.

Result: The search bar disappears.

##### Tested on iPhone 6, iOS 10.1.1, WPiOS 6.8.0.20170112

**Comment by koke** [comment]
Looking at other apps, this seems like the standard behavior on iOS. If the concern is about being able to search while in the middle of a long list of sites, you can tap the status bar to scroll to the top, or we could add a search icon in the navigation bar. Although this feels like an optimization for a small set of users. @mattmiklic any thoughts on this?

**Comment by mattmiklic** [comment]
I think this is OK for two reasons.

- The scrollbar auto-hiding as the list is scrolled is natural behavior on iOS
- If the user taps the search field, it becomes "stuck" to the top bar, and all sites are visible in the list (including hidden ones).

That said, we could consider a search icon in the toolbar instead of a search box at the top of the list. It would be a tradeoff, though, so worth testing with real users.

**Comment by elibud** [comment]
@mattmiklic so this one is OK to close until we dedicate more design time to that screen right?

**Comment by mattmiklic** [comment]
> so this one is OK to close until we dedicate more design time to that screen right?

I just took another quick look at this and am going to contradict what I said in my previous comment. While hiding the search bar on scroll is common behavior, it's also not unheard-of to keep a permanently visible search bar on screen, as the Contacts app does. So I think the fastest solution to the stated issue would be to make the existing search bar permanently visible, rather than auto-hiding.
