### ISSUE TITLE
Posts List: Retain search filter after Viewing post

### ISSUE THREAD

**Issue by hoverduck** [wordpress-mobile/WordPress-iOS#6603]
### Expected behavior
To be able to search for a post, view it, then return to my search results

### Actual behavior
After viewing the post my search filter was cleared and I was returned to the top of the list

### Steps to reproduce the behavior
1) Open the Posts List
2) Search for a post
3) Click the View button to open the post in a webview*
4) Click the Back button to return to the list

*Note that clicking on the card itself opens the preview, and returning from that does retain the search results

**Comment by designsimply** [comment]
Tested this today using WPAndroid alpha-177 (12.8 alpha) on Pixel 3 Android 9 and found that it is still a valid issue and that when I search for a post then view it and tap the back button I land at the unfiltered posts list when I expected to see the filtered search view at that point.

**Comment by designsimply** [comment]
Re-tested and found that this issue is no longer happening. When I tap to either view or edit a post in the Post List search results, I am taken back to the filtered search list after pressing the back button. ([34s](https://cloudup.com/c14drZJowOm)) 👍

![WordPress-iOS-6603-test-with-wpios-15 6 0 2](https://user-images.githubusercontent.com/1119271/92159167-3543fe00-edea-11ea-97f9-a0ab45f345e7.gif)
<p style="clear:both;"><sup>Tested with WPAndroid 15.6-rc-2 on Pixel 3 Android 10.</sup></p>
