### ISSUE TITLE
Aztec: Verify "more" comment functionality works as expected.

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#6630]
The `WPPostViewController` class has logic inside for setting a value on the `AbstractPost` field `mt_text_more`. Verify this code is even necessary - make sure to test with self-hosted sites too. I think it's going to make me cry either way.

**Comment by jleandroperez** [comment]
### Scenario: Aztec to Web
1. Launch Aztec
2. Enter some content in the Post's Title
3. Tap the top right button to visualize the **More** Sheet
4. Launch the **Post Options**
5. Scroll all the way down and insert some random excerpt
6. Publish the post
7. Open the website in a browser
8. In order to visualize the **Excerpt**, run a search using, as a keyword, the content you've entered in (2)

As a result, the Post Excerpt will be onscreen.

### Scenario: Web to Aztec
1. Edit a new post in any of your testing blogs
2. Add an excerpt (click **Screen Options** >> turn on **Excerpt**
3. Publish the post
4. Launch WPiOS and open the Post List
5. Open the Post's Options, and verify that the Excerpt is visible

--

I've conducted both tests (Aztec to Web, Web to Aztec) in both, WordPress.com and Self Hosted sites. Working perfectly!!!

**NOTE:**
- We had a dead property (BasePost::mt_text_more). Nuked via #6734
- **PostSettingsViewController** is actually the component that deals with the **mt_excerpt** edition
- No need to update anything, working "as is"

Thanks @astralbodies!!

**Comment by koke** [comment]
Using an excerpt is just one way of having "Read more". The other one is the `<!--more-->` tag, which Aztec isn't showing:

![simulator screen shot 22 feb 2017 07 59 59](https://cloud.githubusercontent.com/assets/8739/23200550/377c365a-f8d5-11e6-9e6a-0b6cebe82faf.png)
![simulator screen shot 22 feb 2017 08 00 01](https://cloud.githubusercontent.com/assets/8739/23200551/37aef9f0-f8d5-11e6-95c4-0c1371cfaa3e.png)
![screen shot 2017-02-22 at 08 01 55](https://cloud.githubusercontent.com/assets/8739/23200554/3a7518e0-f8d5-11e6-88e8-15b0af9c89f6.png)
![screen shot 2017-02-22 at 08 02 00](https://cloud.githubusercontent.com/assets/8739/23200553/3a74d6c8-f8d5-11e6-9df5-aa2bc9c00d99.png)

**Comment by astralbodies** [comment]
@SergioEstevao Did your changes address this?

**Comment by SergioEstevao** [comment]
@astralbodies  the more tag is supported now, and it should show correctly on visual mode.

**Comment by astralbodies** [comment]
@koke If you're feeling frisky you want to re-test?

**Comment by koke** [comment]
Tested on develop, I can't see anything:

![screen shot 2017-03-03 at 10 36 37](https://cloud.githubusercontent.com/assets/8739/23545880/6c72e7f8-fffd-11e6-9abb-12c99a4fc0e8.png)
![screen shot 2017-03-03 at 10 36 43](https://cloud.githubusercontent.com/assets/8739/23545878/6c717c42-fffd-11e6-9467-180e5fae1332.png)

**Comment by jleandroperez** [comment]
@koke i *Suspect* you're testing the *Hybrid* editor instead. Note that Aztec does not have Syntax Highlight while editing HTML (and the `<!--more Read More-->` snippet shows up grayed out in the shot.

This is how it looks like on my end:

![simulator screen shot mar 3 2017 2 01 14 pm](https://cloud.githubusercontent.com/assets/1195260/23560646/f44c4734-0019-11e7-9f8d-f1c383eaf021.png)

![simulator screen shot mar 3 2017 2 01 15 pm](https://cloud.githubusercontent.com/assets/1195260/23560654/fa0f47ca-0019-11e7-88c7-620e32aa3a81.png)

**Comment by jleandroperez** [comment]
As discussed via Slack, verified by @koke. Thanks gentlemen!!
