### ISSUE TITLE
App sometimes launches without tab bar or navigation

### ISSUE THREAD

**Issue by frosty** [wordpress-mobile/WordPress-iOS#6976]
We've had a number of reports of the app launching with no navigation present at all – navigation bar or tab bar. We've had screenshots of it occurring on details notification and reader detail (which could be via a notification).

![img_2909](https://cloud.githubusercontent.com/assets/4780/24722305/30af9038-1a3b-11e7-97fb-71efff6eb5d7.png)

The issue seems most prevalent when launching the app from a notification, which makes me think it could be something related to state restoration when the app has been killed off in the background. One report stated that it happened just when launching the app from its home screen icon.

I've as yet been unable to reproduce it, but it has happened to me once when I wasn't actively trying to reproduce it.

It's obviously quite a big issue, as the only way for the user to continue to do anything in the app is to kill it off and reopen (providing they know how to do that).

##### Tested on iPhone 7, 7+, iOS 10.2+, WPiOS 7.1 and above

**Comment by koke** [comment]
I've reproduced this! \o/

- Log in with your a8c account, find a notification that mentions you on a post (not a comment)
- The notification opens a reader view for the post.
- Scroll down a bit until the navigation bar disappears
- Put the app in the background
- Generate a new comment notification
- Tap on the new notification
- The comment notification seems to present modally and without navigation

**Comment by ChrisHardie** [comment]
Both @simonwheatley and I are seeing this issue regularly when tapping on notifications from the app while it is in the background. I'm running 7.3.0.20170405 on iOS 10.3.1. @simonwheatley is on 7.2 on 10.3.1. Let us know if we can help with additional information.

**Comment by simonwheatley** [comment]
I can replicate this from a notification every single time, with my current install.

**Comment by frosty** [comment]
@simonwheatley @ChrisHardie This should be fixed in today's 7.4 release – please let us know if you continue to see the problem once you've updated!

**Comment by simonwheatley** [comment]
I'm still getting this issue. Currently running 8.2.

**Comment by bisko** [comment]
I've noticed the issue with the latest stable app at the moment (not sure about the version).

The way to almost 100% reproduce it for me was:

1. Open the app
2. Open a notification about a comment for something
3. Click the box to reply, but don't type anything
4. Go to the home screen (home button)
5. Wait some time
6. Trigger a notification 
7. Open the notification from the lock screen
8. The app almost always bugs out the way described

Also seems like the issue was kind of fixed with the latest testing app (20171205...), where you'll be properly sent to the correct notification when you opened the notification from the lock screen, with the app chrome still visible.

**Comment by frosty** [comment]
Thanks for the report @bisko, and the useful report steps. I had this happen to me yesterday too.
