### ISSUE TITLE
Notifications: Like miscounts -- tracking

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#7039]
Opening this issue to track miscounts of likes in notifications and push notifications. When there are new reports, please leave a comment describing what the user say + the app version affected. 

Originally reported by @astralbodies , postID 6223

> The last week or so I’ve noticed discrepancies with the counts on Like notifications. The push notification payload says (in this specific case) 14 likes + this person and the note body in the app/API says 15 + this other person. The push is fired off at the time person 16 clicked Like but has the text as if the 15th person clicked.

**Comment by designsimply** [comment]
I checked our iOS app reviews for 2019 year-to-date and did not find any reports of miscounts of likes in notifications.

I tried testing by logging in as a different user on the web adding several likes to recent posts on one of my blocked, when the notifications came through in the app the counts matched up with what I see in the Calypso > My Sites > Posts screen on the web ([app screenshot](https://user-images.githubusercontent.com/1119271/66087151-bd16ed80-e533-11e9-822e-9988762fbd2c.PNG), [Calypso screenshot](https://user-images.githubusercontent.com/1119271/66087138-abcde100-e533-11e9-8e5d-9e27cb867486.png)).

I'll check in with the happiness engineers in the Mobile Guild about this, but if there aren't any new cases reported since Apr 2017 then I'd like to close this issue and let it resurface as a new issue (or re-open this one) if it comes up again.

**Comment by designsimply** [comment]
Closing due to no new reports of wrong counts of likes on this issue since the it was originally reported ~3.5 years ago.

@astralbodies please let me know if you spot any like miscounts again and I will re-investigate!

**Comment by astralbodies** [comment]
@designsimply I still see it happen once in a while but I suspect that is now resolved with the push notification backend being replaced. I'll keep my eyes open! 😄

**Comment by designsimply** [comment]
Thank you very much!
