### ISSUE TITLE
Insights: Time since a post was published does not update consistently

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#7160]
Original issue: https://github.com/wordpress-mobile/WordPressCom-Stats-iOS/issues/437

In the "Latest Post Summary" module on the Insights tab, the time since the post was published does not update consistently, and pull to refresh does not refresh it.

After publishing a post, I checked my stats and saw the module update from "It's been <1 hour" to "It's been 1 hour" and then to "It's been 4 hours" since the post was published. However, it seems to be stuck at that. It has been a day since I published the post, which the stats in the browser reflects accurately:

![screen shot 2017-03-08 at 4 17 37 pm](https://cloud.githubusercontent.com/assets/8658164/23712684/90d4e3d6-041b-11e7-9231-8e8f4f2fbe11.png)

I also see the correct time on the post in the Blog Posts list in the app:

![2017-03-08 16 17 06](https://cloud.githubusercontent.com/assets/8658164/23712721/abf164fa-041b-11e7-82e2-887cf2fc0fa2.png)

But even though other stats on the Insights tab are updating (e.g. the View count increased after the post received a new view) the "time since" is stuck at "It's been 4 hours":

![2017-03-08 16 16 56](https://cloud.githubusercontent.com/assets/8658164/23712781/d0b057ec-041b-11e7-84fb-e72ab8f5ba04.png)

Pull to refresh the stats will refresh other stats on that tab, but not the "time since" information.

Originally reported by @catehstn. I tested and reproduced the issue on iPhone 6, iOS 10.2.1, WPiOS 7.1.0.20170306.

**Comment by ScoutHarris** [comment]
This is addressed in Stats Refresh.

**Comment by guarani** [comment]
I'm seeing this issue again on 14.7 where the Latest Post Summary section of site Stats is showing an incorrect time since publish. I think it's a timezone conversion issue.

I made a post on a new site and viewed site stats about 15 minutes later, there the time since post was shown as already _four hours._ Since my local timezone is UTC/GMT-04:00, it looks like the timestamp from the server is being interpreted as local time instead of UTC when calculating elapsed time, which would account for the 4 hour difference.

The Android app is showing the correct elapsed time, and the blog list screen is also showing a correct elapsed time.

Do you recommend reopening this issue or creating a new issue, @ScoutHarris?

| Stats (iOS) | Blog List | Stats (Android) |
| -- | -- | -- |
| ⚠️ | ✅ | ✅ |
| <kbd><img src="https://user-images.githubusercontent.com/1898325/81220091-c0cd8f80-8fae-11ea-9844-f9351f1758ba.jpg"></kbd> | <kbd><img src="https://user-images.githubusercontent.com/1898325/81220094-c1662600-8fae-11ea-968f-8217b9377c6c.PNG"></kbd> | <kbd><img src="https://user-images.githubusercontent.com/1898325/81220083-bdd29f00-8fae-11ea-8146-b77ba9788c7a.jpg"></kbd> |

**Comment by ScoutHarris** [comment]
Hey @guarani . I'd suggest opening a new issue. This one was related to the _old_ stats, so having an issue relevant to the _new_ stats would probably be best.

**Comment by guarani** [comment]
Sure thing, created an issue here: https://github.com/wordpress-mobile/WordPress-iOS/issues/14072
