### ISSUE TITLE
Stats: small squares in the Posting Trends module for single days are difficult to tap

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#7163]
Original issue: https://github.com/wordpress-mobile/WordPressCom-Stats-iOS/issues/406

From @jblz:

> individual days are moderately difficult to tap for me (iPhone 6). Did you play w/ making the cells bigger & only having two months in portrait mode vs. 3

cc: @bummytime

**Comment by designsimply** [comment]
Stats has been updated since this post was originally written. 

@jblz I've tested tapping on individual days in Stats graphs using WPiOS 13.3.0.0 (TestFlight) on iPhone 6S iOS 13.1.2 and found that they were easy for me to tap. Are those the days you were referring to? (the link to the original issue isn't working for me) Are you still having trouble tapping on any other things which might have too-small-targets-areas in Stats in WPiOS?

Aside: I gave similar feedback about the arrows used to navigate some stats screens in [WordPress-iOS/12080](https://github.com/wordpress-mobile/WordPress-iOS/issues/12080) and @ScoutHarris updated those! 😍🎉

**Comment by jblz** [comment]
Thanks for following up, @designsimply. 

I don't have an iPhone anymore, so I can't really test this. And it's been so long ago, I don't really remember specifics. Sorry I'm not more help :)

**Comment by designsimply** [comment]
@SylvesterWilmott would you mind commenting on the design decision for keeping the squares the size they are in Posting Trends?

**Comment by SylvesterWilmott** [comment]
This was an issue in the previous version of stats and continues to be an issue. Due to the low volume of people who visit this screen at the time, it was de-prioritised. @ScoutHarris I couldn't find an event tracking visits to this screen, can you confirm that we are tracking this?

**Comment by ScoutHarris** [comment]
Well, @SylvesterWilmott , you would be right. There is no tracking for Posting Activity. Not that it'll help you now, but I'll add that in the next release.

**Comment by designsimply** [comment]
Sounds like de-prioritizing and revisiting at a later date is a good next step for this issue. Let's see if we get any other user comments about it in the meantime. 👍

**Comment by ScoutHarris** [comment]
> I'll add that in the next release.

Done in https://github.com/wordpress-mobile/WordPress-iOS/pull/12978.
