### ISSUE TITLE
Unify strings and pull from widgets.wp.com if possible

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#7194]
Original issue: https://github.com/wordpress-mobile/WordPressCom-Stats-iOS/issues/132

Right now the strings in iOS stats are not really synced up with what is being used in Calypso.
- Make sure the base strings match what is being used on web stats
- Determine the easiest way to pull in the translations into strings files. This may affect how we're translating things for WordPress-iOS.
- Things like pluralization may not be entirely possible.
- Consider using the latest translation technology (XLIFF) from Apple for this project.

Strings in JSON format from Calypso: https://widgets.wp.com/languages/calypso/es.json

**Comment by designsimply** [comment]
@ScoutHarris do any of the things listed here need to be re-checked after the recent Stats Refresh project? If so, I think we should pull each one out into a separate issue.

**Comment by ScoutHarris** [comment]
@designsimply - honestly, I'm not quite sure exactly what this issue means. But, during Stats Refresh we did update the strings (titles and such) so they should be more inline with Calypso. If they differ anywhere, it's by design.

I think we can close this, but maybe @astralbodies can elaborate a bit and clarify what this was supposed to accomplish?

**Comment by astralbodies** [comment]
We can close the issue. I think the idea was to not do double-work for translations by just using the strings from Calypso. That, in practice, is difficult overall and not something specific to just stats. I'll close this issue!
