### ISSUE TITLE
Orientation changes in the editor reset keyboard state

### ISSUE THREAD

**Issue by tonyr59h** [wordpress-mobile/WordPress-iOS#7222]
### Expected behavior
Rotating the screen while typing in one of the editor fields (title or content) should have no effect on the state of the soft keyboard.

### Actual behavior
The keyboard always behaves as if you're at the beginning of a new sentence after rotation. As demonstrated by the shift key being in the pressed state.

### Steps to reproduce the behavior
* Edit a post
* Begin typing a sentence but stop in the middle, for example `The quick brown f`
* Rotate screen
* Note that the shift key is "pressed" as if at the beginning of a sentence, the next letter will be capitalized

**Comment by elibud** [comment]
@tonyr59h can you verify that this doesn't happen on Aztec (I've tested and did not see it there)? I am tempted to leave it as it since since we've had this issue for a long time and the editor will be replaced soon. Also, TBH, I don't know if I can fix it since it seems to happen as a side effect of a Javascript function.
Thanks

**Comment by elibud** [comment]
Verified with @tonyr59h , only happens on the Visual editor, this is OK to close since we'll be replacing it soon.
