### ISSUE TITLE
Post Settings: Don't allow slug that isn't available

### ISSUE THREAD

**Issue by jeremeylduvall** [wordpress-mobile/WordPress-iOS#7348]
### Expected behavior
When I create a post/page, I'm given a generic slug matching the title after the post/page draft is saved. If the same slug already exists, I'm given a `-2` at the end. I expect that if I try to remove that `-2`, it will automatically get re-added.

### Actual behavior
I can remove the `-2` addition and publish the post with what I think is the base slug without the additional character. However, if you go back and check out the slug after it's published, the `-2` is re-added.

If I'm editing the post slug and I change it to a slug that's not available, I expect my changes to either A) get ignored or B) at least get corrected when I save the post.

### Steps to reproduce the behavior
1. Publish a post with the title "Testing" and the slug "testing"
2. Start a new post with the same title - "Testing". Save the post to create a temporary slug of testing-2.
3. Go into the post options. Manually change the slug back to "testing" (which is already taken).
4. Publish the post. Then, go back to look at the post options. It will get changed back to testing-2.

### GIF
![slug](https://user-images.githubusercontent.com/7240478/26900882-fda08c92-4b90-11e7-8d21-396bcd2f4360.gif)

##### Tested on iPhone 6, iOS 10.3.2, WPiOS 7.8.0.20170605

**Comment by elibud** [comment]
If I update the `slug` field on a Post to an already used one I would expect that upon saving, that field is overwritten to what will actually be used for publishing. This is not what is happening and the user entered value is kept even though it will not be used at all, `other_URLs.suggested_slug` has the correct value.
I am trying to find out if this is expected, and if that's the case we can fix it client side with the following code: 

`PostService.m` Line 547:
```
// The field slug on a remote post is of no value to us since it will reflect
// what a user tried to update their slug to, regardless of whether that url was available
post.wp_slug = remotePost.suggestedSlug;
```

**Comment by elibud** [comment]
We have looked into this and unfortunately there is no clean way to fix it, and particularly no way to fix it for .com and .org. We are choosing to stay consistent for both and leave it as is, since it only affects drafts. 
The bottom line is that there is no certainty of a conflict until the post is actually published and we do not have an endpoint that we can consume to check the availability of a slug.
Thanks for reporting this @jeremeylduvall we will re consider if we get user complains.
Thanks for all the help to understand this issue @aerych
