### ISSUE TITLE
iPad: The App is not aware of the undo / redo & prediction toolbar

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#7439]
Title has it.  This problem seems not to be limited to any specific section of the app, but seems instead like an issue that impact all of our VCs.

Some screenies showing the problem:

![img_0015](https://user-images.githubusercontent.com/1836005/27557527-4d9021be-5a90-11e7-8f00-eaf1e3ac7b92.PNG)

And...

![img_0017](https://user-images.githubusercontent.com/1836005/27557530-51ad8dc2-5a90-11e7-844e-6d888fb5f078.png)

**Comment by designsimply** [comment]
I tested this with WPiOS 14.0.0.0 TestFlight beta on iPad Mini 4 (WiFi) (iPad5,1) iPadOS 13.3 and found that the undo/redo/prediction toolbar overlaps the bottom menu when an external keyboard is used—and the overlap also happens without using an external keyboard but it seems more acceptable in that case since the keyboard takes up so much of the screen real estate by default. 

Screenshots for reference:

<img src="https://user-images.githubusercontent.com/1119271/72926518-ceb61800-3d11-11ea-8315-af2d74cc2b94.PNG" width="620" alt="IMG_0205">

<img src="https://user-images.githubusercontent.com/1119271/72926516-ceb61800-3d11-11ea-82d6-c8acca0661ea.PNG" width="620" alt="IMG_0203">

<img src="https://user-images.githubusercontent.com/1119271/72926517-ceb61800-3d11-11ea-83c0-7e4c22da7837.PNG" width="620" alt="IMG_0204">

<sup>Tested with WPiOS 14.0.0.0 TestFlight beta on iPad Mini 4 (WiFi) (iPad5,1) iPadOS 13.3.</sup>

I would like to get design feedback for this case. What we need next is a decision about whether this is worth making a change and whether that change should apply only to when an external keyboard is in use. Moving to Mobile Design Groundskeeping for review.

**Comment by kean** [comment]
Tab bar is gone in 25.4.

<img width="1316" alt="Screenshot 2024-09-12 at 1 26 12 PM" src="https://github.com/user-attachments/assets/0695151f-f95a-43b6-8368-f539d2b943d4">
