### ISSUE TITLE
Reader: double line returns don't render as a new paragraph

### ISSUE THREAD

**Issue by kwonye** [wordpress-mobile/WordPress-iOS#7512]
### Expected behavior
When a user enters double line returns, we show that as a new paragraph

### Actual behavior
A double line return doesn't have any line breaks in it.

See https://wordpress.com/read/feeds/61073955/posts/1514250564 for how it should render.

### Steps to reproduce the behavior
Check out this post in the reader: https://noccy.com/2017/06/28/debunking-anita-sarkeesian/

![fullsizeoutput_3a08](https://user-images.githubusercontent.com/1158819/27942474-14b69716-628c-11e7-8bb1-7419418a9a43.jpeg)

**Comment by ChrissiePollock** [comment]
Another report of this #226163-h

**Comment by designsimply** [comment]
I tested this by creating a post using double line returns (using the block editor) and the double line returns looked correct to me. 

<img src="https://user-images.githubusercontent.com/1119271/63216508-b3f0cf00-c0f3-11e9-8252-9fa64eb17c40.PNG" width="300" alt="IMG_0155"> <img src="https://user-images.githubusercontent.com/1119271/63216509-b4896580-c0f3-11e9-8dc3-bafb160b432d.PNG" width="300" alt="IMG_0157">
<sup>Tested with WP Internal 13.1.0.20190814 on iPad Mini 4 (WiFi) (iPad5,1) iOS 12.4. The post on the left was made on the web using the block editor, and the post on the right was made with WPiOS 13.1 beta on iPhone 6S iOS 12.4.</sup>

Because I wasn't able to reproduce the problem in a quick test and because there haven't been any recent recent reports of this issue, I am closing with a note to re-open if it comes up again (and in case my test didn't cover the type of content used in the original example post which was too old to view in the Reader when I tried checking it).
