### ISSUE TITLE
wordpress:// url scheme calling newpost not working

### ISSUE THREAD

**Issue by ajgraves** [wordpress-mobile/WordPress-iOS#7585]
### Expected behavior
Call url wordpress://newpost (with optional parameters) used to work with the iOS app, taking you to the post editor with title and content pre-filled if passed along.

### Actual behavior
WordPress app opens, nothing happens.

### Steps to reproduce the behavior
Place a call in Safari to wordpress://newpost and click "Open" to open in WordPress, observe you are not delivered to the post editor.

##### Tested on [device], iOS [version], WPiOS [version]
iPad 2017 and iPhone 7, 10.3.2 and 10.3.3, WPiOS 8.0 (and a few versions before)

**Comment by kwonye** [comment]
Thanks @ajgraves, we'll be working on this very soon.

**Comment by kwonye** [comment]
@diegoreymendez it looks like you removed this in `AppDelegate`, do you remember why?

**Comment by bummytime** [comment]
@kwonye for background: [PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/6139), [issue](https://github.com/wordpress-mobile/WordPress-iOS/issues/6138), and [context](https://github.com/wordpress-mobile/WordPress-iOS/issues/2371).

**Comment by diegoreymendez** [comment]
Even more context: https://github.com/wordpress-mobile/WordPress-iOS/pull/2369

The reasons behind the removal of this was:

- Initially @koke designed a sample "exploit" showing the feature wasn't very safe (see link above).  This may or may not be true for Aztec (we'd need to spend some time going back to the original exploit).
- We decided to remove it because that's what the share extension tumps this feature, and it doesn't bring the same security concerns.

My personal opinion is that, since a decision was taken to remove the feature, we should evaluate if this is really necessary before accepting the request to add it back.

I know "necessary" is not a very precise term, but we should try to qualify / quantify it somehow.

**Comment by mklengel** [comment]
Any solution? It still doesn't work.

**Comment by diegoreymendez** [comment]
@ajgraves, @mklengel - Could you provide us with more information about how you were using this feature?

iOS's built-in share functionality should supersede this feature, but it's currently a bit limited and could definitely be improved.

**Comment by mklengel** [comment]
I am using Drafts on my iPad Pro to write some text which goes via the URL scheme wordpress://newpost to WordPress. It's very annoying that this is not working anymore.

Additionally I have a scrolling problem with WordPress (in Safari) on my iPad Pro aka "WordPress Editor Jump Problem", see here:

https://www.makeuseof.com/tag/ipad-pro-app-problem
https://ditchwalk.com/2015/09/08/wordpress-editor-jump-fix

All in all - very frustrating.
