### ISSUE TITLE
Aztec: When linking text in visual editor, any text is accepted as URL

### ISSUE THREAD

**Issue by deancroyal** [wordpress-mobile/WordPress-iOS#7713]
### Expected behavior
I expected only URLs to work in the URL field when trying to link text in the visual editor.

### Actual behavior
Most text all will be accepted as a valid URL.

![image_uploaded_from_ios_720 3 53 00 pm](https://user-images.githubusercontent.com/13387217/29575145-7a5503fe-8718-11e7-8c3a-c6a76608ba04.jpg)

### Steps to reproduce the behavior
As the screenshot above shows, try the following:
1. Edit a post.
2. Select text to link.
3. Click the link text icon (should now see the option to add URL and word).
4. Enter a non-URL into the field (in my example I mistype a URL "wew.thisisus.com" which is accepted).
5. Tap Update Link to successfully save the change.

##### Tested on [device], iOS [version], WPiOS [version]
iPhone 6 plus, iOS 10.3.3, WPiOS 8.3.0.20170815

**Comment by diegoreymendez** [comment]
Calypso doesn't verify URLs either, and since we're looking for feature parity, we won't be diverging from that direction for the time being.

Any request to parse and validate URLs will require extensive analysis as to what constitutes valid and invalid values for this field (in fact the URL in the example above could be perfectly valid, even if unlikely).

Closing for the time being.
