### ISSUE TITLE
Add links to images in posts from its details editor.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#8045]
Initially reported by @elibud [here](https://github.com/wordpress-mobile/AztecEditor-iOS/issues/776).

### Expected behavior
To be able to add a link for an inserted image as with the visual editor.

### Actual behavior
Images on Aztec are missing several attributes that are available on the visual editor, particularly the ability to add a link.

Aztec | Visual Editor
-|-
|![simulator screen shot - iphone 8 - 2017-10-18 at 09 50 46](https://user-images.githubusercontent.com/5558824/31719482-0186a046-b3ea-11e7-8cde-395099f56fdc.png)|![simulator screen shot - iphone 8 - 2017-10-18 at 09 51 09](https://user-images.githubusercontent.com/5558824/31719485-03294688-b3ea-11e7-9de4-7feee597b50d.png)|

### Steps to reproduce the behavior
Insert an image and tap on Edit.

##### Tested on IPhone 7, iOS 11, Aztec Beta 12

Sister issue on Android: https://github.com/wordpress-mobile/AztecEditor-Android/issues/505

Originally reported by an iOS user via [Twitter](https://twitter.com/meghancolson/status/920269753444392960).

**Comment by jim-rhoades** [comment]
I have this working in a fork [over here](https://github.com/jim-rhoades/WordPress-iOS/tree/issue/8045-aztec-image-links), but to clarify a couple of things:

1. When using the older visual editor, when you add an image to a post it automatically adds a link for "Link To" (linking the image to its source URL)... should I add that same behavior when using the Aztec editor? or should it follow the web-based editor's behavior of NOT automatically adding a link?

Personally I think that NOT automatically adding a link would be the better choice - both to be consistent with the web editor, and because I doubt many people would actually want that behavior.

2. The Aztec "Media Settings" screen has one section labeled "Web Display Settings", and now has the "Link To" row that I've added and a "Alt Text" row that someone else recently added (see the screenshot below). Should it be kept like that or be broken into two separate sections, "Details" and "Web Display Settings", like the older visual editor?

![media_settings](https://user-images.githubusercontent.com/1471338/32289804-347522aa-bf0e-11e7-9683-c65484ca4a64.png)

**Comment by diegoreymendez** [comment]
Ping @iamthomasbishop ^

**Comment by iamthomasbishop** [comment]
> ...should I add that same behavior when using the Aztec editor? or should it follow the web-based editor's behavior of NOT automatically adding a link? Personally I think that NOT automatically adding a link would be the better choice

Agreed - I wouldn't auto-add a link, but instead do what Calypso does (inserts image sans link). The user can then has a couple options for adding a link:

* Tap to focus the image on editor canvas, then add link manually from the formatting toolbar
* Go to the image detail + manually add on the customize details

> Should it be kept like that or be broken into two separate sections, "Details" and "Web Display Settings", like the older visual editor?

The media settings are getting an overhaul right now by @bummytime, so for reference, here is the current design that he's working off of:

<img width="496" alt="screenshot 2017-11-02 11 24 32" src="https://user-images.githubusercontent.com/1200432/32337822-0a860230-bfc1-11e7-95ee-27cc491dbc25.png">

We could probably add `Link To` under the "Customize" section, as it's relative to the post/page the user is editing. I would utilize the same text input style as the title, caption, description, etc in the mock above. 

Let me know if you have any other questions!

**Comment by jim-rhoades** [comment]
That looks great! Love the large image preview. Having "Link To" in the "Customize" section does seem like the right spot for that.
