### ISSUE TITLE
Site picker: update behavior to better match other platforms

### ISSUE THREAD

**Issue by mattmiklic** [wordpress-mobile/WordPress-iOS#8074]
Our site picker on iOS differs from Android and the web in some small but important ways. I'm creating this issue to track the changes we should make on iOS to better align its picker with other platforms.

In Calypso, if the user has 11 or more visible sites, we show the 5 most recently-accessed sites on top of the list. On iOS, we only show 3 recent sites, and the threshold appears to be based on the user's total number of sites, not just what's visible. In Calypso, we show a border to divide the list of 5 recent sites from the rest of the list. On iOS, there is no divider. 

- [ ] Only show recently accessed sites at top of site picker if 10 or more are _visible_.
- [ ] Show 5 recent sites rather than 3.
- [ ] Add a 1px `greyLighten20` horizontal line to separate most recent sites from rest of sites ([Example](https://user-images.githubusercontent.com/1396552/32196339-b0e35a2e-bd96-11e7-9784-973b32d97961.png))

**Comment by designsimply** [comment]
Tested with WPiOS 13.3.0.0 (TestFlight) on iPhone 6S iOS 13.1.2 and found that the latest most-recently-accessed sites is still limited to 3 on WPiOS instead of 5 and that there is no separator in place.

<img src="https://user-images.githubusercontent.com/1119271/66168872-b653ad80-e5fb-11e9-9b21-aa3dd13f22ce.PNG" width="270" alt="IMG_3134">
<sup>Tested with WPiOS 13.3.0.0 (TestFlight) on iPhone 6S iOS 13.1.2.</sup>

Android screenshot for comparison:

<img src="https://user-images.githubusercontent.com/1119271/66168943-f3b83b00-e5fb-11e9-9c92-7c70511bacad.png" width="270" alt="Screenshot_20191003-163148">
<sup>Tested with WPAndroid alpha-190 (13.3 alpha) on Pixel 3 Android 10.</sup>

**Comment by kean** [comment]
The picker was re-implemented in 25.3. It does have the "recent sites" section.
