### ISSUE TITLE
Aztec: No spacing in Bangladeshi 

### ISSUE THREAD

**Issue by nheagy** [wordpress-mobile/WordPress-iOS#8082]
We've had a report that spaces aren't working when editing text in Bangladeshi with Aztec.

**Comment by designsimply** [comment]
I tested this by changing the preferred language to Bangla on my iPhone 6S iOS 13.2.3 and then typing into the Aztec editor using WPiOS 13.9.0.1. I was able to see spaces working in my test. ([14s](https://cloudup.com/cTZ1pBUNCHO))

<img src="https://user-images.githubusercontent.com/1119271/72259244-43050300-3610-11ea-825f-53bedb8e83da.PNG" width="200" alt="IMG_3246"> <img src="https://user-images.githubusercontent.com/1119271/72259057-d4c04080-360f-11ea-94d2-3bd14634b8c4.png" width="200" alt="bangla-in-aztec-example">
<sup>Tested with WPiOS 13.9.0.1 TestFlight beta on iPhone 6S iOS 13.2.3.</sup>

I am closing this because it was reported a while back and I couldn't replicate the problem in a test. It's very possible I didn't have the right testing environment available having an iPhone originally purchased and setup using English. I did try to update the "iPhone Language" setting but when I searched for "Bangla" nothing was returned ([screenshot](https://user-images.githubusercontent.com/1119271/72259387-a000b900-3610-11ea-9234-67f9bf7e82c0.PNG)). If I've missed something in my testing steps or settings or if this comes up again, please re-open or create a new issue that references this one. Thank you!
