### ISSUE TITLE
Unable to like posts from WordPress site

### ISSUE THREAD

**Issue by dougaitken** [wordpress-mobile/WordPress-iOS#8118]
### Expected behavior

If I'm able to like a post on my desktop or mobile browser I should be able to like the post via Reader.

### Actual behavior

Like option isn't available in Reader or post view.

### Steps to reproduce the behavior

* Subscribe to the awesome @catehstn's `cate.blog`
* Go to site in Reader and read post [One Year as 📱  👑 ](https://cate.blog/2017/11/07/one-year-as-📱👑/)
* Realise there is meant to be emoji in the text:

<img width="375" alt="mobilequeen" src="https://user-images.githubusercontent.com/52214/32575139-1a3bd452-c4cb-11e7-89e6-bb6e5d2099ba.png">

##### Tested on [device], iOS [version], WPiOS [version]

Tested on iPhone 7, iOS 11.1, WPiOS `8.8.0.20171108` beta

**Comment by elibud** [comment]
@aerych I've tracked this down to the post not having likes, so this particular function in `ReaderPostCardCell`:

```
fileprivate func configureLikeActionButton() {
    // Show likes if logged in, or if likes exist, but not if external
    guard (enableLoggedInFeatures || contentProvider!.likeCount().intValue > 0) && !contentProvider!.isExternal() else {
```

Do you know/remember why would we hide the like button if the post has no likes? Thanks

**Comment by aerych** [comment]
We only hide the like button in two situations:
- when the post is from an external blog
- when the post is from a wpcom blog, but the user is not logged into wpcom in the app AND the post has zero likes.

So with this particular post, the [response from the REST API](https://public-api.wordpress.com/rest/v1.2/read/feed/66907025/posts/1655692559) shows it belongs to an external blog.  And the absence of the like button on this post is [consistent with the Calypso reader](https://wordpress.com/read/feeds/66907025/posts/1655692559).  Which is interesting because if we look at the [other posts](https://wordpress.com/read/feeds/66907025) on the blog the like button *is* present. 

Going to chalk this one up to an API hiccup and follow up with the reader squad.

**Comment by aerych** [comment]
@dougaitken, Regarding the emoji, it looks like those are .svg graphics and not currently supported. :( 
Checking to see if there are matching pngs we might substitute.  If so I'll open an issue to address that.

**Comment by dougaitken** [comment]
Cheers @aerych 

I'm going to drop Reader an issue about the likes since the Like button shows in Reader view. I wasn't able to like from Reader but I did from visiting the post directly ¯\_(ツ)_/¯ 
Something that was odd about Jetpack sites for a while was the Like button didn't show on the front end desktop site if it was the latest post.

BUT. That post is now not showing in the Reader via for Cate's site on iOS, but it does on [desktop Reader](https://wordpress.com/read/feeds/66907025) ¯\_(ツ)_/¯ (direct Reader link works)

![http://cld.wthms.co/ODlxjE](http://cld.wthms.co/ODlxjE+)

Emoji - bah. svg - good for the web, poor for unsupported platforms.
Odd that the rest of the emoji are png files 👎
