### ISSUE TITLE
Link should not redirect properly from post

### ISSUE THREAD

**Issue by sonali86** [wordpress-mobile/WordPress-iOS#8329]
### Steps to reproduce the behavior
1. Create new post.
2. Enter link on text (ex: Goto google.com [link:google.co.in] )
3. Update or create post.
4. Post created sucessfully with post title.
5. Click on view post link.
6. When we click on link that time it is redirect on link which was added by author while creation post.

##### Tested on [device], iOS [version], WPiOS [version]
iOS : 11.2.1

**Comment by rachelmcr** [comment]
When you select "View Post" after publishing a post, or when you go to My Sites > Blog Posts and select "View" for a post, you can preview the post but links are disabled. (The view is meant to see how the post looks, but it isn't a full browser, so this is the expected behavior.)

You can go to My Sites > View Site, or view the post in Safari or another browser app, to follow links in your posts.
