### ISSUE TITLE
Plugins: Can't remove active plugin

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#8373]
### Expected behavior

I expect that selecting "Remove Plugin" for a plugin will always remove it.

### Actual behavior

If a plugin is active, selecting "Remove Plugin" seems to remove it (it disappears from the plugin list). However, the plugin is still installed and active on the site and it reappears in the app when the plugin list is refreshed.

### Steps to reproduce the behavior

1. Install and activate a plugin (e.g. Hello Dolly) on a site with Jetpack 5.6.
2. In the app, go to My Sites > Plugins.
3. Select the active plugin.
4. Select "Remove Plugin" on the plugin details page.
5. Confirm "Remove" in the confirmation dialog that appears.
6. Note that the plugin is no longer visible when you are returned to the Plugins list.
7. Pull down to refresh the Plugins list. The plugin reappears and is still active.

##### Tested on iPhone 6, iOS 11.2, WPiOS 9.1.0.20171220

**Comment by elibud** [comment]
@koke another one for you, might be a caching issue with the endpoint?

**Comment by koke** [comment]
I'm getting `"You cannot delete a plugin while it is active on the main site."`, so I guess I assumed the API would take care of deactivating first 😩 

I have a small patch to at least show an error and trigger a refresh on failure (the code was trying to do this already but it wasn't updated with the flux changes, and it wasn't updating the cached data). The problem is that showing an error would introduce a new string to be translated 😬 

![simulator screen shot - iphone x - 2017-12-22 at 09 20 29](https://user-images.githubusercontent.com/8739/34290822-ba821da4-e6f9-11e7-98ee-0b02718a081d.png)

**Comment by koke** [comment]
Calypso [is deactivating](https://github.com/Automattic/wp-calypso/blob/8675a046404f88a0624e8cf69a25610fe9c423ee/client/state/plugins/installed/actions.js#L315) (and switching off autoupdates) before removing.

```js
doDeactivate( plugin )
			.then( doDisableAutoupdate )
			.then( doRemove )
```

This seems like a big fix to squeeze into 9.1, @elibud what do you think?

**Comment by elibud** [comment]
I'm fine targeting 9.1, it's a long code freeze ❄️❄️❄️❄️❄️, I'll take care of pushing a new version out next week.

**Comment by designsimply** [comment]
Tested and confirmed with iPhone 6S, iOS 11.2.1, WPiOS 9.1.

**Comment by elibud** [comment]
@designsimply @rachelmcr This one has been fixed and it's available on the latest internal release. Thanks again for all your brilliant testing and reporting.
