### ISSUE TITLE
Upgrade Crashlytics to Firebase

### ISSUE THREAD

**Issue by nheagy** [wordpress-mobile/WordPress-iOS#8426]
Crashlytics seems to be succeeded by Firebase.

One advantage to upgrading is that we can get stats for AdWords installs without adding another analytics library to the app.

The documentation from Google [looks fairly simple](https://firebase.google.com/docs/crashlytics/upgrade-from-crash-reporting). 🤞

**Comment by SergioEstevao** [comment]
@nheagy I'm a bit confused looking at the document you linked above, the title says:

```Upgrade to Firebase Crashlytics from Firebase Crash Reporting```

And reading the document it looks they still use the Crashalytics we use, they are basically replacing their Firebase Crash Reporting with Crashlytics. Not the other way around. 

Am I'm getting it wrong?

**Comment by designsimply** [comment]
Closing because we decided to implement a server-to-server solution instead, noted at https://github.com/wordpress-mobile/WordPress-iOS/pull/8505#issuecomment-361231941.

<sup>Background: p77Llu-9IY-p2</sup>

Also noteworthy, we opted not to use Firebase Crashlytics in favor of Sentry and migrated to Sentry in Apr 2019. 

<sup>(internal references: https://wp.me/paaHJt-sV-p2 & p77Llu-bYv-p2)</sup>
