### ISSUE TITLE
Follow buttons not syncing in notifications, making the follow button get stuck

### ISSUE THREAD

**Issue by charliescheer** [wordpress-mobile/WordPress-iOS#8492]
This bug is very similar to one that I filed before about <a href="https://github.com/wordpress-mobile/WordPress-iOS/issues/8352"> notifications getting out of sync </a> In that if you go to the notifications window and find a notification with a follow button, and then click on that follow button, the follow button for the notification it's self will not change to say follow as well.
However in this case there is a little bit of a twist, if you get these two follow buttons out of sync, one of them will get stuck, so if you try to click on it it will change for a second and then snap back to the incorrect state.
The behavior is sort of hard to explain, please check out this video to see an example
<a href="https://charlietestsiteblog.files.wordpress.com/2018/01/screenrecording_01-22-2018-20-58-37.m4v"> video</a>

To replicate what is going on here
1: Go to the notifications in the app and find a notification that has a follow button on it.
2: tap on the notification to see just the notification (not the whole list)
3: Tap on the follow button on that page
4: back out to the list view again and try to tap on the follow button for the notification

It should change for a quick second and then snap back to it's previous state.

WordPress 9.2
iOS 11.2.2
iPhone 6s

**Comment by elibud** [comment]
@jleandroperez I think the more ugly part of this one is fixed as part of #8815 however I don't think we can really fix cells getting out of sync with actions performed in the reader, what do you think?

**Comment by jleandroperez** [comment]
@elibud @charliescheer I'm afraid sync'ing Notifications with actions performed in the reader, should actually be a backend task: the Follow API should probably trigger an invalidation / refresh over Notifications that display the Follow button.

That update should come thru Pinghub, and the app should work accordingly. That way, a single fix would patch iOS and Android.

**Comment by elibud** [comment]
Makes sense, @dmsnell what do you think?

**Comment by dmsnell** [comment]
this is a mix of issues:

one is that we have the same action "follow a site" not being listened for throughout the app because notifications get their data in fully denormalized form. that is, whether a site is followed in the notifications stream is produced by the notifications system and won't respect any additional updates the app might have for its site object in memory.

the other is that updating a follow status is a one-to-many type of operation. since most notifications show user information and the user block shows if we are following a user's primary site then every time we follow or unfollow a site we risk the need to invalidate all existing notifications.

it could be worth doing what @jleandroperez suggests and simply do that - invalidate all existing notifications for a user's account every time we follow or unfollow. this would obviously increase data loading but would remove the visual glitch

**Comment by jleandroperez** [comment]
@dmsnell we could find and invalidate the notifications locally, but there's probably gonna be a UI flicker anyways, if you hit *Back* (and get the Note Details onscreen) before the entire sync finishes.

As you said D, if we had a normalized scheme, this should be super easy!!!

**Comment by dmsnell** [comment]
@jleandroperez one of my ideas for the web version is eventually to normalize in the client. there's nothing preventing us to trapping user blocks or blog blocks and requesting data from outside the note source itself.

for now we could imagine regenerating all notes for a user on the server which would invalidate all the hashes for notes that change and send updates to the client and no flicker should occur. I'm AFK today but I'll try and get a patch for that ASAP

**Comment by dmsnell** [comment]
Closing because this isn't a priority at the moment.
