### ISSUE TITLE
Reader: heading fonts in subsets other than latin

### ISSUE THREAD

**Issue by kovshenin** [wordpress-mobile/WordPress-iOS#870]
Hey there, excuse my first bug report :)

While working in the Reader I noticed that the heading font does not support cyrillic so it looks strange when the title contains both latin and non-latin characters. Attached a screenshot, here's a feed you can test with: http://wpmag.ru/feed/

![Screenshot](https://f.cloud.github.com/assets/108344/1774334/88b0d034-67f7-11e3-8c94-a4c0cc03875d.jpg)

**Comment by cosmix** [comment]
This is not just about Cyrillic though. It's about international support.

Merriweather is not and probably will never be that font – Google still only provides the font that is limited to latin-ext at the moment and that's more than 20 months since the author announced he had shipped the Cyrillic-containing version to Google. 

I second the need to replace Merriweather with a font that at least supports Cyrillic, Greek and extended-latin, preferably a font with as wide a character set support as possible. There are numerous, well-designed, open source/usable choices out there.

**Comment by drw158** [comment]
The new updated font is available on Font Squirrel and Github:

https://ebensorkin.wordpress.com/2015/02/06/the-updated-free-merriweather-is-finally-available-from-font-squirrel/

Let's ask MT about the new font though. If I recall correctly, we decided to go with the older Google Fonts version.

**Comment by mnt** [comment]
Yeah, we decided to go with the Google Fonts version of Merriweather because the "newer" one isn't really complete (its italic variant still matches the visual style and weight of the old version of Merriweather). Even the newer one doesn't include support for some languages we need, so I've started gathering some feedback on how we should handle this, both in the apps and on the web.

**Comment by catehstn** [comment]
@mattmiklic I remember you mentioned this to me the other day - is there a resolution?

**Comment by mattmiklic** [comment]
Discussed, but no resolution. Will keep poking at this.

**Comment by koke** [comment]
Just tested on that site, and looks good to me 🎉 

![simulator screen shot 24 feb 2017 09 29 06](https://cloud.githubusercontent.com/assets/8739/23296058/b5eee150-fa73-11e6-979e-4e383bd64a1d.png)
