### ISSUE TITLE
Security notification doesn't show which site is it for

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#8737]
I received a notification about a security threat on a site, but it didn't say what site:

![img_0700](https://user-images.githubusercontent.com/8739/36724922-eda88fca-1bb4-11e8-8c3d-aeb4395992fe.png)

When I tapped on the Activity Log link, it took me to stats:

![img_0701](https://user-images.githubusercontent.com/8739/36724949-f9cbba3e-1bb4-11e8-9c99-a897bcce8401.png)

Tested on WP Internal (9.4.0.20180221), iOS 11, iPhone 8

**Comment by MichaelArestad** [comment]
Ah! Good catch! Let's change it to:

```
Jetpack  found 1 issue on <a>Koke's Cool Site</a>. To review...
```

That would resolve the site issue, but leaves the fact that mobile doesn't have the Activity Log yet. @elibud do you have any suggestions for what to do here? Should we change the string for mobile users or change the link to point to the web app?

**Comment by elibud** [comment]
We should not use the same `Notification.kind=Stats` that we are using for the previously existing Stats since that will cause both Android and iOS to redirect to the Statistics screen. 
Instead we should use a new kind, `Activity` since that will load the web version of the activity log for now, and we can redirect it to the native implementation in the future.
Let me know when the change is made and I can help testing it @MichaelArestad and thanks for jumping into this one.

**Comment by elibud** [comment]
Just got some help from @jleandroperez  to properly debug this: the incorrect field is in `body.ranges.type`, currently set to `stat` instead of `activity` (my previous comment referred to the parsed info and not the raw data from the server).

**Comment by dmsnell** [comment]
> Instead we should use a new kind, Activity since that will load the web version of the activity log for now, and we can redirect it to the native implementation in the future.

How do you feel @elibud about `type='activity'` for this new kind?
@roundhill do you see any issue with adding this new type for the Android app? (I don't know who is working on it these days)

**Comment by elibud** [comment]
That's perfect @dmsnell  and on Android it would also be Hogwarts :)

**Comment by jleandroperez** [comment]
Anytime @elibud !! YO @dmsnell 👊

**Comment by dmsnell** [comment]
I think we really need an editorial review of this text. There are several things I don't like about it:
 - There are grammatical bugs "to which to rewind" vs. "to rewind to"
 - "you can head over to" sounds more awkward than the terser "head over to"
 - There is a comma which isn't needed
 - "Find a point before…" is unspecific about what a "point" is
 - Many events in the Activity Log shows that threats were detected which are no longer present. This notification may lead people to believe they need to rewind past events they don't need to.
 - Rewinding isn't the only resolution and it suggesting that with the text may lead people to rewind over legitimate events and lose work they performed since the threat was detected.

These can come in steps and don't need to have review for this specific change, but I think it would help out the notification.

**Comment by elibud** [comment]
@dmsnell @MichaelArestad maybe you want to move this item over to your repo to make sure it's worked on? If so please drop a link here and copy me so I get the notifications. Thanks

**Comment by dmsnell** [comment]
@elibud working on it now - no need to shuffle it around

**Comment by elibud** [comment]
Such efficiency! Thanks a million.

**Comment by jleandroperez** [comment]
@elibud let me introduce you @dmsnell. Dennis, meet Elisa.

Dennis is amazing. I still wonder how he manages to stay on top of *EVERYTHING*

**Comment by dmsnell** [comment]
Updates pending review in D10502 - I'll get some screenies soon!

**Comment by dmsnell** [comment]
Changes from the patch:
 - no longer showing "found 1 issue" > replaced with "found an issue"
 - two blocks for the description: "we found this" … "here's what you can do"
 - site title now displayed and linked
 - minor wording changes

**One issue**
<img width="402" alt="screen shot 2018-02-27 at 10 50 18 am" src="https://user-images.githubusercontent.com/5431237/36745204-06a3d1be-1bac-11e8-88c0-c62921e1ad81.png">

**Many issues**
<img width="401" alt="screen shot 2018-02-27 at 10 50 12 am" src="https://user-images.githubusercontent.com/5431237/36745202-06881906-1bac-11e8-9d8a-0b2fcdf074bf.png">

**Comment by roundhill** [comment]
> Press a Bull

🤣

**Comment by dmsnell** [comment]
Merged in r170791-wpcom
