### ISSUE TITLE
Add UI test cases

### ISSUE THREAD

**Issue by michelleXue** [wordpress-mobile/WordPress-iOS#8862]
### Expected behavior
Adding UI test cases to maximize the code coverage

### Actual behavior
Adding 31 UI test cases with 40% code coverage

##### Tested on [device], iOS [version], WPiOS [version]
iPhone 7, iOS 10.3

**Comment by rachelmcr** [comment]
Hi @michelleXue! Thanks for getting involved with this!

Rather than focusing on code coverage as the goal, our current approach is to focus on specific, key user flows through the app and ensuring there are tests to cover those cases. We identified our top priorities in https://github.com/wordpress-mobile/WordPress-iOS/issues/11013 — if you'd like to get involved, feel free to discuss/work on the cases in that issue or propose additional user flows that should be tested. For now I'm going to close this issue, since we're not using code coverage as a measure of success for our UI tests.
