### ISSUE TITLE
Editor should not remove "empty" (but styled) elements

### ISSUE THREAD

**Issue by salty-horse** [wordpress-mobile/WordPress-iOS#8878]
This bug is split off from #7932. Could be related to #7920.

### Expected behavior
All HTML elements should be kept intact.

### Actual behavior
Empty `<a>` elements are removed, maybe other element types.
Such elements are also silently removed when trying to edit existing posts with the rich text editor, which is bad.

### Steps to reproduce the behavior
Enter this `<a>` element in HTML editing mode (from iTunes' official [Link Maker](https://linkmaker.itunes.apple.com/en-us/details/335703880))
```<a href="https://itunes.apple.com/us/app/wordpress/id335703880?mt=8" style="display:inline-block;overflow:hidden;background:url(https://linkmaker.itunes.apple.com/assets/shared/badges/en-us/appstore-lrg.svg) no-repeat;width:135px;height:40px;background-size:contain;"></a>```

Switch back to the rich text editing mode. The element is gone.

##### Tested on WPiOS 9.4 (latest)

In general, empty elements should not be removed. Every element can important behavior attached to it, even if it's empty. For example, their contents can be controlled by CSS styles or javascript, and empty <a> tags can still serve as linkable anchors for fragment URLs, used by e.g. a table of contents on the same page.

**Comment by salty-horse** [comment]
This is still an issue with version 11.9.
The element doesn't show up in rich text editing mode, and once an actual edit is made in that mode, it is automatically removed.

**Comment by designsimply** [comment]
@salty-horse thanks for the issue and comment! We are moving toward a new block editor, so I tested this with 11.9 using Me > App Settings > Use Block Editor enabled and found that the empty `a` tag you provided as an example is maintained when using the block editor.

Video: [1m34s](https://cloudup.com/c5N8xxU1pCs) (tested with WPiOS 11.9 on iPhone 6S iOS 12.1.4)

Because the functionality works as requested in the block editor, I recommend closing this issue and would also like to get a second opinion about that.

**Comment by koke** [comment]
I can see how that's annoying, but I don't think we can support in Aztec without major changes. The block editor should do a better job of respecting HTML, although it's still based on Aztec for rich text editing, so if you edit the block with that tag it might get corrupted.

I agree with @designsimply, closing this one. Please reopen if you see it happening in the block editor and we'll evaluate options again.
