### ISSUE TITLE
After creating a new post draft, it doesn't appear in the draft list

### ISSUE THREAD

**Issue by etoledom** [wordpress-mobile/WordPress-iOS#8916]
### Expected behavior
A new draft post appears in the draft list.

### Actual behavior
When creating a new draft and going back to the draft list, the newly created draft doesn't appear in the list until I refresh the list.

### Steps to reproduce the behavior
1. Go to the posts list
2. Display the drafts list
3. Open the editor to create a new Post
4. Save it as a Draft
5. Close the editor to go back to the Draft list
6. The list will be as it was before, without displaying the new draft

![vid2](https://user-images.githubusercontent.com/9772967/37521037-03737fe4-28fe-11e8-854f-5bf23018d181.gif)

**Comment by frosty** [comment]
Thanks for opening this. This is likely to change fairly soon, as we make tweaks for async – we'll ensure that posts show up in the list during the upload process and reflect their current status :)

**Comment by frosty** [comment]
This is fixed in one situation, and still valid in another:

* Following the steps shown above (tapping ... > Save as Draft, then leaving the editor), the issue still persists and the post doesn't immediately appear in the list.
* If you instead tap the X in the editor and choose "Save Draft" from that menu, the draft appears in the posts list as soon as the editor disappears.
