### ISSUE TITLE
Media: Clarify that disk quota refers to site storage and not device storage

### ISSUE THREAD

**Issue by gpmw** [wordpress-mobile/WordPress-iOS#8926]
This is cool and is great information for the user but when I first saw it, I wasn’t sure if that was the space on my phone as it says “0% of 6 GB used”. Maybe need to add “on your site storage” to the end so it is not confusing.

**Comment by annelizs** [comment]
Howdy! I was thinking about tackling this issue, but I have a few questions first, after looking at the code:

1) I'm assuming you would only want the English string changed, and then translators or a localization team would update the other language strings? 
2) Are your Localizable.strings files auto-generated or manually updated? I'd like to change the actual key string in Blog+Quota.swift, but I don't want to break something unexpectedly, and the issue could be fixed by just changing the righthand side of line 37 in Localizable.strings (English), ex:

`"%@ of %@ used" = "%1$@ of %2$@ on your site storage used";`

Thanks!

**Comment by jkmassel** [comment]
Hi @annelizs,

1. That's correct – as part of the build process, the strings are added for future translation.
2. Updating the string in code is sufficient – as part of the build process, we'll regenerate the `Localizable.strings` files.

One thing to keep in mind – the string in `Blog+Quota.swift` is also used in `MediaService.m` to notify users that they don't have space for the object they're currently attempting to upload. Any text change here will need to be useful in both places, or we'll need to split them up :)

I hope that helps – sorry for the wait in getting back to you, and if you're still interested we'd love to have you as a contributor!

**Comment by annelizs** [comment]
Hey! Thanks for the response! I'm definitely still interested in contributing, although I've since picked up another project, but I'll try to find some time in the next few weeks to look at this again :)

**Comment by rfaile313** [comment]
Hey there this has been sitting for a few months and I've been moving things around today with an idea in place to fix it in both places in the app.

I have the changes made. I could open a PR but I'd prefer to test first. I'm still working on being able to login via the simulated app. Once that's settled I'll test and create a PR for the changes and hopefully we can get this closed 😄

**Comment by annelizs** [comment]
Thank you that's great!
