### ISSUE TITLE
Posts/Pages Search: spinner for pull-down refresh is beneath the search input

### ISSUE THREAD

**Issue by brbrr** [wordpress-mobile/WordPress-iOS#8980]
### Expected behavior

On Posts/Pages search when I pulling down (to update) the list - I can clearly see the spinner, similar to Posts/Pages list pull-down action.

Discovered while testing https://github.com/wordpress-mobile/WordPress-iOS/pull/8891

### Actual behavior

Spinner appears beneath the search input component, so it's mostly not visible

### Steps to reproduce the behavior

1. Open Posts/Pages
2. Tap on Search component
3. pull-down screen content

##### Tested on iPhone SE, iOS 11.2.6, WPiOS 9.7.020180316

![screenrecording_03-28-2018 22-25-46](https://user-images.githubusercontent.com/5654161/38051879-3df4ad80-32d8-11e8-9290-372ba1c48f52.gif)

**Comment by designsimply** [comment]
Thank you for the report @brbrr!

I tested with 15.8 beta and found that the spinner is no longer below the search results. ([26s](https://cloudup.com/cslcgQ0kdH9))

Pages > Search > pull-to-refresh|Posts > Search > pull-to-refresh
---|---
![Screen Shot 2020-10-02 at Oct 2 9 40 58 AM](https://user-images.githubusercontent.com/1119271/94942672-db3f6280-0493-11eb-9b26-3caf7a9e8a4a.png)|![Screen Shot 2020-10-02 at Oct 2 9 41 13 AM](https://user-images.githubusercontent.com/1119271/94942660-d7134500-0493-11eb-97d3-f7b14f4ba33e.png)

<p style="clear:both;"><sup>Tested with WPiOS 15.8.0.0 TestFlight beta on iPhone 6S iOS 13.7.</sup></p>

Because I can see the spinner in my tests and because several changes have been made to the Posts and Pages Lists since you first reported this issue, I would like to close this issue as resolved but ask that you please leave me a comment if you're still seeing any problems.
