### ISSUE TITLE
Can't compose offline

### ISSUE THREAD

**Issue by elibud** [wordpress-mobile/WordPress-iOS#9025]
### Expected behavior

I should be able to compose a post while offline.

### Actual behavior

I keep getting this alert while trying to create a post while on Airplane mode.

![image uploaded from ios 3](https://user-images.githubusercontent.com/5558824/38253987-68b970c8-372e-11e8-819f-be52a357b5bb.png)

Note: This works correctly on version 9.6 of the app.

### Steps to reproduce the behavior

Start composing a post and turn airplane mode on.

**Comment by frosty** [comment]
I looked into this some more, and the issue looks like the following:

* Aztec saves the post to Core Data on every keystroke
* These saves cause AbstractPostListViewController's fetched results controller to update, and the view controller tries to reload its data
* The NetworkAware code displays a no network alert because there's no network

I think the easiest fix for now would be twofold:

1) AbstractPostListViewController should only display an alert if it's topmost
2) It should only attempt to display an alert if the refresh was user initiated. We should pass a parameter to the refresh method to indicate whether the refresh was caused by the user (pull to refresh) – only in that situation should we display the alert.

@ctarda Want to take this one?

**Comment by diegoreymendez** [comment]
@elibud, @ctarda - This issue may need updating since 9.7 was sent to App Store review yesterday.

**Comment by ctarda** [comment]
@diegoreymendez I've just updated the milestone to 9.8 (frozen)

**Comment by diegoreymendez** [comment]
@ctarda - Just checked the PR I see linked above... wasn't this delivered in 9.7?

**Comment by nellofn** [comment]
A user reported this issue on #276743-h and I was able to replicate this issue on my iPhone 7+ with app 9.7.2.

**Comment by nellofn** [comment]
@elibud Tried on version 9.8 and I still get the "Unable to sync" error while working offline.

**Comment by ctarda** [comment]
Argh. I'll take another look. I'll ping you on Monday @nellofn

**Comment by diegoreymendez** [comment]
Reopening, given the recent developments.

**Comment by ctarda** [comment]
I was finally able to reproduce it:
1. Navigate to Me tab
2. Navigate to any of the sections in the Me tab (i.e. Account Settings) (this is the key step)
3. Enter flight mode
4. Start composing a post.
