### ISSUE TITLE
Media Library: Enable multiple selection for document picker

### ISSUE THREAD

**Issue by frosty** [wordpress-mobile/WordPress-iOS#9128]
The Media Library section of the app allows a user to import files from other apps using `UIDocumentPickerViewController`. Currently this support is limited to selecting a single image / video at a time.

We should extend this feature by enabling multiple selection within the document picker.

Note that in there past there may have been an issue with this feature not working correctly, but as far as I'm aware it should be possible now.

**Comment by a8c-sab-trial** [comment]
@frosty in my research, it appears that this is possible [beginning with iOS 11](https://developer.apple.com/documentation/uikit/uidocumentpickerviewcontroller/2902365-allowsmultipleselection).

I have submitted a [PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/9145) that takes this into consideration. In my testing, this change benefits the _Browse_ tab in the presented view controller, but not the _Recents_ tab.

It's unclear if this behavior (i.e., multiple selection is limited to the _Browse_ tab) is intentional or a [regression](https://github.com/lionheart/openradar-mirror/issues/18190).
