### ISSUE TITLE
Reader: Page jumps don't work within the Reader

### ISSUE THREAD

**Issue by SiobhyB** [wordpress-mobile/WordPress-iOS#9140]
### Expected behavior

When viewing a post that contains anchor links ("page jumps"), I expected to be taken to section that's linked to in the post.

### Actual behavior

Tapping on the the anchor links has no effect when viewed within the app. The links work correctly when selected in a browser (both from the Reader and the site itself).

### Steps to reproduce the behavior

1. Follow the steps in [this support documentation](https://en.support.wordpress.com/splitting-content/page-jumps/) to add "page jumps" to a post.

2. View the post from within the app's Reader and tap on the anchor links.

##### Tested on iPad Mini, iOS 11.3, version 9.7.2 of the app

Reported in 275749-h. Android version of issue: https://github.com/wordpress-mobile/WordPress-Android/issues/7654.

**Comment by rachelmcr** [comment]
I confirmed that this is still an issue, even with the latest Reader improvements in WPiOS Internal 15.2.0.20200707.

Currently the links do have an effect, but instead of taking you to the correct place in the post they open a blank screen. Screencast: https://cloudup.com/cEyDe1D1LuS

The links do work as expected in the web Reader.

FYI @yaelirub

**Comment by yaelirub** [comment]
Thanks for the screen share, @rachelmcr! Can you please share the link to the reader post? 🙏

**Comment by rachelmcr** [comment]
Sure! I recreated the post on a public test site here: https://rachel-test-domain.com/2020/07/09/page-jumps/
And you can see it in the web reader here: https://wordpress.com/read/blogs/93917131/posts/2091
