### ISSUE TITLE
Implement autosaves to preview published posts

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#9287]
When the user wants to preview a draft, we can just save a revision and preview it (#9286). However, when dealing with published posts saving would mean changing the published content and not just previewing it.

**Warning:** Note that "autosaves" here doesn't refer to the editor periodically saving changes, but core's idea of an [autosaved post revision](https://codex.wordpress.org/Revisions#Autosaves):

> Autosaves are stored as a special type of revision; they do not overwrite the actual post. In fact, whether your power goes out, your browser crashes, or you lose your internet connection, when you go back to edit that post, WP will toss up a warning telling you that it has a backup of your post and a link to restore the backup

I'm not sure if it's technically feasible, but what I know so far:
- There is a `/sites/$site/posts/$post/autosave` endpoint on WordPress.com that will return a preview URL for the changed content.
- Looking at an [old conversation in trac](https://core.trac.wordpress.org/ticket/21397) we might be able to create an autosave on self hosted by setting the `status` to `autosave` in `wp.editPost`, but this has to be tested.

If this is not possible on self hosted sites, I'd first make sure we're getting this on WP-API so we can do it whenever we add support. Also, I'd rather tell users that we can't preview edits to a published post rather than showing a fake preview.

**Comment by yaelirub** [comment]
I have implemented the end point call for `/sites/$site/posts/$post/autosave`.
Calling the endpoint when previewing a published post returns post data with `Preview_URL`. I'm using that url when generating a preview which works as expected for *.wordpress.com sites but returns 403 for other sites.
![Simulator Screen Shot - iPhone 8 - 2019-04-22 at 12 57 27](https://user-images.githubusercontent.com/1335657/56685585-22160f80-6687-11e9-9040-d737bbc63b2a.png)

Any ideas?

**Comment by elibud** [comment]
@yaelirub have you checked the URL Calypso is using for the preview?

**Comment by yaelirub** [comment]
@elibud , yes. using the same call

**Comment by yaelirub** [comment]
The work for this issue is done in https://github.com/wordpress-mobile/WordPress-iOS/tree/issue/9286_published_post_oreview

Currently:
Published post preview is calling autosave endpoint but showing the published post content instead of the latest updates

**Comment by yaelirub** [comment]
Update (work in https://github.com/wordpress-mobile/WordPress-iOS/tree/issue/9286_published_post_oreview):
When previewing a published post we are now calling the autosave endpoint (like in the browser). The returned response contains a preview_URL which we use in `PostPreviewGenerator: attemptPreview(url:  preview_URL)`
since authenticationRequired = .nonce (updated needsLogin() method to return true in case the status is .published) `attemptNonceAuthenticatedRequest(url: preview_URL)` is getting called and the nonce_frame value is added to the Preview_URL before creating a request and loading that request in a web view. 
When pasting that url in browser it does show the updated preview but the web view in the app shows the last published post (without the recent updates)

When loading the post in the browser after requesting to preview it does show that there is an autosave version of the post and when hitting that autosave the right content is suggested meaning the autosave call did succeed.

PREVIEW PUBLISHED POST NOT WORKING IN THE APP:
![preview_not_updating](https://user-images.githubusercontent.com/1335657/57002245-e4c3ed00-6b72-11e9-894b-e32e3295d042.gif)

AUTOSAVE VERSION IS AVAILABLE
![preview_in_browser](https://user-images.githubusercontent.com/1335657/57002265-058c4280-6b73-11e9-8745-712bd554c633.gif)

APP AFTER LOADING AUTOSAVE VERSION 
![preview_after_autosave_in_browser](https://user-images.githubusercontent.com/1335657/57002380-d1fde800-6b73-11e9-8607-6989ac4a0648.gif)

These gifs also show issues with the post in the post list not being updated on local and remote changes (when exiting the editor and when updating remotely)
cc: @diegoreymendez , @koke , @aerych , @maxme

**Comment by diegoreymendez** [comment]
As mentioned in your latest comment, in [this method](https://github.com/wordpress-mobile/WordPress-iOS/blob/12.4.0.0/WordPress/Classes/ViewRelated/Post/PostPreviewGenerator.swift#L99) we're trying to set the "frame_nonce" parameter value.

Is that value being set in the URL we're trying to open?

If I remember correctly you mentioned the "frame_nonce" value was not present in the URL we were trying to open, but I don't know what the result of that analysis is.  Can you let me know?

**Comment by yaelirub** [comment]
@diegoreymendez, it is being added before creating the request as I mentioned:
>the nonce_frame value is added to the Preview_URL before creating a request with this url and loading that request in a web view.

**Comment by diegoreymendez** [comment]
Does this param contain a value that seems legit in the URL we're using?  Where is the value coming from / where is it generated?

**Comment by yaelirub** [comment]
Seems legit and does work on the browser:
> When pasting that url in browser it does show the updated preview but the web view in the app shows the last published post (without the recent updates)

It's generated in the PostPreviewGenerator in `attemptNonceAuthenticatedRequest` we are constructing it in addNonce. 

When we chatted about this issue before I was looking at the preview_URL before we were adding it the frame_nonce. The right url to look at is `authenticatedUrl` that is created and previewed in `attemptNonceAuthenticatedRequest`

**Comment by diegoreymendez** [comment]
Adding some info for context on this issue...

So here are my findings when testing previews in a WP.com site using your branch `issue/9286_published_post_oreview`.

The first thing I noticed is that nonce authentication is apparently not enabled for WP.com sites in WPiOS due to [this condition](https://github.com/wordpress-mobile/WordPress-iOS/blob/issue/9286_published_post_oreview/WordPress/Classes/Models/Blog.m#L500).

This results in all of the requests sent from WPiOS were using cookies instead of nonce auth.  Honestly I don't think the form of authentication should affect the end result though.

I then proceeded to force nonce authentication to see what happened, and found out that the URLs produced by WPiOS and Calypso were very similar, but the preview was different.

WPiOS is showing the published post. (BAD)
Calypso is showing the autosaved post. (GOOD)

My next step was to remove the `frame-nonce` param from the requests and simply paste it in my browser (while logged into WP.com).  It worked fine.

Logging out of WP.com from Safari made the preview URL without the `frame-nonce` param stop working.

I saw the same thing happen in Safari iOS.

**Comment by diegoreymendez** [comment]
Long story short: it seems to me the auth cookie isn't being set in the WPiOS requests I'm intercepting through Charles.app, and I think that may be the problem.

**Comment by yaelirub** [comment]
I was doing my testing on my site with custom domain wp site and now I realize it returns false for `post.blog.isHostedAtWPcom` and hence was trying to setup the frame_nonce

**Comment by koke** [comment]
🎉 So excited to finally see this becoming a reality. Thanks for all the effort doing this right @yaelirub
