### ISSUE TITLE
Reader Save For Later: Investigate handling cross-post posts and discover posts

### ISSUE THREAD

**Issue by kwonye** [wordpress-mobile/WordPress-iOS#9312]

**Comment by frosty** [comment]
It looks like there may be some complexity handling both of these post types, which we'll have to work around during implementation.

Both cross posts and discover posts contain some metadata about the original post that they reference, either in `crossPostMeta` or `sourceAttribution`. Normally, when the user navigates into `ReaderDetailViewController`, we fetch the contents of the original posts to display to the user.

Note that not all Discover posts work in this way. Some contain all of the post content, and some contain a reference to the original post.

With Save for Later, if the user saves a post for later in the reader detail screen we'll have all the content we need but we'll need to make sure we save both the cross post / discover post _and_ the original post content.

If the user saves a post for later in the reader stream view controller, we'll ideally need to go away and fetch the post content so that we'll have it to display later. However, offline isn't necessarily a part of v1 of Save for Later, so we could initially just hit the network to fetch the content for these post types if necessary when the user views them.

cc @ctarda

**Comment by ctarda** [comment]
🤔 I guess my first question would be what are Cross-posts and Discover Posts? 😛 
I think we should try to remove any knowledge about the type of content that we are presenting from the UI. If we need to deal with different kinds of content, that should be done by the time we mark the content to be saved for later.

**Comment by frosty** [comment]
So:

* Cross-posts are when a post is cross-posted to another blog. I _think_ this feature is p2 specific. We display a special cell for these in reader streams, and I the `ReaderPost` contains a `crossPostMeta` object which contains information about the actual post. When we tap display the detail for a cross-post, we fetch the real post content.
  * We'll need to make sure we mark both the actual post and the cross-post 'placeholder' as being saved for later, so that we have them when we need to display them.
  * We could also leave handling these as v2 if they are indeed p2 specific.
* Discover posts are the curated posts that appear in the Discover feed in the Reader. If I remember correctly there are two types of post in there. Some contain all of the post content, and some work a bit like cross-posts where they contain some extra info in the `sourceAttribution` property that references the original post. When a user visits the post detail view controller, we fetch the original post content like we do for cross-posts.
  * The difficulty here is whether the user saves the post from the card view or the detail view, and whether we mark the correct post as saved for later.

**Comment by frosty** [comment]
Closing this one for now as we've decided not to support these types of post for v1. I'll write up a post with more detail in the near future.
