### ISSUE TITLE
User unable to follow other sites

### ISSUE THREAD

**Issue by SiobhyB** [wordpress-mobile/WordPress-iOS#9415]
In 280561-h, a user reported that they’re unable to follow other sites via the app. When they attempt to follow a site, they see an error that there was a problem and to contact support if the problem persists.

They’re able to follow sites while logged into WordPress.com in a browser and I can’t see anything on their Report Card that should block them.

Further details, including logs, found at p4a5px-2cN-p2.

##### Tested on iPhone 8 Plus, iOS 11.3.1, WPiOS 9.9

**Comment by elibud** [comment]
@SergioEstevao please look at this one as part of your groundskeeping this week.

**Comment by elibud** [comment]
@SiobhyB do you have a screenshot of the error they get?

**Comment by charliescheer** [comment]
Here is a screenshot of what they are seeing
<img src='http://cld.wthms.co/jR7NCC+'>

**Comment by nheagy** [comment]
We hope to gather some specific data on what's happening here. Plan to revisit in the future once we have that.

**Comment by elibud** [comment]
@nheagy any update on this one?

**Comment by rachelmcr** [comment]
We added generic debug logging for follow requests (internal ref: p4a5px-2cN-p2) and contacted the user on Aug 31 (internal ref: 1262138-z) to ask them to try again so we can check the logs. We haven't heard back from the user yet.

I'm closing this issue for now, since it has been over two weeks without hearing back from this user and we haven't heard similar reports from other users. We can reopen the issue and investigate further if anyone reports still having trouble with this.
