### ISSUE TITLE
Default Category not enabled in settings view when creating a new post

### ISSUE THREAD

**Issue by alisterscott** [wordpress-mobile/WordPress-iOS#9423]
### Expected behavior

When creating a new post the default category used to show as ticked/enabled in the post settings panel

### Actual behavior

No categories are enabled by default

### Steps to reproduce the behavior

1. Open app
2. Create a new post
3. Tap ...
4. Tap Post Settings
5. Tap Categories

##### Tested on [device], iOS [version], WPiOS [version]

iPhone 7+, 11.3.1, 10.0.1.20180516

Works on 9.9 App Store

![fullsizeoutput_117d6](https://user-images.githubusercontent.com/128826/40335695-57e2ae54-5da8-11e8-9e62-a75315dc6259.jpeg)

**Comment by ScoutHarris** [comment]
Hey @alisterscott . 

I believe this has been fixed.

Go to Site Settings > Default Category, add categories, and set one as default. (I'm assuming this step was done at some point, since your screenshot clearly has custom categories.)
![site_default_category](https://user-images.githubusercontent.com/1816888/40946579-73165130-681b-11e8-9764-09f1cf91d132.png)

Then, if I follow your repro steps, the Default Category is in fact checked:
![post_categories](https://user-images.githubusercontent.com/1816888/40946587-818062b0-681b-11e8-8be8-380bba52809a.png)

**Comment by alisterscott** [comment]
Thanks, I can confirm this is closed
