### ISSUE TITLE
iOS: Add “Duplicate” post or "Copy post" functionality

### ISSUE THREAD

**Issue by nozomimimi** [wordpress-mobile/WordPress-iOS#9662]
### Expected behavior
Currently on the mobile app, "Duplicate post" functionality is not available. (It exists on Calypso, see the image below)
We should bring this functionality to the mobile app.

[![https://gyazo.com/0eb5ef47b7f9c8c333ce096ae30f8895](https://i.gyazo.com/0eb5ef47b7f9c8c333ce096ae30f8895.png)](https://gyazo.com/0eb5ef47b7f9c8c333ce096ae30f8895)

**Comment by cecilearkay** [comment]
Also asked by user on the French forums: [link](https://fr.forums.wordpress.com/topic/dupliquer-une-page/#post-95294)

**Comment by elibud** [comment]
+1 to adding this feature.

**Comment by designsimply** [comment]
I also would benefit a lot from this feature on mobile! I use it all the time to post calls for testing. 😊

**Comment by designsimply** [comment]
Found that we have designs for this already https://github.com/wordpress-mobile/WordPress-Android/issues/7954#issuecomment-515509809, courtesy @osullivanchris. 👏

<img src="https://user-images.githubusercontent.com/50576199/61965121-676c1500-afc7-11e9-8d9f-b9c0546844c3.png" alt="Duplicate Post iOS">

**Comment by mindgraffiti** [comment]
One thing to note.
- `copy` is a reserved keyword in iOS. I suggest using `duplicate` everywhere, including in the UI, because that's the term Calypso uses. @osullivanchris wdyt?

**Comment by mindgraffiti** [comment]
Implementation hints:

@Gio2018 and I explored some classes related to cloning or copying. There is no duplication helper `PostCoordinator` or `PostService`, but there is one in `AbstractPost`, `- (AbstractPost *)cloneFrom:(AbstractPost *)source`, so that may be of some use.

You might also check out the `reblog` feature, where a new draft post is created and then the fields were added one-by-one from the original post. This worked out because there were not very many fields and some of them required processing (like adding quotes or a caption). Check out `ReaderReblogPresenter.swift` for details.

**Comment by osullivanchris** [comment]
> copy is a reserved keyword in iOS. I suggest using duplicate everywhere, including in the UI, because that's the term Calypso uses. @osullivanchris wdyt?

that's totally fine with me, @mindgraffiti ! Copy can mean a lot of things. Duplicate sounds more clear and specific. 

I hadn't heard of reserved keywords before, that's interesting to know too.

**Comment by mindgraffiti** [comment]
@osullivanchris a reserved keyword is a word that the programming language already uses for OS-level work. Thankfully, it is rare to have a naming conflict like that. Most Swift keywords are not things you would normally use when naming your feature, such as: enum, for, if, else, subscript, var, const, struct. Think of it like naming your circles 'pixels' in a design, even though pixels are a measuring unit and not meant to describe a shape.

**Comment by ericamQA** [comment]
3523700-zd
