### ISSUE TITLE
Pasting Animated GIF's results in tiny (non animated) thumbnail

### ISSUE THREAD

**Issue by jleandroperez** [wordpress-mobile/WordPress-iOS#9663]
### Steps:
1. Open Safari in your favorite device
2. Open [this URL](https://www.lantean.co/stabby-today/)
3. Perform a long press (or force press) over the image itself
4. As soon as the Action Sheet shows up, press **Copy**
5. Open WPiOS and launch Aztec
6. Hit Paste

As a result, the image will be (really) small, and the GIF animation will be lost.
cc @etoledom

**Comment by etoledom** [comment]
Interesting!

Importing wasn't really addressed in the GIFs project (it was focused on playback). Apparently, when importing gif images in this way, they are added to the media library as `jpg`.

I tested the same in **Calypso**. For my surprise, it doesn't work either:
When pasting the gif in visual mode, It tries to import the image as raw data, and it won't show at all after publishing (not even as static image):
```
<img src="data:image/tiff;base64,TU0AKgAW3EgLAQr/CwEK/wsBCv8LAQr/CwEK/wsBCv8LAQr/CwEK/wsBCv8LAQr/CwEK/wsBCv8LAQr/CwEK/wsBCv8LAQr/...
```
It works perfectly when pasting the image in the HTML mode. It will paste just the link, and Calypso magically converts the link into an animated gif image when going back to the visual editor.

**Back to the app**: Pasting the gif in the Aztec HTML mode seems like it won't work since it only shows the link, even when going back to the visual mode and in the posts list cell.

But after publishing, it works just fine with the Reader, showing and animating the gifs images in the in-app reader list cell, in the reader detail, and also in Calypso (and in the post website directly too).

I think this issue would be best addressed as part of a 2nd part of GIFs project where we plan to focus on imports.

cc @elibud
