### ISSUE TITLE
Translating notifications

### ISSUE THREAD

**Issue by chantalcoolsma** [wordpress-mobile/WordPress-iOS#9690]
Can someone tell me where I can find the strings used in the app notifications. There are not on https://translate.wordpress.org/projects/apps/ios/dev

I am using the latest beta (10.4.0.0), but all notifications are in English while I use my iPhone in Dutch:

![img_9302](https://user-images.githubusercontent.com/867632/42220067-390b9d32-7ece-11e8-9e71-0a22ba39ffb7.jpg)

**Comment by rachelmcr** [comment]
Great question! The text from the notifications come directly from WordPress.com, rather than in the app. Translations are managed here: https://translate.wordpress.com/

The language for those notifications depends on your account settings, so if your account language is set to English currently that text will appear in the app in English regardless of the language settings on your device/app.
