### ISSUE TITLE
Add Ability to Change Username

### ISSUE THREAD

**Issue by SiobhyB** [wordpress-mobile/WordPress-iOS#9705]
We receive questions around changing usernames frequently in support.

At the moment, we have to guide users away from the app and to a web browser to change their username.

It'd be convenient if users were able to edit their usernames directly from the app itself, and it may also reduce the volume of requests we receive.

Further discussion can be found at p7cLQ7-uk-p2.

**Comment by SiobhyB** [comment]
Android issue: https://github.com/wordpress-mobile/WordPress-Android/issues/8002

**Comment by SiobhyB** [comment]
We chatted about this in p1562572814187500-slack-mobile-support and confirmed it's still something that comes up in support a lot.

**Comment by thehenrybyrd** [comment]
I run into requests like this _all the time_. I looked up tickets about this based on the snippet I use + assigned to me, and found 9 from this week alone.
While the workflow of 'send a snippet' doesn't make this feel like a "bug" or "problem", it's clearly a common request from users. Would be great to let them stay in the app for this! ❤

**Comment by designsimply** [comment]
@SiobhyB @thehenrybyrd can you document these requests as you find them so I can use that info as part of prioritizing issues? 

The format I find most helpful is to include the shorthand (internal reference) and a small quote from the user mentioning the pain point or (especially helpful) **why** they want the change in one note per comment (this helps with searching by number of comments later). In this case specifically, I think it would also be interesting to know if the users most commonly requesting to be able to change their username from the WP apps are brand new users who have made a mistake in spelling or just changed their mind about a username or if they have come back to blogging after a break or if they're asking because of another reason I haven't thought of yet.

Thank you for raising the issue! I've added it to Groundskeeping `To Do` and it will be considered for prioritization within the next few months.

**Comment by thehenrybyrd** [comment]
#2178404-zen (internal reference)

> How to change the username?

The user doesn't specify why - and this is the case for almost all cases I come across. This account has been around for two years, so I'm thinking more like your second case.
I can start asking why they want to change their username, while sending instructions, but honestly I don't expect to get a lot of response. 😕

**Comment by thehenrybyrd** [comment]
Another in #2196455-zen.

> I've got absolutely the wrong username, [@username] is not my name 😆

**Comment by thehenrybyrd** [comment]
# 2199257-zen

> can i change my username?

The account is two months old, and the user just changed their site address.

**Comment by sophiegyo** [comment]
Another (Italian) in 2233788-zen.
Quick translation:

>Is it possible to change my username?

They were contacting us through the app and weren't specifically asking about how to do it within the app, but I still had to direct them to browser.

**Comment by thehenrybyrd** [comment]
This is closed now, but for the record I did get feedback on one of these in #2266916-zen:

> I created the wordpress username and domain in 2011 and I’ve just changed a lot as a person.
