### ISSUE TITLE
New Zendesk Mobile Fields

### ISSUE THREAD

**Issue by charliescheer** [wordpress-mobile/WordPress-iOS#9883]
As discussed here p8wKgj-A2-p2, we need to add some new fields for the Zendesk mobile support.

First a sub category in ZD for where the issue was created (iOS, Android, email)  
That subcategory was created and has the potential for three values.
Mobile – iOS
Mobile – Android
Mobile – Email
That field has a field ID of 25176023

Second there is a freeform text field for Language, so that we can keep track of the language of the app that the user is contacting us from (preferably the language of the app and not the device since it does not have to be the same on Android)
The field ID for that field is 360008583691

Thanks!!

**Comment by andrewspittle** [comment]
I updated the subcategory field to be an independent, user-editable field. It has a label of "WP Mobile App Platform" an ID of `360009311651` and values matching those above:

Mobile – iOS
Mobile – Android
Mobile – Email

**Comment by ScoutHarris** [comment]
> preferably the language of the app and not the device

It looks like the language we're passing is actually the device language.

@aerych - coincidentally while looking for something else, I came across [this](https://stackoverflow.com/a/45299393/3354034) article that says:

> Will return the **Device** language:
> `let locale = NSLocale.current.languageCode`
> 
> Will return the **App** language:
> `let pre = Locale.preferredLanguages[0]`

We are currently using the first method. Since @charliescheer asked for the App language, I'll go ahead and change it while I'm upgrading Zendesk to v2 (https://github.com/wordpress-mobile/WordPress-iOS/issues/9137).

**Comment by aerych** [comment]
Ah good catch! I didn't realize the app could be different from the device.
